### PR TITLE
[java] Update rule BrokenNullCheck

### LINKED ISSUE #3071: [java] BrokenNullCheck FP with PMD 6.30.0
**Affects PMD Version:** pmd 6.30.0

**Rule:** BrokenNullCheck
https://pmd.github.io/pmd-6.30.0/pmd_rules_java_errorprone.html#brokennullcheck

**Description:** 
Hello, I think I found some False Positives in BrokenNullCheck and I want to report them.

There are some alarms on cases which don't call method on object. It means that they cannot throw NullPointException.
I think that I found three cases which are different from each other.
Case 1. Using ```instanceof```
Case 2. Using ```Boolean``` Class
Case 3. Comparing between ```Local Variable``` and ```Field``` which have the same identifier and accessed by ```this```.

Details about codes are below.
Thank you.

**Code Sample demonstrating the issue:**

```java
class Test {
    Object obj = new Object();
    Object objectWithDifferentName;

    public void testPMD(){
        Object obj = new Object();
        String str = "str";
        Boolean boo = null;

        //Case 1. : An Alarm is generated
        if(obj == null && !(obj instanceof String));

        //Case 2. : Alarms are generated for each line.
        if(boo == null && boo != true) ;
        if(boo == null && boo != false);

        //Case 3.
        if(obj == null && this.obj == null); //An Alarm is generated
        if(obj == null && this.objectWithDifferentName); //An Alarm isn't generated
        if(obj == null && objectWithDifferentName); //An Alarm isn't generated
    }
 }
```

**Expected outcome:**
Expected that there wouldn't be any alarms.

**Running PMD through:** *[CLI]*

### PR DESCRIPTION
**Pull request by oowekyala**
## Related issues

- Item of #2701 
- Fixes #3071

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to pmd/7.0.x:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/2b618fea8d5342e1811e524d3020db91/diff1/index.html">Full report</a></td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 2919 violations,<br />
introduces 8064 new violations, 1 new errors and 0 new configuration errors,<br />
removes 15623 violations, 10 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/2b618fea8d5342e1811e524d3020db91/diff2/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/StablePathMatcher.java [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+ * A matcher for an expression like {@code a}, {@code a.b}, {@code a.getFoo()}.
+ * Those are expressions we assume to be pure, and to be referring to
+ * the same reference when they're called repeatedly if no side effect
+ * occurs between calls.
+ *
+ * <p>Note that this is not relocatable: you must use a matcher in the
+ * same scope it has been created in, to avoid bugs with accessibility/shadowing/etc.
+ * You must take care yourself that no side-effect occurs.
+ */
+public final class StablePathMatcher {
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/StablePathMatcher.java:30]: Note: this thing, might look overweight for the task (there's a single test case in BrokenNullCheck that requires it), but I think it could be used in other rules to make them smarter. For instance, in ForLoopCanBeForeach, we could recognise looping on any "stable path", eg `this.field.collection` or `this.getCollection()`.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/BrokenNullCheck.xml [hunk 2]
```diff
@@ -150,40 +163,114 @@ public class Foo {
...
+                public void testPMD(){
+                    Object obj = new Object();
+                    String str = "str";
+                    Boolean boo = null;
+
+                    //Case 1. : An Alarm is generated
+                    if(obj == null && !(obj instanceof String));
+
+                    //Case 2. : Alarms are generated for each line.
+                    if(boo == null && boo != true);
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/BrokenNullCheck.xml:222]: We have to report this - boo is null and for comparison with "true", auto-unboxing takes place, which throws a null pointer exception. This is exactly the case, the rule is supposed to detect...

So, this case 2 is not a false positive....

Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/BrokenNullCheck.xml:222]:
```suggestion
                    if(boo == null || boo != true);
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/BrokenNullCheck.xml [hunk 3]
```diff
@@ -150,40 +163,114 @@ public class Foo {
...
+                    if(boo == null && boo != false);
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/BrokenNullCheck.xml:223]:
```suggestion
                    if(boo == null || boo != false);
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/BrokenNullCheck.xml (hunk 2 above)
Comment (adangel) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/BrokenNullCheck.xml:222]: Hm... maybe we need to test both variants and expect a violation here....

Comment (oowekyala) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/BrokenNullCheck.xml:222]: > Hm... maybe we need to test both variants and expect a violation here....

I think this is the way. I'll look into it later. Thanks for your review!

File: pmd-java/src/main/resources/category/java/errorprone.xml [hunk 4]
```diff
@@ -697,7 +697,7 @@ private int getMoreFoo(){
     <rule name="BrokenNullCheck"
           language="java"
           since="3.8"
-          message="Method call on object which may be null"
+          message="This expression will throw a NullPointerException"
```
Comment (oowekyala) [inline pmd-java/src/main/resources/category/java/errorprone.xml:700]: I changed this because we now report on other kinds of expressions than just method calls (all QualifiableExpressions + operands that are unboxed)

**Review by adangel — APPROVED** [review]
