### PR TITLE
[java] Fix UR anomaly in assert statements

### LINKED ISSUE #408: [java] DFA not analyzing asserts
I came across this StackOverflow post, I haven't checked if the issue remains, but since I was unable to find any related issue on our trackers it's highly probable that it's still an issue.

https://stackoverflow.com/questions/1150633/pmd-rule-dataflowanomalyanalysis-oddness

### PR DESCRIPTION
**Pull request by oowekyala**
**PR Description:**
Just added support for `ASTAssertStatements` to DFA (see commit 7af9c23) to fix #408

The other commits contain various cleanups on the DFA framework, mainly changing `NodeType` to an enum (NodeTypes were previously implemented as integer ids).  I also cleaned up the logging messages in `StatementAndBraceFinder` which made the code a pain to read. So not the revamp the framework needs but a start aha

### CODE REVIEW

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/AbstractDataFlowNode.java [hunk 1]
```diff
@@ -131,25 +126,21 @@ public void setVariableAccess(List<VariableAccess> variableAccess) {
 
     @Override
     public String toString() {
-        String res = "DataFlowNode: line " + this.getLine() + ", ";
-        String tmp = type.toString();
-        String newTmp = "";
-        for (char c : tmp.toCharArray()) {
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/AbstractDataFlowNode.java]: the pain in my eyes

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/AbstractDataFlowNode.java [hunk 2]
```diff
@@ -22,7 +22,7 @@
 
     protected List<DataFlowNode> parents = new ArrayList<>();
     protected List<DataFlowNode> children = new ArrayList<>();
-    protected BitSet type = new BitSet();
+    protected Set<NodeType> type = new HashSet<>();
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/AbstractDataFlowNode.java]: I'd change this to the more specific `EnumSet` type, since it's optimized for enums

**Comment by jsotuyod** [comment]
The change looks great, but the public API changes mean this has to be pushed back to 6.0.0.

I don't personally see much benefit in porting the fix to 5.8.0, since no-one asked about that for almost 8 years now.

**Comment by adangel** [comment]
I agree with Juan - it's a nice refactoring.
I had a short look, whether we could make the change backwards compatible (e.g. keeping the old isType()/setType() methods in DataFlowNode in addition to the new), but the change for `NodeType` is too big. I'd assume, you could get a "IncompatibleClassChangeError" at runtime. The scenario would be: Someone has an own custom DFA rule and wants to update from PMD 5.7.0 to 5.8.0. He has once compiled the class against PMD 5.1.0 and never touched again...
So, yes, this will have to wait for 6.0.0.

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/AbstractDataFlowNode.java (hunk 2 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/AbstractDataFlowNode.java]: Nice, I didn't know of that!

**Comment by oowekyala** [comment]
Ok thanks both of you for your input, you're definitely right

**Comment by adangel** [comment]
@jsotuyod @ryan-gustafson What do you think about creating a "next-6.0.0" branch and merge these PRs for 6.0.0 into this next branch? We would continue to work on the master branch for the 5.x version, but in parallel could prepare/work on the 6.x version. We would need to merge now and then from master to next (and solve potential conflicts, adapt to new APIs).

**Comment by jsotuyod** [comment]
@adangel I think it boils down to how we foresee the roadmap after 5.8.0 (due next week).

If after 5.8.0 we decide to jump to 6.0.0 having an extra branch and dealing with merge backs for so little time is probably not worth it. If we see 6.0.0 as a long lived branch with further releases to version 5 in the meantime, then it makes more sense (and the merge conflicts increase proportionally).

**Comment by jsotuyod** [comment]
@adangel have you thought about this? We have [plenty of things already in line for 6.0.0](https://github.com/pmd/pmd/milestone/12), so we should probably get started on that soon.

Shall 5.8.0 be the last release of version 5? Or do we foresee enough improvements coming in to make a 5.9.0 release before we are able to ship 6.0.0?

**Comment by adangel** [comment]
@jsotuyod I'm struggling a bit to directly jump to 6.0.0 for master. I assume, it will take a bit longer, to do all the stuff, we want for 6.0.0 - this means, any other potential release (other than hotfixes) would need to be delayed, too. This would include any GSoC features - but on the other hand, would allow to do some refactoring/cleanup.

**Comment by jsotuyod** [comment]
@adangel I guess we can start a 6.0.0 branch from master then just in case. If nothing happens on master we can always fast-forward when we merge, and if not, we can still merge back and remove the 6.0.0 development branch staying back with only master.

**Comment by adangel** [comment]
@jsotuyod I actually would then follow the suggestion by @oowekyala : Let's make master the new 6.0.0 branch, and if we have something for 5.9.0, we can still create a branch from now and merge bugfixes and release from the branch.

**Comment by jsotuyod** [comment]
@adangel sounds good, we can merge from the tagged commit. It's settled then.

**Comment by jsotuyod** [comment]
With 5.8.0 already published, I'm merging this to master for 6.0.0
