### PR TITLE
[java] Fix scoping inconsistencies

### LINKED ISSUE #1051: [java] ConsecutiveAppendsShouldReuse false-negative
This rule seems to work sporadically. I have cases with tens of lines of:

```java
builder.append(...);
builder.append(...);
builder.append(...);
```

Which don't give the warning. Not sure when it happens - perhaps when they are in a lambda where `builder` is a parameter.

### PR DESCRIPTION
**Pull request by jsotuyod**
- Reduce LocalScope creations. Method parameters and method locals have
the same visibility / reachability, so they should be in the same scope.
 - Fix the grammar `assert` lookahead. There is no need to use `(`
 - Fix illegal test code (shadowing of parameters is illegal)
 - Update Scope tests to deal with changes
 - Fixes #1051

### CODE REVIEW

File: pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/ScopeCreationVisitorTest.java [hunk 1]
```diff
@@ -9,14 +9,16 @@
...
+import net.sourceforge.pmd.lang.java.ast.ASTBlock;
 import net.sourceforge.pmd.lang.java.ast.ASTIfStatement;
 
 public class ScopeCreationVisitorTest extends STBBaseTst {
 
     @Test
     public void testScopesAreCreated() {
         parseCode(TEST1);
-        ASTIfStatement n = acu.findDescendantsOfType(ASTIfStatement.class).get(0);
+        ASTBlock n = acu.findDescendantsOfType(ASTIfStatement.class).get(0)
```
Comment (oowekyala) [inline pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/ScopeCreationVisitorTest.java]: This could be a `getFirstDescendantOfType`

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ScopeAndDeclarationFinder.java [hunk 2]
```diff
@@ -304,13 +303,6 @@ public Object visit(ASTForStatement node, Object data) {
         return data;
     }
 
-    @Override
-    public Object visit(ASTIfStatement node, Object data) {
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ScopeAndDeclarationFinder.java]: Don't `if` statements have their own scope?

**Comment by jsotuyod** [comment]
Brief explanation of what's going on here...

Given a method:
```java
public void foo(String s) {
    int i;
}
```

`s` was stored in a `MethodScope`, while `i` in a child `LocalScope`. This makes little sense, as both `s` and `i` have the same reachability AND it's illegal for a local to shadow a parameter. The difference was artificial and just added overhead. Moreover, it would have allowed code such as:

```java
public void foo(String s) {
    int s;
}
```

Which is exactly what happened on the test cases for `AvoidAssertAsIdentifier` (which in turn covered a small error in the grammar).

This silly local scope creation was also being done on a bunch of other nodes...

```java
if (something) // new LocalScope around if - nonsense as there is no block after the if, no locals can be declared here
  return true;
```

and nested LocalScope where created were a single scope should indeed be in place:

```java
if (something) // new LocalScope, empty
{ // The block defines a new nested LocalScope
}

for (int i = 0; i < 5; i++) // new LocalScope to contain i
{ // The block defines a new nested LocalScope
}

try {
} catch (Exception e) // new LocalScope to contain e
{ // The block defines a new nested LocalScope
}
finally // For unknown reasons, finally created a new LocalScope
{ // The block defines a new nested LocalScope
}
```

Applying the same logic as for methods, for and catch scopes are simplified to a single level.
The finally statement no longer creates a new scope, but the block after the finally keyword does.

So, with this update, the above example would be:

```java
if (something) // No scope here
{ // The block defines a new LocalScope for locals in this block
}


for (int i = 0; i < 5; i++) // new LocalScope to contain i + all locals within the next block
{
}

try {
} catch (Exception e) // new LocalScope to contain e + all locals within the next block
{
}
finally
{ // a new LocalScope for locals in the finally block
}
```

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ScopeAndDeclarationFinder.java (hunk 2 above)
Comment (jsotuyod) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ScopeAndDeclarationFinder.java]: No, they don't do on their own. Only if using a block after the if (in which case the block itself defines the scope). I was just writing a brief explanation of the situation before / after this change, please review it and let me know if you have doubts

**Comment by oowekyala** [comment]
Thanks for the detailed explanation! I noticed that for lambdas, the parameters are declared in a local scope, and the block creates another nested scope. They should probably use a single scope, like methods

**Comment by jsotuyod** [comment]
@oowekyala done!

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.java [hunk 3]
```diff
@@ -63,6 +63,10 @@ public boolean isExceptionBlockParameter() {
         return jjtGetParent().jjtGetParent() instanceof ASTTryStatement;
     }
 
+    public boolean isFormalParameter() {
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.java]: I just noticed that this method would also return true for exception variables in a catch block, since catch blocks use a FormalParameter node (related to #998), which might not be expected. I think the method should filter those out, and be documented properly.
