### PR TITLE
[java] Fix LiteralsFirstInComparison ignoring constants

### LINKED ISSUE #3236: [java] LiteralsFirstInComparisons should consider constant fields (cont'd)
**Affects PMD Version:** 
6.31+
Observed on 6.34

**Rule:**
[LiteralsFirstInComparisons](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#literalsfirstincomparisons)

**Description:**
Some constant fields are not considered by the rule.

**Code Sample demonstrating the issue:**

```java
class DT1 {
  public static final String Q = "q";
  public static final String T = "t";

  public static int convert(String type) {
    if (type.equals(Q)) { // 8
        return 1;
    } else if (type.equals(T)) { // 10
        return 2;
    } else {
        return 3;
    }
  }
}

class DT2 {
  public static final String Q = "q";
  public static final String T = "t";

  public static int convert(String type) {
    if (Q.equals(type)) { // 23
        return 1;
    } else if (type.equals(T)) { // 25
        return 2;
    } else {
        return 3;
    }
  }
}

class DT3 {
  public static int convert(String type) {
    if (type.equals("q")) { // 35
        return 1;
    } else if (type.equals("t")) { // 37
        return 2;
    } else {
        return 3;
    }
  }
}
```
Line 23 has fixed violation from line 8.
Lines 35 and 37 use literals (and rule works fine for them).

**Expected outcome:**
*   Is PMD missing to report a violation, where there should be one? -> false-negative

For the code above I'd also expect violations reported for lines 10 and 25.

**Running PMD through:**
Found with maven, and here is from CLI:
```
$ run.sh pmd -R category/java/bestpractices.xml/LiteralsFirstInComparisons -f text -d src/main/java
```
which results in only
```
Apr 27, 2021 9:15:32 PM net.sourceforge.pmd.PMD encourageToUseIncrementalAnalysis
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.34.0/pmd_userdocs_incremental_analysis.html
.../DTs.java:8:	LiteralsFirstInComparisons:	Position literals first in String comparisons
.../DTs.java:35:	LiteralsFirstInComparisons:	Position literals first in String comparisons
.../DTs.java:37:	LiteralsFirstInComparisons:	Position literals first in String comparisons
```

### PR DESCRIPTION
**Pull request by oowekyala**
## Related issues

- Fixes #3236 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/LiteralsFirstInComparisonsRule.java [hunk 1]
```diff
@@ -162,17 +159,13 @@ private boolean isStringLiteral(JavaNode node) {
     private boolean isConstantString(JavaNode node) {
         if (node instanceof ASTName) {
             ASTName name = (ASTName) node;
-            ASTClassOrInterfaceBody classBody = name.getFirstParentOfType(ASTClassOrInterfaceBody.class);
-            ASTClassOrInterfaceBodyDeclaration classOrInterfaceBodyDeclaration = classBody.getFirstChildOfType(ASTClassOrInterfaceBodyDeclaration.class);
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/LiteralsFirstInComparisonsRule.java:166]: The problem was that here, we only looked for the first declaration. So only the first field declaration was considered.

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset changes 0 violations,<br />
introduces 39 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 2 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/b7377d49c239430bb4cce7cb7c79ceb8/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
