### PR TITLE
[java] Fix #4477: A false-positive about SignatureDeclareThrowsException

### LINKED ISSUE #4477: [java] SignatureDeclareThrowsException: false-positive with TestNG annotations
**Affects PMD Version:7.0.0-rc1** 

**Rule: SignatureDeclareThrowsException**

Please provide the rule name and a link to the rule documentation:
<https://docs.pmd-code.org/latest/pmd_rules_java_design.html#signaturedeclarethrowsexception>

**Description:**
The first code sample uses the annotation `org.testng.annotations.AfterClass`, and the second one uses `org.junit.AfterClass`. The analysis results of the two cases should be equivalent because these two annotations are equivalent. However, PMD reports a warning in the first sample and no warnings in the second one. Actually, PMD should not report a warning like the first sample because it is a unit test method and throwing an exception is allowed here.

**Code Sample demonstrating the issue:**

**Case 1**
```java
import net.sourceforge.pmd.lang.java.rule.design.signaturedeclarethrowsexception.*;
import org.testng.annotations.AfterClass;
public class TestA extends MyTestCase {
 @AfterClass
  void setUp() throws Exception {} // report a warning
}
```

**Case 2**
```java
import net.sourceforge.pmd.lang.java.rule.design.signaturedeclarethrowsexception.*;
import org.junit.AfterClass;
public class TestB extends MyTestCase {
 @AfterClass
  void setUp() throws Exception {} // report no warning
}

```

**Expected outcome:** PMD reports a violation at line 5 in the first class, but that's wrong. That's a false positive. PMD will report no violation if PMD sees `org.junit.AfterClass`.

**Running PMD through:** *CLI*

### PR DESCRIPTION
**Pull request by LynnBroe**
## Describe the PR

This PR excludes `org.testng.annotations.AfterClass` and `org.testng.annotations.BeforeClass` which cause FP when using in a unit test method and throwing an exception is allowed.

## Related issues

- Fixes #4477 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 3 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/96e9e58e3dd84792b55c9317a8e12ed0/diff1/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/TestFrameworksUtil.java [hunk 1]
```diff
@@ -79,6 +79,8 @@ public static boolean isTestConfigurationMethod(ASTMethodDeclaration method) {
                 || method.isAnnotationPresent("org.junit.BeforeClass")
                 || method.isAnnotationPresent("org.junit.After")
                 || method.isAnnotationPresent("org.junit.AfterClass")
+                || method.isAnnotationPresent("org.testng.annotations.AfterClass")
+                || method.isAnnotationPresent("org.testng.annotations.BeforeClass")
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/TestFrameworksUtil.java:83]: nice catch! There are however a bunch of other TestNG annotations that are missing:

`@BeforeMethod`, `@AfterMethod`, `@BeforeGroup`, `@AfterGroup`, `@BeforeTest`, `@AfterTest`, `@BeforeSuite` and `@AfterSuite`…

To keep this method manageable, we probably want to move all these annotation name Strings (both for junit and testng) to a private static immutable `Set<String>`, and replace all these `method.isAnnotationPresent` with something along the lines:

```java
return TEST_CONFIGURATION_ANNOTATIONS.stream().anyMatch(method::isAnnotationPresent)
    || …
```

Comment (LynnBroe) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/TestFrameworksUtil.java:83]: Thanks for comment. I will revise it later.

**Comment by jsotuyod** [comment]
Thanks! I'll merge after a couple minor edits.
