### PR TITLE
[java] AvoidThrowingNullPointerException marks all NullPointerException…

### LINKED ISSUE #2580: [java] AvoidThrowingNullPointerException marks all NullPointerException objects as wrong, whether or not thrown
**Affects PMD Version:** 
6.22.0

**Rule:**
[AvoidThrowingNullPointerException](https://pmd.github.io/latest/pmd_rules_java_design.html#avoidthrowingnullpointerexception)

**Description:**
AvoidThrowingNullPointerException marks all <code>NullPointerException</code> objects as wrong, whether or not thrown.
This rule is implemented through xpath search:

```
<![CDATA[
//AllocationExpression/ClassOrInterfaceType[@Image='NullPointerException']
]]>
```

This marks all <code>new NullPointerException()</code>, although these errors are not thrown.
It is recommended to adjust the detection content of the rule to reduce unimportant error warnings.

**Code Sample demonstrating the issue:**
Example 1

```java
@Override
public LogEntry next() {
	long delay = (long) ((Math.random()*1800)/**(Math.random()*10)*/);
	try {
		Thread.sleep(delay);
	} catch (InterruptedException e) {/**/}
		
	Severity severity = Severity.Trace;
	StackTraceElement[] trace = null;
	if ( delay%2==0 ) {
		severity = Severity.Info;
	} else if ( delay%3==0 ) {
		severity = Severity.Error;
		trace = new NullPointerException("Sample").getStackTrace();
	}
		
	return new LogEntry(new Date(), severity, "Random entry with a delay of "+delay+"ms.", trace);
}
```

Example 2

```java
public Config init() throws InvalidConfigurationException {
	if(CONFIG_FILE==null) throw new InvalidConfigurationException(new NullPointerException());
	if(CONFIG_FILE.exists()) return reload();
	else return save();
}

```

**Expected outcome:**
false-positive

**Running PMD through:**
CLI

### PR DESCRIPTION
**Pull request by Drofff**
… objects as wrong, whether or not thrown

## Describe the PR

Separate java class has been added for the rule AvoidThrowingNullPointerException. In this implementation NPEs are marked as wrong only in case they are thrown. NPE allocations are tracked and rule violation is detected even if intermediate variable has been used.

## Related issues

- Fixes #2580 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 4 new violations, 0 new errors and 0 new configuration errors,<br />
removes 11 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/44fa6a6ad2ec4529bf30b3f49c755296/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/AvoidThrowingNullPointerExceptionRule.java [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+        for (ASTThrowStatement throwStatement : throwStatements) {
+            if (throwsNullPointerException(throwStatement, npeInstances)) {
+                throwNPEStatements.add(throwStatement);
+            }
+        }
+        return throwNPEStatements;
+    }
+
+    private List<String> getNullPointerExceptionInstances(ASTClassOrInterfaceBody body) {
+        List<ASTAllocationExpression> allocations = body.findDescendantsOfType(ASTAllocationExpression.class);
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/AvoidThrowingNullPointerExceptionRule.java:47]: We are finding here allocation in all methods. It could be a case, where one method creates a NPE and in another method some variable is thrown - it happens to have the same name (valid, because in a different method), but it might be a different exception, e.g.:

```java
public void bar() {
   NullPointerException e = new NullPointerException();
   e.printStackTrace();
}

public void foo() {
   RuntimeException e = new RuntimeException();
   throw e;
}
```

Could you please add this as an additional test case?

Maybe it's better to visit `ASTMethodDeclaration` and `ASTConstructorDeclaration` instead of the whole class via ASTClassOrInterfaceBody. If we change that, we need to add both classes as rule chain visits.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/AvoidThrowingNullPointerExceptionRule.java [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+        }
+        return npeInstances;
+    }
+
+    private boolean allocatesNullPointerException(ASTAllocationExpression allocation) {
+        Class<?> allocatedType = getAllocatedInstanceType(allocation);
+        return allocatedType != null && NullPointerException.class.isAssignableFrom(allocatedType);
+    }
+
+    private Class<?> getAllocatedInstanceType(ASTAllocationExpression allocation) {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/AvoidThrowingNullPointerExceptionRule.java:63]: This can be done easier: `return allocation.getType()` - this uses type resolution and should work.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/AvoidThrowingNullPointerExceptionRule.java [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+
+    private String getNameOfAssignedVariable(ASTAllocationExpression allocation) {
+        List<ASTVariableDeclarator> variableDeclarators = allocation.getParent()
+                .findDescendantsOfType(ASTVariableDeclarator.class);
+        return variableDeclarators.isEmpty() ? null : variableDeclarators.get(0).getName();
+    }
+
+    private boolean throwsNullPointerException(ASTThrowStatement throwStatement, List<String> npeInstances) {
+        String thrownImage = throwStatement.getFirstClassOrInterfaceTypeImage();
+        return "NullPointerException".equals(thrownImage) || npeInstances.contains(thrownImage);
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/AvoidThrowingNullPointerExceptionRule.java:77]: Do we also detect, if someone does this? `throw new java.lang.NullPointerException()` - actually, would be a bit weird, if someone writes it that way, but still....

**Comment by Drofff** [comment]
@adangel thank you for the review! Changes have been made
