### PR TITLE
[java] Fix memory-leak in type resolution

### LINKED ISSUE #2911: [java] ClassTypeResolver#searchNodeNameForClass leaks memory
**Affects PMD Version:** 

6.29.0

**Description:**

`ClassTypeResolver#searchNodeNameForClass` does many more `ClassLoader.loadClass()` calls than there are classes in the project. Because the looked up names do not exist, the calls go through all the classloaders in the hierarchy, and every classloader creates an entry for the name in its `parallelLockMap`.

In turn, `JavaTypeDefinition#CLASS_EXACT_TYPE_DEF_CACHE` holds references to the types that do exist in the project, which keep alive the classloaders of all the modules in the Maven reactor, along with their `parallelLockMap`.

**Steps to reproduce:**

1. Set a conditional breakpoint in `ClassLoader#getClassLoadingLock` with condition `className.contains(".get")`
1. Start a debug configuration listening on port 5005
1. Run `MAVEN_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=n,suspend=y,address=localhost:5006" mvn pmd:pmd`

**Running PMD through:** *Maven*

### PR DESCRIPTION
**Pull request by oowekyala**
## Describe the PR

* Remove the static type definition cache
* Make the constructor of JavaTypeDefinitionSimple cheaper
* Stop trying to load method names as class names

Note that this does nothing for the `parallelLockMap` issue (except reducing the number of wrong class names we try to load). ~This looks like it's specific to JDK 1.7.~ We could "fix" it in PMDAsmClassLoader by overriding `getClassLoadingLock` and returning always the same instance. But this would make us give up concurrent classloading, and would not prevent other kinds of classloaders to create their own lock. I think this particular sub-issue is a wont fix.

## Related issues

- Fixes #2911 (in pmd 7 there is no problem and this should be thrown away when merging)

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinition.java [hunk 1]
```diff
@@ -52,33 +51,22 @@ public static JavaTypeDefinition forClass(TypeDefinitionType type, JavaTypeDefin
...
-        if (typeDef != null) {
-            return typeDef;
-        }
-
-        final JavaTypeDefinition newDef;
         try {
-            newDef = new JavaTypeDefinitionSimple(clazz);
-        } catch (final NoClassDefFoundError e) {
+            return new JavaTypeDefinitionSimple(clazz, boundGenerics);
+        } catch (final LinkageError e) {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinition.java:67]: I think, we should also catch here TypeNotPresentException, see also #2940

Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinition.java:67]: Hm... maybe not - we don't seem to load anything here anymore. So I think, not even LinkageError would occur here... but somewhere else....

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java [hunk 2]
```diff
@@ -26,21 +26,38 @@
...
+            return clazz.getEnclosingClass();
+        } catch (LinkageError e) {
+            if (LOG.isLoggable(Level.WARNING)) {
+                LOG.log(Level.WARNING, "Could not load enclosing class of " + clazz.getName() + ", due to: " + e);
+            }
+            return null;
+        }
+    }
+
+    private TypeVariable<?>[] getTypeParameters(Class<?> clazz) {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java:60]: I think, this method might throw LinkageError when loading the interfaces or superclass.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java [hunk 3]
```diff
@@ -83,12 +80,25 @@ protected JavaTypeDefinitionSimple(Class<?> clazz, JavaTypeDefinition... boundGe
...
     @Override
     public boolean isGeneric() {
-        return isGeneric;
+        return getTypeParameterCount() != 0;
+    }
+
+    @Override
+    public int getTypeParameterCount() {
+        if (typeParameterCount == -1) {
+            typeParameterCount = getTypeParameters(clazz).length;
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java:99]: I think, we should add here a try-catch for LinkageError. In case, we couldn't determine the type parameters, can we then set typeParametersCount=0 ?

Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java:99]: I think you're right, will do

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/ec66dd536cd545b098702781648bd96a/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by adangel — APPROVED** [review]
:+1: I'll merge this to master and afterwards merge master to pmd/7.0.x
