### PR TITLE
[java] Add exclude property to FieldNamingConventions

### LINKED ISSUE #1329: [java] FieldNamingConventions: false positive in serializable class with serialVersionUID
**Affects PMD Version:** 
6.7.0

**Rule:**
https://pmd.github.io/pmd-6.7.0/pmd_rules_java_codestyle.html#fieldnamingconventions

**Description:**
After updating PMD from version 6.6.0 to 6.7.0 all these false positive appear. 
I like all these new checks but I think that in a serializable class, `serialVersionUID` souldn't be considered.

**Code Sample demonstrating the issue:**

```
public class MyException extends RuntimeException {

	private static final long serialVersionUID = -8134636876462178354L;

	public MyException(String message, Throwable cause) {
		super(message, cause);
	}

	public MyException(String message) {
		super(message);
	}

}
```

**Running PMD through:**
Gradle 4.10
java 8

Thanks in advance

### PR DESCRIPTION
**Pull request by oowekyala**
Exclude serialVersionUID by default. Fix #1329 

I think it would be better to have a more powerful scheme to match excluded fields than just comparing the name. But property versatility is stuck for now, because values are expected to be a single string.

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Please check the <a href="http://chunk.io/pmd/1897e17615944d89aa0594db5fd18340/diff/index.html">regression diff report</a> to make sure that everything is expected</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/FieldNamingConventionsRule.java [hunk 1]
```diff
@@ -20,6 +21,14 @@
  * @since 6.7.0
  */
 public class FieldNamingConventionsRule extends AbstractNamingConventionRule<ASTVariableDeclaratorId> {
+    // TODO we need a more powerful scheme to match some fields, e.g. include modifiers/type
+    // We could define a new property, but specifying property values as a single string doesn't scale
+    private static final StringMultiProperty EXCLUDED_NAMES = StringMultiProperty.named("exclusions")
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/FieldNamingConventionsRule.java]: unrelated: why aren't the other properties static?

Comment (jsotuyod) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/FieldNamingConventionsRule.java]: right! thanks!
