### PR TITLE
[java] Don't expect to load classes from execution classpath

### LINKED ISSUE #732: [java] LinkageError with aux classpath
There is one integration test with the maven-pmd-plugin, that fails with PMD 6.0.0: It uses the aux classpath (maven dependency scope test) and should detect a subclass of JUnit's TestCase, which has no test methods.

It seems, we load some classes twice. Error Message:

Could not find class it.TestSupport, due to: java.lang.LinkageError: loader (instance of  net/sourceforge/pmd/util/ClasspathClassLoader): attempted  duplicate class definition for name: "org/custommonkey/xmlunit/XMLTestCase"

Since we couldn't determine the type of TestSupport, we didn't figure out that the class `NoTestsHere` is actually a TestCase, too, and do not report the violation.

### PR DESCRIPTION
**Pull request by jsotuyod**
- We can't assume the classes needed for analysis will be available
in the execution classpath, we need to make sure to load them from the
same classloader / auxclaspath used during analysis.
 - Resolves #732

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/TypeHelper.java [hunk 1]
```diff
@@ -45,21 +65,6 @@ public static boolean subclasses(TypeNode n, Class<?> clazz) {
...
-        }
-        Class<?> superC = type.getSuperclass();
-        while (superC != null && !superC.equals(Object.class)) {
-            if (superC.equals(clazz)) {
-                return true;
-            }
-            superC = superC.getSuperclass();
-        }
-        return false;
+        return clazz.isAssignableFrom(type);
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/TypeHelper.java]: Not sure why it wasn't this way before, considering this is a native (and much faster) method; and the old code was broken when dealing with an interface that extends another one (`getInterfaces()` returns only **direct** implemented interfaces); and when the interface was implemented by a super class.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java [hunk 2]
```diff
@@ -22,42 +22,14 @@
...
 
     private boolean isJUnit3Class;
     private boolean isJUnit4Class;
     private boolean isJUnit5Class;
 
-    static {
-        Class<?> c;
-
-        try {
-            c = Class.forName(JUNIT3_CLASS_NAME);
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java]: I guess, we have the same problem in [MoreThanOneLoggerRule](https://github.com/pmd/pmd/blob/70fc3d75bb018a333c4612fc5f37446d43b32844/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/MoreThanOneLoggerRule.java#L32)...

Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java]: I'll adjust this class the same way.

Comment (jsotuyod) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java]: Definitely! Good catch!
