### PR TITLE
[java] Fix for issue #816

### LINKED ISSUE #816: [java] SingleMethodSingleton false positives with inner classes
**Affects PMD Version:** 6.0.0

**Rule:** [`SingleMethodSingleton`](https://pmd.github.io/pmd-6.0.0/pmd_rules_java_errorprone.html#singlemethodsingleton)

**Description:** `SingleMethodSingleton` [uses a single `Set`](https://github.com/pmd/pmd/blob/pmd_releases/6.0.0/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingleMethodSingletonRule.java#L31) to determine if any duplication happened. But while traversing the AST multiple classes may be visited. I think that needs to be a `Map<Class, Method>`. (Also it should only warn for `static` methods.)

**Code Sample demonstrating the issue:**

```java
// real example that triggered this report
final class Outer {
  private static final Outer INSTANCE = new Outer();
  private Outer() {}
  static Outer getInstance() { return INSTANCE; }

  static class Factory {
    private static final Factory FACTORY = new Factory();
    private Factory() { }
    static Factory getInstance() { return FACTORY; }
  }
}

// another possible scenario
final class Siblings {
  static class Inner1 {
    static Inner1 getInstance() { return null; }
  }
  static class Inner2 {
    static Inner2 getInstance() { return null; }
  }
}
```
> Outer.java | 4 | Class contains multiple getInstance methods. Please review.
> Outer.java | 9 | Class contains multiple getInstance methods. Please review.
> Siblings.java | 3 | Class contains multiple getInstance methods. Please review.
> Siblings.java | 6 | Class contains multiple getInstance methods. Please review.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*: Gradle

### PR DESCRIPTION
**Pull request by akshatbahety**
Fixed the issue with traversing the tree and checking out if the getInstance method is used twice under the same class.
Fixes #816 

**PR Description:**
It checks the AST in from top to bottom getting to check the names of methods and making sure that only one method with the same name is present there. In this regard "getInstance()"

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingleMethodSingletonRule.java [hunk 1]
```diff
@@ -4,35 +4,58 @@
...
 
-    @Override
-    public Object visit(ASTMethodDeclaration node, Object data) {
-        if (node.getResultType().isVoid()) {
-            return super.visit(node, data);
-        }
+    public Object visit(ASTClassOrInterfaceDeclaration node, Object data) {
+
+        String a = node.getImage(); // Get the name of the Class it's part of
+        System.out.println(a);
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingleMethodSingletonRule.java]: this seems like a leftover from debugging, please remove it

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingleMethodSingletonRule.java [hunk 2]
```diff
@@ -4,35 +4,58 @@
...
 
-        if ("getInstance".equals(node.getMethodName())) {
-            if (!methodset.add(node.getMethodName())) {
-                addViolation(data, node);
+        List<ASTMethodDeclaration> methods = node.findDescendantsOfType(ASTMethodDeclaration.class); // Find the name of methods in it
+
+        System.out.println(methods);
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingleMethodSingletonRule.java]: ditto

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingleMethodSingletonRule.java [hunk 3]
```diff
@@ -4,35 +4,58 @@
...
+
+        int count = 0;
+        for (ASTMethodDeclaration method : methods) {
+
+            System.out.println(method.getName());
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingleMethodSingletonRule.java]: ditto

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingleMethodSingletonRule.java [hunk 4]
```diff
@@ -4,35 +4,58 @@
...
+            if (method.getName().equals("getInstance")) {
+                count++;
             }
+
         }
 
+        if (count > 1) {
+            System.out.println("error");
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingleMethodSingletonRule.java]: ditto

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingleMethodSingletonRule.java [hunk 5]
```diff
@@ -4,35 +4,58 @@
...
+        List<ASTMethodDeclaration> methods = node.findDescendantsOfType(ASTMethodDeclaration.class); // Find the name of methods in it
+
+        System.out.println(methods);
+
+        int count = 0;
+        for (ASTMethodDeclaration method : methods) {
+
+            System.out.println(method.getName());
+            if (method.getName().equals("getInstance")) {
+                count++;
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingleMethodSingletonRule.java]: we could check for the value of `count` right here, and report the violation / break if over 1, no need to keep looking at all methods
