### PR TITLE
[java] Fix false positive in UnnecessaryLocalBeforeReturn with method references

### LINKED ISSUE #2167: [java] UnnecessaryLocalBeforeReturn false positive with variable captured by method reference
For example:

```java
    public Supplier<Object> create() {
        final Object o = new Object();
        return o::clone; // violation
    }
```

`o` is captured, and keeping its declaration separate keeps the code readable (more so with a more complicated RHS).

### PR DESCRIPTION
**Pull request by oowekyala**
Fix #2167

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 2 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/6dc6ab6228fd42fa8f387ca9f3fae3f3/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeReturnRule.java [hunk 1]
```diff
@@ -134,7 +136,7 @@ private boolean isInitDataModifiedAfterInit(final VariableNameDeclaration variab
                             // Variable found! Check usage locations
                             for (final NameOccurrence occ : entry.getValue()) {
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeReturnRule.java:137]: I know this is really old… but I just realized, we are checking the symbol table, and it hadn't picked up the usage in member selection. Even though we fixed the rule, we still seem to have a bug in the symbol table for PMD 6 / a new test case for the PMD 7 rework
