### PR TITLE
[java] UnusedLocalVariable: fix false positive with guard in switch

### LINKED ISSUE #6257: [java] UnusedLocalVariable: False positive with instanceof pattern guard
**Affects PMD Version:** 

7.18.0

**Rule:**
[UnusedLocalVariable](https://pmd.github.io/pmd/pmd_rules_java_bestpractices.html#unusedlocalvariable)

**Description:**

When using an instanceof guard with pattern matching in a switch expression, then the local variable matched by that pattern will be marked as unused by PMD.

**Code Sample demonstrating the issue:**

```java
public class Reproducer {
    public static boolean customEquals(Object foo, Object bar) {
        return switch (foo) {
            case String fooString when bar instanceof String barString -> fooString.equals(barString);
            default -> false;
        };
    }
}
```

**Expected outcome:**

PMD reports a violation at line 4, but that's wrong. That's a false positive.

**Running PMD through:** Gradle 9.2.1 and Java 21

### PR DESCRIPTION
**Pull request by zbynek**
## Describe the PR

Look for all pattern bindings in switch label.

## Related issues

- Fix #6257 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java [hunk 1]
```diff
@@ -387,7 +387,7 @@ private Void visitSwitch(ASTSwitchLike node, @NonNull ReferenceCtx ctx) {
                 ASTSwitchLabel label = branch.getLabel();
                 // collect all bindings. Maybe it's illegal to use composite label with bindings, idk
                 BindSet bindings =
-                    label.children(ASTPattern.class)
+                    label.descendants(ASTPattern.class)
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java]: I think this doesn't work properly as pattern bindings need to consider the boolean context in which they occur. Eg in
```java
switch (foo) {
  case String fooString when !(bar instanceof String barString) -> /* barString not in scope here */;
  default -> false;
};
```

The relevant JLS is [here](https://docs.oracle.com/javase/specs/jls/se25/html/jls-6.html#jls-6.3.3) (emphasis mine):
> A pattern variable is introduced by a guarded case label if it is introduced by the associated guard **when true** ([§6.3.1](https://docs.oracle.com/javase/specs/jls/se25/html/jls-6.html#jls-6.3.1)).

So this needs a slight change. On the one hand we should still explore the children (the label expressions), or rather the first one. On the other we need to put the bindings of the label expression in scope in the guard, and collect the _true_ bindings of the guard to put them in scope in the body of the branch.

Additionally, about the comment right above (`// collect all bindings. Maybe it's illegal to use composite label with bindings, idk`): this is in fact illegal. JLS 14.11.1 says the following:
> It is a compile-time error for a case label to have more than one case pattern and declare any pattern variables (other than those declared by a guard associated with the case label).
> ```java
> switch (obj) {
>  case Integer i, Boolean b -> {
>    ...       // Error! Is i or b initialized?
>  }
>  ...
> }
> ```

**Review by oowekyala — CHANGES_REQUESTED** [review]
Thanks for starting work on this, I think it needs a revision though

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java [hunk 2]
```diff
@@ -385,14 +386,17 @@ private Void visitSwitch(ASTSwitchLike node, @NonNull ReferenceCtx ctx) {
...
-                    label.children(ASTPattern.class)
+                // Collect all bindings. Composite label with bindings would be a compilation error.
+                BindSet bindings = label.children(ASTPattern.class)
                          .reduce(BindSet.EMPTY, (bindSet, pat) -> bindSet.union(bindersOfPattern(pat)));
 
                 // visit guarded patterns in label
                 int pushBindings = pushOnStack(f.localVarSymTable(top(), enclosing(), bindings.getTrueBindings()));
                 setTopSymbolTableAndVisit(label, ctx);
+                bindings = label.children(ASTGuard.class).reduce(BindSet.EMPTY,
+                        (bindSet, pat) -> bindSet.union(bindersOfExpr(pat.getGuard())));
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java]: Same here, as there is at most one guard:
```suggestion
                bindings = bindersOfExpr(label.children(ASTGuard.class).map(ASTGuard::getGuard).first());
```
I think `bindersOfExpr` already returns an empty BindSet when the param is null.
