### PR TITLE
[java] UselessParentheses: fix false positives for switch expressions

### LINKED ISSUE #6123: [java] `UselessParentheses` around `switch` expression
**Affects PMD Version:** 6.55.0, 7.13.0

**Rule:** [UselessParentheses](https://docs.pmd-code.org/pmd-doc-7.13.0/pmd_rules_java_codestyle.html#uselessparentheses)

**Description:**

When chaining a method call directly after a switch expression, the expression has to be wrapped into parentheses. Removing the parentheses is a syntax error (at least in Java 17.0.16). PMD detects this as a `UselessParentheses` rule violation.

**Code Sample demonstrating the issue:**

```java
public class Main {
  public enum E {
    A, B;
  }

  public static String foo(final E e) {
    return (switch (e) {
      case A -> "bar";
      case B -> "baz";
    }).toUpperCase();
  }
}
```

**Expected outcome:**

PMD shouldn't detect the parentheses around the switch expression as `UselessParentheses` violation.

**Running PMD through:** CLI and Gradle

### PR DESCRIPTION
**Pull request by zbynek**
## Describe the PR

Switch expressions should have parentheses when used in method call, field access or array access.

## Related issues

- Fix #6123 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UselessParenthesesRule.java [hunk 1]
```diff
@@ -111,10 +114,15 @@ public static Necessity needsParentheses(ASTExpression inner, JavaNode outer) {
...
 
-        if (inner instanceof ASTPrimaryExpression
-            || inner instanceof ASTSwitchExpression) {
+        if (inner instanceof ASTPrimaryExpression) {
             return NEVER;
         }
+        if (inner instanceof ASTSwitchExpression) {
+            return (outer instanceof ASTMethodCall
+                || outer instanceof ASTArrayAccess
+                || outer instanceof ASTFieldAccess) && inner.getIndexInParent() == 0
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UselessParenthesesRule.java]:
```suggestion
            return outer instanceof ASTPrimaryExpression && inner.getIndexInParent() == 0
```
