### PR TITLE
[java] CloseResource: false positive with reassignment detection

### LINKED ISSUE #2977: [java] CloseResource: false positive with reassignment detection
Rule: [CloseResource](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#closeresource)

Upgraded to 6.30.0, having previously been using 6.28.0.  Now seeing false positives with the CloseResource rule, with this contrived example:

```java
import java.io.RandomAccessFile;

public class FalsePositive {
    private boolean isHundredBytes = false;

    public void bar() throws Exception {
        RandomAccessFile file = null;
        try {
            file = new RandomAccessFile("name", "r");
            this.isHundredBytes = file.length() == 100;  /* violation here... */
        } finally {
            file.close();
        }
    }
}
```

### PR DESCRIPTION
**Pull request by adangel**
- fixes #2977

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 1 violations, 2 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/a7aec92c2a874fa49f2acd816fcf6baa/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java [hunk 1]
```diff
@@ -736,16 +736,21 @@ private boolean isAssignmentForVariable(ASTStatementExpression statement, ASTVar
...
-        NameDeclaration statementVariable = name.getNameDeclaration();
-        if (statementVariable == null) {
-            return false;
+
+        List<ASTAssignmentOperator> assignments = statement.findDescendantsOfType(ASTAssignmentOperator.class);
+        for (ASTAssignmentOperator assignment : assignments) {
+            // The sibling before the operator is the left hand side
+            JavaNode lhs = assignment.getParent().getChild(assignment.getIndexInParent() - 1);
+
+            ASTName name = lhs.getFirstDescendantOfType(ASTName.class);
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java:745]: Not sure if this is important, but this `descendants` check could misinterpret `array[...] = ...`, because it will fetch the name of the array.

Might be worth figuring out a test case

Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java]: I've tested it a bit and I don't think, that's relevant: If the variable we search here would actually be an array, we wouldn't search it in the first place, because then it is not autocloseable.
