### PR TITLE
[core] Add error recovery mode

### LINKED ISSUE #2885: [core] Error recovery mode
It's probably not a super good idea to recover from StackOverflowErrors in all cases (#2808). Possibly, we could be leaving some external library in an inconsistent state. However, for a developer of PMD, it may be useful to do so, so that the error ends up in a report, or so that more errors can be discovered by continuing the run.

So we could have a "debug" mode that tries to be more error tolerant, but which is not the default behavior. This could be used in tests, and in particular, for the regression tester. This could also be useful for bug reports ("run pmd with these options and paste the report").

As a first step we could enable such a "debug" mode with a system property (`PMD_JAVA_OPTS=”-Derror_recovery -ea” run.sh ...`). 

If it's worth it we could also add a CLI switch for that, eg `-Xerror_recovery`. Other obscure system properties we use to enable advanced logging (like the Java type inference logger) could be added as switches too.

### PR DESCRIPTION
**Pull request by adangel**
This can be enabled by setting system property "pmd.error_recovery"
to an arbitrary value, e.g. "-Dpmd.error_recovery".

Next step is, to add enable this in our regression tester by default (setting both "-Dpmd.error_recovery" and "-ea" for assertions).

## Related issues

- Fixes #2885

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Running pmdtester failed, this message is mainly used to remind the maintainers of PMD.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-core/src/main/java/net/sourceforge/pmd/internal/SystemProps.java [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+public final class SystemProps {
+
+    public static final String PMD_ERROR_RECOVERY = "pmd.error_recovery";
+
+    private SystemProps() {
+    }
+
+    /**
+     * In error recovery mode errors like StackOverflowError or AssetionErrors are logged
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/internal/SystemProps.java:15]:
```suggestion
     * In error recovery mode errors like StackOverflowError or AssertionErrors are logged
```

**Review by oowekyala — APPROVED** [review]
Very cool, thanks, especially for the tests !

**Comment by oowekyala** [comment]
For reference, the TODO item about documenting this feature is [on the wiki](https://github.com/pmd/pmd/wiki/PMD-7.0.0-API#cli-api)
