### PR TITLE
[java] Fix #5293: Parse number of type parameters eagerly

### LINKED ISSUE #5293: Deadlock when executing PMD
**Affects PMD Version:** 

7.7.0, 7.6.0
probably all releases in recent time

**Description:**

Initial report was done here: 

We are executing the following on a multi-Maven project:
``mvn -B test pmd:check -P pmd -DskipTests``

Which causes a deadlock:
MvnPMDDeadlock

The problem is likely caused by some unfortunate CPU situation that only occurs on certain machines with certain code and is therefore extremely difficult to reproduce.

<details><summary>Summary from the <a href="https://issues.apache.org/jira/browse/MPMD-408">initial maven issue</a></summary>

> **michael-o**
> Does a downgrade help?

> **AB-xdev**
> @ michael-o
> I'm currently checking the exact cause as we got a ton of Maven plugin updates over the weekend.
> Maybe also one of those broke it...

> **AB-xdev** 
> Okay my conclusions so far: This is probably not related to the PMD version
>
> I downgraded to a state before the update and the same error also occurs randomly.
> I was unable to reproduce or find the problem ín any of our ~50 CIs so this must be caused either by
> * Windows
> * hardware configuration
> * anti-virus solution
>
> However as of now I think this is a hardware configuration based problem:
>
> * The problem also occurred with disabled anti-virus
> * I checked with a colleague which has nearly the same hardware as I but a different Windows version (10/11) and it also happened on his machine:
> screenshot-1
> Doing some further testing with thread configurations now...

> **AB-xdev**
> I was able to reproduce the problem with different maven parallelization/thread configurations (-T8, -T1, ...) on the same machine but not on others.
> The amount of spawned PMD threads does NOT depend on the selected maven parallelization and is ALWAYS the same amount as CPU threads ([Runtime.getRuntime().availableProcessors()](https://github.com/pmd/pmd/blob/4473aa666754f888ace372ec3d5ca183f6e0af23/pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java#L100)).
> It's likely some unfortunate CPU situation that only occurs on certain machines with certain code.
>
>I inspected another [Threaddump](https://github.com/user-attachments/files/17542449/Threaddump2.txt) further and as far as i can tell the problem is a legitimate PMD problem.
> It looks like multiple threads are started for analysis, which process different classes/pieces of code and walk through related code.
> While they are being processed the threads (sometimes) lock each other, resulting in a deadlock:
>
> Example from the Threaddump:
> ```
> Thread #1: Class A (locked) -> ... -> Class C (waits for lock from Thread #16)
> Thread #16: Class C (locked) -> Class A (waits for lock from Thread #1)
> → Deadlock
> ```
>
> (for more details see the deadlock section at the end of the attached Thread dump)

</details>

The key finding from the Maven issue is:

>I inspected another [Threaddump](https://github.com/user-attachments/files/17542449/Threaddump2.txt) further and as far as i can tell the problem is a legitimate PMD problem.
> It looks like multiple threads are started for analysis, which process different classes/pieces of code and walk through related code.
> While they are being processed the threads (sometimes) lock each other, resulting in a deadlock:
>
> Example from the Threaddump:
> ```
> Thread #1: Class A (locked) -> ... -> Class C (waits for lock from Thread #16)
> Thread #16: Class C (locked) -> Class A (waits for lock from Thread #1)
> → Deadlock
> ```

**Exception Stacktrace:**

Here a a few thread-dumps:
[Threaddump2.txt](https://github.com/user-attachments/files/17542449/Threaddump2.txt) (recommended dump)
[Threaddump.txt](https://github.com/user-attachments/files/17542447/Threaddump.txt)
[Threaddump_colleague.txt](https://github.com/user-attachments/files/17542448/Threaddump_colleague.txt)

**Steps to reproduce:**

Reproducing the bug is next to impossible, I could only do so on machines with similar hardware.
However here are a few steps that can be followed:

1. Get a recently complex maven project that uses PMD
2. Run  ``mvn -B test pmd:check -P pmd -DskipTests `` (maybe also with ``-T2C``) with an insanely high CPU count: ``-XX:ActiveProcessorCount=64``

**Running PMD through:** * Maven*

Java version: 21.0.5, vendor: Eclipse Adoptium
aka OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Windows 10 & 11
CPU: AMD Ryzen 3700X (8C/16T)
Private Multi Maven Project with around 15 modules and 30k LoC

### PR DESCRIPTION
**Pull request by adangel**
## Describe the PR

When creating a LazyClassSignature or LazyMethodType, make sure
to parse the number of type parameters eagerly, so that AstDisambiguationPass
can get this number without triggering additional parsing.

## Related issues

- Fixes #5293

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java [hunk 1]
```diff
@@ -315,9 +310,9 @@ public List<JTypeVar> getTypeParameters() {
     }
 
     @Override
-    public boolean isGeneric() {
+    public int getTypeParameterCount() {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java:313]: We implement getTypeParameterCount() explicitly for ClassStub (the default impl would call signature.getTypeParameters().size() which would trigger the full parsing of the signature).

Note: the default impl of isGeneric() is good enough and uses just the type parameter count. So, no need to override it here.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java [hunk 2]
```diff
@@ -84,12 +84,7 @@ private static boolean isValidInternalName(String internalName) {
         this.resolver = resolver;
         this.names = new Names(internalName);
 
-        this.parseLock = new ParseLock() {
-            // note to devs: to debug the parsing logic you might have
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java:88]: The toString() method in ClassStub already as a comment about avoiding full parsing logic in debug mode. So, this comment is not necessary anymore here.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/GenericSigBase.java [hunk 3]
```diff
@@ -81,7 +81,11 @@ protected final void ensureParsed() {
 
     protected abstract boolean postCondition();
 
-    protected abstract boolean isGeneric();
+    protected abstract int getTypeParameterCount();
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/GenericSigBase.java:84]: Each GenericSigBase impl must provide a implementation for getTypeParameterCount()

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/GenericSigBase.java [hunk 4]
```diff
@@ -116,8 +121,9 @@ static class LazyClassSignature extends GenericSigBase<ClassStub> {
                            @Nullable String signature, // null if doesn't use generics in header
                            @Nullable String superInternalName, // null if this is the Object class
                            String[] interfaces) {
-            super(ctx);
+            super(ctx, "LazyClassSignature:" + ctx.getInternalName() + "[" + signature + "]");
             this.signature = signature;
+            this.typeParameterCount = GenericTypeParameterCounter.determineTypeParameterCount(this.signature);
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/GenericSigBase.java:126]: Here we parse partially the signature already to determine the type parameter count. That way, we know the number of types, without the need to know the exact types of the type parameters.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/GenericSigBase.java [hunk 5]
```diff
@@ -157,8 +163,9 @@ protected void doParse() {
         }
 
         @Override
-        protected boolean isGeneric() {
-            return signature != null && TypeParamsParser.hasTypeParams(signature);
+        protected int getTypeParameterCount() {
+            // note: no ensureParsed() needed, the type parameters are counted eagerly
+            return typeParameterCount;
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/GenericSigBase.java:168]: Note: you can easily recreate the bug by adding `ensureParsed()` here...

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to main:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/11662339000?pr=5309">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/DeadlockTest.java [hunk 6]
```diff
@@ -0,0 +1,157 @@
...
+        }
+
+        And then, introduce a bug again. One way to make the test fail is:
+        Comment out the method "public int getTypeParameterCount()", so that it is inherited again.
+        Add the following method:
+            @Override
+            public boolean isGeneric() {
+                parseLock.ensureParsed();
+                return signature.isGeneric();
+            }
```
Comment (adangel) [inline pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/DeadlockTest.java:83]: btw. I have no idea, why adding this method would reintroduce the deadlock. At least, the test seems to detect this, in case we accidentally add the deadlock again...
