### PR TITLE
[java] Fix #2996 - CommentSize/CommentContent suppression

### LINKED ISSUE #2996: [java] CommentSize rule violation is not suppressed at method level
**Affects PMD Version:** 
6.30.0

**Rule:** [CommentSize](https://docs.pmd-code.org/latest/pmd_rules_java_documentation.html#commentsize)

**Description:**
Violations of rule CommentSize are not suppressed by the annotations @SuppressWarnings("PMD.CommentSize") or @SuppressWarnings("PMD") when placed on the method definition.

**Code Sample demonstrating the issue:**

```java
package pmdtests;

public final class TestComment {
  @SuppressWarnings("PMD.CommentSize")
  private TestComment() {
    /*
     * Writing and maintaining complicated software is a difficult task,
     * and every programmer inadvertently makes mistakes.
     * Usually these are minor typographical errors that will be caught at
     * compile time, but others may remain undetected until the system is in production.
     * In the most extreme cases, the bug will cause system failure, as was the case in
     * the massive blackout in the Northeast last summer.
     * In addition to the consequences of system malfunction,
     * software defects have a substantial financial cost.
     * A 2003 report from the National Institute of Standards and Technology (NIST)
     * calculated the total annual cost of bugs at nearly $60 billion.
     * The report also confirmed what most developers already know:
     * the difficulty and cost of fixing a problem grows dramatically throughout the development cycle.
     * Although the report concluded that it is not practical to locate and remove all defects
     * from an application, it stated that nearly 40% could be eliminated by an improved inspection and testing
     * process.
     *
     * Two common methods for improving software quality are code reviews and automated
     * testing. The goal of both is to detect mistakes, but the distinction between them
     * is how this is achieved. Automated testing attempts to expose problems by executing
     * the code, while reviews rely on "another set of eyes" to verify that it's correct.
     * Problems can arise when we get too involved with the code to be objective or to consider
     * unusual paths of execution. Certainly every programmer has at one time
     * spent hours trying to track down a problem only to have someone else spot it
     * immediately.
     */
    throw new UnsupportedOperationException(
        "This is a utility class and cannot be instantiated");
  }

  public static void main(String... args) {
    // empty main
  }
}


```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Referred from: https://github.com/pmd/pmd/discussions/2995

### PR DESCRIPTION
**Pull request by oowekyala**
## Describe the PR

Suppressing violations of comment related rules doesn't work well right now, because they are reported against the compilation unit node. This adds some utilities to be able to report violations on a specific token. The RuleContext finds the closest node to the token and uses that to look for suppression annotations. 

See also https://github.com/pmd/pmd/issues/2996#issuecomment-1254921605 

~Draft because probably other comment rules have the same problem.~

Java documentation rules have been updated, but there are two other PLSQL rules that still use the broken overload `addViolationWithPosition`. I think we can land this without necessarily updating those.

## Related issues

- Fixes #2996
- Refs #5039

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-core/src/main/java/net/sourceforge/pmd/reporting/RuleContext.java [hunk 1]
```diff
@@ -130,22 +134,43 @@ public void addViolationWithMessage(Node location, String message, Object... for
...
+     * as a format string for a {@link MessageFormat} and should hence use
+     * appropriate escapes. The given formatting arguments are used.
+     *
+     * @param reportable Location of the violation (node or token)
+     * @param astInfo    Info about the root of the tree ({@link Node#getAstInfo()})
+     * @param message    Violation message
+     * @param formatArgs Format arguments for the message
+     */
+    public void addViolationWithPosition(Reportable reportable, AstInfo<?> astInfo, FileLocation location,
+                                         String message, Object... formatArgs) {
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/reporting/RuleContext.java:160]: One problem I have with this is the unreadability of these overloads... Maybe this API could have a makeover? Maybe we should write it like that:
```java
ctx.report(at(node), fmt("msg", a, b))
ctx.report(at(token, astInfo, loc), msg, a, b)

// or

ctx.at(node).warnWithDefaultMsg();
ctx.at(node).warnWithDefaultMsg(arg1, arg2);
ctx.at(token, astInfo, loc).warnWithDefaultMsg();
ctx.at(token, astInfo, loc).warnWithDefaultMsg();
ctx.at(token, astInfo, loc).warn("Custom msg {0}", arg);
```

We could also probably dispense with the `token` and `astInfo` parameters with some magic (store the AstInfo in the RuleContext) and get
```java
ctx.at(loc).warn(...);
```
But apparently changing the construction of the RuleContext would require changing a bunch of test code... Just a small hurdle though if this is what we want.

@jsotuyod @adangel any thoughts?

Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/reporting/RuleContext.java:160]: Maybe we could implement it with a builder? Which could look like (similar to your suggestions):

```java
ctx.newViolation(message).withArgs(arg1, arg2).at(node);
ctx.newViolation(message).withArgs(arg1, arg2).at(token, astInfo);
```

In this example, `at(Reportable)` would actually add the ruleviolation to the rule context. We could also have a separate, explicit build method, which would allow to refine the location:

```java
ctx.newViolation(message).withArgs(arg1, arg2).at(node).atBeginLine(4).build();
```

This could be an additional API first, as an alternative to the overloads addViolation...

We could do it slightly different:

```java
new ViolationMessageBuilder().with(message).withArgs(arg).at(node).build(ctx);
```

Which would be then more separated from RuleContext, but honestly, I like it that the entry point for reporting violations is in rulecontext.

Comment (jsotuyod) [reply pmd-core/src/main/java/net/sourceforge/pmd/reporting/RuleContext.java:160]: Late to the party, but here are some thoughts:

1. I support the fluent API, I think it's a neat solution. Moreover, it's very flexible looking forward for adding things like #4327)
2. I feel shaping up that in this PR would be muddying the waters / delay getting this fixed, I'd recommend a separate PR.
3. Any fluent API needs to be flagged `@Experimental`, I'd not commit our first iteration to a stable public API.
4. Starting at `RuleContext` is the cleanest approach, I like it. This is irrespective of wether that is passed down directly or still obtained through `asCtx(data)` (again, separate issue / PR eventually).
5. I'd have the finalizer method be a verb (not `at`!), descriptive (ie: `warn()` or `report()`) and return `void` to avoid any ambiguity (*I've this `ViolationMessage` object, how do I report it? what do I do with it now?*
6. SLF4J v2 introduced it's own fluent API which may work as reference / inspiration: https://slf4j.org/manual.html#fluent

Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/reporting/RuleContext.java:160]: I've created #5039 to track this. I marked the new method as experimental with a disclaimer:

> This will probably never be stabilized, will instead be replaced by a fluent API or something to report violations. Do not use this outside of the PMD codebase. See https://github.com/pmd/pmd/issues/5039

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentContent.xml [hunk 2]
```diff
@@ -54,6 +54,37 @@ public class Foo {
     // doNothing
     public void doNothing() {
     }
+}
+        ]]></code>
+    </test-code>
+    <test-code>
+        <description>Suppression</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentContent.xml:61]:
```suggestion
        <description>#2996 Test Suppression</description>
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentSize.xml [hunk 3]
```diff
@@ -46,6 +46,47 @@ public class Foo {
 
     public void doNothing() {
     }
+}
+        ]]></code>
+    </test-code>
+    <test-code>
+        <description>Suppression</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentSize.xml:53]:
```suggestion
        <description>#2996 Test Suppression</description>
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentSize.xml [hunk 4]
```diff
@@ -46,6 +46,47 @@ public class Foo {
...
+        a
+        long
+        comment
+        */
+    }
+}
+        ]]></code>
+    </test-code>
+    <test-code>
+        <description>Not suppressed</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentSize.xml:74]:
```suggestion
        <description>#2996 Not suppressed</description>
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentSize.xml [hunk 5]
```diff
@@ -46,6 +46,47 @@ public class Foo {
...
+        <rule-property name="maxLines">2</rule-property>
+        <expected-problems>1</expected-problems>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentSize.xml:76]:
```suggestion
        <expected-problems>1</expected-problems>
        <expected-linenumbers>6</expected-linenumbers>
```

**Review by adangel — APPROVED** [review]
Thanks!

I'll update the small fixes myself and merge it aftwards.
