### PR TITLE
[java] UnusedPrivateMethod - fix false positive with lambdas

### LINKED ISSUE #4817: [java] UnusedPrivateMethod false-positive used in lambda
**Affects PMD Version:** 
7.0.0-rc4

**Rule:** [UnusedPrivateMethod](https://docs.pmd-code.org/latest/pmd_rules_java_bestpractices.html#unusedprivatemethod)

**Description:**

False-positive as `notCachedGetAllDps` is used

```
[INFO] --- maven-pmd-plugin:3.21.2:check (default-cli) @ web-test ---
[INFO] PMD version: 7.0.0-rc4
[INFO] PMD Failure: io.mitrust.backoffice.NotUsedPrivateMethodFalsePositive:15 Rule:UnusedPrivateMethod Priority:3 Avoid unused private methods such as 'notCachedGetAllDps(String)'
```

**Code Sample demonstrating the issue:**

```java
package io.mitrust.backoffice;

import java.util.Collections;
import java.util.List;

import com.google.common.cache.CacheBuilder;
import com.google.common.cache.CacheLoader;
import com.google.common.cache.LoadingCache;

public class NotUsedPrivateMethodFalsePositive {

    private final LoadingCache<String, List<? extends String>> clientIdsToDps = CacheBuilder.newBuilder()
            .build(CacheLoader.from(clientId -> notCachedGetAllDps(clientId)));

    private List<? extends String> notCachedGetAllDps(String clientId) {
        return Collections.singletonList(clientId);
    }

    public List<?> getClientIdsToDps() {
        return clientIdsToDps.getUnchecked("");
    }

}

```

**Expected outcome:**

PMD reports a violation at line ..., but that's wrong. That's a false positive.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

### PR DESCRIPTION
**Pull request by adangel**
- Fixes #4817

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java [hunk 1]
```diff
@@ -103,6 +104,25 @@ public Object visit(ASTCompilationUnit file, Object param) {
                         consideredNames.remove(methodName); // clear this name
                     }
                 }
+
+                // TODO workaround for missing method symbol resolution
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java:108]: did you try to solve the underlaying resolution issue? what issue did you run into doing so?

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 7 violations, 0 errors and 7 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/8097179684">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java (hunk 1 above)
Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java:108]: No, I didn't investigate that. In the debugger I saw, that the symbol we got here was net.sourceforge.pmd.lang.java.types.UnresolvedMethodSig.UnresolvedMethodSym

Comment (jsotuyod) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java:108]: I've been playing with this a little…

Either specifying the parameter type as `(String clientId) -> this.notCachedGetAllDps(clientId))` or using a method reference such as `this::notCachedGetAllDps` will not produce a FP.

When using `clientId -> this.notCachedGetAllDps(clientId))` it will infer `clientId` to be a `java.lang.Object`, and then test applicability of the method, which will fail, as `java.lang.Object` can't be used for `java.lang.String`.

The issue seems to be on how infered types for generics are propagated down to the `LambdaExpression`s `LambdaMirrorImpl`

**Comment by jsotuyod** [comment]
Ok, I've spent my whole Saturday juggling between the JLS and the code, but I think I'm starting to understand what the underlaying issue is…

Running this in verbose mode, we get some clues. The code runs in loop through the different stages, but takes care to understand which are invocation runs and which are not… mostly!

As it starts analyzing on the first STRICT phase looking for applicability of methods, it goes:

```
Phase STRICT           newBuilder() -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheBuilder<java.lang.Object, java.lang.Object>
    ARGUMENTS
    
    Success: newBuilder() -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheBuilder<java.lang.Object, java.lang.Object>
Skipping instantiation of net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheBuilder.newBuilder() -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheBuilder<java.lang.Object, java.lang.Object>, it's already complete
Phase STRICT           build(net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<? super X, Y>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.LoadingCache<X, Y>
    Context 3          build(net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<? super 'a, 'b>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.LoadingCache<'a, 'b>
    ARGUMENTS
        Phase STRICT           from(java.util.function.Function<K, V>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<K, V>
            Context 5          from(java.util.function.Function<'c, 'd>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<'c, 'd>
            ARGUMENTS
                Argument 0 is not pertinent to applicability
                    At:   file:13:37
                    Expr: clientId -> this.notCachedGetAllDps(clientId)
```

Effectively, an an implicitly typed lambda expression isn't pertitent to applicability as per [jls-15.12.2.2](https://docs.oracle.com/javase/specs/jls/se9/html/jls-15.html#jls-15.12.2.2). Therefore, applicability is decided by simply checking wether the `B2` set is reducible as per [jls-18.5.2.1](https://docs.oracle.com/javase/specs/jls/se9/html/jls-18.html#jls-18.5.2.1).

And so, the code performs a `boolean isDone = infCtx.solve(/*onlyBoundedVars:*/isPreJava8());`, and effectively, it is reducible…

```
            Ivar instantiated   (ctx 5):   'c := java.lang.Object
            Ivar instantiated   (ctx 5):   'd := java.lang.Object
            Success: from(java.util.function.Function<java.lang.Object, java.lang.Object>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<java.lang.Object, java.lang.Object>
```

So the inference moves, and it's now on invocation phase:

```
        Checking arg 0 against net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<? super 'a, 'b>
            At:   file:13:20
            Expr: CacheLoader.from(clientId -> this.notCachedGetAllDps(clientId))
            Phase INVOC_STRICT     from(java.util.function.Function<K, V>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<K, V>
                Context 7          from(java.util.function.Function<'e, 'f>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<'e, 'f>
                RETURN
                    New bound           (ctx 7):   'e >: 'a
                    New bound           (ctx 3):   'b = 'f
                
                ARGUMENTS
                    Checking arg 0 against java.util.function.Function<'e, 'f>
                        At:   file:13:37
                        Expr: clientId -> this.notCachedGetAllDps(clientId)
                    
                
                New bound           (ctx 3):   'a <: 'e
                Ctx 3 adopts ['e, 'f] from ctx 7
                Success: from(java.util.function.Function<'e, 'f>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<'e, 'f>
```

It set's the lambda's inferred type to a still partial type `java.util.function.Function<'e, 'f>`, and as this **is** an invocation run, sets a listener on the context waiting for resolution of `e` and `f`.

https://github.com/pmd/pmd/blob/8cc2d291da4053d1e64051fb334e07069cdc9cfb/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/ExprCheckHelper.java#L477-L482

Here is were things go south… as that inference bubbles up, we eventually get back to context 3 (the one being used in a `STRICT` evaluation looking for a match on the `build` method. The context 3 constraints start getting bubbled up and eventually reach context 7, which again, as is on an applicability test, will try to reduce `b2` to ensure applicability. Once again, this can be done by reducing `e` and `a` to `java.lang.Object` among other things:

```
    Ivar merged         (ctx 3):   'b <=> 'f
    Ivar instantiated   (ctx 3):   'a := java.lang.Object
    New bound           (ctx 3):   'e >: java.lang.Object
    Ivar instantiated   (ctx 3):   'e := java.lang.Object
```

But in context 3 we actually set listeners for the resolution of `e` and `f`, so we get a report that `e` is `java.lang.Object`, leaving the lambda's inferred type as `java.util.function.Function<java.lang.Object, 'f>`.

And so, as the algorithm moves forward…

```
    Phase STRICT           notCachedGetAllDps(java.lang.String) -> java.util.List<? extends java.lang.String>
        ARGUMENTS
            Checking arg 0 against java.lang.String
                At:   file:13:73
                Expr: clientId
                Failed: Incompatible formals: java.lang.Object is not convertible to java.lang.String
        FAILED! SAD!
```

It sees the lambda actually expects a `java.lang.String`, which doesn't fit with `java.util.function.Function<java.lang.Object, 'f>` and fails.

I'm not 100% sure yet, but I believe we need to split how `InferenceContext.solve` works, so that during applicability it's actually a `canSolve` vs actually solving it. Maybe just trying to solve on a copy of the context with no listeners can be enough…

This seems to be in compliance with the [jls-18.5.2](https://docs.oracle.com/javase/specs/jls/se9/html/jls-18.html#jls-18.5.2) where it reads:

> It is important to note that multiple "rounds" of inference are involved in finding the type of a method invocation. This is necessary, for example, to allow a target type to influence the type of the invocation without allowing it to influence the choice of an applicable method. *The first round ([§18.5.1](https://docs.oracle.com/javase/specs/jls/se9/html/jls-18.html#jls-18.5.1)) produces a bound set and tests that a resolution exists, but **does not commit** to that resolution.* Subsequent rounds reduce additional constraints until a final resolution step determines the "real" type of the expression.

I'll keep tinkering, but maybe this is enough for @oowekyala to know better…

**Comment by jsotuyod** [comment]
I did a **very** dirty test, and it seems to work… now I get this beautiful log without failures, and the FP is gone without changing the rule :yay:

```
Phase STRICT           newBuilder() -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheBuilder<java.lang.Object, java.lang.Object>
    ARGUMENTS
    
    Success: newBuilder() -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheBuilder<java.lang.Object, java.lang.Object>
Skipping instantiation of net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheBuilder.newBuilder() -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheBuilder<java.lang.Object, java.lang.Object>, it's already complete
Phase STRICT           build(net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<? super X, Y>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.LoadingCache<X, Y>
    Context 3          build(net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<? super 'a, 'b>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.LoadingCache<'a, 'b>
    ARGUMENTS
        Phase STRICT           from(java.util.function.Function<K, V>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<K, V>
            Context 5          from(java.util.function.Function<'c, 'd>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<'c, 'd>
            ARGUMENTS
                Argument 0 is not pertinent to applicability
                    At:   file:13:37
                    Expr: clientId -> this.notCachedGetAllDps(clientId)
                
            
            Success: from(java.util.function.Function<'c, 'd>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<'c, 'd>
        Checking arg 0 against net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<? super 'a, 'b>
            At:   file:13:20
            Expr: CacheLoader.from(clientId -> this.notCachedGetAllDps(clientId))
            Phase INVOC_STRICT     from(java.util.function.Function<K, V>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<K, V>
                Context 7          from(java.util.function.Function<'e, 'f>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<'e, 'f>
                RETURN
                    New bound           (ctx 7):   'e >: 'a
                    New bound           (ctx 3):   'b = 'f
                
                ARGUMENTS
                    Checking arg 0 against java.util.function.Function<'e, 'f>
                        At:   file:13:37
                        Expr: clientId -> this.notCachedGetAllDps(clientId)
                    
                
                New bound           (ctx 3):   'a <: 'e
                Ctx 3 adopts ['e, 'f] from ctx 7
                Success: from(java.util.function.Function<'e, 'f>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<'e, 'f>
        
    
    Ivar merged         (ctx 3):   'b <=> 'f
    Success: build(net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<? super 'a, 'f>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.LoadingCache<'a, 'f>
Phase INVOC_STRICT     build(net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<? super X, Y>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.LoadingCache<X, Y>
    Context 8          build(net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<? super 'g, 'h>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.LoadingCache<'g, 'h>
    RETURN
        New bound           (ctx 8):   'g = java.lang.String
        New bound           (ctx 8):   'h = java.util.List<? extends java.lang.String>
    
    ARGUMENTS
        Checking arg 0 against net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<? super 'g, 'h>
            At:   file:13:20
            Expr: CacheLoader.from(clientId -> this.notCachedGetAllDps(clientId))
            Phase INVOC_STRICT     from(java.util.function.Function<K, V>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<K, V>
                Context 11         from(java.util.function.Function<'i, 'j>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<'i, 'j>
                RETURN
                    New bound           (ctx 11):   'i >: 'g
                    New bound           (ctx 8):   'h = 'j
                
                ARGUMENTS
                    Checking arg 0 against java.util.function.Function<'i, 'j>
                        At:   file:13:37
                        Expr: clientId -> this.notCachedGetAllDps(clientId)
                    
                
                New bound           (ctx 8):   'g <: 'i
                Ctx 8 adopts ['i, 'j] from ctx 11
                Success: from(java.util.function.Function<'i, 'j>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<'i, 'j>
        
    
    New bound           (ctx 8):   'i >: java.lang.String
    New bound           (ctx 8):   'j = java.util.List<? extends java.lang.String>
    Ivar merged         (ctx 8):   'h <=> 'j
    Ivar instantiated   (ctx 8):   'g := java.lang.String
    Ivar instantiated   (ctx 8):   'i := java.lang.String
    Phase STRICT           notCachedGetAllDps(java.lang.String) -> java.util.List<? extends java.lang.String>
        ARGUMENTS
            Checking arg 0 against java.lang.String
                At:   file:13:73
                Expr: clientId
            
        
        Success: notCachedGetAllDps(java.lang.String) -> java.util.List<? extends java.lang.String>
    New bound           (ctx 8):   'j >: java.util.List<? extends java.lang.String>
    Skipping instantiation of net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.NotUsedPrivateMethodFalsePositive.notCachedGetAllDps(java.lang.String) -> java.util.List<? extends java.lang.String>, it's already complete
    Ivar instantiated   (ctx 8):   'h := java.util.List<? extends java.lang.String>
    Success: build(net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.CacheLoader<? super java.lang.String, java.util.List<? extends java.lang.String>>) -> net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.LoadingCache<java.lang.String, java.util.List<? extends java.lang.String>>
Phase STRICT           singletonList(T) -> java.util.List<T>
    Context 15         singletonList('k) -> java.util.List<'k>
    ARGUMENTS
        Checking arg 0 against 'k
            At:   file:16:42
            Expr: clientId
            New bound           (ctx 15):   'k >: java.lang.String
        
    
    Success: singletonList('k) -> java.util.List<'k>
Phase INVOC_STRICT     singletonList(T) -> java.util.List<T>
    Context 16         singletonList('l) -> java.util.List<'l>
    RETURN
        New bound           (ctx 16):   'l <: java.lang.String
    
    ARGUMENTS
        Checking arg 0 against 'l
            At:   file:16:42
            Expr: clientId
            New bound           (ctx 16):   'l >: java.lang.String
        
    
    Ivar instantiated   (ctx 16):   'l := java.lang.String
    Success: singletonList(java.lang.String) -> java.util.List<java.lang.String>
Phase STRICT           getUnchecked(java.lang.String) -> java.util.List<? extends java.lang.String>
    ARGUMENTS
        Checking arg 0 against java.lang.String
            At:   file:20:44
            Expr: \"\"
        
    
    Success: getUnchecked(java.lang.String) -> java.util.List<? extends java.lang.String>
Skipping instantiation of net.sourceforge.pmd.lang.java.rule.bestpractices.unusedprivatemethod.cache.LoadingCache<java.lang.String, java.util.List<? extends java.lang.String>>.getUnchecked(java.lang.String) -> java.util.List<? extends java.lang.String>, it's already complete
```

I'll clean it up, check a full build, and hopefully update this PR with it.

Interestingly, it is ~42% smaller, which hopefully also means this is actually faster, by avoiding several phases / runs by being more accurate… at least on this scenario.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/Infer.java [hunk 2]
```diff
@@ -561,52 +563,76 @@ private JMethodSig instantiateImpl(JMethodSig m, MethodCallSite site, MethodReso
...
-
-            if (isPreJava8() && !isDone) {
-                // this means we're not in an invocation context,
-                // if we are, we must ignore it in java 7
-                if (site.getOuterCtx().isEmpty()) {
-                    // Then add the return contraints late
-                    // Java 7 only uses the context type if the arguments are not enough
-                    // https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.12.2.8
-                    m = doReturnChecksAndChangeReturnType(m, site, infCtx);
+            // TODO : check why we allow some inferences to skip the invocation phase… maybe an optimization?
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/Infer.java:566]: @oowekyala I'd love your insights on this… I couldn't find in the JLS anything referring to this, so I assumed it was you being smart about when we actually needed another pass or not (given que old code committed changes in all phases).

If that's the case, this change should keep the behavior

**Comment by adangel** [comment]
@jsotuyod Awesome! Thanks for digging into this!

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/Infer.java (hunk 2 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/Infer.java:566]: So this is in fact an optimization but it is also very natural. Just like skipping type inference if a method is not generic.

In [JLS 18](https://docs.oracle.com/javase/specs/jls/se17/html/jls-18.html#jls-18.5.2) when they introduce invocation type inference, they mention that it is like regular invocation with possibly additional constraints. We skip invocation when we determine that there can be no additional constraints, so that the result of another round of invocation inference would be the same as the current result we have (because inference with the same constraints gives the same result).

I will try to review this PR shortly and understand better what's going on...

**Comment by adangel** [comment]
I had a look at the regression report now:

- :+1: we don't introduce new violations, or remove unintended violations. That means, this change didn't affect other rules.
- :-1: :question: Not sure, if we should keep digging here: My initial commit removed a couple of false positives (removes 7 violations). At least, I assumed, these were actual false positives:
  - https://github.com/openjdk/jdk/tree/jdk-11+28/src/java.base/share/classes/java/lang/Integer.java#L170 'toStringUTF16(int, int)'
  - https://github.com/openjdk/jdk/tree/jdk-11+28/src/java.base/share/classes/java/lang/Integer.java#L338 'toUnsignedString0(int, int)'
  - https://github.com/openjdk/jdk/tree/jdk-11+28/src/java.base/share/classes/java/lang/Integer.java#L389 'formatUnsignedIntUTF16(int, int, byte[], int, int)'
  - https://github.com/openjdk/jdk/tree/jdk-11+28/src/java.base/share/classes/java/lang/Long.java#L154 'toStringUTF16(long, int)'
  - https://github.com/openjdk/jdk/tree/jdk-11+28/src/java.base/share/classes/java/lang/Long.java#L241 'toUnsignedBigInteger(long)'
  - https://github.com/openjdk/jdk/tree/jdk-11+28/src/java.base/share/classes/java/lang/Long.java#L417 'formatUnsignedLong0UTF16(long, int, byte[], int, int)'
  - https://github.com/openjdk/jdk/tree/jdk-11+28/src/java.base/share/classes/java/lang/Object.java#L41 'registerNatives()'

We could also declare these false positives as a separate issue. Maybe we should - they all seem to be static methods...

I'll try to retest my test case for #4817 with the changes from here, to make sure, the original issue is indeed fixed (and the rule test case really works).

**Comment by jsotuyod** [comment]
@adangel good catch! I had completely missed that. And yes, there seems to be some issues with static methods, definitely worth having a separate issue to track and fix it regardless of wether we change the rule here or not.

The case for #4817 is still part of this PR, the additional test cases for the rule are in here and they pass. Or did you have an additional scenario?

**Comment by jsotuyod** [comment]
A very preliminar look into the FP on openjdk shows that the node is null not because inference failed, but because, as those classes (ie: `java.lang.Integer`) are part of the auxclasspath, they resolve to an ASM-backed symbol instead of an AST-backed symbol… and ASM-backed symbols can't reference the AST, so `tryGetNode()` returns `null`.

3 possible ways around this would be:
- Understand why ASM is prefered over AST-backed and see if it makes sense to switch over (probably there are performance issues at play, and ASM is objectively more reliable with things such as extending a class in a library).
- Change the rule to compare matches by `JMethodSig` instead of by node (this is in practice similar to what this PR tried, but without reimplementing arg-matching manually).

**Comment by adangel** [comment]
> The case for https://github.com/pmd/pmd/issues/4817 is still part of this PR, the additional test cases for the rule are in here and they pass. Or did you have an additional scenario?

I've tested it now (6.55.0 vs. 7.0.0-rc4 vs 7.0.0-SNAPSHOT)  - and #4817 is still fixed. So we are good (just wanted to double check, as the regression tester didn't show any changes anymore).

I'll create a separate issue for these static methods false positives now....

**Comment by adangel** [comment]
I'm going to merge this now. The original bug is fixed and there are no obvious side effects on other rules. In case we find a better/more correct solution, we can ship this improved code with the next version.

**Comment by oowekyala** [comment]
Yeah fwiw I fiddled around with the code and I also think this is a good solution. I think there might still problems with how we type resolve lambdas but well... For now it's the best thing we have. Thanks Juan for implementing this and Andreas for taking care it is merged!
