### PR TITLE
[java] Implement record patterns and fix switch pattern scoping

### LINKED ISSUE #5050: [java] Problems with pattern variables in switch branches
It seems there is an issue with the scope of pattern variables in switch branches. In the following, the variable `array` is undefined in the RHS of the branch:

```java
return switch (foo) {
	case char[] array -> new String(array);
	case String string -> string;
	default -> throw new Exception();
};
```

_Originally posted by @boris-petrov in https://github.com/pmd/pmd/issues/4874#issuecomment-2143520536_

### PR DESCRIPTION
**Pull request by oowekyala**
## Describe the PR

Fix some things around pattern matching/record support:
- Implement bindings for record patterns (was buggy and untested)
- Implement bindings in switch branches properly (fix #5050)
- Record patterns may contain TypePatterns whose type is inferred (with `var`), currently these were not being parsed properly
- Make ASTPattern a TypeNode
- Add a method to fetch record components from a symbol (ref #4335)
  - [x] todo this needs a test for the ASM implementation 

## Related issues

- Fixes #5050 
- Ref #4335

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 3 new violations, 0 new errors and 0 new configuration errors,<br />
removes 10 violations, 0 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/9382407019?pr=5051">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JRecordComponentSymbol.java [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+import net.sourceforge.pmd.lang.java.ast.ASTRecordComponent;
+import net.sourceforge.pmd.lang.java.types.JTypeMirror;
+import net.sourceforge.pmd.lang.java.types.Substitution;
+
+/**
+ * Represents a record component. Record components are associated
+ * with a private final {@link JFieldSymbol} and a public
+ * {@linkplain JMethodSymbol accessor method}.
+ *
+ * @since 7.0.0
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JRecordComponentSymbol.java:21]:
```suggestion
 * @since 7.3.0
```

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTRecordPattern.java [hunk 2]
```diff
@@ -29,13 +29,27 @@ protected <P, R> R acceptVisitor(JavaVisitor<? super P, ? extends R> visitor, P
...
+    }
+
+
+    /**
+     * Returns the declared variable.
+     *
+     * @deprecated This method was added here by mistake
+     */
+    @Deprecated
     public ASTVariableId getVarId() {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTRecordPattern.java:53]: TODO: For release notes

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/SymbolEquality.java [hunk 3]
```diff
@@ -176,6 +177,25 @@ public boolean equals(JFormalParamSymbol f1, Object o) {
...
+            return 31 * t1.getEnclosingClass().hashCode() + t1.getSimpleName().hashCode();
+        }
+
+        @Override
+        public boolean equals(JRecordComponentSymbol f1, Object o) {
+            if (!(o instanceof JRecordComponentSymbol)) {
+                return false;
+            }
+            JRecordComponentSymbol f2 = (JRecordComponentSymbol) o;
+            return f1.nameEquals(f2.getSimpleName())
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/SymbolEquality.java:193]:
```suggestion
            return Objects.equals(f1.getSimpleName(), f2.getSimpleName())
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java21/EnhancedTypeCheckingSwitch.txt [hunk 4]
```diff
@@ -72,7 +72,7 @@
          |        |        +- InfixExpression[@CompileTimeConstant = false, @Operator = BinaryOp.ADD, @ParenthesisDepth = 0, @Parenthesized = false]
          |        |           +- StringLiteral[@CompileTimeConstant = true, @ConstValue = "Color: ", @Empty = false, @Image = "\"Color: \"", @Length = 7, @LiteralText = "\"Color: \"", @ParenthesisDepth = 0, @Parenthesized = false, @TextBlock = false]
          |        |           +- MethodCall[@CompileTimeConstant = false, @Image = "toString", @MethodName = "toString", @ParenthesisDepth = 0, @Parenthesized = false]
-         |        |              +- AmbiguousName[@CompileTimeConstant = false, @Image = "c", @Name = "c", @ParenthesisDepth = 0, @Parenthesized = false]
+         |        |              +- VariableAccess[@AccessType = AccessType.READ, @CompileTimeConstant = false, @Image = "c", @Name = "c", @ParenthesisDepth = 0, @Parenthesized = false]
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java21/EnhancedTypeCheckingSwitch.txt:75]: :+1:

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/StringInstantiation.xml [hunk 5]
```diff
@@ -161,4 +161,19 @@ public class Foo {
 }
 ]]></code>
     </test-code>
+    <test-code>
+        <description>FP in switch</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/StringInstantiation.xml:165]:
```suggestion
        <description>FP in switch #5050</description>
```

**Review by adangel — APPROVED** [review]
Thanks!

I'll update it and merge it for 7.3.0

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/SymbolEquality.java (hunk 3 above)
Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/SymbolEquality.java:193]: Reason for this change: when reading this line, it is not clear that "nameEquals" actually means "simpleNameEquals" - better be explicit so that it is immediately clear that we compare the same attributes.

I'll change it for the other equal impls in this class as well. We used a mixture of nameEquals and Objects.equals already - so I'm changing it now for all to be Objects.equals.
