### PR TITLE
[xml] Replace synthetic proxy with static proxy for Xml nodes

### LINKED ISSUE #739: [xml] IllegalAccessException when accessing attribute using Saxon on JRE 9
Trying to use **Saxon and jre 9** to execute *any* xml xpath rule that accesses an attribute causes an IllegalAccessException. The attribute value is [defaulted to null](https://github.com/pmd/pmd/blob/ab80d18ff61d28bafdf8bece762d9385f0a6183b/pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/Attribute.java#L49).

```
java.lang.IllegalAccessException: class net.sourceforge.pmd.lang.ast.xpath.Attribute cannot access class com.sun.proxy.jdk.proxy2.$Proxy10 (in module jdk.proxy2) because module jdk.proxy2 does not export com.sun.proxy.jdk.proxy2 to unnamed module @59e84876
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at net.sourceforge.pmd.lang.ast.xpath.Attribute.getValue(Attribute.java:43)
	at net.sourceforge.pmd.lang.ast.xpath.saxon.AttributeNode.atomize(AttributeNode.java:50)
	at net.sf.saxon.om.AxisIteratorImpl.atomize(AxisIteratorImpl.java:74)
	at net.sf.saxon.expr.AxisAtomizingIterator.next(AxisAtomizingIterator.java:43)
	at net.sf.saxon.expr.ItemMappingIterator.next(ItemMappingIterator.java:39)
	at net.sf.saxon.expr.ItemMappingIterator.next(ItemMappingIterator.java:39)
	at net.sf.saxon.expr.CardinalityChecker.evaluateItem(CardinalityChecker.java:262)
	at net.sf.saxon.functions.Contains.evaluateItem(Contains.java:42)
	at net.sf.saxon.expr.Expression.iterate(Expression.java:370)
	at net.sf.saxon.expr.Expression.effectiveBooleanValue(Expression.java:421)
	at net.sf.saxon.functions.BooleanFn.effectiveBooleanValue(BooleanFn.java:179)
	at net.sf.saxon.expr.FilterIterator$NonNumeric.matches(FilterIterator.java:182)
	at net.sf.saxon.expr.FilterIterator.getNextMatchingItem(FilterIterator.java:65)
	at net.sf.saxon.expr.FilterIterator.next(FilterIterator.java:44)
	at net.sf.saxon.value.SequenceExtent.<init>(SequenceExtent.java:98)
	at net.sf.saxon.sort.DocumentOrderIterator.<init>(DocumentOrderIterator.java:30)
	at net.sf.saxon.sort.DocumentSorter.iterate(DocumentSorter.java:85)
	at net.sf.saxon.sxpath.XPathExpression.evaluate(XPathExpression.java:98)
	at net.sourceforge.pmd.lang.rule.xpath.SaxonXPathRuleQuery.evaluate(SaxonXPathRuleQuery.java:116)
	at net.sourceforge.pmd.lang.rule.XPathRule.evaluate(XPathRule.java:93)
	at net.sourceforge.pmd.lang.rule.XPathRule.apply(XPathRule.java:78)
	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:473)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:143)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:181)
```

After some digging I found [this relevant resource](https://docs.oracle.com/javase/9/docs/api/java/lang/reflect/Proxy.html#membership). I think we may be in case 2.a : [the proxy](https://github.com/pmd/pmd/blob/ab80d18ff61d28bafdf8bece762d9385f0a6183b/pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlParser.java#L87) we use lives in a dynamic module, (here named jdk.proxy2) which makes it inaccessible to the unnamed package (in which the code of pmd currently lives I guess).

### PR DESCRIPTION
**Pull request by oowekyala**
Fixes #739

### CODE REVIEW

File: pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlParser.java [hunk 1]
```diff
@@ -65,35 +64,31 @@ protected Document parseDocument(Reader reader) throws ParseException {
...
 
-    public void addAllInterfaces(Set<Class<?>> interfaces, Class<?> clazz) {
-        interfaces.addAll(Arrays.asList(clazz.getInterfaces()));
-        if (clazz.getSuperclass() != null) {
-            addAllInterfaces(interfaces, clazz.getSuperclass());
+
+    /**
+     * The root should implement {@link RootNode}.
+     */
+    public class RootXmlNode extends XmlNodeWrapper implements RootNode {
```
Comment (jsotuyod) [inline pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlParser.java]: this class should be static

File: pmd-xml/src/main/resources/category/pom/errorprone.xml [hunk 2]
```diff
@@ -25,14 +25,17 @@ The following types are considered valid: pom, jar, maven-plugin, ejb, war, ear,
...
-//dependencyManagement/dependency/type/text[not(contains('pom, jar, maven-plugin, ejb, war, ear, rar, par',@Image))]
+                    <![CDATA[
+//dependencyManagement/dependency/type/text[not(@Image = $validTypes)]
 ]]>
                 </value>
             </property>
-            <!-- FIXME: property injection seems to be failing with XML.... -->
-            <!-- property name="validTypes" value="pom, jar, maven-plugin, ejb, war, ear, rar, par" description="Set of valid types."-->
-            <!-- Then use as message: "By default, Maven only recognizes the following types: $validTypes." -->
+            <property name="version" value="2.0"/>
```
Comment (jsotuyod) [inline pmd-xml/src/main/resources/category/pom/errorprone.xml]: I'd leave a proper comment as to way this needs to be an xpath 2 rule

File: pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlParser.java [hunk 3]
```diff
@@ -65,35 +64,31 @@ protected Document parseDocument(Reader reader) throws ParseException {
...
-        if (proxy != null) {
-            return proxy;
-        }
 
-        // TODO Change Parser interface to take ClassLoader?
-        LinkedHashSet<Class<?>> interfaces = new LinkedHashSet<>();
-        interfaces.add(XmlNode.class);
-        if (node instanceof Document) {
-            interfaces.add(RootNode.class);
+    public XmlNode wrapDomNode(org.w3c.dom.Node domNode) {
```
Comment (jsotuyod) [inline pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlParser.java]: why is this method public?

Comment (oowekyala) [reply pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlParser.java]: I didn't think about it, it could be package private

File: pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlParser.java (hunk 1 above)
Comment (oowekyala) [reply pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlParser.java]: Good catch
