### PR TITLE
[test] Properly reset log level in slf4j-simple

### LINKED ISSUE #4234: [test] Tests that change the logging level do not work
**Affects PMD Version:** 7.0.x - because of SLF4J #896 

**Description:**

There are a couple of tests that change the logging level in the pmd 7 branch, to test the `--debug` cli switch for instance:
https://github.com/pmd/pmd/blob/1f43af7d831e5b2d63b13d5b2c8f22916609379a/pmd-cli/src/test/java/net/sourceforge/pmd/cli/PmdCliTest.java#L174

I'm afraid this only works by chance... When the trace level is enabled we are supposed to see log statements like `Adding file ...` from the file collector. If you add an assert like `assertThat(log, containsString("Adding file"));` to the linked test you will see that it fails, but only if you run the entire test class (not just the given test).

The problem is that when we reinitialize the log level in [Slf4jSimpleConfiguration](https://github.com/pmd/pmd/blob/c0536d5cb99445d5e4aa59b50c8630aeaaec1a32/pmd-core/src/main/java/net/sourceforge/pmd/internal/Slf4jSimpleConfiguration.java#L42), that doesn't change the log level of loggers that have already been created. This reset routine calls two methods via reflection:
- `org.slf4j.impl.SimpleLogger#init`: this parses system properties and changes the default logging level of the logger factory, meaning, *new* loggers will use that log level
- `org.slf4j.impl.SimpleLoggerFactory#reset`: this clears the `Map<String, Logger>` that caches loggers that have already been created. So the next time eg `LoggerFactory.getLogger(FileCollector.class)` is called, it will get a new logger with the correct new logging level.

The problem is that we create logger instances only once, and then store them in static final fields:
https://github.com/pmd/pmd/blob/dd96116c3150730101db7ee9065f6a6709595576/pmd-core/src/main/java/net/sourceforge/pmd/lang/document/FileCollector.java#L52

The call to `LoggerFactory` is executed only once in a given VM, and the created logger will use whatever default log level is defined at that point. But if you later change the log level with the reset method, the logger of `FileCollector` will be the same in that static field, and will still use the old log level.

This makes it significantly harder to test the behavior of the CLI with this debug flag... Tests are order dependent.

For instance in this test class:
https://github.com/pmd/pmd/blob/29d31ec8d22b4fedaf72c8e148ee345bd5c90e87/pmd-java/src/test/java/net/sourceforge/pmd/cli/CLITest.java#L68-L70

This test apparently succeeds, but it's only because by chance, the first test that gets executed in this class uses the `--debug` flag. All other tests then actually observe TRACE and DEBUG level log statements, even those that don't use the `--debug` flag. For instance this is the log of the `testWrongRuleset` test in this class, which doesn't use the debug flag:
```
[main] INFO net.sourceforge.pmd.PMD - Log level is at INFO
[main] DEBUG net.sourceforge.pmd.internal.util.FileCollectionUtil - Adding directory src/test/resources/net/sourceforge/pmd/cli.
[main] TRACE net.sourceforge.pmd.lang.document.FileCollector - Adding file /home/clem/Documents/Git/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/cli/EmptyIfStatement.java (lang: java 19) 
```
We announce that the log level is INFO, even though the level of other internal loggers actually stayed at TRACE.

#### Possible solutions

1. Maybe we should never store loggers in final fields, but always call `LoggerFactory.getLogger`? This would work but would probably be bad for performance, because `getLogger` performs a lookup in a ConcurrentMap.
1. Maybe we can ask the test runner to fork a JVM for each test?
1. A hacky fix: instead of calling `SimpleLoggerFactory#reset` and clearing the logger cache, we could
   - fetch the map field by reflection
   - iterate through all the loggers currently alive
   - set their log level field by reflection

This third item seems to me like the easiest thing to do... @adangel wdyt?

### PR DESCRIPTION
**Pull request by oowekyala**
## Describe the PR

Reset log level of already created loggers via reflection. This increases our coupling to slf4j-simple internals, but it really only changes anything in VMs that run multiple instances of PMD one after the other (presumably, mostly our tests).

## Related issues

- Fix #4234
- Unblocks #4060 and #4235

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-core/src/main/java/net/sourceforge/pmd/internal/Slf4jSimpleConfiguration.java [hunk 1]
```diff
@@ -41,19 +44,42 @@ public static void reconfigureDefaultLogLevel(Level level) {
...
+        configParamsField.setAccessible(true);
+        Object configParams = configParamsField.get(null);
+        Field defaultLogLevelField = configParams.getClass().getDeclaredField("defaultLogLevel");
+        defaultLogLevelField.setAccessible(true);
+        return (int) defaultLogLevelField.get(configParams);
+    }
+
     public static Level getDefaultLogLevel() {
-        Logger rootLogger = LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
+        Logger rootLogger = LoggerFactory.getLogger(PMD_ROOT_LOGGER);
```
Comment (adangel) [inline pmd-core/src/main/java/net/sourceforge/pmd/internal/Slf4jSimpleConfiguration.java:82]: It probably doesn't make a big difference in practice (only if someone indeed confiugres the logging via simplelogger.properties), but only the root logger would have the default log level. The pmd root logger (`net.sourceforge.pmd`) could have a different log level configured.
So, I'd leave it as before.

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to pmd/7.0.x:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/a158a8d7d0ef4d7c802355e6d07a160a/diff1/index.html">Full report</a></td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 49576 violations,<br />
introduces 33947 new violations, 1446 new errors and 0 new configuration errors,<br />
removes 195311 violations, 4 errors and 7 configuration errors.<br />
<a href="https://chunk.io/pmd/a158a8d7d0ef4d7c802355e6d07a160a/diff2/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by adangel — APPROVED** [review]
I think, that's the correct fix for now.
Maybe at some point, we can move this code to pmd-cli, where we have a compile time dependency on slf4j-simple, so we don't need reflection.

For some reason, the build doesn't work on Windows anymore. When I try it in my Windows VM, the build gets stuck on CoreCliTest (pmd-core). So, for me it fails because of a different reason (maybe?).
Looking at the log on github, something is happening here with that test:

```
2022-12-19T15:35:49.1325048Z [INFO] Running net.sourceforge.pmd.cli.CoreCliTest
2022-12-19T15:36:07.2397490Z [ERROR] [SUREFIRE] std/in stream corrupted
2022-12-19T15:36:12.2205109Z [INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.128 s - in net.sourceforge.pmd.cli.CoreCliTest
```

It has something to do with the progress bar - I remember disabling once in all cli tests the progress bar, to get it building again under windows. Not sure, why that wasn't a problem yet on Github actions.
The progressbar somehow messes with system.out, which surefire also uses...

If it helps, here's the stacktrace when it is stuck for me:

```
"main" #1 prio=5 os_prio=0 cpu=14171.88ms elapsed=158.72s tid=0x00000181123bb800 nid=0x1e30 runnable  [0x00000065d1bfb000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(java.base@11.0.13/Native Method)
        at java.io.FileInputStream.read(java.base@11.0.13/FileInputStream.java:279)
        at java.io.BufferedInputStream.fill(java.base@11.0.13/BufferedInputStream.java:252)
        at java.io.BufferedInputStream.read(java.base@11.0.13/BufferedInputStream.java:271)
        - locked <0x00000000e0278440> (a java.io.BufferedInputStream)
        at org.jline.utils.ExecHelper.waitAndCapture(ExecHelper.java:58)
        at org.jline.utils.ExecHelper.exec(ExecHelper.java:36)
        at org.jline.terminal.impl.ExecPty.current(ExecPty.java:41)
        at org.jline.terminal.TerminalBuilder$TerminalBuilderSupport.<init>(TerminalBuilder.java:567)
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:330)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:271)
        at me.tongfei.progressbar.TerminalUtils.getTerminal(TerminalUtils.java:83)
        at me.tongfei.progressbar.TerminalUtils.getTerminalWidth(TerminalUtils.java:28)
        - locked <0x00000000e0145aa8> (a java.lang.Class for me.tongfei.progressbar.TerminalUtils)
        at me.tongfei.progressbar.DelegatingProgressBarConsumer.<init>(DelegatingProgressBarConsumer.java:16)
        at net.sourceforge.pmd.cli.internal.ProgressBarListener.<init>(ProgressBarListener.java:35)
        at net.sourceforge.pmd.PmdAnalysis.performAnalysisImpl(PmdAnalysis.java:285)
```

**Comment by adangel** [comment]
I'll give it a try to disable the progress bar for the tests with `--no-progress`. Maybe that's enough to get it building under Windows again. Hopefully, this doesn't create a conflict with #4235 ...
If it works, I'll merge this PR then.

**Comment by adangel** [comment]
Seems to be ok now - I'll merge this now.

Note: Regarding the potential conflicts with #4235 - the two files (CliTest in pmd-java and CoreCliTest in pmd-core) are being deleted - and my changes here are irrelevant: As far as I see, the option `--no-progress` has been added now by default to all cli tests, so we should not run into the same problem.

**Comment by oowekyala** [comment]
Thanks for looking into this issue and merging. I'll update the other PRs
