### PR TITLE
[java] Make yield statements more conditional

### LINKED ISSUE #2319: [java] Parse errors with yield statement
**Affects PMD Version:** 6.21.0

**Description:** Our parser is not conservative enough when it comes to parsing yield statements. For now javac has the following behaviour:
- [ ] yield *may* only start a yield statement inside a switch
- [ ] even in this case, yield is only tokenized as a statement if it's followed by a token that may start an expression (eg not `=`), allowing `yield = 0;` to parse as an assignment
- [ ] if it's followed by an opening parenthesis, javac counts the commas (balancing parentheses), to allow eg `yield(a,b);` or `yield((a),b);` to parse as method calls

https://hg.openjdk.java.net/jdk/jdk/file/bc3da0226ffa/src/jdk.compiler/share/classes/com/sun/tools/javac/parser/JavacParser.java#l2580

**Code Sample demonstrating the issue:**

```java
class Foo {
 {
  int yield = 0;
  yield = 0; // not even inside a switch  (currently an error)
  yield(2);  // not even inside a switch, should be a method call  (currently an error)

  switch (e) {
    case 1 -> {
       yield(a,b); // should be a method call     (currently an error)
       yield = 2;  // should be an assignment     (currently an error)
       yield (2);  // should be a yield statement (currently ok)
    }
  }
 }
}
```

The parse exception is either `yield statements are only supported on java 13 preview` or 
```
Encountered "=" at line ....
Was expecting one of:
    "++" ...
    "--" ...
    "+" ...
    "-" ... 
```

### PR DESCRIPTION
**Pull request by oowekyala**
Fix #2319

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 13 new errors and 0 new configuration errors,<br />
removes 0 violations, 13 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/e6788659205543d0b399acdfd065396c/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java [hunk 1]
```diff
@@ -284,7 +284,7 @@
      * @return List of all children of type targetType. Returns an empty list if
      *         none found.
      */
-    <T> List<T> findDescendantsOfType(Class<T> targetType);
+    <T> List<T> findDescendantsOfType(Class<? extends T> targetType);
```
Comment (adangel) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java:287]: @oowekyala I've not merged this into pmd/7.0.x, as this would have created too many follow up changes (e.g. in NodeStream). I think, this change is useful and we should tackle it in a separate change and doing this for the other methods here in Node as well (findChildrenOfType, getParentsOfType, ...). It will then also change the API: https://github.com/pmd/pmd/wiki/PMD-7.0.0-API#description-of-node-api (at least the doc, I assume this change is compatible).
