### PR TITLE
[java] Consider ASTCatchParameter in AnnotationSuppressionUtil

### LINKED ISSUE #4873: [java] AvoidCatchingGenericException: Can no longer suppress on the exception itself
**Affects PMD Version:** 7.0.0

**Rule:** [AvoidCatchingGenericException](https://docs.pmd-code.org/latest/pmd_rules_java_design.html#avoidcatchinggenericexception)

**Description:**

```java
try {
	someMethod();
} catch (@SuppressWarnings("PMD.AvoidCatchingGenericException") Exception exception) {
	...
}
```

This used to work on PMD 6.55.0. That is, it suppressed the PMD warning. It no longer works on 7.0.0 and I have to either put `// NOPMD` or put the suppression on the method.

**Code Sample demonstrating the issue:**

See above.

**Steps to reproduce:**

Have this code and run PMD on it.

**Running PMD through:** Gradle

Gradle 8.7, JDK 21.0.1, Linux.

P.S. Congratulations on the release!

### PR DESCRIPTION
**Pull request by adangel**
## Related issues

- Fixes #4873

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/AnnotationSuppressionUtil.java [hunk 1]
```diff
@@ -116,7 +117,8 @@ private static Annotatable getSuppressor(Node node) {
             // also works for ASTResource when Resource uses LocalVariableDeclaration
             || node instanceof ASTLocalVariableDeclaration
             || node instanceof ASTFieldDeclaration
-            || node instanceof ASTFormalParameter) {
+            || node instanceof ASTFormalParameter
+            || node instanceof ASTCatchParameter) {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/AnnotationSuppressionUtil.java:121]: Would it make sense to test if just for `node instanceof Annotatable` instead?

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/8395038324">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/AnnotationSuppressionUtil.java (hunk 1 above)
Comment (jsotuyod) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/AnnotationSuppressionUtil.java:121]: yeah, I don't see why not…
