### PR TITLE
[core] Fix Kotest based tests

### LINKED ISSUE #5009: [core] Kotest tests aren't picked up by surefire
Many tests written in kotlin for Kotest are not being executed by Maven. 

For instance see this log:
https://github.com/pmd/pmd/actions/runs/9036543035/job/24833638646#step:7:6447

>   [INFO] Running net.sourceforge.pmd.lang.java.types.internal.infer.CaptureInferenceTest
  [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.178 s -- in net.sourceforge.pmd.lang.java.types.internal.infer.CaptureInferenceTest
  [INFO] Running net.sourceforge.pmd.lang.java.types.internal.infer.CtorInferenceTest
  [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.100 s -- in net.sourceforge.pmd.lang.java.types.internal.infer.CtorInferenceTest

Those are these files: [CaptureInferenceTest](https://github.com/pmd/pmd/blob/master/pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/CaptureInferenceTest.kt#L21) and [CtorInferenceTest](https://github.com/pmd/pmd/blob/master/pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/CtorInferenceTest.kt)

The tests that are picked up show "Tests run: 0", and many other tests are not picked up (search [BranchingExprsTestCases](https://github.com/pmd/pmd/blob/master/pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/BranchingExprsTestCases.kt#L16) in the log for instance, it's not there).

I tried to upgrade kotest but that makes surefire hang completely... Not sure what happens. I noticed this because I can actually run all those tests from within Intellij, and one test case in BranchingExprsTestCases has been failing for a while... but the Maven build succeeds.

Related issue (maybe) #4236

### PR DESCRIPTION
**Pull request by adangel**
## Describe the PR

The changes are in pmd-java only:

- Renamed BranchingExprsTestCases to BranchingExprsTests so that it is picked up by surefire
- Fixed BranchingExprsTests (the test code sample wouldn't actually be compileable, so I guess, expected a wildcard for the type is ok)
- Added a check in pmd-java's ParserTestSpec, so that test sets ("container" in kotest speak) that don't have any test cases, are failing. This makes sure, that the tests are reported correctly via surefire (only for single test cases the succeed counter is incremented). Now such tests don't end up with ("Tests run: 0...") anymore.
- Fixed tests in pmd-java, that didn't define test cases yet. I simply wrapped the test code inside a "doTest", which registers a test case. Some tests did this already, but many didn't. This created many whitespace changes due to indentation/reformatting.
- Update build-tools to pick up https://github.com/pmd/build-tools/pull/31 - note: this is only cosmetical, so that junit suites are displayed as indented cases.

## Related issues

- Fixes #5009
- Refs https://github.com/pmd/build-tools/pull/31

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No regression tested rules have been changed.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/OverrideResolutionTest.kt [hunk 1]
```diff
@@ -37,24 +43,30 @@ class OverrideResolutionTest : ProcessorTestSpec({
...
+            supFoo.overriddenMethod shouldBe barFoo.genericSignature
+            subFoo.overriddenMethod shouldBe fooFoo.genericSignature
+            barFoo.overriddenMethod shouldBe null
+            fooFoo.overriddenMethod shouldBe null
+        }
     }
 
     parserTest("Test override resolution unresolved") {
-        val acu = parser.parse("""
+        doTest {
```
Comment (oowekyala) [inline pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/OverrideResolutionTest.kt:57]: Instead of needing to wrap everything in a doTest, could we redefine the method `parserTest(String)` to add a doTest internally, and add a new `parserTestContainer` method for tests that want to call doTest directly?

Comment (adangel) [reply pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/OverrideResolutionTest.kt]: I've added now a `parserTestContainer` and refactored all tests to use either `parserTest` or `parserTestContainer`.

**Comment by oowekyala** [comment]
This looks good, thanks :)

**Comment by adangel** [comment]
FYI - I was now investigating the root cause for the following problem: We have a disabled test in `TypeDisambiguationTest` (disabled via bang) - this is listed correctly when the test is running, but it is missing in the summary. So, disabled kotest tests can be overseen very easily:

```
$ ./mvnw surefire:test -pl pmd-java -Dtest=TypeDisambiguationTest,CtorInvocMirrorTest,ReportTest
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running net.sourceforge.pmd.lang.java.ReportTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.136 s -- in net.sourceforge.pmd.lang.java.ReportTest
[INFO] Running net.sourceforge.pmd.lang.java.ast.TypeDisambiguationTest
[INFO]     └─ ↷  TODO Import on demand of class defined in same compilation unit that has an extends clause
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 2.856 s -- in net.sourceforge.pmd.lang.java.ast.TypeDisambiguationTest
[INFO] Running net.sourceforge.pmd.lang.java.types.internal.infer.ast.CtorInvocMirrorTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.206 s -- in net.sourceforge.pmd.lang.java.types.internal.infer.ast.CtorInvocMirrorTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 21, Failures: 0, Errors: 0, Skipped: 0
```

It turns out, that the surefire/junit-platform integration is tailored against methods based test frameworks, where each test is based on a method. For kotest, when it reports the tests up to junit-platform, it only provides a class source (and not a method source): https://github.com/kotest/kotest/blob/6f371fbd0af65577f9a5092d3abab017613afa98/kotest-runner/kotest-runner-junit5/src/jvmMain/kotlin/io/kotest/runner/junit/platform/descriptors.kt#L34
When surefire receives such a TestDescriptor, it tries to convert it here https://github.com/apache/maven-surefire/blob/790e332790b1d601cb58e566c29eef3e47353f7d/surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/RunListenerAdapter.java#L366 into classname and methodname, but the method name will always be null for kotest tests. This is used to create a ReportEntry here: https://github.com/apache/maven-surefire/blob/790e332790b1d601cb58e566c29eef3e47353f7d/surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/RunListenerAdapter.java#L218 - so the report entry for the test has a classname, but no method name. These ReportEntries are collected and converted into TestMethodStats instances (https://github.com/apache/maven-surefire/blob/790e332790b1d601cb58e566c29eef3e47353f7d/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/TestSetRunListener.java#L288). The "classMethodName" will be something like "TestClassName.null" - for _all_ test cases in the same kotest class. These TestMethodStats are later on accumulated: https://github.com/apache/maven-surefire/blob/790e332790b1d601cb58e566c29eef3e47353f7d/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/DefaultReporterFactory.java#L243 - the grouping happens by "ClassMethodName" (`Map<String, List<TestMethodStats>> mergedTestHistoryResult`). We still have the one skipped TestMethodStat and a couple of other, but they are dealt here as multiple executions of the same test (probably for the feature to automatically repeat failing tests x times until they succeed - flaky tests). But the tests should actually be dealt as separate test cases...
For now, I don't see how this could be fixed without a change to either surefire or kotest. I think, this problem is also the cause for https://github.com/kotest/kotest/issues/4024 ...
