### PR TITLE
Fix #5621: [java] Fix FPs with UnusedPrivateMethod

### LINKED ISSUE #5621: [java] UnusedPrivateMethod with method ref
**Affects PMD Version:** 7.7.0

**Rule:** [UnusedPrivateMethod](https://docs.pmd-code.org/latest/pmd_rules_java_bestpractices.html#unusedprivatemethod)

**Description:**

**Code Sample demonstrating the issue:**

```java

    private String foo(final Object foo, final String bar) {
        final String abc = Optional.ofNullable(foo.toString()).map(Foo::getNormalizedAddress).orElse(null);
        return abc;
    }

private static String getNormalizedAddress(final String encoded) {
        try (var objectInputStream = new ObjectInputStream(new ByteArrayInputStream(Base64.getDecoder().decode(encoded)))) {
            final var inetSocketAddress = (InetSocketAddress) objectInputStream.readObject();
            return inetSocketAddress.toString().substring(1);
        } catch (IOException | ClassNotFoundException | IllegalArgumentException e) {
            return null;
        }
    }

```

**Expected outcome:**

PMD reports a violation at line ..., but that's wrong. That's a false positive.

The method is clearly being used

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Maven

```
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>3.26.0</version>
            </plugin>
```

### PR DESCRIPTION
**Pull request by oowekyala**
## Describe the PR

Now if we cannot resolve a method call or method ref, and we think it may call a method of the current class, we whitelist all methods with that name. This also makes the MethodUsage interface more useful by providing an OverloadSelectionInfo, also on method references now.

## Related issues

- Fix #5621

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/InvocationNode.java [hunk 1]
```diff
@@ -49,11 +49,4 @@ default JMethodSig getMethodType() {
     }
 
 
-    /**
-     * Returns information about the overload selection for this call.
-     * Be aware, that selection might have failed ({@link OverloadSelectionResult#isFailed()}).
-     */
-    OverloadSelectionResult getOverloadSelectionInfo();
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/InvocationNode.java:56]: Removing this method, wouldn't this be a breaking API change?

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/OverloadSelectionResult.java [hunk 2]
```diff
@@ -82,4 +86,19 @@ default JTypeMirror ithFormalParam(int i) {
...
+     * Return the type from which the search for accessible candidates
+     * for overload resolution starts. This is just a hint as to where
+     * the candidates come from. There may actually be candidates that
+     * don't come from this type, eg in the case where this is an
+     * unqualified method call, and some candidate methods are imported.
+     * The type is null in some cases, eg, this is not implemented for
+     * constructor call expressions.
+     *
+     * @see ExprMirror.MethodUsageMirror#getTypeToSearch()
+     */
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/OverloadSelectionResult.java:101]:
```suggestion
     * @experimental Since 7.14.0
     */
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml [hunk 3]
```diff
@@ -2618,4 +2618,165 @@ public class Foo {
...
+    private void alala(String rc) { }
+    
+    private void elelel(RoutingContext rc) { }
+    private void elelel(String rc) { }
+}
+]]></code>
+    </test-code>
+
+    <test-code>
+        <description>[java] UnusedPrivateMethod false-positive #5664</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml:2735]: So #5664 is also fixed with this PR?

Ahh - it's not reproducible...

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/InvocationNode.java (hunk 1 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/InvocationNode.java:56]: I added it to a super interface, so I think it's not breaking anything :)
