### PR TITLE
[java] UnusedAssignment false positive when reporting unused variables

### LINKED ISSUE #3114: [java] UnusedAssignment false positive when reporting unused variables
**Affects PMD Version:** 
6.31.0

**Rule:**
[UnusedAssignment](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#unusedassignment)
Property reportUnusedVariables=true

**Description:**
False positive when declared variables are initialized and referenced in multi-line code-blocks surrounded by curly braces.

**Code Sample demonstrating the issue:**

```java
import java.io.IOException;
import static org.objectweb.asm.Opcodes.*;
import org.objectweb.asm.ClassWriter; 
import org.objectweb.asm.FieldVisitor; 
import org.objectweb.asm.MethodVisitor;

public class Dumper {
    private static final String VERSION = "version";
    private static final String CLASS = "Dumper";

    public static byte[] dump() throws IOException {
        // ClassWriter is a class visitor that generates the code for the class
        ClassWriter cw = new ClassWriter(0);
        // Start creating the class.
        cw.visit(V11, ACC_PUBLIC + ACC_SUPER, CLASS, null, "java/lang/Object", null);
        FieldVisitor fv; // false positive
        MethodVisitor mv; // false positive
        {
            // version field
            fv = cw.visitField(ACC_PRIVATE, VERSION, "I", null, null);
            fv.visitEnd();
        }
        {
            // Implementing the constructor
            mv = cw.visitMethod(ACC_PUBLIC, "<init>", "()V", null, null);
            mv.visitCode();
            mv.visitVarInsn(ALOAD, 0);
            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
            mv.visitInsn(RETURN);
            mv.visitMaxs(1, 1);
            mv.visitEnd();
        }
        cw.visitEnd();

        return cw.toByteArray();
    }
}
```

Second example:
```java
 int start;
     if (isOdd(firstPartitionSize))       start = firstPartitionSize;
     else start =                         firstPartitionSize + 1;
```

Third example
```java
private boolean isPair(int number) {
    // Unlike SoftWorker's isPair(int) method,
    // this one contains a little bit more code not necessarily
    // related to pair number detection. It's here to detect if
    // a long method can be inlined
    String stringNumber = String.valueOf(number);
    int divRest;
    if (stringNumber.length() == 3)
      divRest = number % 10;
    else if (stringNumber.length() == 4)
      divRest = number % 100;
    else if (stringNumber.length() == 5)
      divRest = number % 1000;
    else if (stringNumber.length() == 6)
      divRest = number % 1000;
    else
      divRest = number % 10_000;
    if (divRest == 0)
      return true;
    return number % 2 == 0;
  }
```

**Expected outcome:**

No violation reported.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

### PR DESCRIPTION
**Pull request by adangel**
## Related issues

- Fixes #3114

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/990588b9cc6d44da97c2d894ffaa815a/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentRule.java [hunk 1]
```diff
@@ -175,6 +175,9 @@ private void reportFinished(GlobalAlgoState result, RuleContext ruleCtx) {
                 if (isIgnorablePrefixIncrement(entry.rhs)) {
                     continue;
                 }
+                if (isUsedLocalVarWithoutInitializer(entry, result.usedVariables)) {
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentRule.java]: I don't think we need to maintain a separate set. The problem here is that the "assignment" that is killed for this variable is not really an assignment. If we just don't `assign` the variable with the non-existent value, it will not be reported. I pushed a fix.
