### PR TITLE
[core] Simplify the rulechain

### LINKED ISSUE #1785: [core] Allow abstract node types to be valid rulechain visits
Rulechain visits are for now entirely handled as strings:

https://github.com/pmd/pmd/blob/4bb55e4193a2f347de6471121da3ac9ead673cb9/pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java#L44

The implementation also throws an exception (!) if the node class doesn't have a hardcoded "AST" prefix:

https://github.com/pmd/pmd/blob/4bb55e4193a2f347de6471121da3ac9ead673cb9/pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java#L319-L324

Introducing some abstractions into the AST (like done in #1759, argumented on [the wiki](https://github.com/pmd/pmd/wiki/PMD-7.0.0-Java#identifying-abstractions)) has a number of advantages, but the current rulechain implementation doesn't scale. **Adding a rulechain visit to an abstract node type currently does nothing, instead of visiting all nodes having the specified supertype.**

Refs #1772 

There's the exact same problem with XPath queries, which I'll explain in another issue

### PR DESCRIPTION
**Pull request by oowekyala**
## Describe the PR

Simplify the way the rulechain is implemented, clarify the contract of Rule::apply, remove some needless API about the rulechain. In effect, this makes applying rules on a tree index the only way to apply rules. This subsumes the two previous ways to apply rules (rulechain, which uses an index, and Rule.apply, which doesn't).

### Current problems

* Currently rules are artificially split between those that use the rulechain and those that don't. This split affects several classes: RuleSet, RuleSets, Rulechain, etc.
* Rulechain rules, for some reason, use one custom "RulechainVisitor" per language. All of those are nearly perfect duplicates, and are completely unnecessary. We can traverse a tree without using the language-specific visitor interface.
* RulechainVisitors also circumvent the Rule::apply method for XPath rules (they call XPathRule::evaluate). This is inconsistent and unnecessary. It weakens the contract of Rule::apply.
* Rule::apply, by taking a list of nodes as an argument, potentially hides  errors: if an error occurs, the remaining nodes are not processed.
  * In most usages we use a singleton list anyway, so passing a list is useless
* Rule::apply is also implemented the same way everywhere: basically loop over all nodes and visit them. But implementations are inconsistent w.r.t. error handling:
  * some test the node explicitly for some node type and ignore the rest (even if the node is from the same language)

https://github.com/pmd/pmd/blob/1c09a4f8be322c1245f4d28fa3201f70a23e0733/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaRule.java#L42-L54

  * some cast the node without checking if this is appropriate, which may fail at runtime

https://github.com/pmd/pmd/blob/1c09a4f8be322c1245f4d28fa3201f70a23e0733/pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/rule/AbstractJspRule.java#L29-L34

* Another problem with those implementations is that they define an auxilliary `visitAll` method. This multiplies the extension points (and hence the failure points) for no benefit at all.

This PR irons out this part of the API, by removing the divide between rulechain rules and other ones, and simplifying those extension points.

### Changes

The basic API change to Rule is the following:

* Every rule exposes a RuleTargetSelector, a strategy that selects the nodes that a rule should visit. There are several strategies:
  * Select nodes by their XPath names: used to implement XPath rulechain rules
  * Select nodes by their class: used to implement Java rulechain rules
  * Just select the root node: used to implement other rules (matches the current behavior of making a recursive top-down visit starting from the root)
* Foreach tree, foreach rule, the Rule::apply method is systematically fed with the nodes of the tree that match the selector. This means Rule::apply is now the only entry point to apply a rule (not circumvented by XPath rules).

The selectors select nodes from an index of the tree, similar to the one previously built by RulechainVisitors. This is now used by all rules though. The same implementation is used by all languages.

Other API changes include:
* RulechainVisitor and Rulechain are removed. Rule application is managed by a RuleApplicator object
  * The constructor of BaseLanguageModule is altered, since there's no need to provide a rulechain visitor class. Language::getRulechainVisitorClass is removed
* RuleSet::apply is deprecated. RuleSets with an 's' should be used for that
* Rule::apply now takes a single node instead of a list
* All the visitAll methods are removed. Since by contract `apply` is only called with nodes selected by the target selector, it's safe to rely on this and throw an exception if the node is not of the correct type. So implementations of `apply` always cast without checking now.
* Rule::addRuleChainVisit is deprecated. Users should override AbstractRule::buildTargetSelector instead. It's still there temporarily, for compatibility

In the non-API changes, there is now a way to index and visit abstract types efficiently. This simplifies some rulechain rules (though eg for the java tree, many abstractions only exist in the java-grammar branch). This represents most of the code additions of this PR mind you. 

## Related issues

- Fixes #1785

## Ready?

- [ ] Port remaining usages of addRuleChainVisit

- [x] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
  - [x] There's a problem caused by #1937 and AvoidGlobalModifier, I'll fix this when I have the time -> #2491 
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [x] Added (in-code) documentation (if needed)

#### Deprecations due on master

* Rulesets. This is an implementation detail
* Benchmark API (internal)

## Future work

As part of the broader API changes around eg RuleContext and SourceCodeProcessor, I think removing RuleSets::apply would be appropriate. Possibly removing RuleSets altogether would be beneficial.

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/internal/LatticeRelation.java [hunk 1]
```diff
@@ -0,0 +1,339 @@
...
+import java.util.stream.Collector;
+
+import org.checkerframework.checker.nullness.qual.NonNull;
+import org.checkerframework.checker.nullness.qual.Nullable;
+
+import net.sourceforge.pmd.internal.util.AssertionUtil;
+import net.sourceforge.pmd.lang.rule.internal.GraphUtils.DotColor;
+
+/**
+ * Indexes data of type {@code <V>} with keys of type {@code <K>}, where
```
Comment (adangel) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/internal/LatticeRelation.java:32]: Just a question: Do we really need to be that generic? We are dealing with AST Nodes, don't we?
That's btw one example for #2611 - it will be very difficult to understand this class without looking at many more classes in parallel to understand, what's going on....
Maybe the question in a different way: Do we really implement it that abstract? We only need it for PMD purposes, not for general purpose....

Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/internal/LatticeRelation.java:32]: Ok, as far as I understand, that is your solution for dealing with Abstract node types.... right?

File: pmd-core/src/main/java/net/sourceforge/pmd/util/CollectionUtil.java [hunk 2]
```diff
@@ -532,6 +554,94 @@ public static boolean isNotEmpty(Object[] items) {
         return Collections.unmodifiableList(res);
     }
 
+    /**
+     * Map each element of the given iterable with the given function,
+     * and accumulates it into the collector.
+     */
+    public static <T, U, A, C> C map(Collector<? super U, A, ? extends C> collector,
```
Comment (adangel) [inline pmd-core/src/main/java/net/sourceforge/pmd/util/CollectionUtil.java:561]: Another example of overly used generics... What is T, U, A ,C?... Maybe I'm just not that into streams...

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaRulechainRule.java [hunk 3]
```diff
@@ -18,32 +19,25 @@
  */
 public abstract class AbstractJavaRulechainRule extends AbstractJavaRule {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaRulechainRule.java:20]: Maybe we can get rid of this class eventually?

File: pmd-core/src/main/java/net/sourceforge/pmd/util/CollectionUtil.java (hunk 2 above)
Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/util/CollectionUtil.java:561]: I think this is just "used generics" rather than overused... It's not my fault that the Collector API uses 3 type parameters...

`U, A, C` in that order correspond to the `T, A, R` type parameters of [Collector](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collector.html):
>    T - the type of input elements to the reduction operation
>    A - the mutable accumulation type of the reduction operation (often hidden as an implementation detail)
>    R - the result type of the reduction operation

On this method we have a source of `T` elements, a mapper from `T` to `U`, and a collector that accumulates a bunch of `U`s to produce a `C`, which is generally a collection of `U`.

The `A` is an implementation detail, when you make methods that *return* collectors, this is generally some wildcard to not expose it to clients. But when you *use* the collector to perform the collection operation, then you need to declare `A` to capture it. You don't need to know that to use methods that use collectors, but the implementation of the method has to capture it.

It takes some time to get used to the collector API but once you get it there's really nothing voodoo happening.

Consider that this method is super reusable, you can do `map(toSet(), listOfT, t -> t.getU())` and end up with a `Set<U>`. You can use any of the standard collectors in `Collectors`.  It's much better than writing one specialized `map` function for each kind of result type (`mapToSet`, `mapToList`, etc).

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaRulechainRule.java (hunk 3 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaRulechainRule.java:20]: Probably yes. But the fact that rules also implement the visitor interface is a problem for that, as the default visit method traverses the tree, which we want to avoid.

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/internal/LatticeRelation.java (hunk 1 above)
Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/internal/LatticeRelation.java:32]: > Ok, as far as I understand, that is your solution for dealing with Abstract node types.... right?

Yes that's it.

Honestly making it generic is easy and makes tests much more comprehensive and easier to write. This data structure is a kind of multimap where values are added at once to several keys, doing minimal work. So we can add `Node` values to several `Class` keys at once, just by knowing `node.getClass()`, without having to traverse all the supertypes for every instance. We also don't accumulate values for keys that won't be queried (those `Class` instances for which no rulechain rule has added a visit request).


The API is really simple I think, you just use `put` and `get` as if it was a regular map.

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleTargetSelector.java [hunk 4]
```diff
@@ -0,0 +1,140 @@
...
+import net.sourceforge.pmd.lang.rule.internal.TargetSelectorInternal;
+import net.sourceforge.pmd.lang.rule.internal.TreeIndex;
+import net.sourceforge.pmd.util.CollectionUtil;
+
+/**
+ * A strategy for selecting nodes that will be targeted by a rule.
+ *
+ * @see Rule#getTargetSelector()
+ */
+public abstract class RuleTargetSelector extends TargetSelectorInternal {
```
[the remark this answers is not in the document]
Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleTargetSelector.java:27]: Yes this is super weird. I wanted to make RuleTargetSelector published because it's somewhere on the Rule interface, but still keep everything about TreeIndex internal... So no one can implement their RuleTargetSelector because that would require us to expose TreeIndex.

I'm truly not sure this is the best way to do it, if you have a better idea go ahead

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java [hunk 5]
```diff
@@ -227,36 +232,42 @@ public ParserOptions getParserOptions() {
...
+    }
+
+    /**
+     * Create the targeting strategy for this rule. Please override
+     * this instead of using {@link #addRuleChainVisit(Class)}.
+     * Use the factory methods of {@link RuleTargetSelector}.
+     */
+    @NonNull
+    protected RuleTargetSelector buildTargetSelector() {
+        Set<Class<? extends Node>> crvs = getClassRuleChainVisits();
```
[the remark this answers is not in the document]
Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java:268]: Yes :)

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java [hunk 6]
```diff
@@ -70,17 +78,14 @@ public void deepCopyValuesTo(AbstractRule otherRule) {
         otherRule.priority = priority;
         otherRule.propertyDescriptors = new ArrayList<>(getPropertyDescriptors());
         otherRule.propertyValuesByDescriptor = copyPropertyValues();
-        otherRule.ruleChainVisits = copyRuleChainVisits();
+        otherRule.ruleChainVisits = new LinkedHashSet<>(ruleChainVisits);
+        otherRule.classRuleChainVisits = new LinkedHashSet<>(classRuleChainVisits);
```
[the remark this answers is not in the document]
Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java:82]: Could be... but since we don't know exactly how the caller uses the deepCopy, we can't assume that they won't call `addRuleChainVisit`. If we copy `myStrategy`, then if it was not null, `buildTargetSelector` will never be called.

This is only relevant while `addRuleChainVisit` exists, when it's removed there will be no way to override the target selector of the implementation, and then it can be copied.

File: pmd-core/pom.xml [hunk 7]
```diff
@@ -149,6 +149,11 @@
             <artifactId>checker-qual</artifactId>
             <version>2.5.2</version>
         </dependency>
+        <dependency>
+            <groupId>org.pcollections</groupId>
+            <artifactId>pcollections</artifactId>
```
[the remark this answers is not in the document]
Comment (oowekyala) [reply pmd-core/pom.xml:154]: We could do without it in this PR, but I use it in the type resolution code, and I think it's better introduced now rather than later. This can have many many applications

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/AvoidLogicInTriggerRule.java [hunk 8]
```diff
@@ -6,14 +6,18 @@
...
 import net.sourceforge.pmd.lang.apex.ast.ASTUserTrigger;
 import net.sourceforge.pmd.lang.apex.rule.AbstractApexRule;
+import net.sourceforge.pmd.lang.rule.RuleTargetSelector;
 
 public class AvoidLogicInTriggerRule extends AbstractApexRule {
 
-    public AvoidLogicInTriggerRule() {
-        addRuleChainVisit(ASTUserTrigger.class);
+    @Override
+    protected @NonNull RuleTargetSelector buildTargetSelector() {
```
[the remark this answers is not in the document]
Comment (oowekyala) [reply pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/AvoidLogicInTriggerRule.java:19]: Not sure I follow... The super method has this annotation, which means implementations are expected to never return null too. So yes it's part of the API, or rather it's an explicit "contract" that the implementor must respect. 

By copying it to the implementation we let static analysis tools make sure you respect the contract (eg the IDE, maybe PMD in the future?)

**Comment by oowekyala** [comment]
Thanks for merging! 

> What do you mean with that? Benchmark is currently possible to be called from CLI (-benchmark), so we need to define, what exactly the API is...
But I guess, this can be done later as well, as I didn't see, that you modified the benchmark classes here.

Yeah I don't remember why I mentioned the benchmark api here. What I meant, is that the implementation classes are probably internal API (and the `-benchmark` option is the published API to use it). We need to review that somewhere before we decide on this
