### PR TITLE
[apex] Fixes #4556 - Update Apex bind regex match for all possible combinations

### LINKED ISSUE #4556: [apex] UnusedLocalVariable flags for variables which are using in SOQL/SOSL binds
**Affects PMD Version:** 7.0.0-rc2

**Rule:** [UnusedLocalVariable](https://docs.pmd-code.org/latest/pmd_rules_apex_bestpractices.html#unusedlocalvariable)

**Description:**

**Code Sample demonstrating the issue:**

```apex
    String unusedFlag = 'this string';
    String query = 'SELECT Id FROM Account WHERE Name =: unusedFlag';
```

**Expected outcome:**

PMD reports a violation at line 1, but that's wrong. That's a false positive.

**Running PMD through:** *[CLI]*

image

### PR DESCRIPTION
**Pull request by nwcm**
Matches variables with underscores
Matches `=:food` and `=: foo`

## Describe the PR

Updates the regex for matching bind variables in string SOQL queries. 

## Related issues

- Fixes #4556 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/UnusedLocalVariableRule.java [hunk 1]
```diff
@@ -34,7 +34,7 @@ public class UnusedLocalVariableRule extends AbstractApexRule {
             "Database.countQuery".toLowerCase(Locale.ROOT)
     ));
 
-    private static final Pattern BINDING_VARIABLE = Pattern.compile("(?i):([a-z0-9]+)");
+    private static final Pattern BINDING_VARIABLE = Pattern.compile("(?i):(?:\s|)([_a-z0-9]+)");
```
Comment (oowekyala) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/UnusedLocalVariableRule.java:37]: There could be more than one space
```suggestion
    private static final Pattern BINDING_VARIABLE = Pattern.compile("(?i):\s*+([_a-z0-9]+)");
```

Comment (adangel) [reply pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/UnusedLocalVariableRule.java:37]: Also we should add a test case testing this in https://github.com/pmd/pmd/blob/master/pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/bestpractices/xml/UnusedLocalVariable.xml

Comment (dschach) [reply pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/UnusedLocalVariableRule.java:37]: The spaces are all optional. I don't understand the syntax enough to know if that is accounted for in the patterns, even before `=` and after `:`.

Comment (oowekyala) [reply pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/UnusedLocalVariableRule.java:37]: It's not a typo, it's a possessive quantifier. It will not backtrack so the regex will be faster.

Comment (jsotuyod) [reply pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/UnusedLocalVariableRule.java:37]: And here I was thinking I knew my regular expressions… thanks for that!

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 23 errors and 7 configuration errors.<br />
<a href="https://chunk.io/pmd/bf0bc728fb03443680da2f80642de5f9/diff1/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by adangel — APPROVED** [review]
Thanks!
