### PR TITLE
[plsql] Fix ParseException for EXECUTE IMMEDIATE str1||str2;

### LINKED ISSUE #3106: [plsql] ParseException while parsing EXECUTE IMMEDIATE 'drop database link ' || linkname;
It seems like PMD 6.31.0 does not like

    EXECUTE IMMEDIATE 'drop database link ' || linkname;

or more generally the case where the statement to be executed with EXECUTE IMMEDIATE is a concatenation:

Caused by: net.sourceforge.pmd.lang.plsql.ast.ParseException: Encountered " "||" "|| "" at line ..., column ....
Was expecting one of:
    ";" ...
    "INTO" ...
    "RETURN" ...
    "RETURNING" ...
    "USING" ...

Execute Immediate Statement Spec:
https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/EXECUTE-IMMEDIATE-statement.html#GUID-C3245A95-B85B-4280-A01F-12307B108DC8

### PR DESCRIPTION
**Pull request by hvbtup**
## Describe the PR

This fixes the ParseExeception for the PLSQL parser when it finds a statement like

    EXECUTE IMMEDIATE 'drop database link ' || v_link_name;

## Related issues

- Fixes #3106

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oowekyala** [comment]
Thanks for contributing this! Please add a test case for the issue in [PLSQLParserTest](https://github.com/pmd/pmd/blob/master/pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParserTest.java) though

File: pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParserTest.java [hunk 1]
```diff
@@ -73,4 +73,9 @@ public void testCodingStyleExample() {
     public void testCaseIssue1454() {
         plsql.parseResource("CaseIssue1454.pls");
     }
+
+    @Test
+    public void testCaseIssue3106() {
```
Comment (adangel) [inline pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParserTest.java:78]: Test name should be something like "testExecuteImmediateIssue3106" - the test before (#1454) is indeed about the case statement.... but #3106 is about execute immediate.

Please put the test source in a separate file, so that we can better read it. In that file, you can use multiple lines and don't need escapes.

File: pmd-plsql/etc/grammar/PldocAST.jjt [hunk 2]
```diff
@@ -2686,7 +2686,7 @@ ASTFetchStatement FetchStatement()  :
 ASTEmbeddedSqlStatement EmbeddedSqlStatement()  :
 {}
 {
-   <EXECUTE> <IMMEDIATE> (StringLiteral() | Expression())
+   <EXECUTE> <IMMEDIATE> Expression()
```
Comment (adangel) [inline pmd-plsql/etc/grammar/PldocAST.jjt:2689]: Technically, this allows now more than should be allowed. Here's the doc/spec about this statement: https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/EXECUTE-IMMEDIATE-statement.html#GUID-C3245A95-B85B-4280-A01F-12307B108DC8

It takes "dynamic_sql_stmt" as the first production, which is

> String literal, string variable, or string expression that represents a SQL statement. Its type must be either CHAR, VARCHAR2, or CLOB. 

I guess, by using "StringLiteral()" here, almost always a StringLiteral (probably something starting with `'` or `"`)  was used and almost never Expression() (only in cases a variable was used). The "||" is the [concatenation operator](https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/plsql-language-fundamentals.html#GUID-4792284C-D82B-4F6A-8554-45CF1BFAE6EB). We use this in our production [StringExpression](https://github.com/pmd/pmd/blob/2b6dcb3f22431f511aca86d3543ecf7515892cac/pmd-plsql/etc/grammar/PldocAST.jjt#L3190-L3203).

Using Expression() here would probably resolve the "||"-operator to a AdditiveExpression which doesn't sound right.

Could you add a test case with 3 variants calling execute immediate?
1. direct string literal, e.g. `EXECUTE IMMEDIATE 'UPDATE employees_temp SET name = NULL'` (see also https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/dynamic-sql.html#GUID-BAC52F38-B427-4860-9B6D-336B3AEE6AD2)
2. string variable, e.g. `EXECUTE IMMEDIATE plsql_block` (see also https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/dynamic-sql.html#GUID-30ADFC05-8DFB-4C8A-831D-426C2E97F217)
3. string expression, like your example `EXECUTE IMMEDIATE 'drop database link ' || v_link`

And could you try out using here `StringExpression()` instead of `Expression()`?

**Review by adangel — COMMENTED** [review]
Thanks for the PR!

Please have a look at my comments about the grammar change. I think, we should try to use "StringExpression()" here.

File: pmd-plsql/etc/grammar/PldocAST.jjt (hunk 2 above)
Comment (hvbtup) [reply pmd-plsql/etc/grammar/PldocAST.jjt]: I didn't see your last comment until now. I renamed the unit test, switched to StringExpression() and move the test code to a separate file as you suggested in your comment. Regarding the test cases:
I added a test case for 3), and test cases for 1) and 2) already exist (see files resources/net/sourceforge/pmd/lang/plsql/ExecuteImmediate*.pls)

**Review by adangel — APPROVED** [review]
Thanks, looks good!
