### PR TITLE
[java] Fixes false positive for `DoNotExtendJavaLangError`

### LINKED ISSUE #1021: [java] False positive for `DoNotExtendJavaLangError`
**Affects PMD Version:** 6.2.0

**Rule:** DoNotExtendJavaLangError

**Description:** If I extend a class `Error` (a class of my own, *not* `java.lang.Error`) PMD finds a false positive.

**Code Sample demonstrating the issue:** Too difficult to cut and paste here. Just declare a class `Error` and another one that extends it.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]* pmd-eclipse 1.11.0

### PR DESCRIPTION
**Pull request by akshatbahety**
**PR Description**
Fixes #1021

### CODE REVIEW

File: pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/donotextendjavalangerror/Error.java [hunk 1]
```diff
@@ -0,0 +1,16 @@
+/**
+ * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
+ */
+
+package net.sourceforge.pmd.lang.java.rule.design.donotextendjavalangerror;
+
+
+
+/*
```
Comment (oowekyala) [inline pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/donotextendjavalangerror/Error.java]: This should be a javadoc comment (`/**`). Please use a formatter to add stars on the left and remove the excessive whitespace all over.

File: pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/donotextendjavalangerror/Error.java [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+    @author Akshat Bahety
+    @since 6.4.1
```
Comment (oowekyala) [inline pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/donotextendjavalangerror/Error.java]: Actually 6.4.0

File: pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/donotextendjavalangerror/Error.java [hunk 3]
```diff
@@ -0,0 +1,14 @@
+/**
+ * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
+ */
+
+package net.sourceforge.pmd.lang.java.rule.design.donotextendjavalangerror;
+
+/*
```
Comment (jsotuyod) [inline pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/donotextendjavalangerror/Error.java]: this should still be with double asterisk `/**`
