### PR TITLE
[java] Fix AvoidUsingOctalValues false-positive

### LINKED ISSUE #5007: [java] AvoidUsingOctalValues triggers on non-octal double literals with a leading 0
**Affects PMD Version:** 7.1.0

**Rule:** [AvoidUsingOctalValues](https://docs.pmd-code.org/latest/pmd_rules_java_errorprone.html#avoidusingoctalvalues)

**Description:**

When a double literal has a leading 0, and ends with either `d` or `.0`, the literal is not treated as an octal value. However, PMD still reports a violation.

**Code Sample demonstrating the issue:**

```java
double literal1 = 017.0; // Not octal!
double literal2 = 017d; // Also not octal!
double octal = 017; // Definitely octal!
```

**Expected outcome:**

PMD should only report a violation at line 3 only, but it reports on all three.

**Running PMD through:** *Gradle*

### PR DESCRIPTION
**Pull request by Gold856**
## Describe the PR

ASTNumericLiteral did not correctly determine the base when a number ended with a non-number (L, F, D, .) This PR checks if the number ends with one of those characters, and correctly returns a base of 10.

## Related issues

- Fixes #5007

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java [hunk 1]
```diff
@@ -124,18 +124,19 @@ public int getBase() {
...
-            case 'X':
-                return 16;
-            case 'b':
-            case 'B':
-                return 2;
-            case '.':
-                return 10;
-            default:
-                return 8;
+        switch (image.charAt(image.length() - 1)) {
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java:127]: this should have the same length check we have in line 131 for defensiveness

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java [hunk 2]
```diff
@@ -124,18 +124,19 @@ public int getBase() {
...
+        case 'l', 'L', 'f', 'F', 'd', 'D', '.':
```
[the remark this answers is not in the document]
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java:128]: Numeral type suffixes only influence the type and not the base of the number. You can write `0x0123L` and that is a long but still base 16

**Comment by Gold856** [comment]
I added some test cases and fixed the logic; the code now checks for a period in the literal along with a float or double suffix at the end, since those do cause the base to change to base 10.

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 63 new violations, 0 new errors and 0 new configuration errors,<br />
removes 2 violations, 0 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/9102279270?pr=5020">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java [hunk 3]
```diff
@@ -125,17 +125,26 @@ public int getBase() {
 
     static int getBase(Chars image) {
         if (image.length() > 1 && image.charAt(0) == '0') {
+            if (image.indexOf('.') != -1) {
+                return 10;
+            }
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java:130]: this is actually not true…

The value `0x1.0p+2f` is an hexadecimal float literal in Java. It's still base 16.

I'm seeing a lot of false positives in the `UseUnderscoresInNumericLiterals` rule because of this changeset.

**Review by jsotuyod — CHANGES_REQUESTED** [review]

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java (hunk 3 above)
Comment (Gold856) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java]: Moved this check to after the binary and hex checks.

**Comment by jsotuyod** [comment]
Let's see what the regression tester shows, but it seems better.

I'd probably just add a test case before merging on the case `0x1.0000_ffff_eeeep+2f` for the rule `UseUnderscoresInNumericLiterals`, as this was detected by the regression tester but not our own rules, so we are obviously missing this scenario there.

But other than that, if @pmd-test doesn't show anything weird, this is good to go.

**Comment by Gold856** [comment]
Added the float literal test case. Also added code to check for exponents (those can also change an octal to decimal) with a test case.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java [hunk 4]
```diff
@@ -132,10 +132,19 @@ static int getBase(Chars image) {
             case 'b':
             case 'B':
                 return 2;
-            case '.':
-                return 10;
             default:
-                return 8;
+                if (image.indexOf('.') != -1 || image.indexOf('e') != -1 || image.indexOf('E') != -1) {
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java:136]: I think instead of all this logic we could add a parameter `boolean isIntegral` to `getBase(Chars)`. Then in the default case we just have `return isIntegral? 8 : 10;`. In `parseIntegralValue` this value is true, we know it's integral. In `getBase()` we can just use the field `isIntegral`. This would simplify this function a lot.

**Review by jsotuyod — APPROVED** [review]
This looks great! Thanks!
