### PR TITLE
[java] Support Java 23

### LINKED ISSUE #5062: [java] Support Java 23
Java 23 will be released on September 17th. It ships a number of new feature previews that will impact PMD.

[OpenJDK 23](https://openjdk.org/projects/jdk/23/) GA is scheduled for 2024/09/17.

I here list the JEPs I've so far confirmed to be of impact:

- [467: Markdown Documentation Comments](https://openjdk.org/jeps/467)
  - It allows Javadocs to be written in Markdown using `///` on each line, instead of `/** … */`. This will impact our grammar to identify these as Javadocs, but also all rules parsing these (ie: to detect unused imports).
- [476: Module Import Declarations (Preview)](https://openjdk.org/jeps/476)
  - Preview feature, allows modules to be imported directly, treating all public classes in exported packages to be imported on demand. This will affect the grammar around imports, affect all rules working with them, and may require us to revamp how PMD models and manages modules (which is quite weak honestly, as no rules currently deal with them directly).
- [482: Flexible Constructor Bodies (Second Preview)](https://openjdk.org/jeps/482)
  - Not much changed since the first preview at first glance, need to double check…
- [455: Primitive Types in Patterns, instanceof, and switch (Preview)](https://openjdk.org/jeps/455)
  - Relaxed constraints on what is allowed in these patterns. Should be easy, but needs appropriate tests to be added.
- [477: Implicitly Declared Classes and Instance Main Methods (Third Preview)](https://openjdk.org/jeps/477)

In summary: https://javaalmanac.io/jdk/23/

This issue is similar to the previous: #4794

EA Release of JDK23 is available here: https://jdk.java.net/23/

**Tasks:**

- [x] Add new java language versions 23 and 23-preview: `net.sourceforge.pmd.lang.java.JavaLanguageModule`
    - 23 is the new default
    - update also java.md and ant.md
    - and add in KotlinTestingDsl.kt.
    - Update `net.sourceforge.pmd.lang.java.LanguageVersionTest`
    - Update `net.sourceforge.pmd.lang.java.JavaLanguageModuleTest#previewVersionShouldBeGreaterThanNonPreview`
    - Update `net.sourceforge.pmd.lang.java.ast.AllJavaAstTreeDumpTest`
    - Update `net.sourceforge.pmd.dist.BinaryDistributionIT`
- [x] Update asm dependency to 9.7:
    - https://search.maven.org/artifact/org.ow2.asm/asm
    - https://asm.ow2.io/versions.html
    - Update net.sourceforge.pmd.lang.java.symbols.internal.asm.AsmSymbolResolver#ASM_API_V if necessary
- [x] Remove java language version 21-preview: `net.sourceforge.pmd.lang.java.JavaLanguageModule`
    - update also java.md
    - update KotlinTestingDsl.kt
    - remove exclusions in pmd-core/src/main/resources/internal/all-java.xml
    - Update `net.sourceforge.pmd.lang.java.LanguageVersionTest`
    - Remove `net.sourceforge.pmd.lang.java.ast.Java21PreviewTreeDumpTest`  (including resources)
- [x] Update implementation for "Implicitly Declared Classes and Instance Main Methods" (445, 463, 477)
    - https://cr.openjdk.org/~gbierman/jep477/jep477-20240507/specs/implicitly-declared-classes-instance-main-methods-jls.html
- [x] Update implementation for "Flexible Constructor Bodies" (447, 482)
    - JEP was named before "Statements before super(...)"
    - https://cr.openjdk.org/~gbierman/jep482/jep482-20240604/specs/flexible-constructor-bodies-jls.html
- [x] Implement preview feature "Markdown Documentation Comments" (467)
- [x] Implement preview feature "Module Import Declarations" (476)
    - https://cr.openjdk.org/~gbierman/jep476/jep476-20240604/specs/module-import-declarations-jls.html
- [x] Implement preview feature "Primitive Types in Patterns, instanceof, and switch" (455)
    - https://cr.openjdk.org/~abimpoudis/instanceof/jep455-20240424/specs/instanceof-jls.html
- [x] Remove support for String Templates (430, 459)
    - It was decided, that String Templates will be removed: See https://bugs.openjdk.org/browse/JDK-8329949 and https://www.youtube.com/watch?v=c6L4Ef9owuQ
    - It should only work with 22-preview, but not anymore with 23-preview
    - It might come back in some way, but if it doesn't come back for 24, we can remove the code completely from our grammar.
- [x] Write release notes
    - removed experimental: done
    - removed classes: none
    - deprecated classes: none
    - new experimental: done
- [x] Add JDK23 to the build, so that we integration test with 23, ~as this is a LTS version~
    - integration test in pmd-dist
    - Not necessary, as JDK23 is not LTS
- [x] Make sure, we can build PMD with JDK23
- [x] Update https://github.com/pmd/java-regression-tests
    - ~new regular language features, so update needed~
    - not necessary for 23, as there are no new regular language features
    - Note: This can only be done, after this issue has been implemented
- [x] Create a new issue for the next Java version 24
    - https://jdk.java.net/24/
    - https://openjdk.org/projects/jdk/24/
    - #5154

### PR DESCRIPTION
**Pull request by adangel**
## Describe the PR

This is ready now.

I pushed the branch is directly to our main repo on github: https://github.com/pmd/pmd/tree/issue-5062-support-java-23.

Java 23 is GA in September, which means it would be great, if we could finish this latest in August, so that in lands in PMD 7.5.0 to be released end of August.

## Related issues

- Fixes #5062

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableId.java [hunk 1]
```diff
@@ -135,7 +135,7 @@ private ModifierOwner getModifierOwnerParent() {
      * identifier.
      */
     public boolean isUnnamed() {
-        return "_".equals(name) && getLanguageVersion().compareToVersion("21-preview") >= 0;
+        return "_".equals(name) && getLanguageVersion().compareToVersion("21") >= 0;
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableId.java:138]:
```suggestion
        return "_".equals(name) && getLanguageVersion().compareToVersion("22") >= 0;
```

It is a 21-preview or 22 release feature.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java [hunk 2]
```diff
@@ -213,11 +213,19 @@ public Void visit(ASTCompilationUnit node, @NonNull ReferenceCtx ctx) {
...
 
+            // TODO Java 23 implicitly imports "import static java.io.IO.*" for implicitly declared classes
+            boolean implicitlyDeclaredClass = node.isImplicitlyDeclaredClass();
+
             NodeStream<ASTTypeDeclaration> typeDecls = node.getTypeDeclarations();
 
             // types declared inside the compilation unit
             pushed += pushOnStack(f.typesInFile(top(), typeDecls));
 
+            if (implicitlyDeclaredClass) {
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java:224]: I think we need to add a node that implements ASTAnyTypeDeclaration for the implicit class declaration. Otherwise the method "getEnclosingType" that is available on all nodes may return null in places where we expect there to be an enclosing class (eg methods or field declarations), which is a source of bugs.

These if statements won't be necessary anymore.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ast/AstSymbolMakerVisitor.java [hunk 3]
```diff
@@ -80,7 +80,7 @@ private boolean isTrueLocalVar(ASTVariableId node) {
 
     @Override
     public Void visit(ASTCompilationUnit node, AstSymFactory data) {
-        if (node.isUnnamedClass()) {
+        if (node.isImplicitlyDeclaredClass()) {
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ast/AstSymbolMakerVisitor.java:83]: This will also not be necessary.

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/9905957490?pr=5112">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTImportDeclaration.java [hunk 4]
```diff
@@ -115,4 +128,20 @@ protected <P, R> R acceptVisitor(JavaVisitor<? super P, ? extends R> visitor, P
...
+    /**
+     * If this import declaration imports all the public top-level classes and interfaces
+     * of a module.
+     *
+     * @return {@code true} if this is a module declaration import
+     * @since 7.4.0
+     * @see <a href="https://openjdk.org/jeps/476">JEP 476: Module Import Declarations (Preview)</a> (Java 23)
+     */
+    @Experimental
+    public boolean isModuleImport() {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTImportDeclaration.java:144]: Maybe name this just `isModule()` - since that it is a import declaration is already clear from the class name...

**Comment by garydgregory** [comment]
Also, 24-ea is available to GitHub actions, which we use over at Apache Commons as we do 23-ea, but all these fail due to the dependency on ASM 9.6.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java (hunk 2 above)
Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java]: I've added now a new node "ImplicitClassDeclaration". Its structure is similar to an anonymous class declaration.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java [hunk 5]
```diff
@@ -204,14 +204,32 @@ public Void visit(ASTModifierList node, @NonNull ReferenceCtx ctx) {
 
         @Override
         public Void visit(ASTCompilationUnit node, @NonNull ReferenceCtx ctx) {
-            Map<Boolean, List<ASTImportDeclaration>> isImportOnDemand = node.children(ASTImportDeclaration.class)
-                                                                            .collect(Collectors.partitioningBy(ASTImportDeclaration::isImportOnDemand));
+            List<ASTImportDeclaration> importsOnDemand = new ArrayList<>();
+            List<ASTImportDeclaration> singleImports = new ArrayList<>();
+            List<ASTImportDeclaration> moduleImports = new ArrayList<>();
+
+            node.children(ASTImportDeclaration.class).toStream().forEach(i -> {
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java:211]:
```suggestion
            node.children(ASTImportDeclaration.class).forEach(i -> {
```

File: pmd-core/src/main/java/net/sourceforge/pmd/internal/util/ClasspathClassLoader.java [hunk 6]
```diff
@@ -233,12 +251,77 @@ public InputStream getResourceAsStream(String name) {
...
+                Enumeration<URL> moduleInfoUrls = findResources(MODULE_INFO_SUFFIX);
+                URL moduleUrl = findModule(moduleInfoUrls, moduleName);
+
+                // no match in this classloader, search in parents
+                if (moduleUrl == null) {
+                    moduleInfoUrls = getParent().getResources(MODULE_INFO_SUFFIX);
+                    moduleUrl = findModule(moduleInfoUrls, moduleName);
+                }
+
+                return moduleUrl;
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/internal/util/ClasspathClassLoader.java:319]: Should we keep a mapping `name -> URL` to cache the result? This whole branch seems like an expensive operation with a lot of IO.

Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/internal/util/ClasspathClassLoader.java]: I'm keeping now a map. Right now, I don't think, it would really be necessary, as currently it is only triggered by `import module ...`. But probably this will be used more often in the future.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTImportDeclaration.java (hunk 4 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTImportDeclaration.java]: I think it would read better with the old name, especially in xpath rules. The other getters in this class also already have Import in their name (eg `isImportOnDemand`/`@ImportOnDemand`) and it would be more consistent.

Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTImportDeclaration.java:144]: I've renamed it back to `isModuleImport` now...

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/JavaResolvers.java [hunk 7]
```diff
@@ -73,6 +74,39 @@ static boolean canBeImportedIn(String thisPackage, JAccessibleElementSymbol memb
...
 
+    @NonNull
+    static NameResolver<JTypeMirror> moduleImport(Set<String> moduleNames,
+                                                  final SymbolResolver symbolResolver,
+                                                  final String thisPackage) {
+        return new SingleNameResolver<JTypeMirror>() {
+            @Override
+            public @Nullable JTypeMirror resolveFirst(String simpleName) {
+                for (String module : moduleNames) {
+                    JModuleSymbol moduleSymbol = symbolResolver.resolveModule(module);
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/JavaResolvers.java:85]: This should be cached in the name resolver, otherwise it will perform a classloader lookup and parse the module file for every name that is requested (which is probably all the type identifiers in the compilation unit).

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/JavaResolvers.java [hunk 8]
```diff
@@ -73,6 +74,39 @@ static boolean canBeImportedIn(String thisPackage, JAccessibleElementSymbol memb
...
+
+                    if (moduleSymbol == null) {
+                        // TODO: log warning about incomplete auxclasspath
+                        return null;
+                    }
+
+                    for (String packageName : moduleSymbol.getExportedPackages()) {
+                        JClassSymbol sym = symbolResolver.resolveClassFromCanonicalName(packageName + "." + simpleName);
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/JavaResolvers.java:93]: This should resolve from binary name instead of canonical name, otherwise it will try every package segment. But we know that these segments are packages and not outer classes. This is different from type import on demand, because these can import inner types too.
