### PR TITLE
Fix #5587: [java] Fix deadlock while loading ClassStub

### LINKED ISSUE #5587: [java] Thread deadlock during PMD analysis in ParseLock.getFinalStatus
**Affects PMD Version:** 
7.10.0 and 7.11.0

Make sure, to test with the latest PMD version.

**Description:**

We got reports of PMD analysis blocking the build pipelines. It seems to happen in one particular project using the sonar-pmd plugin which uses PMD 7.10.0. Running with PMD plugin in Intellij (PMD 7.7.0) and running from command line with 7.11.0 and `pmd check -t 10` on same code base also results in deadlocks. The source code is a Java Spring Boot application.

**Exception Stacktrace:**

<details>
<summary>From jstack:</summary>

```
Found one Java-level deadlock:
=============================
"PmdThread 1":
  waiting to lock monitor 0x00006000032dc340 (object 0x00000004085d1cd8, a net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub$1),
  which is held by "PmdThread 4"

"PmdThread 4":
  waiting to lock monitor 0x00006000032dc410 (object 0x0000000408510468, a net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub$1),
  which is held by "PmdThread 1"

Java stack information for the threads listed above:
===================================================
"PmdThread 1":
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.getFinalStatus(ParseLock.java:41)
	- waiting to lock <0x00000004085d1cd8> (a net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub$1)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.isFailed(ParseLock.java:82)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub.isUnresolved(ClassStub.java:524)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.checkUserEnclosingTypeIsOk(ClassTypeImpl.java:452)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.validateParams(ClassTypeImpl.java:418)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.<init>(ClassTypeImpl.java:69)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.<init>(ClassTypeImpl.java:64)
	at net.sourceforge.pmd.lang.java.types.TypeSystem.typeOf(TypeSystem.java:466)
	at net.sourceforge.pmd.lang.java.types.TypeSystem.rawType(TypeSystem.java:493)
	at net.sourceforge.pmd.lang.java.types.TypeSystem.parameterise(TypeSystem.java:527)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser$TypeScanner.makeClassType(TypeSigParser.java:364)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser.classType(TypeSigParser.java:164)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser.typeSignature(TypeSigParser.java:148)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser.typeSignature(TypeSigParser.java:124)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser.arrayType(TypeSigParser.java:216)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser.typeSignature(TypeSigParser.java:146)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser.methodType(TypeSigParser.java:53)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.SignatureParser.parseMethodType(SignatureParser.java:65)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase$LazyMethodType.doParse(GenericSigBase.java:265)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase$1.doParse(GenericSigBase.java:56)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.getFinalStatus(ParseLock.java:48)
	- locked <0x00000004085d1d00> (a net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase$1)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.ensureParsed(ParseLock.java:27)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase.ensureParsed(GenericSigBase.java:87)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase$LazyMethodType.getParameterTypes(GenericSigBase.java:333)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ExecutableStub.getArity(ExecutableStub.java:83)
	at net.sourceforge.pmd.lang.java.symbols.JMethodSymbol.isAnnotationAttribute(JMethodSymbol.java:51)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub$1$$Lambda/0x00003ffc013641c8.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(java.base@23.0.2/ReferencePipeline.java:196)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.base@23.0.2/ArrayList.java:1709)
	at java.util.stream.AbstractPipeline.copyInto(java.base@23.0.2/AbstractPipeline.java:570)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@23.0.2/AbstractPipeline.java:560)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java.base@23.0.2/ReduceOps.java:921)
	at java.util.stream.AbstractPipeline.evaluate(java.base@23.0.2/AbstractPipeline.java:265)
	at java.util.stream.ReferencePipeline.collect(java.base@23.0.2/ReferencePipeline.java:727)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub$1.finishParse(ClassStub.java:139)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.getFinalStatus(ParseLock.java:50)
	- locked <0x0000000408510468> (a net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub$1)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.isFailed(ParseLock.java:82)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub.isUnresolved(ClassStub.java:524)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.checkUserEnclosingTypeIsOk(ClassTypeImpl.java:452)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.validateParams(ClassTypeImpl.java:418)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.<init>(ClassTypeImpl.java:69)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.<init>(ClassTypeImpl.java:64)
	at net.sourceforge.pmd.lang.java.types.TypeSystem.typeOf(TypeSystem.java:466)
	at net.sourceforge.pmd.lang.java.symbols.table.internal.SymTableFactory.fillSingleImports(SymTableFactory.java:299)
	at net.sourceforge.pmd.lang.java.symbols.table.internal.SymTableFactory.singleImportsSymbolTable(SymTableFactory.java:270)
	at net.sourceforge.pmd.lang.java.symbols.table.internal.SymbolTableResolver$MyVisitor.visit(SymbolTableResolver.java:232)
	at net.sourceforge.pmd.lang.java.symbols.table.internal.SymbolTableResolver$MyVisitor.visit(SymbolTableResolver.java:138)
	at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.acceptVisitor(ASTCompilationUnit.java:109)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.acceptVisitor(AbstractJavaNode.java:38)
	at net.sourceforge.pmd.lang.java.symbols.table.internal.SymbolTableResolver$MyVisitor.traverse(SymbolTableResolver.java:164)
	at net.sourceforge.pmd.lang.java.symbols.table.internal.SymbolTableResolver.traverse(SymbolTableResolver.java:101)
	at net.sourceforge.pmd.lang.java.internal.JavaAstProcessor.lambda$process$1(JavaAstProcessor.java:132)
	at net.sourceforge.pmd.lang.java.internal.JavaAstProcessor$$Lambda/0x00003ffc01358000.run(Unknown Source)
	at net.sourceforge.pmd.benchmark.TimeTracker.bench(TimeTracker.java:163)
	at net.sourceforge.pmd.lang.java.internal.JavaAstProcessor.process(JavaAstProcessor.java:132)
	at net.sourceforge.pmd.lang.java.internal.JavaAstProcessor.process(JavaAstProcessor.java:166)
	at net.sourceforge.pmd.lang.java.internal.JavaAstProcessor.process(JavaAstProcessor.java:150)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.parseImpl(JavaParser.java:69)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.parseImpl(JavaParser.java:25)
	at net.sourceforge.pmd.lang.ast.impl.javacc.JjtreeParserAdapter.parse(JjtreeParserAdapter.java:36)
	at net.sourceforge.pmd.lang.impl.PmdRunnable.parse(PmdRunnable.java:112)
	at net.sourceforge.pmd.lang.impl.PmdRunnable.processSource(PmdRunnable.java:132)
	at net.sourceforge.pmd.lang.impl.PmdRunnable.run(PmdRunnable.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@23.0.2/Executors.java:572)
	at java.util.concurrent.FutureTask.run(java.base@23.0.2/FutureTask.java:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@23.0.2/ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@23.0.2/ThreadPoolExecutor.java:642)
	at java.lang.Thread.runWith(java.base@23.0.2/Thread.java:1588)
	at java.lang.Thread.run(java.base@23.0.2/Thread.java:1575)
"PmdThread 4":
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.getFinalStatus(ParseLock.java:41)
	- waiting to lock <0x0000000408510468> (a net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub$1)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.ensureParsed(ParseLock.java:27)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub.getEnclosingTypeParameterOwner(ClassStub.java:418)
	at net.sourceforge.pmd.lang.java.symbols.JTypeParameterOwnerSymbol.getLexicalScope(JTypeParameterOwnerSymbol.java:40)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub.getLexicalScope(ClassStub.java:333)
	at net.sourceforge.pmd.lang.java.symbols.JTypeParameterOwnerSymbol.getLexicalScope(JTypeParameterOwnerSymbol.java:41)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub.getLexicalScope(ClassStub.java:333)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase.getEnclosingTypeParams(GenericSigBase.java:83)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.SignatureParser.typeParamsWrapper(SignatureParser.java:94)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.SignatureParser.parseMethodType(SignatureParser.java:64)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase$LazyMethodType.doParse(GenericSigBase.java:265)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase$1.doParse(GenericSigBase.java:56)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.getFinalStatus(ParseLock.java:48)
	- locked <0x00000004085104b0> (a net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase$1)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.ensureParsed(ParseLock.java:27)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase.ensureParsed(GenericSigBase.java:87)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase$LazyMethodType.getParameterTypes(GenericSigBase.java:333)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ExecutableStub.getArity(ExecutableStub.java:83)
	at net.sourceforge.pmd.lang.java.symbols.JMethodSymbol.isAnnotationAttribute(JMethodSymbol.java:51)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub$1$$Lambda/0x00003ffc013641c8.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(java.base@23.0.2/ReferencePipeline.java:196)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.base@23.0.2/ArrayList.java:1709)
	at java.util.stream.AbstractPipeline.copyInto(java.base@23.0.2/AbstractPipeline.java:570)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@23.0.2/AbstractPipeline.java:560)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java.base@23.0.2/ReduceOps.java:921)
	at java.util.stream.AbstractPipeline.evaluate(java.base@23.0.2/AbstractPipeline.java:265)
	at java.util.stream.ReferencePipeline.collect(java.base@23.0.2/ReferencePipeline.java:727)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub$1.finishParse(ClassStub.java:139)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.getFinalStatus(ParseLock.java:50)
	- locked <0x00000004085d1cd8> (a net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub$1)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.isFailed(ParseLock.java:82)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub.isUnresolved(ClassStub.java:524)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.checkUserEnclosingTypeIsOk(ClassTypeImpl.java:452)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.validateParams(ClassTypeImpl.java:418)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.<init>(ClassTypeImpl.java:69)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.<init>(ClassTypeImpl.java:64)
	at net.sourceforge.pmd.lang.java.types.TypeSystem.typeOf(TypeSystem.java:466)
	at net.sourceforge.pmd.lang.java.types.TypeSystem.rawType(TypeSystem.java:493)
	at net.sourceforge.pmd.lang.java.types.TypeSystem.parameterise(TypeSystem.java:527)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser$TypeScanner.makeClassType(TypeSigParser.java:364)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser.classType(TypeSigParser.java:164)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser.typeSignature(TypeSigParser.java:148)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser.typeSignature(TypeSigParser.java:124)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser.arrayType(TypeSigParser.java:216)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser.typeSignature(TypeSigParser.java:146)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.TypeSigParser.methodType(TypeSigParser.java:53)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.SignatureParser.parseMethodType(SignatureParser.java:65)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase$LazyMethodType.doParse(GenericSigBase.java:265)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase$1.doParse(GenericSigBase.java:56)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.getFinalStatus(ParseLock.java:48)
	- locked <0x0000000408510490> (a net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase$1)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.ensureParsed(ParseLock.java:27)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase.ensureParsed(GenericSigBase.java:87)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.GenericSigBase$LazyMethodType.getParameterTypes(GenericSigBase.java:333)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ExecutableStub.getArity(ExecutableStub.java:83)
	at net.sourceforge.pmd.lang.java.symbols.JMethodSymbol.isAnnotationAttribute(JMethodSymbol.java:51)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub$1$$Lambda/0x00003ffc013641c8.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(java.base@23.0.2/ReferencePipeline.java:196)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.base@23.0.2/ArrayList.java:1709)
	at java.util.stream.AbstractPipeline.copyInto(java.base@23.0.2/AbstractPipeline.java:570)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@23.0.2/AbstractPipeline.java:560)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java.base@23.0.2/ReduceOps.java:921)
	at java.util.stream.AbstractPipeline.evaluate(java.base@23.0.2/AbstractPipeline.java:265)
	at java.util.stream.ReferencePipeline.collect(java.base@23.0.2/ReferencePipeline.java:727)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub$1.finishParse(ClassStub.java:139)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.getFinalStatus(ParseLock.java:50)
	- locked <0x0000000408510a38> (a net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub$1)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.isFailed(ParseLock.java:82)
	at net.sourceforge.pmd.lang.java.symbols.internal.asm.ClassStub.isUnresolved(ClassStub.java:524)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.checkUserEnclosingTypeIsOk(ClassTypeImpl.java:452)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.validateParams(ClassTypeImpl.java:418)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.<init>(ClassTypeImpl.java:69)
	at net.sourceforge.pmd.lang.java.types.ClassTypeImpl.<init>(ClassTypeImpl.java:64)
	at net.sourceforge.pmd.lang.java.types.TypeSystem.typeOf(TypeSystem.java:466)
	at net.sourceforge.pmd.lang.java.symbols.table.internal.SymTableFactory.fillSingleImports(SymTableFactory.java:299)
	at net.sourceforge.pmd.lang.java.symbols.table.internal.SymTableFactory.singleImportsSymbolTable(SymTableFactory.java:270)
	at net.sourceforge.pmd.lang.java.symbols.table.internal.SymbolTableResolver$MyVisitor.visit(SymbolTableResolver.java:232)
	at net.sourceforge.pmd.lang.java.symbols.table.internal.SymbolTableResolver$MyVisitor.visit(SymbolTableResolver.java:138)
	at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.acceptVisitor(ASTCompilationUnit.java:109)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.acceptVisitor(AbstractJavaNode.java:38)
	at net.sourceforge.pmd.lang.java.symbols.table.internal.SymbolTableResolver$MyVisitor.traverse(SymbolTableResolver.java:164)
	at net.sourceforge.pmd.lang.java.symbols.table.internal.SymbolTableResolver.traverse(SymbolTableResolver.java:101)
	at net.sourceforge.pmd.lang.java.internal.JavaAstProcessor.lambda$process$1(JavaAstProcessor.java:132)
	at net.sourceforge.pmd.lang.java.internal.JavaAstProcessor$$Lambda/0x00003ffc01358000.run(Unknown Source)
	at net.sourceforge.pmd.benchmark.TimeTracker.bench(TimeTracker.java:163)
	at net.sourceforge.pmd.lang.java.internal.JavaAstProcessor.process(JavaAstProcessor.java:132)
	at net.sourceforge.pmd.lang.java.internal.JavaAstProcessor.process(JavaAstProcessor.java:166)
	at net.sourceforge.pmd.lang.java.internal.JavaAstProcessor.process(JavaAstProcessor.java:150)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.parseImpl(JavaParser.java:69)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.parseImpl(JavaParser.java:25)
	at net.sourceforge.pmd.lang.ast.impl.javacc.JjtreeParserAdapter.parse(JjtreeParserAdapter.java:36)
	at net.sourceforge.pmd.lang.impl.PmdRunnable.parse(PmdRunnable.java:112)
	at net.sourceforge.pmd.lang.impl.PmdRunnable.processSource(PmdRunnable.java:132)
	at net.sourceforge.pmd.lang.impl.PmdRunnable.run(PmdRunnable.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@23.0.2/Executors.java:572)
	at java.util.concurrent.FutureTask.run(java.base@23.0.2/FutureTask.java:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@23.0.2/ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@23.0.2/ThreadPoolExecutor.java:642)
	at java.lang.Thread.runWith(java.base@23.0.2/Thread.java:1588)
	at java.lang.Thread.run(java.base@23.0.2/Thread.java:1575)

Found 1 deadlock.
```

</details>

A heapdump analysis on the hanging threads shows at `net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock.getFinalStatus`:

Thread 1: ClassStub:org/springframework/context/annotation/ComponentScan$Filter

Thread 4: ClassStub:org/springframework/context/annotation/ComponentScan

Further up the stack we see in `net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.acceptVisitor` these two files are parsed: `ApiApplication.java` (thread 4) and `JpaConfiguration.java' (thread 1)

We notice `@ComponentScan` annotation used in `ApiApplication.java` and `@EnableJpaRepositories` annotation used in `JpaConfiguration.java`. 

We notice that `@EnableJpaRepositories` uses the `Filter` _inner_ interface from `ComponentScan` via

```java
import org.springframework.context.annotation.ComponentScan.Filter;
```

When we remove `@EnableJpaRepositories` from `JpaConfiguration.java` _and_ remove the java import of that `org.springframework.data.jpa.repository.config.EnableJpaRepositories` annotation, we cannot get deadlock situation.

**Code Sample demonstrating the issue:**

ApiApplication.java:

```java
@SpringBootApplication
@ComponentScan({"io.example.auth", "io.example.api"})
public class ApiApplication {

    public static void main(String[] args) {
        SpringApplication.run(ApiApplication.class, args);
    }

}
```

JpaConfiguration.java:

```java
@Configuration
@EnableJpaRepositories(repositoryFactoryBeanClass = SomeRepositoryFactoryBean.class, basePackages = "io.example.persistence")
public class JpaConfiguration {
...
}
```

If needed, we can try to create a small SpringBoot app that triggers the deadlock.

**Steps to reproduce:**

From cli (note it is running with 10 threads, if running with 1 no deadlock occurs):

```bash
/.../pmd-bin-7.11.0/bin/pmd check -t 10 -R /.../PMD-jPinpoint-rules/rulesets/java/jpinpoint-rules.xml -d src/main/java -f text --aux-classpath=target/classes:$(cat classpath.txt) -r java-issues-$(date +"%Y%m%d_%H%M").txt
```

Need to run multiple times to get deadlock, but happens quite often on machine described below.

To generate `classpath.txt`: 

```bash
mvn dependency:build-classpath -Dmdep.outputFile=classpath.txt
```

**Running PMD through:** CLI (see above) | Maven (via sonar:sonar) | PMD Intellij Plugin

When running locally in command line on MacOS (Apple M1 Max - Sequoia 15.3.1):

```bash
java -version
openjdk version "23.0.2" 2025-01-21
OpenJDK Runtime Environment Zulu23.32+11-CA (build 23.0.2+7)
OpenJDK 64-Bit Server VM Zulu23.32+11-CA (build 23.0.2+7, mixed mode, sharing)
```

Same happens with Java 21.

Might be related to #5293. 

Can deadlock be caused by use of  inner interface/class? E.g. `org/springframework/context/annotation/ComponentScan$Filter`

**Related / Similar issues in the past:**
* #5583
* #5309
* #5293
* #4834
* #4757

### PR DESCRIPTION
**Pull request by oowekyala**
ClassStubs now cannot request parsing of another ClassStub while they are themselves being parsed. This is enforced when assertions are enabled. ClassStubs can still be loaded in parallel but they never have to wait for another thread anymore which might be good for performance.

Maybe we should remove the logging statements in ParseLock, the ones about threads locking and such. There shouldn't be any threading problem happening

## Related issues

- Fix #5587
- Related to #5293 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ParseLock.java [hunk 1]
```diff
@@ -116,4 +134,39 @@ private enum ParseStatus {
...
+    abstract static class CheckedParseLock extends ParseLock {
+        private static final ThreadLocal<ParseLock> CURRENT_LOCK = new ThreadLocal<>();
+
+        protected CheckedParseLock(String name) {
+            super(name);
+        }
+
+        @Override
+        final void checkWeAreNotParsingAnother() {
+            if (isAssertEnabled()) {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ParseLock.java:153]: Why do we do this check only when asserts are enabled? Wouldn't it be better to always check, that we don't reenter/parse another class, while parsing? Then we would simply throw a IllegalStateException - as this is a bug.
Or is it so much slower using ThreadLocal, that his has a significant impact?

It seems, that we have `-ea` enabled for the regression-tester (https://github.com/pmd/pmd-regression-tester/blob/2684c6395d958d176eee659ebb776000c843b094/lib/pmdtester/builders/pmd_report_builder.rb#L96) - so we should at least see the errors (if any) there.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ParseLock.java [hunk 2]
```diff
@@ -27,49 +29,65 @@ public void ensureParsed() {
...
+                        // returns. Otherwise, some fields might not have been initialized.
+                        //
+                        // Note: the current thread might reenter the parsing logic through
+                        // finishParse() -> ... -> ensureParsed(). In that case the status is still BEING_PARSED,
+                        // and we don't call finishParse() again. See below for canReenter()
+                        this.status = status;
+
+                        assert status.isFinished : "Inconsistent status " + status;
+                        assert postCondition() : "Post condition not satisfied after parsing sig " + this;
+                    } else if (status == ParseStatus.BEING_PARSED && !canReenter()) {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ParseLock.java:83]: The only place, where we still use canReenter is now in GenericSigBase... did you try, whether we can get rid of canReenter there too? That would make it a bit simpler, I hope...

**Review by adangel — APPROVED** [review]
Thanks!

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ParseLock.java (hunk 1 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ParseLock.java:153]: I think it is just not possible that this branch is taken given how the code is written. It is just validating an assumption for our peace of mind. I don't think using the threadlocal significantly degrades performance but still to me this belongs to the kind of check that we will only want to do to debug a problem

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ParseLock.java (hunk 2 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ParseLock.java:83]: I tried this and the one time this behavior is used is related to type parameters. When we compute annotations on type parameters we go and ask for the typevar's upper bound, which is in the same parse lock. I will take a look to see if we can also get rid of this

Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ParseLock.java]: Thanks!
