### PR TITLE
[java] UnsynchronizedStaticFormatter reports commons lang FastDateFormat

### LINKED ISSUE #1633: [java] UnsynchronizedStaticFormatter reports commons lang FastDateFormat
**Affects PMD Version:** 
6.11

**Rule:**
`UnsynchronizedStaticFormatter`

**Description:**
The new rule `UnsynchronizedStaticFormatter` reports  usage of `org.apache.commons.lang3.time.FastDateFormat` which is a commonly used thread safe alternative to `java.text.SimpleDateFormat`. 

Could you add an exception to not check the instances of  `FastDateFormat`?

`UnsynchronizedStaticDateFormatter` will be removed in PMD 7.0. 

**Code Sample demonstrating the issue:**
```
private static final FastDateFormat FDF = FastDateFormat.getInstance("dd.MM.yyyy HH:mm:ss");
```

### PR DESCRIPTION
**Pull request by Shubham-2k17**
**PR Description:**
Thread safe formatter org.apache.commons.lang3.time.FastDateFormat can now avoid UnsynchronizedStaticFormatterRule.

Fixes #1633

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 2 errors and 2 configuration errors.<br />
<a href="http://chunk.io/pmd/db7cb509663541ea861836e23529b5be/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/multithreading/UnsynchronizedStaticFormatterRule.java [hunk 1]
```diff
@@ -48,6 +52,9 @@ public Object visit(ASTFieldDeclaration node, Object data) {
         }
 
         ASTVariableDeclaratorId var = node.getFirstDescendantOfType(ASTVariableDeclaratorId.class);
+        if (var.getType() != null && Arrays.asList(threadSafeFormatter).contains(var.getType().getName())) {
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/multithreading/UnsynchronizedStaticFormatterRule.java]: this check will work on `FastDateFormat`, but not classes that extend `FastDateFormat`, which makes it somewhat brittle.

I'd suggest you use `TypeHelper.isA(TypeNode, String)` directly (you don't even need to check for `var.getType() == null`, the type helper does everything for you.
