### PR TITLE
[java] CloseResource: Fix NPE in case of "var"

### LINKED ISSUE #2755: [java] [6.27.0] Exception applying rule CloseResource on file ... java.lang.NullPointerException
**Affects PMD Version:** 

6.27.0

**Description:**

Rule: [CloseResource](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#closeresource)

Upgrading from 6.25.0 (because 6.26.0 also had a problem) and running PMD leads to:

**Exception Stacktrace:**

```
Exception applying rule CloseResource on file /home/boris/project/src/File.java, continuing with next rule
java.lang.NullPointerException
        at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.isResourceTypeOrSubtype(CloseResourceRule.java:336)
        at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.getResourceVariables(CloseResourceRule.java:178)
        at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.checkForResources(CloseResourceRule.java:159)
        at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.visit(CloseResourceRule.java:153)
        at net.sourceforge.pmd.lang.java.ast.ASTMethodDeclaration.jjtAccept(ASTMethodDeclaration.java:37)
        at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
        at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:267)
...

```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Gradle

### PR DESCRIPTION
**Pull request by adangel**
## Describe the PR

Fixes the NPE when trying to determine the type. The type might be null.

## Related issues

- Fixes #2755 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR cannot be merged yet.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java [hunk 1]
```diff
@@ -175,7 +175,7 @@ private void checkForResources(ASTMethodOrConstructorDeclaration methodOrConstru
         Map<ASTVariableDeclarator, TypeNode> resVars = new HashMap<>();
         for (ASTVariableDeclarator var : vars) {
             TypeNode varType = getTypeOfVariable(var);
-            if (isResourceTypeOrSubtype(varType)) {
+            if (varType != null && isResourceTypeOrSubtype(varType)) {
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java:178]: So we don't get a NPE anymore, but we also don't consider the var as a violation? I wonder, for example, what is the behavior of the rule if you write
```java
import java.io.*;
public class Foo {
    public int bar() throws IOException {
        var inputStream = getInputStreamFromSomewhere();
        char c = reader.read();
        return c;
    }

    InputStream getInputStreamFromSomewhere() { return null; }
}
```

Normally, it should be exactly the same behavior as if `var` was explicitly written, right? In that case, I'm not sure the rule accounts for that, given we test the ASTType node, not VariableDeclaratorId::getType (which is the type of the var). (Note: since we do that, we are probably failing if the var is declared like `InputStream streamArray[]`)

I think it would make more sense to test VariableDeclaratorId::getType, though I don't know how that interacts with existing tests

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml [hunk 2]
```diff
@@ -1385,6 +1385,27 @@ public class Foo {
...
+
+    <test-code>
+        <description>[java] [6.27.0] Exception applying rule CloseResource on file ... java.lang.NullPointerException #2755</description>
+        <expected-problems>0</expected-problems>
+        <code><![CDATA[
+import java.io.*;
+
+public class Foo {
+    public int bar() {
+        var inputStream = getInputStreamFromSomewhere();
```
Comment (oowekyala) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml:1400]: I don't really like that this method is undefined. In PMD 7 we have good type resolution, but this method call, and the variable, would have type `TypeSystem.UNKNOWN`. If we want to use type resolution in this rule later to improve its precision/generality, we have to use "compilable" code in tests.

You can just define the method in the file, so that typeres can see the signature:
```
InputStream getInputStreamFromSomewhere() { return null; }
```

Note that this is not specific to this PR, but really is a common problem in our tests, because often we just copy-paste the test case provided in the issue, where many types are unresolved.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java (hunk 1 above)
Comment (KroArtem) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java:178]: I was passing by and wanted to ask how is it possible to get var Type in PMD? In that case `var` variable is just ignored, right?

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java [hunk 3]
```diff
@@ -189,7 +189,7 @@ private TypeNode getTypeOfVariable(ASTVariableDeclarator var) {
 
     private TypeNode getDeclaredTypeOfVariable(ASTVariableDeclarator var) {
```
Comment (KroArtem) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java:190]: This is a random place to ask: is it a good idea to use `var` as a variable name?

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java (hunk 1 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java:178]: If the variable type is inferred, then there is no type node, but the type of the VariableDeclaratorId node may be set anyway, if we can resolve the type of the initializer. In the example above, if `Foo` is on the classpath, then `varId.getType() == InputStream.class`

The type of the VariableDeclaratorId is always the "real" type of the variable, provided it's on the classpath and we can resolve it. Manipulating the VariableDeclaratorId is always preferable to testing the type node manually, for reasons explained in [the javadoc](https://docs.pmd-code.org/apidocs/pmd-java/6.27.0/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.html#getType())

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java (hunk 3 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java:190]: There is no ambiguity with the `var` keyword for type inference if that's what you mean, and in this context it's semantically descriptive (not like `int var1, var2` would be), so to me it's fine

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java (hunk 1 above)
Comment (KroArtem) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java:178]: Thanks for your explanation!

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java (hunk 3 above)
Comment (KroArtem) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java:190]: Yep, this is what I was asking, I see your point of view, thanks 👌

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java (hunk 1 above)
Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java:178]: @oowekyala I've added a simple test case for var and it seems to work *as long as the initializer expression is not a method call*. But I think, the lack of resolving method call result types is part of PMD 6. Maybe you fixed this already on the 7 branch?

Anyway: The goal of this PR was to fix the NPE, it was never a goal to improve the rule.
Feel free to create a new issue for tracking the false negative with the above sample.

Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java:178]: OK in that case I believe this pr is good to merge. I'll open an issue as you said
