### PR TITLE
[core] Fix broken concatenation on CPD GUI

### LINKED ISSUE #1173: [core] Some characters in CPD are not shown correctly.
In commit https://github.com/pmd/pmd/commit/e1b954289a7386896edf17c44659cd7f92a52d90 one character strings have been changed to characters. 

However this breaks the string if for example a number will be added after as the number is added to the character instead of the string. 

For example this happens in: 
https://github.com/pmd/pmd/blob/4e29b793d260570ccd71e36876833e4f6a67f2d4/pmd-core/src/main/java/net/sourceforge/pmd/cpd/GUI.java#L634

Which will result in "42 seperate files)" instead of "(2 seperate files)".

### PR DESCRIPTION
**Pull request by jsotuyod**
- Fixes #1173

### CODE REVIEW

File: pmd-core/src/main/java/net/sourceforge/pmd/cpd/GUI.java [hunk 1]
```diff
@@ -631,7 +631,7 @@ private String setLabelFor(Match match) {
             int separatorPos = sourceId.lastIndexOf(File.separatorChar);
             label = "..." + sourceId.substring(separatorPos);
         } else {
-            label = '(' + sourceIDs.size() + " separate files)";
+            label = '(' + String.valueOf(sourceIDs.size()) + " separate files)";
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/cpd/GUI.java]: Wouldn't it be better to use double quotes for the opening parenthesis ?

Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/cpd/GUI.java]: How about `label = String.format("( %d separate files)", sourceIDs.size());`?
