### PR TITLE
[core] Fix HTMLRenderer not using linkPrefix/linePrefix

### LINKED ISSUE #2412: [core] HTMLRenderer doesn't render links to source files
**Affects PMD Version:** 6.22.0

**Description:** When using `-f format` with the properties `-P linkPrefix=https://github.com/user/myproject/blob/master -P linePrefix`, no links are rendered.

**Steps to reproduce:**

1.  `bin/run.sh pmd -d pmd-core -R rulesets/java/quickstart.xml -f html -P linkPrefix=https://github.com/pmd/pmd/blob/master -P linePrefix=L`

The output looks e.g. like this:
```html
<td align="center">70</td>
<td width="*%">/home/andreas/PMD/source/pmd-github/pmd-core/src/main/java/net/sourceforge/pmd/properties/MethodProperty.java</td>
<td align="center" width="5%">93</td>
<td width="*"><a href="https://pmd.github.io/pmd-6.22.0/pmd_rules_java_codestyle.html#unnecessaryfullyqualifiedname">Unnecessary use of fully qualified name 'ValueParserConstants.METHOD_PARSER' due to existing static import 'net.sourceforge.pmd.properties.ValueParserConstants.METHOD_PARSER'</a></td>
</tr>
```

There is no "<a"-tag ...

It should be

```html
<td align="center">70</td>
<td width="*%"><a href="https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/properties/MethodProperty.java#L93">/home/andreas/PMD/source/pmd-github/pmd-core/src/main/java/net/sourceforge/pmd/properties/MethodProperty.java</a></td>
<td align="center" width="5%">93</td>
<td width="*"><a href="https://pmd.github.io/pmd-6.22.0/pmd_rules_java_codestyle.html#unnecessaryfullyqualifiedname">Unnecessary use of fully qualified name 'ValueParserConstants.METHOD_PARSER' due to existing static import 'net.sourceforge.pmd.properties.ValueParserConstants.METHOD_PARSER'</a></td>
</tr>
```

**Running PMD through:** CLI

### PR DESCRIPTION
**Pull request by adangel**
* add new option "htmlExtension", so that the mechanism can
be used with github as well
* render links for suppressed violations and errors

Fixes #2412

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/f9fd6258fe6d4292ab6d31d00ec78b92/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-core/src/main/java/net/sourceforge/pmd/renderers/HTMLRenderer.java [hunk 1]
```diff
@@ -78,6 +89,10 @@ public void renderBody(Writer writer, Report report) throws IOException {
 
     @Override
     public void start() throws IOException {
+        linkPrefix = getProperty(LINK_PREFIX);
```
Comment (adangel) [inline pmd-core/src/main/java/net/sourceforge/pmd/renderers/HTMLRenderer.java:92]: that was the bug

File: pmd-core/src/main/java/net/sourceforge/pmd/renderers/HTMLRenderer.java [hunk 2]
```diff
@@ -134,6 +148,20 @@ private void glomRuleViolations(Writer writer, Iterator<RuleViolation> violation
         }
     }
 
+    private String renderFileName(String filename, int beginLine) {
+        return maybeWrap(StringEscapeUtils.escapeHtml4(determineFileName(filename)),
+                linePrefix == null || beginLine < 0 ? "" : linePrefix + beginLine);
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/renderers/HTMLRenderer.java:153]: The control flow confused me so I added another test. What happens when the link prefix is set but not the line prefix? Currently the link is rendered, but there's nothing behind the `#`. I think this might be useful behavior (no line prefix != empty line prefix), let me know if this is expected and I'll merge the PR

Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/renderers/HTMLRenderer.java:153]: I think we should preserve whatever current behavior it is (not sure, what exactly is correct/expected). But "no line prefix!=empty line prefix" sounds reasonable.

The use cases are:
* noLinePrefix - then, as it is implemented like now, we don't output the line number in the link
* LinePrefix is an empty string - then we should output "#4711". Some systems might use directly the linenumbers as target
* LinePrefix is any non-empty string - like github uses "L". Then we should output "#L4711".

I'll double check, that we have a test case for the empty lineprefix and merge afterwards.

Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/renderers/HTMLRenderer.java:153]: SGTM. Side note: this will make it so, that the property wil need to be changed to `Optional<String>` on 7.0 because the new property framework explicitly forbids null property values. So `Optional.empty()` would mean "no line prefix" instead of null
