### PR TITLE
[core] Log only once all messages

### LINKED ISSUE #1036: [core] Non-XML output breaks XML-based CLI integrations
**Affects PMD Version:**
6.2.0

**Rule:**
All

**Description:**
It looks like in recent builds when you specify `-f xml`, some non-XML information is written to stdout causing XML-based integrations such as my IDE (Illuminated Cloud) to break. For example, here's he result of an otherwise successful execution:

```
This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html#incremental-analysis …<?xml version="1.0" encoding="UTF-8"?><pmd ...>...</pmd>
```

When the CLI is run for structured output, nothing but the structured output should be emitted to stdout/stderr. Otherwise parsing of the contents of the streams will fail unless some form of scrubbing/pre-processing is performed by every integrating client.

**Running PMD through:**

While found through the integration with Illuminated Cloud, this is easily reproducible via the CLI.

### PR DESCRIPTION
**Pull request by jsotuyod**
- CLI runs log only to stderr, never to stdout
 - Both Ant and CLI runs log only once, the root logger never gets a
hold of the logs, completely isolating PMD
 - Fixes #1036

### CODE REVIEW

**Comment by jsotuyod** [comment]
Once merged, remember to add removing `ConsoleLogHandler` to #881

File: pmd-core/src/main/java/net/sourceforge/pmd/util/log/ConsoleLogHandler.java [hunk 1]
```diff
@@ -14,7 +14,9 @@
  * Log to the console using a basic formatter.
  *
  * @author Wouter Zelle
+ * @deprecated This class will be complety removed in 7.0.0
  */
+@Deprecated
 public class ConsoleLogHandler extends Handler {
```
Comment (adangel) [inline pmd-core/src/main/java/net/sourceforge/pmd/util/log/ConsoleLogHandler.java]: So, the culprit was actually this class "ConsoleLogHandler", correct? Because it simply wrote to stdout...

Comment (jsotuyod) [reply pmd-core/src/main/java/net/sourceforge/pmd/util/log/ConsoleLogHandler.java]: Correct!
