### PR TITLE
[cli] Clarify CPD documentation, fix positional parameter handling

### LINKED ISSUE #4676: [doc] Clarify how CPD `--ignore-literals` and `--ignore-identifiers` work
**Affects PMD Version:** 

pmd-bin-7.0.0-rc3

**Description:**

I use the cpd function, and the command is as follows:
```bash
pmd-bin-7.0.0-rc3\bin>.\pmd.bat cpd --language java --format xml --ignore-annotations false --ignore-literals false --ignore-identifiers false --minimum-tokens 45 --dir "...Enum.java"
```
the result is as follows:
```bash
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/.../pmd/lib/groovy-2.4.21.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[main] INFO net.sourceforge.pmd.cli.commands.internal.AbstractPmdSubcommand - Log level is at INFO
<?xml version="1.0" encoding="UTF-8"?>
<pmd-cpd>
   <file path="C:\...Enum.java"
         totalNumberOfTokens="137"/>
   <duplication lines="15" tokens="49">
      <file begintoken="4"
            column="5"
            endcolumn="17"
            endline="16"
            endtoken="52"
            line="2"
            path="C:\...Enum.java"/>
      <file begintoken="59"
            column="5"
            endcolumn="23"
            endline="30"
            endtoken="107"
            line="20"
            path="C:\...Enum.java"/>
      <codefragment><![CDATA[    SUB_LIST("subList"), /* List.subList(int start, int end) */
    GET_BYTES1("getBytes"), /* String.getBytes(...) */

    GET("get"), /* List.get(int index) / FileItem.get() / Properties.get() / Map.get() */
    SET("set"), /* set() / Collection.set(int index, E element) */
    GET_BYTES("getBytes"), /* String.getBytes(...) */

    GET_NAME("getName"), /* ZipEntry.getName(), Class.getName() */
    GET_SIZE("getSize"), /* ZipEntry.getSize() */

    GET_INSTANCE("getInstance"), /* Calendar.getInstance() */

    GET_AND_INCREMENT("getAndIncrement"), /* AtomicInteger.getAndIncrement */

    LOCK("lock"), /* Lock.lock() */]]></codefragment>
   </duplication>
</pmd-cpd>
```
The content from row 2 to 16 is different from row 20 to 30. Args `--ignore-literals` and `--ignore-identifiers` have been set to false. The expected result is no duplicates be found which contradicts the actual result. 

* Is there something wrong with my args? What should I do if I want to reach my expectations?

* And is there any way to know the similarity rate of the duplicates?

Thanks so much!

**Exception Stacktrace:**

```
# Copy-paste the stack trace here
```

**Code Sample demonstrating the issue:**

```java
public enum Enum {
    SUB_LIST("subList"), /* List.subList(int start, int end) */
    GET_BYTES1("getBytes"), /* String.getBytes(...) */

    GET("get"), /* List.get(int index) / FileItem.get() / Properties.get() / Map.get() */
    SET("set"), /* set() / Collection.set(int index, E element) */
    GET_BYTES("getBytes"), /* String.getBytes(...) */

    GET_NAME("getName"), /* ZipEntry.getName(), Class.getName() */
    GET_SIZE("getSize"), /* ZipEntry.getSize() */

    GET_INSTANCE("getInstance"), /* Calendar.getInstance() */

    GET_AND_INCREMENT("getAndIncrement"), /* AtomicInteger.getAndIncrement */

    LOCK("lock"), /* Lock.lock() */
    TRY_LOCK("tryLock"), /* Lock.tryLock() */


    VALIDATE("validate"), /* ValidatorForm.validate */

    PARSE_INT("parseInt"), /* Integer.parseInt */
    PARSE_BYTE("parseByte"), /* Byte.parseByte */
    PARSE_SHORT1("parseShort"), /* Short.parseShort */
    PARSE_LONG("parseLong"), /* Long.parseLong */
    PARSE_FLOAT("parseFloat"), /* Float.parseFloat */
    PARSE_DOUBLE1("parseDouble"), /* Double.parseDouble */
    PARSE_BOOLEAN("parseBoolean"), /* Boolean.parseBoolean */
    SUBMIT("submit"), /* ThreadPoolExecutor.submit(), ExecutorService.submit() */
    EXECUTE("execute"); /* ThreadPoolExecutor.execute() */

    private final String name;

    private CommonMethodEnum(String name) {
        this.name = name;
    }

    public String simpleName() {
        return this.name;
    }
}

```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1.  ... (e.g. if you're using maven: `mvn clean verify`)
2.  ...

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

### PR DESCRIPTION
**Pull request by adangel**
## Related issues

- Fixes #4676

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/6277215263">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/AbstractAnalysisPmdSubcommand.java [hunk 1]
```diff
@@ -34,6 +33,14 @@ public abstract class AbstractAnalysisPmdSubcommand<C extends AbstractConfigurat
             arity = "1..*", split = ",")
     protected List<Path> inputPaths;
 
+    @Parameters(arity = "*", description = "Path to a source file, or directory containing source files to analyze. "
+            + "Equivalent to using --dir.")
+    // Note: we can't directly use inputPaths here, because "--dir" might be specified later in the
+    // command line. And PicoCli will then initialize the field inputPaths with a fresh empty List, replacing
+    // anything what was added before.So we need to combine the two lists in #validate()
+    private List<Path> positionalInputPaths;
```
Comment (jsotuyod) [inline pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/AbstractAnalysisPmdSubcommand.java:41]: I'm unsure I follow… positional parameters are always at the end. Any `--dir` occurrences must be previous…

Comment (adangel) [reply pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/AbstractAnalysisPmdSubcommand.java:41]: apparently, every unmatched parameter is taken as positional, which means these positional parameters can appear at any location...

E.g. `--minimum-tokens 34 --dir SRC_DIR --ignore-identifiers false --debug` was executed before my change as follows:
1. dir: sets "inputPaths" to contain SRC_DIR
2. false: resets the "inputPaths" to only contain false

I don't remember the exact details, but it's implementation specific to PicoCli (I debugged a lot). PicoCli at some point re-initializes the fields before calling the setter or so... the net result was, that SRC_DIR got removed, because PicoCli reset the field to an empty List again before adding/processing the positional parameters...

Comment (jsotuyod) [reply pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/AbstractAnalysisPmdSubcommand.java:41]: Have you tried using a setter for both `--dir` and positional parameters? Reflection to override the value should not be used if a setter is present, and the old `public void setInputPaths(final List<Path> inputPaths)` handled the null case… so maybe having the same for `--dir` would work, without relying on calling `validate` for something that is not a validation.

Comment (adangel) [reply pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/AbstractAnalysisPmdSubcommand.java:41]: I'll give it a try - would be good, if we don't need to depend on `validate` being called....

Comment (adangel) [reply pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/AbstractAnalysisPmdSubcommand.java]: This seems to be working - at lest the unit tests are still good.

I'm going to merge this PR now.
