### PR TITLE
[java] Fix JUnitSpellingRule false positive

### LINKED ISSUE #2477: [java] JUnitSpelling false-positive for JUnit5/4 tests
**Affects PMD Version:** 
6.23

**Description:**
[JUnitSpelling](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#junitspelling) requires some tweaks in terms of documentation and produces false positives for:
1) JUnit4 class when it doesn't extend `TestCase` but has a `setup` method
2) JUnit5 class when it has a `setup` method

**Code Sample demonstrating the issue:**

```java
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class BTest {

    @BeforeEach
    void setup() {    }

    @Test
    void test() {    }
}
```

```java
import org.junit.Before;
import org.junit.Test;
public class BTest {

    @Before
    void setup() {    }

    @Test
    void test() {    }
}
```

**Running PMD through:** *[CLI]*

I suggest two things:

1) Do not trigger if it's a junit5 class (`isJUnit5Class` from `AbstractJUnitRule` can be used).
2) Do not trigger if junit4 doesn't extend `TestCase`

WDYT?

### PR DESCRIPTION
**Pull request by KroArtem**
## Describe the PR

    Do not trigger if it's a junit5 class (isJUnit5Class from AbstractJUnitRule can be used).
    Do not trigger if junit4 doesn't extend TestCase

It'd be probably good to add more explanation to the rule itself.

## Related issues

- Fixes #2477

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 286 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/54d513afcb8640a68403f1eb5a880ac6/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java [hunk 1]
```diff
@@ -89,7 +89,7 @@ private boolean isJUnit3Method(ASTMethodDeclaration method) {
         return isJUnit3Class && method.isVoid() && method.getName().startsWith("test");
     }
 
-    private boolean isJUnit3Class(ASTCompilationUnit node) {
+    protected boolean isJUnit3Class(ASTCompilationUnit node) {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java:92]: I'd not expose these methods.
These methods are called already when visiting CompilationUnit and the result is stored in fields, see lines 38-40 above.
I'd make these fields protected, so that you can use it in the rule.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/JUnitSpellingRule.java [hunk 2]
```diff
@@ -5,13 +5,19 @@
...
+import net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit;
 import net.sourceforge.pmd.lang.java.ast.ASTMethodDeclaration;
 import net.sourceforge.pmd.lang.java.rule.AbstractJUnitRule;
 
 public class JUnitSpellingRule extends AbstractJUnitRule {
 
     @Override
     public Object visit(ASTMethodDeclaration node, Object data) {
+        ASTCompilationUnit acu = node.getFirstParentOfType(ASTCompilationUnit.class);
+        if (isJUnit5Class(acu) || isJUnit4Class(acu)) {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/JUnitSpellingRule.java:17]: If using the protected fields from the base class, you don't need to search here again for the compilation unit and call again the methods - that was already done....

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java (hunk 1 above)
Comment (KroArtem) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java:92]: Indeed, fixed.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/JUnitSpellingRule.java (hunk 2 above)
Comment (KroArtem) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/JUnitSpellingRule.java:17]: You're right

**Comment by KroArtem** [comment]
@adangel , I've changed the description to this one:
```
<description>
            In JUnit 3, the setUp method is used to set up all data entities required in running tests.
            The tearDown method is used to clean up all data entities required in running tests.
            You should not misspell method name if you want your test to set up and clean up everything correctly.
</description>
```
Other remarks are also fixed.
