### PR TITLE
[java] Fix false positive for ModifierOrder

### LINKED ISSUE #6057: [java] ModifierOrder false positive on "abstract sealed class"
**Affects PMD Version:** 7.17.0

**Rule:** ModifierOrder https://docs.pmd-code.org/pmd-doc-7.17.0/pmd_rules_java_codestyle.html#modifierorder
Please provide the rule name and a link to the rule documentation:
<https://docs.pmd-code.org/latest/pmd_rules_XXX_XXX.html#XXX>

**Description:** False positive with the "sealed" modifier on an abstract class.

**Code Sample demonstrating the issue:**

```java
abstract sealed class Test permits Test1 {}
```

**Expected outcome:**: No error.

PMD reports a violation "ModifierOrder:  Missorted modifiers `abstract sealed`."
but that's wrong according to the JLS (Java 17 version linked for `sealed`): https://docs.oracle.com/javase/specs/jls/se17/html/jls-8.html#jls-8.1.1

```text
ClassModifier:
(one of)
[Annotation](https://docs.oracle.com/javase/specs/jls/se17/html/jls-9.html#jls-Annotation) public protected private
abstract static final sealed non-sealed strictfp
```

Note that checkstyle and Google Java format get this right.

**Running PMD through:** *Gradle*

### PR DESCRIPTION
**Pull request by zbynek**
## Describe the PR

Updates order of enum fields to match expected modifier order.

## Related issues

Fixes #6057 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JModifier.java [hunk 1]
```diff
@@ -26,27 +26,25 @@ public enum JModifier {
     PROTECTED(Modifier.PROTECTED),
     PRIVATE(Modifier.PRIVATE),
 
+    ABSTRACT(Modifier.ABSTRACT),
```
Comment (zbynek) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JModifier.java:32]: https://google.github.io/styleguide/javaguide.html#s4.8.7-modifiers

> public protected private abstract default static final sealed non-sealed
  transient volatile synchronized native strictfp

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JModifier.java [hunk 2]
```diff
@@ -26,27 +26,25 @@ public enum JModifier {
...
     /** Modifier {@code "sealed"} (since Java 17). */
     SEALED(0),
     /** Modifier {@code "non-sealed"} (since Java 17). */
     NON_SEALED("non-sealed", 0),
 
-    ABSTRACT(Modifier.ABSTRACT),
-    STATIC(Modifier.STATIC),
-    FINAL(Modifier.FINAL),
-
+    // for fields
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JModifier.java]: I think these comments should be removed. They're likely the reason the modifiers ended up in the wrong order: I added constants in one of those sections instead of focusing on the ordering

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JModifier.java [hunk 3]
```diff
@@ -26,27 +26,25 @@ public enum JModifier {
...
+    TRANSIENT(Modifier.TRANSIENT),
+    VOLATILE(Modifier.VOLATILE),
     // for methods
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JModifier.java]: same

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JModifier.java [hunk 4]
```diff
@@ -26,27 +26,25 @@ public enum JModifier {
...
     SYNCHRONIZED(Modifier.SYNCHRONIZED),
     NATIVE(Modifier.NATIVE),
-    DEFAULT(0),
 
     // not for fields
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JModifier.java]: same

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JModifier.java (hunk 2 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JModifier.java]: Maybe even a comment should be added to say something like 
```java
/*******************************************************************
    NOTE: When adding a constant, check the ordering is consistent with the recommended modifier ordering!
********************************************************************/
```
or something similarly "high visibility"
