### PR TITLE
[java] Fixed 3468 UnusedPrivateMethod false positive when outer class calls private static method on inner class

### LINKED ISSUE #3209: [java] UnusedPrivateMethod false positive with static method and cast expression
**Affects PMD Version:** 6.33.0

**Rule:** [UnusedPrivateMethod](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#unusedprivatemethod)

**Description:**
The usage of the static method is not detected anymore (not sure, if these details are relevant).
The false positive was not reported with PMD 6.32.0.
Maybe this is a side-effect of fixing #3118

**Code Sample demonstrating the issue:**

Method declaration: https://github.com/pmd/pmd/blob/30e841a9cadfbf6395857eedc987c6fdb3075a7d/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentRule.java#L909

Method call: https://github.com/pmd/pmd/blob/30e841a9cadfbf6395857eedc987c6fdb3075a7d/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentRule.java#L1396

**Expected outcome:**

*   Does PMD report a violation, where there shouldn't be one? -> false-positive

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

### LINKED ISSUE #3468: [java] UnusedPrivateMethod false positive when outer class calls private static method on inner class
**Affects PMD Version:** >=6.33.0

**Rule:** [UnusedPrivateMethod](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#unusedprivatemethod)

**Description:** Outer class calling a private method of a static inner class. -> False positive ('unused private method') on the inner class method.

Looks like this was introduced by #3157.

**Code Sample demonstrating the issue:**

```java
public class OuterClass {

	public void foo() {
		InnerClass.doSomething();
	}

	static class InnerClass {
		private static void doSomething() {
		}
	}
}
```

**Expected outcome:** No PMD messages

PMD reports a violation at line 8, but that's wrong. That's a false positive.

**Running PMD through:** *Maven | [eclipse-pmd](https://github.com/eclipse-pmd/eclipse-pmd/)*

### PR DESCRIPTION
**Pull request by johnra2**
- Fixes #3468 
- Fixes #3209

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset changes 92 violations,<br />
introduces 35 new violations, 0 new errors and 0 new configuration errors,<br />
removes 35 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/81bfc9ac8e7d440185b05be84267e847/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java [hunk 1]
```diff
@@ -230,7 +230,13 @@ public String getClassName() {
         Map<ClassNameDeclaration, List<NameOccurrence>> classDeclarations = getClassDeclarations();
         if (result.isEmpty() && !classDeclarations.isEmpty()) {
             for (ClassNameDeclaration innerClass : getClassDeclarations().keySet()) {
+                ASTMethodDeclarator md = innerClass.getNode().getFirstDescendantOfType(ASTMethodDeclarator.class);
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java:233]: This doesn't look correct - only the first method is used and added to the images we search for. Which means, we definitely find the first method always whether it's used or not...

In our case, the name occurrence doesn't reference a field or a method, it references a class - e.g. the inner class and this classnamedeclaration is what we should use. Then the search for the next part - the method in this class - can ontinue starting with this class declaration...

This change as it is right now produces false negatives in other rules, e.g. BeanMembersShouldSerialize and false positives in UnusedPrivateField when inner classes are used...

I'll try to work on this...
