### PR TITLE
[java] JUnitTestsShouldIncludeAssertRule should support `this.exception` as well as just `exception`

### LINKED ISSUE #647: [java] JUnitTestsShouldIncludeAssertRule should support `this.exception` as well as just `exception`
**RuleSet**: JUnit

**Description**: Related to #285, the following variant on the code there will produce an error about missing assertions:

```java
public class DigitalAssetManagerTest {
  @Rule
  public final ExpectedException exception = ExpectedException.none();
  @Test
  public void throwsIllegalArgumentExceptionIfIconIsNull() {
    this.exception.expect(IllegalArgumentException.class);
    this.exception.expectMessage("Icon is null, not a file, or doesn't exist.");
    new DigitalAssetManager(null, null);
  }
}
```
If either of the `this.exception`s are changed to merely `exception`, then the reported error goes away.  While the code samples in https://github.com/junit-team/junit4/wiki/Rules don't display the use of `this.` as a general matter, it is semantically allowed.

This is run with v5.8.1 of PMD via the command line, so it's current behavior.

### PR DESCRIPTION
**Pull request by adangel**
This fixes #647 .
It uses the test from PR #1457.

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations and 0 new errors,<br />
removes 104 violations and 2 errors. <a href="http://chunk.io/pmd/170f0a2552b14bc38c981e86167d339d/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java [hunk 1]
```diff
@@ -173,29 +175,25 @@ private boolean isVerifyStatement(ASTStatementExpression expression) {
...
-                }
-                String varname = img.split("\\.")[0];
-
-                if (!expectables.containsKey(varname)) {
-                    return false;
+        ASTPrimaryExpression pe = expression.getFirstChildOfType(ASTPrimaryExpression.class);
+        if (pe != null) {
+            ASTPrimaryPrefix primaryPrefix = pe.getFirstChildOfType(ASTPrimaryPrefix.class);
+            Node name = pe.getFirstDescendantOfType(ASTName.class);
+            if (!primaryPrefix.usesThisModifier() && name != null) {
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java]: We should probably one day consider `super` here too, but I don't think this would work right now... We'd probably have to explore supertypes via reflection.
