### PR TITLE
[java] InvalidLogMessageFormat - fix false positive with logstash

### LINKED ISSUE #3644: [java] InvalidLogMessageFormat: false positives with logstash structured logging
**Affects PMD Version:** 6.36.0

**Rule:** [InvalidLogMessageFormat](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#invalidlogmessageformat)

**Description:**

**Code Sample demonstrating the issue:**

When using https://github.com/logfellow/logstash-logback-encoder for structured logging (example below), PMD detects it as false positive.

With markers:
```java
import static net.logstash.logback.marker.Markers.*;

// Add "foo:bar" to the JSON output
    LOGGER.info(append("foo", "bar"), "Some log message");
// Add "foo:bar,name:value" to the JSON output
    LOGGER.info(append("foo", "bar").and(append("name", "value")), "Some log message");
```

With structured arguments:
```java
import static net.logstash.logback.argument.StructuredArguments.*;

// Add "foo:bar" to JSON output and "bar" to log message
    LOGGER.info("log message {}", value("foo", "bar"));
// Add "foo:bar" to JSON output only
    LOGGER.info("log message", keyValue("foo", "bar"));
```

**Expected outcome:**

PMD reports a violation at line ..., but that's wrong. That's a false positive.

**Running PMD through:** *Gradle*

### PR DESCRIPTION
**Pull request by adangel**
* Fixes #3644

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 3 configuration errors.<br />
<a href="https://chunk.io/pmd/e310a71093784ee1b2345675831b99ef/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java [hunk 1]
```diff
@@ -319,4 +342,50 @@ private int countPlaceholders(final ASTExpression node) {
...
+    private boolean isStructuredArgumentMethodCall(ASTExpression argument) {
+        if (argument.getNumChildren() == 1 && argument.getChild(0) instanceof ASTPrimaryExpression) {
+            ASTPrimaryExpression primary = (ASTPrimaryExpression) argument.getChild(0);
+            if (primary.getNumChildren() == 2 && primary.getChild(1) instanceof ASTPrimarySuffix) {
+                ASTPrimaryPrefix prefix = (ASTPrimaryPrefix) primary.getChild(0);
+                ASTPrimarySuffix suffix = (ASTPrimarySuffix) primary.getChild(1);
+                if (suffix.isArguments() && prefix.getNumChildren() == 1 && prefix.getChild(0) instanceof ASTName) {
+                    ASTName name = (ASTName) prefix.getChild(0);
+                    return name.getImage().startsWith("StructuredArguments.")
+                        || StringUtil.isAnyOf(name.getImage(), STRUCTURED_ARGUMENTS_METHODS);
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java:385]: This could be replaced by a Set.contains call if `STRUCTURED_ARGUMENTS_METHODS` was a Set
