### PR TITLE
[java] Fix False-positive UnnecessaryFullyQualifiedName when nested and non-nest… #4103

### LINKED ISSUE #4085: [java] UnnecessaryFullyQualifiedName false positive when nested and non-nested classes with the same name and in the same package are used together
One can find a project to reproduce this issue here: https://github.com/OlegAndreych/PMDNestedClassFQNTest.

```java
package some.pkg;

public class Test {
}
```

```java
package some.pkg;

public class OuterTest {
    public static class Test{
        private final some.pkg.Test test; // line 5 - false positive

        public Test(some.pkg.Test test){ // line 7 - false positive

            this.test = test;
        }
    }
}
```

PMD Reports the following violations:

```
[INFO] PMD Failure: some.pkg.OuterTest$Test:5 Rule:UnnecessaryFullyQualifiedName Priority:4 Unnecessary use of fully qualified name 'some.pkg.Test' due to existing same package import 'some.pkg.*'.
[INFO] PMD Failure: some.pkg.OuterTest$Test:7 Rule:UnnecessaryFullyQualifiedName Priority:4 Unnecessary use of fully qualified name 'some.pkg.Test' due to existing same package import 'some.pkg.*'.
```

Both are false positives - the fully qualified name is necessary, since the enclosing class has the same name (`Test`).

### PR DESCRIPTION
**Pull request by OlegAndreych**
…ed classes with the same name and in the same package are used together https://github.com/pmd/pmd/issues/4085

## Describe the PR

Additional search and exclusion of inner classes/interfaces with the same simple name as fully qualified class usage is added.

## Related issues

- Fixes #4085 

## Ready?

- [X] Added unit tests for fixed bug/feature
- [X] Passing all unit tests
- [X] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by OlegAndreych** [comment]
Unfortunately, I’ve messed up with the https://github.com/pmd/pmd/pull/4103, so I’ve created a new pull request.

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 2 errors and 6 configuration errors.<br />
<a href="https://chunk.io/pmd/e010ca5d857d45cfae3f272aa3d2137b/diff1/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java [hunk 1]
```diff
@@ -199,9 +204,27 @@ private void checkImports(TypeNode node, Object data) {
                 String importStr = firstMatch.getImportedName() + (firstMatch.isImportOnDemand() ? ".*" : "");
                 String type = firstMatch.isStatic() ? "static " : "";
 
-                addViolation(data, node, new Object[] { node.getImage(), importStr, type });
+                addViolation(data, node, new Object[]{node.getImage(), importStr, type});
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java:207]: Nit: This can be probably written with `asCtx(data).addViolation(...` as well

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml [hunk 2]
```diff
@@ -622,6 +622,40 @@ public class UnnecessaryFullyQualifiedName {
         ]]></code>
     </test-code>
 
+    <test-code>
+        <description>False positive when same package inner class is referenced (not enum)</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml:626]:
```suggestion
        <description>False positive when same package inner class is referenced (not enum) #4085</description>
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml [hunk 3]
```diff
@@ -622,6 +622,40 @@ public class UnnecessaryFullyQualifiedName {
...
+
+            this.test = test;
+        }
+    }
+}
+        ]]></code>
+    </test-code>
+
+    <test-code>
+        <description>Should report fully-qualified name usage of a class in itself.</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml:645]:
```suggestion
        <description>Should report fully-qualified name usage of a class in itself #4085</description>
```

**Review by adangel — APPROVED** [review]
LGTM, Thanks!
