### PR TITLE
[java] Updates to AST nodes

### LINKED ISSUE #1307: [java] AccessNode API changes
The purpose of AccessNode is to denote a node which can have declaration modifiers, eg `abstract`, `final`, `public`, etc. Some nodes implement it just to get the "final" modifier:
* ASTFormalParameter
* ASTResource (relates to #998)
* ASTLocalVariableDeclaration

ASTLambdaExpression implements it for nothing, due to an implementation error: AbstractMethodLikeNode extends AbstractJavaAccessNode...

1. I think all of these should stop implementing the interface in 7.0.0. We could have a separate base class for nodes that can be final, or implement it ad-hoc with a boolean since FormalParameter is a TypeNode and so we'd have to have several base classes. The amount of duplication seems acceptable
2. The setters should be removed from the interface. They're only used by the parser, and could be package-private

### LINKED ISSUE #3751: [java] Rename some node types
These renamings should not be done while the PMD 6 branch remains active, as they could introduce more conflicts when merging master back into the pmd 7 branch.

  * ASTClassOrInterfaceType -> ASTClassType
  * ASTClassOrInterfaceDeclaration -> ASTClassDeclaration

   These currently match the JLS productions, but we're not the JLS and can use more convenient names.

  * ASTAnyTypeDeclaration -> ASTTypeDeclaration (ASTTypeDeclaration is a node in the current tree but was removed)
  * ASTMethodOrConstructorDeclaration -> ASTExecutableDeclaration
  * AccessNode -> ModifierOwner

This issue was extracted from #2701

### PR DESCRIPTION
**Pull request by adangel**
## Describe the PR

Finish the remaining open tasks for Java (#1307, #3751).

~Note: I don't want to remove any methods for now, just deprecate them, if not already. I think, we should remove the deprecated methods only after a RC5, to have some deprecation notice. However, renaming classes definitely breaks...
Not sure, if it's worth to wait. I'll see, once I proceed with this PR.~

In this case, I decided now to remove the method ASTClassDeclaration#isPackagePrivate since we renamed the class from ASTClassOrInterfaceDeclaration. So, deprecating isn't that helpful.

**Tasks:**
*   [x] push down isStatic to just ASTMethodOrConstructorDeclaration, ASTFieldDeclaration and ASTAnyTypeDeclaration as it's convenient (like isAbstract)
    * Note: moved isStatic to ASTMethodDeclaration instead, as constructors can't be static
*   [x] add a hasVisibility(Visibility) method to AccessNode, to replace the isPublic/Private/*, etc, for the convenience of java rules
*   [x] Remove FinalizableNode, as it's not a solid abstraction, and just push down isFinal to ASTVariableDeclaratorId, ASTAnyTypeDeclaration, ASTFieldDeclaration, and ASTMethodOrConstructorDeclaration for convenience
    * Note: added to ASTAnyTypeDeclaration, ASTCatchParameter, ASTFormalParameter, ASTLambdaParameter, ASTLocalVariableDeclaration, ASTVariableDeclaratorId, ASTMethodDeclaration
*   [x] Rename AccessNode -> ModifierOwner, including API doc in release notes
*   [x] Rename ASTClassOrInterfaceType -> ASTClassType, including API doc in release notes
*   [x] Rename ASTClassOrInterfaceDeclaration -> ASTClassDeclaration, including API doc in release notes
*   [x] Rename ASTAnyTypeDeclaration -> ASTTypeDeclaration (ASTTypeDeclaration is a node in the current tree but was removed), including API doc in release notes
    * including AbstractAnyTypeDeclaration -> AbstractTypeDeclaration
    * Old ASTTypeDeclaration in PMD6: https://github.com/pmd/pmd/blob/pmd_releases/6.55.0/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTTypeDeclaration.java
*   [x] Rename ASTMethodOrConstructorDeclaration -> ASTExecutableDeclaration
    * including AbstractMethodOrConstructorDeclaration -> AbstractExecutableDeclaration
*   [x] Rename ASTVariableDeclaratorId -> ASTVariableId
*   [x] Rename ASTClassOrInterfaceBody -> ASTClassBody
*   [x] Fix deprecated API usages in rules (e.g. addViolation calls, deprecated getter usages)
*   [x] Integrate some parts of #4352 - notably:
    * ASTLiteral improvements and introducing getLiteralText(). Note: Using `Long.parseUnsignedLong` rather than a custom implementation.
    * Expose Chars-typed attributes in XPath, so that `@LiteralText` is available
    * The goal is, that we don't use deprecated methods anymore, so we can delete them. It's not the goal to improve rule implementations in general.

## Related issues

* Fixes #1307
* Fixes #3751

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/7169965293">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oowekyala** [comment]
Thanks for starting this! I would also suggest renaming VariableDeclaratorId to VariableId since it's used relatively often in the codebase.

**Comment by adangel** [comment]
I guess, we should also rename ASTClassOrInterfaceBody to ASTClassBody. It looks odd, if we leave ASTClassOrInterfaceBody... (it's the only one with "ClassOrInterface")

**Comment by adangel** [comment]
I think, this is ready now.
It's unfortunately quite big, but the task list gives a good overview I think.

Many deprecated API usages are resolved. I integrated parts of #4352 (ASTLiteral improvements, XPath Attribute improvements).
I kept out changing getImage in general (which was started in #4352) and only fixed usage, when there is a direct
replacement (e.g. getName). Reasons:

- I don't want to make this PR even bigger.
- I think, we should back out the deprecation of Node::getImage and improve it later - see #4318 for that.
  There are still some issues, e.g. XPathRule requires something to get the message for reporting violations...
  without that, we can't finish it.
- Node::getImage is _not_ deprecated on PMD6, it was only deprecated on the PMD7 branch
- Similar case is PropertySource::dysfunctionReason - I think, it's better to un-deprecate it and deprecate it
  again only when we have a replacement for it.

Deleting deprecations needs to be done in a separate PR (I don't want to make this even bigger).

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/PrettyPrintingUtil.java [hunk 1]
```diff
@@ -170,19 +170,19 @@ public static String getNodeName(JavaNode node) {
...
-            return ((ASTAnyTypeDeclaration) node).getSimpleName();
-        } else if (node instanceof ASTVariableDeclaratorId) {
-            return ((ASTVariableDeclaratorId) node).getName();
+        } else if (node instanceof ASTTypeDeclaration) {
+            return ((ASTTypeDeclaration) node).getSimpleName();
+        } else if (node instanceof ASTVariableId) {
+            return ((ASTVariableId) node).getName();
         } else {
-            return node.getImage(); // todo get rid of this
+            throw new IllegalArgumentException("Node " + node + " has no defined name");
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/PrettyPrintingUtil.java:185]: Just a detail, but since the node toString might be large and contain spaces I think it's nicer to put it at the end
```suggestion
            throw new IllegalArgumentException("Node has no defined name: " + node);
```

**Review by oowekyala — APPROVED** [review]
Thanks, this looks good
