### PR TITLE
[core] Allow symlinking run.sh

### LINKED ISSUE #1272: [core] Could not find or load main class when using symlinked run.sh
**Affects PMD Version:**  pmd-bin-6.6.0

**Description:**

```
LANG=C run.sh cpd --files myfoo 
Error: Could not find or load main class net.sourceforge.pmd.cpd.CPD

```

```
java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

```

Please let me know if you need further information.

OS: Ubuntu 16.04.4 LTS

### PR DESCRIPTION
**Pull request by jsotuyod**
Fixes #1272

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-dist/src/main/scripts/run.sh [hunk 1]
```diff
@@ -61,7 +61,13 @@ java_heapsize_settings() {
 
 set_lib_dir() {
   if [ -z ${LIB_DIR} ]; then
-    local script_dir=$(dirname "${0}")
+    # Allow for symlinks to this script
+    if [ -L $0 ]; then
+      local script_real_loc=$(readlink "$0")
```
Comment (oowekyala) [inline pmd-dist/src/main/scripts/run.sh]: Maybe we should `readlink --canonicalize` here to follow links recursively if need be? The script_real_loc would be an absolute path too, which may helps debugging

Comment (adangel) [reply pmd-dist/src/main/scripts/run.sh]: It's not strictly needed (it seems to be working for all cases), however: we could spare the if-statement, because with --canonicalize, readlink always returns the absolute path (whether a symlink has been involved or not).

So, we could just always execute readlink:

`local script_real_loc=$(readlink --canonicalize "$0")`

Comment (jsotuyod) [reply pmd-dist/src/main/scripts/run.sh]: `--canonicalize` is not a valid flag for `readlink` under Mac OS, that's why I went another direction

Comment (adangel) [reply pmd-dist/src/main/scripts/run.sh]: You're right, `--canonicalize` is a GNU extension...
