### PR TITLE
[java] GuardLogStatement false positive on return statements and Math.log

### LINKED ISSUE #869: [java] GuardLogStatement false positive on return statements and Math.log
**Affects PMD Version:** 

6.0.1 (did not happen with 6.0.0)

**Rule:**

GuardLogStatement

**Description:**

The code below gets flagged although it should not since I'm not using any exception.

**Code Sample demonstrating the issue:**

```java
return Single.error(new IllegalStateException("No permission was pre-configured for " + permission));
```

You can also check out this PR - https://github.com/vanniktech/RxPermission/pull/21 - which fails

**Report**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd"
    version="6.0.1" timestamp="2018-01-21T19:15:40.307">
<file name="/Users/nik/tmp/RxPermission/library/src/main/java/com/vanniktech/rxpermission/MockRxPermission.java">
<violation beginline="32" endline="32" begincolumn="12" endcolumn="104" rule="GuardLogStatement" ruleset="Best Practices" package="com.vanniktech.rxpermission" class="MockRxPermission" method="request" externalInfoUrl="https://pmd.github.io/pmd-6.0.1/pmd_rules_java_bestpractices.html#guardlogstatement" priority="2">
There is log block not surrounded by if
</violation>
</file>
</pmd>
```

**Running PMD through:** *[Gradle]*

### PR DESCRIPTION
**Pull request by adangel**
Fixes #869 

The rule is still very prone to false-positives, since we use string matching...

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementRule.java [hunk 1]
```diff
@@ -171,23 +185,54 @@ private String getLastPartOfName(String name) {
...
+     * Gets the first child, first grand child, ... of the given types.
+     * The children must follow the given order of types
+     *
+     * @param root the node from where to start the search
+     * @param childrenTypes the list of types
+     * @param <N> should match the last type of childrenType, otherwise you'll get a ClassCastException
+     * @return the found child node or <code>null</code>
+     */
+    @SafeVarargs
+    private static <N> N getFirstChild(Node root, Class<? extends Node> ... childrenTypes) {
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementRule.java]: this is interesting, something we may want to even move to `AbstractNode` maybe?

Comment (jsotuyod) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementRule.java]: Also, it should probably be `<N extends Node> N`
