### PR TITLE
[core] Fix renderer tests for windows builds

### LINKED ISSUE #2067: [core] Build issue on Windows
**Affects PMD Version:**  Freshly checked out master (commit bf2bece0856dd7c9d1a6a8ea976bc0f798e67413) 

**Description:** Tests fail during build on Windows due to file separator issues.

Built on Windows 7 w/ OpenJDK 13 and the provided maven wrapper. [Build log.](https://gist.github.com/Saladoc/350bc65496d0f0121b1b3543a243c023)

All failures follow the pattern of ```[ERROR]   Run 2: CSVRendererTest>AbstractRendererTst.testRenderer:111 expected:<...t","Rule"
"1","","n[/]a","5","1","blah","R...> but was:<...t","Rule"
"1","","n[\]a","5","1","blah","R...>```

I'm opening this issue to make sure that it is an actual problem with the code and not my setup and have started working on a PR to use the platform dependent file separator as obtained from `File.separator()` for the tests.

### PR DESCRIPTION
**Pull request by Saladoc**
Before submitting a PR, please check that:
 - [X] The PR is submitted against `master`. 
 - [X] `./mvnw clean verify` passes.

**PR Description:**

Remove the platform-specific file separators from the test cases and does some cleaning work.

Before, there were many instances of the `sourcecodeFilename` being hard-coded into the dest data. This PR also cleans up the tests so that they will always rely on the values returned by a utility method (most commonly `AbstractRendererTest#getSourceCodeFilename`.

Fixes #2067

### CODE REVIEW

**Comment by Saladoc** [comment]
Fixes #2067

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-core/src/test/java/net/sourceforge/pmd/renderers/SummaryHTMLRendererTest.java [hunk 1]
```diff
@@ -31,6 +31,11 @@ public Renderer getRenderer() {
         return result;
     }
 
+    @Override
+    protected String getSourceCodeFilename() {
+        return "notAvailable";
```
Comment (adangel) [inline pmd-core/src/test/java/net/sourceforge/pmd/renderers/SummaryHTMLRendererTest.java]: Did you need to override this to get it working? Would it work with the super method when the source code filename is "notAavailable.ext"?

Comment (Saladoc) [reply pmd-core/src/test/java/net/sourceforge/pmd/renderers/SummaryHTMLRendererTest.java]: It would not work with the super method. The final file name in the source code then would be *link_prefix**notAvilable.ext**.html#line_prefix1* which causes the Renderer to throw up since it then assumes `ext.html` is the file extension.

Comment (Saladoc) [reply pmd-core/src/test/java/net/sourceforge/pmd/renderers/SummaryHTMLRendererTest.java]:
```[ERROR] net.sourceforge.pmd.renderers.SummaryHTMLRendererTest.testRendererMultiple(net.sourceforge.pmd.renderers.SummaryHTMLRendererTest)
[ERROR]   Run 1: SummaryHTMLRendererTest>AbstractRendererTest.testRendererMultiple:125 expected:<..._prefixnotAvailable.[ext.html#line_prefix1">notAvailable.ext</a></td>
<td align="center" width="5%">1</td>
<td width="*">blah</td>
</tr>
<tr> 
<td align="center">2</td>
<td width="*%"><a href="link_prefixnotAvailable.ext.html#line_prefix1">notAvailable.ext]</a></td>
<td align...> but was:<..._prefixnotAvailable.[html#line_prefix1">notAvailable</a></td>
<td align="center" width="5%">1</td>
<td width="*">blah</td>
</tr>
<tr> 
<td align="center">2</td>
<td width="*%"><a href="link_prefixnotAvailable.html#line_prefix1">notAvailable]</a></td>
<td align...>
[ERROR]   Run 2: SummaryHTMLRendererTest>AbstractRendererTest.testRendererMultiple:125 expected:<..._prefixnotAvailable.[ext.html#line_prefix1">notAvailable.ext</a></td>
<td align="center" width="5%">1</td>
<td width="*">blah</td>
</tr>
<tr> 
<td align="center">2</td>
<td width="*%"><a href="link_prefixnotAvailable.ext.html#line_prefix1">notAvailable.ext]</a></td>
<td align...> but was:<..._prefixnotAvailable.[html#line_prefix1">notAvailable</a></td>
<td align="center" width="5%">1</td>
<td width="*">blah</td>
</tr>
<tr> 
<td align="center">2</td>
<td width="*%"><a href="link_prefixnotAvailable.html#line_prefix1">notAvailable]</a></td>
<td align...>
```
If the sourceFilename has an extension, it is apprently stripped away by the renderer
