### PR TITLE
[java] JavaRuleViolation reports wrong class name

### LINKED ISSUE #2212: [java] JavaRuleViolation reports wrong class name
**Affects PMD Version:** 6.20.0

**Description:**

In some cases, the reported class is wrong. This might be a regression of #2105 .

**Code Sample demonstrating the issue:**

```java
package pkg;
public class Foo {
    int a;
}
```

If e.g. UnusedField is reported on the node "FieldDeclaration", then the resulting class name is "Foo$Foo" instead of just "Foo".

```xml
<violation beginline="3" endline="3" begincolumn="4" endcolumn="9" rule="UnusedPrivateField" ruleset="Best Practices" package="pkg" class="Foo$Foo" variable="a" externalInfoUrl="https://pmd.github.io/pmd-6.20.0/pmd_rules_java_bestpractices.html#unusedprivatefield" priority="3">
 Avoid unused private fields such as 'a'.
 </violation>
```

Note, that this only affects nodes, the are descendants of the class declaration. If the violation is created directly on the class node, then the class name is fine.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

### PR DESCRIPTION
**Pull request by adangel**
Fixes #2212

Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/f281859f262b4472b7afa11c53f4c0da/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolation.java [hunk 1]
```diff
@@ -105,7 +105,7 @@ public static boolean isSupressed(Node node, Rule rule) {
     private void setClassNameFrom(JavaNode node) {
         String qualifiedName = null;
 
-        if (node.getScope() instanceof ClassScope) {
+        if (node instanceof AbstractAnyTypeDeclaration && node.getScope() instanceof ClassScope) {
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolation.java]: Why not use ASTAnyTypeDeclaration? AbstractAnyTypeDeclaration is deprecated

Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolation.java]: Mm I see the rest of the class does use ASTAnyTypeDeclaration
