### PR TITLE
[java] Multiple improvements to JavaQualifiedName

### LINKED ISSUE #837: [java] CFGs of declared but not called lambdas are treated as parts of an enclosing method's CFG
**Affects PMD Version:** 
6.0.0 (and older ones I suppose)

**Rule:**
`CyclomaticComplexity`

**Description:**
Currently, PMD treats CFG's of lambdas that are declared but not called in a method as a part of the method's CFG which falsely increases a reported cyclomatic complexity values of such methods.

**Code Sample demonstrating the issue:**

Here is an example of a dummy method which is considered by PMD as having cyclomatic complexity = 12 while the expected value is below 10:
```
public void notSoComplex(int intInput)
{
	boolean binary;

	switch (intInput)
	{
		case 0:
			binary = false;

			break;

		case 1:
			binary = true;

			break;

		default:
			throw new RuntimeException();
	}

	BiConsumer<Object, Object> lambda1 = (message, nme) ->
	{
		if (binary)
		{
			System.out.println(message);
		}
		else
		{
			System.out.println(nme);
		}
	};

	BiConsumer<Integer, Integer> lambda2 = (nme, message) ->
	{
		if ((nme != 0) && (message != 0))
		{
			try
			{
				System.out.println(nme);
			}
			catch (IllegalArgumentException illegalArgumentException)
			{
				throw new RuntimeException();
			}

			if (binary)
			{
				System.out.println(nme);
			}
			else
			{
				System.out.println(nme);

				if (nme != 1)
				{
					System.out.println(nme);
				}

				for (int i = 0; i < message; i++)
				{
					System.out.println(nme);
				}
			}
		}
	};
}
```

**Running PMD through:** *[Gradle]*

### PR DESCRIPTION
**Pull request by oowekyala**
Hi,

I thought that the commit history is clean enough to submit all that at once, but let me know if you want me to split the PR

Many refactorings were made in view of #864, and the PR adds support for anonymous class and lambda expression qnames

Commit b30d64d fixes #837

### CODE REVIEW

**Comment by oowekyala** [comment]
This is part of a bigger changeset, which aims to implement #864. The next PR in line is an implementation of the qualified name resolving visitor discussed in that issue, which significantly reduces the complexity of the qualified name resolution code, and simplifies some parts of ClassTypeResolver. 

The changeset as a whole fixes a lot of type resolution bugs and clarifies its code. I think this PR should be scheduled for 6.2.0 to move forward.

**Comment by jsotuyod** [comment]
@oowekyala great! I'll schedule some time for this over my weekend. It's a large PR, but I think I can make it.

**Comment by oowekyala** [comment]
@jsotuyod Great, thanks :)

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnnotationTypeDeclaration.java [hunk 1]
```diff
@@ -7,9 +7,8 @@
 
 import java.util.List;
 
-public class ASTAnnotationTypeDeclaration extends AbstractJavaAccessTypeNode implements ASTAnyTypeDeclaration {
+public class ASTAnnotationTypeDeclaration extends ASTAnyTypeDeclaration {
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnnotationTypeDeclaration.java]: this is a breaking API change. Do we really need to do it in 6.2.0? Can't we just deprecate the methods?

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnyTypeDeclaration.java [hunk 2]
```diff
@@ -6,33 +6,72 @@
...
 
+
 /**
- * Groups enums, classes and interface declarations.
+ * Groups enum, class, annotation and interface declarations.
  *
  * @author Clément Fournier
  */
-public interface ASTAnyTypeDeclaration extends JavaQualifiableNode, AccessNode, JavaNode {
+public abstract class ASTAnyTypeDeclaration extends AbstractJavaAccessTypeNode implements JavaQualifiableNode, AccessNode, JavaNode {
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnyTypeDeclaration.java]: the change from interface to abstract class is also a breaking API change

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceDeclaration.java [hunk 3]
```diff
@@ -10,13 +10,12 @@
 import net.sourceforge.pmd.lang.ast.Node;
 
 
-public class ASTClassOrInterfaceDeclaration extends AbstractJavaAccessTypeNode implements ASTAnyTypeDeclaration {
+public class ASTClassOrInterfaceDeclaration extends ASTAnyTypeDeclaration {
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceDeclaration.java]: ditto

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTConstructorDeclaration.java [hunk 4]
```diff
@@ -5,13 +5,10 @@
 
 package net.sourceforge.pmd.lang.java.ast;
 
-import net.sourceforge.pmd.lang.java.multifile.signature.JavaOperationSignature;
 
-public class ASTConstructorDeclaration extends AbstractJavaAccessNode implements ASTMethodOrConstructorDeclaration {
+public class ASTConstructorDeclaration extends ASTMethodOrConstructorDeclaration {
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTConstructorDeclaration.java]: ditto

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTEnumDeclaration.java [hunk 5]
```diff
@@ -7,9 +7,8 @@
 
 import java.util.List;
 
-public class ASTEnumDeclaration extends AbstractJavaAccessTypeNode implements ASTAnyTypeDeclaration {
+public class ASTEnumDeclaration extends ASTAnyTypeDeclaration {
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTEnumDeclaration.java]: ditto

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ImmutableList.java [hunk 6]
```diff
@@ -0,0 +1,542 @@
...
+ * <p>This implementation is designed for {@link JavaQualifiedName}, to
+ * represent package and class hierarchies. It is not meant as a general-
+ * purpose implementation.
+ *
+ * @param <E> Element type
+ *
+ * @author Clément Fournier
+ * @since 6.1.0
+ */
+public interface ImmutableList<E> extends Iterable<E> {
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ImmutableList.java]: why do we need our own inmutable list implementation? What's wrong with `Collections.unmodifiableList`?

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTMethodOrConstructorDeclaration.java [hunk 7]
```diff
@@ -7,16 +7,34 @@
...
  * @author Clément Fournier
+ * @see MethodLike
+ * @since 5.8.1
  */
-public interface ASTMethodOrConstructorDeclaration extends
-                                                   SignedNode<ASTMethodOrConstructorDeclaration>,
-                                                   JavaQualifiableNode,
-                                                   AccessNode,
-                                                   JavaNode {
+public abstract class ASTMethodOrConstructorDeclaration extends MethodLike implements SignedNode<ASTMethodOrConstructorDeclaration> {
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTMethodOrConstructorDeclaration.java]: ditto

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/QualifiedNameFactory.java [hunk 8]
```diff
@@ -0,0 +1,598 @@
+/**
+ * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
+ */
+
+package net.sourceforge.pmd.lang.java.ast;
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/QualifiedNameFactory.java]: this class should probably not be part of this package

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/MethodLike.java [hunk 9]
```diff
@@ -0,0 +1,56 @@
...
+
+package net.sourceforge.pmd.lang.java.ast;
+
+/**
+ * Groups method, constructor and lambda declarations under a common type.
+ *
+ * @author Clément Fournier
+ * @since 6.1.0
+ */
+public abstract class MethodLike extends AbstractJavaAccessNode implements JavaQualifiableNode, JavaNode {
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/MethodLike.java]: why is this the only class on the AST that is not named a `Node`?

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java [hunk 10]
```diff
@@ -4,379 +4,156 @@
 
 package net.sourceforge.pmd.lang.java.ast;
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java]: this class should probably not be part of this package

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ImmutableList.java (hunk 6 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ImmutableList.java]: `Collections.unmodifiableList` isn't persistent, and doesn't have a free prepend or append operation. I feel like an immutable list like what's found in functional languages is perfect for the problem, and especially for the visitor (next PR). It's good for clarity and conciseness of code, clarity of interface, and performance too. I implemented what I was missing. 

If using this interface instead of List for the return type of a few methods doesn't bother you in itself, then the factories are private so the only dependable code we introduce is the interface, which is in itself very thin. Otherwise, well we could use util.List, but I think it would feel like a workaround...

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnyTypeDeclaration.java (hunk 2 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnyTypeDeclaration.java]: This seems to cause trouble. We could very much keep the abstract class and interface separate, which wouldn't be API breaking. We'd just insert an abstract class in the hierarchy.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnnotationTypeDeclaration.java (hunk 1 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnnotationTypeDeclaration.java]: Which methods?

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java (hunk 10 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java]: Moving it out would be API breaking

**Comment by oowekyala** [comment]
@jsotuyod I used Japicmp to test binary compatibility with the latest released version. This version of the PR introduces only minute binary compatibility-breaking changes, namely, I didn't bridge the `supports` method of concrete operation metrics classes, like what I did in 2fd5d7c. E.g.:

```scala
***! MODIFIED CLASS: PUBLIC net.sourceforge.pmd.lang.java.metrics.impl.NpathMetric  (not serializable)
  ===  CLASS FILE FORMAT VERSION: 51.0 <- 51.0
  ---! REMOVED METHOD: PUBLIC(-) double computeFor(net.sourceforge.pmd.lang.java.ast.ASTMethodOrConstructorDeclaration, net.sourceforge.pmd.lang.metrics.MetricOptions)
```


Bridging preserves binary compatibility but compels clients to explicitly add a cast to the method argument to link to the recommended method instead of the deprecated one. Without bridging, a simple recompilation links correctly to the new API. Under those conditions, I'm not sure whether adding bridges like in 2fd5d7c is the best idea, but at least it's binary compatible now, except for those corner cases which I think should be rare enough.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java (hunk 10 above)
Comment (jsotuyod) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java]: True, I've added it to #881. I'd avoid having the factory on this package non the less to avoid that breaking change in 7.0.0

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ImmutableList.java (hunk 6 above)
Comment (jsotuyod) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ImmutableList.java]: I'm just very cautious about including (and maintaining!) ~600 LoCs for a basic data structure for which Java has several implementations and decorators.... Even if you want a smaller API just allowing prepends, does it earn us anything at all to manually implement the linked list over just using `LinkedList`?

>  This implementation has constant-time prepend, size, head and tail

`LinkedList`:
* [x] constant-time `addFirst()`
* [x] constant-time `size()`
* [x] constant-time `getFirst()`
* [x] constant-time `getLast()`

> Most other operations are linear-time, but caching helps reduce the overhead of some common operations (reverse)

Equally applicable over a `LinkedList`

> Allows structural sharing of the tail, which makes many operations constant- or zero-memory cost.

`LinkedList`:
* [x] `subList()` provides a "view" of the original list, effectively sharing whatever part of the list you want

Even if we keep the `ImmutableList<E>` interface as API, most of the current implementation is just a `LinkedList` when a thin wrapper over  `LinkedList` suffices; so I'd rather just use it than reinvent the wheel

Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ImmutableList.java]: The interface of a LinkedList is very different from the interface of that list: `void addFirst(E)` vs `ImmutableList<E> prepend(E)`. A LinkedList can add an element to a list in o(1), while an immutable list can *create a new list* with one more element in o(1) (time and space).  We don't want to add elements fast, we want to create a new, bigger collection fast, and never add elements. This is something you only get with o(n) time and space in java, because you have to copy the old list each time

Besides subList cannot be used for proper structural sharing. You could use it for a `tail` operation but not for a `prepend`. From the subList doc:
> The semantics of the list returned by this method become undefined if the backing list (i.e., this list) is structurally modified in any way other than via the returned list. (Structural modifications are those that change the size of this list, or otherwise perturb it in such a fashion that iterations in progress may yield incorrect results.)

I can't see a way to wrap a LinkedList to make it conform to that interface, without creating a full new LinkedList at each prepend operation, which is exactly what I was trying to avoid. 

I understand the concern about not reimplementing the wheel because it's hard to maintain, but the Java standard lib lacks immutable and persistent collections, which is a shame. Alternatively, I found a light [3rd party lib](https://pcollections.org/) that implements some basic ones, and is very compatible with the standard Collections framework. It's less than 20 classes, and I think it could be useful in other places -- some algorithms are better expressed with them. I'd much rather use that than keep the current full implementation -- i just didn't bother to search

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java (hunk 10 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java]: The next PR moves ~80% of the factory out into the visitor. If you're ok with it, I'd rather move it out of the package then, otherwise I'd have some merge conflicts to resolve ^^

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ImmutableList.java (hunk 6 above)
Comment (jsotuyod) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ImmutableList.java]: I'd rather not add a dependency for a single class.

I'm still hesitant, specially given you are only using an iterator + the ability to skip the first element on this PR, but I'll give you benefit of the doubt to see what's in follow up PRs. I hope you can convince me, I'd hate to see us roll it back in 7.0.0

However, I still strongly believe this class should not be part of this package.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java (hunk 10 above)
Comment (jsotuyod) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java]: If the next PR doesn't make it into 6.2.0 we would be in the very difficult position of either having to roll this back before the release, or deprecate it in 6.3.0. Not the happiest path in either case... I'm trusting you on this one, but let's be careful.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CyclomaticComplexityRule.java [hunk 11]
```diff
@@ -139,11 +139,17 @@ public Object visit(ASTAnyTypeDeclaration node, Object data) {
...
+    public final Object visit(MethodLikeNode node, Object data) {
 
         int cyclo = (int) JavaMetrics.get(JavaOperationMetricKey.CYCLO, node, cycloOptions);
         if (cyclo >= methodReportLevel) {
-            addViolation(data, node, new String[]{node instanceof ASTMethodDeclaration ? "method" : "constructor",
+            String nodeType = node.getKind() == MethodLikeKind.METHOD
+                    ? "method"
+                    : node.getKind() == MethodLikeKind.CONSTRUCTOR
+                            ? "constructor"
+                            : "lambda";
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CyclomaticComplexityRule.java]: sounds like a name for `MethodLikeKind`, something that should be part of the enum itself possibly

**Comment by jsotuyod** [comment]
@oowekyala I'm merging this as is, so as to not block you anymore. Please, look into the remaining comments in upcoming PRs. Sorry for the delay, the changeset resulted to be a little less straightforward than anticipated.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java (hunk 10 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java]: I'll open the next PR asap

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CyclomaticComplexityRule.java (hunk 11 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CyclomaticComplexityRule.java]: I think I can open another PR for this small changeset
