### PR TITLE
[java] Fix #6127: Correct var name in violation decorator

### LINKED ISSUE #6127: [java] Incorrect variable name in violation
> Also notice that `${variableName}` is not being replaced by a value in the warning message. 

 _Originally posted by @cowwoc in [#5750](https://github.com/pmd/pmd/issues/5750#issuecomment-2889209156)_

Reproducer example:

Rule: [AvoidUsingHardCodedIP](https://docs.pmd-code.org/latest/pmd_rules_java_bestpractices.html#avoidusinghardcodedip)

Code sample:
```java
import java.net.InetAddress;
class TestCase {
    InetAddress address = InetAddress.getByName("0.0.0.0");
}
```

Expected message: "Do not hard code the IP address address"

Actual message: "Do not hard code the IP address ${variableName}"

### PR DESCRIPTION
**Pull request by adangel**
## Related issues

- Fix #6127 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by zbynek** [comment]
Since the rule checks for literals in general, not just in assignments, maybe the error message for this rule should mention the hardcoded IP and not the variable it's assigned to? Or at least do that as a fallback if there is no assignment ancestor?

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaViolationDecorator.java [hunk 1]
```diff
@@ -100,7 +100,7 @@ private static String getVariableNames(Iterable<ASTVariableId> iterable) {
         } else if (node instanceof ASTFormalParameter) {
             return getVariableNameIfExists(node.firstChild(ASTVariableId.class));
         } else if (node instanceof ASTExpression) {
-            return getVariableNameIfExists(node.getParent());
+            return getVariableNameIfExists(node.ancestors(ASTVariableDeclarator.class).first());
```
Comment (zbynek) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaViolationDecorator.java]: This will claim that hardcoded IP is assigned to variable named `run` in

```java
public class Foo {
    public void foo() {
        Runnable run = () -> {
            System.out.println("0.0.0.0");
        };
    }
}
```

which is somewhat misleading, the iteration up the tree should probably stop on `ReturnScopeNode`.
