### PR TITLE
[java] Fix #6502: CloseResource should consider unqualified method calls

### LINKED ISSUE #6502: [java] CloseResource: False positive for allowedResourceMethodPatterns entries when using unqualified method calls
**Affects PMD Version:** 
PMD 7.22.0 (7f74d775143d842c9a9964e59e64284596a83a84, 2026-02-27T10:20:20Z)

**Description:**
If you add custom entries to the `allowedResourceMethodPatterns` property of the `CloseResource` rule, those functions still produce violations if they are invoked from within the same class, or from a derived class. They correctly exclude violations from unrelated classes.

**Code Sample demonstrating the issue:**

####  src/mypack/Action.java
```java
package mypack;

import java.sql.Connection;

public abstract class Action implements AutoCloseable {
    private Connection connection;

    @Override
    public void close() throws Exception {
        connection.close();
    }

    public Connection getConnection() {
        return connection;
    }

    public abstract void run();

    public void func() {
        final var c = getConnection(); // violation detected
    }
}
```

####  src/mypack/ConsumerAction.java
```java
package mypack;

public class ConsumerAction extends Action {

    @Override
    public void run() {
        final var c = getConnection(); // violation detected
    }
}
```

####  src/mypack/ConsumerClass.java
```java
package mypack;

public class ConsumerClass {

    public void run(Action action) {
        final var c = action.getConnection(); // no violation detected
    }
}
```

####  test-ruleset.xml
```xml
<ruleset xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd"
         name="Customized ruleset"
>
    <description>Customized rule set</description>
    <rule ref="category/java/errorprone.xml/CloseResource">
        <properties>
            <property name="allowedResourceMethodPatterns"
                      value="mypack.Action#getConnection()" />
        </properties>
    </rule>
</ruleset>
```

**Steps to reproduce:**

```shell
javac -d classes src/mypack/*
pmd check --no-progress --rulesets=test-ruleset.xml --dir=src --aux-classpath classes
```

**Output:**

```
[WARN] This analysis could be faster, please consider using Incremental Analysis: https://docs.pmd-code.org/pmd-doc-7.22.0/pmd_userdocs_incremental_analysis.html
src/mypack/Action.java:20:	CloseResource:	Ensure that resources like this Connection object are closed after use
src/mypack/ConsumerAction.java:7:	CloseResource:	Ensure that resources like this Connection object are closed after use
```

**Running PMD through:** *[CLI | Maven]*

Java version: 25.0.2, vendor: Amazon.com Inc., runtime: /Library/Java/JavaVirtualMachines/amazon-corretto-25.jdk/Contents/Home

### PR DESCRIPTION
**Pull request by adangel**
## Related issues

- Fix #6502

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java [hunk 1]
```diff
@@ -167,7 +167,10 @@ boolean matches(ASTExpression expr) {
                 return false;
             }
             ASTExpression qualifier = call.getQualifier();
-            return qualifier != null && TypeTestUtil.isA(qualifierType, qualifier);
+            if (qualifier != null) {
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java]: Why is this not an InvocationMatcher? This class doesn't validate the pattern at all (which may very well make the constructor crash with IndexOutOfBoundsException). InvocationMatcher is more flexible and well specified. It also handles this specific case (unqualified method calls) better, as it also handles static methods.

Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java]: Thanks for pointing this out.
The only difference is, that for InvocationMatcher to work correctly, PMD must be called with the correct auxclasspath.
But honestly, if PMD is not called correctly, then no one can expect correct results.

I'll change to to use InvocationMatcher.

Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java]: I think InvocationMatcher is using TypeTestUtil internally and should therefore work the same most of the time. The difference is maybe with overload resolution, but then yes, users should call PMD correctly anyway

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml [hunk 2]
```diff
@@ -2182,11 +2182,11 @@ public class RegularWriter {
 
     <test-code>
         <description>#6436 Custom allowedResourceMethodPatterns property</description>
-        <rule-property name="allowedResourceMethodPatterns">com.example.MyFactory#getResource()</rule-property>
+        <rule-property name="allowedResourceMethodPatterns">net.sourceforge.pmd.lang.java.rule.errorprone.closeresource.MyFactory#getResource()</rule-property>
         <expected-problems>0</expected-problems>
         <code><![CDATA[
+package net.sourceforge.pmd.lang.java.rule.errorprone.closeresource;
 import java.io.InputStream;
-import com.example.MyFactory;
```
Comment (oowekyala) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml:2189]: I would actually expected an InvocationMatcher to also match `factory.getResource()` below even with a type that is not on the classpath... I will take a look to see if we can fix InvocationMatcher in this case

Comment (adangel) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml:2189]: I'm going to merge this PR now. You can create a new PR, if there is a better way.

IMHO it could only work for this simple case (method defined on the same type as the reference), but not anymore, if the called method is defined on an interface/super class - in that case, we need the full types.
