### PR TITLE
[core] CPD: Lexical error in file (no file name provided)

### LINKED ISSUE #1559: [core] CPD: Lexical error in file (no file name provided)
**Affects PMD Version:** 6.10.0

**Rule:** CPD

**Description:**

Running CPD on the given file (`run.sh cpd --minimum-tokens 100 --language cpp --files File.cpp`) produces the following error:
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file (no file name provided) at line 7, column 37.
The parse error is unfortunate, but what is more surprising is that the error message says "no file name provided", even though I have provided the filename. When running the same command with PMD 6.9.0, the error message does contain the correct filename:
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file /tmp/project/File.cpp at line 7, column 37.  Encountered: "\n" (10), after : "\"QML("

**Code Sample demonstrating the issue:**

```
namespace ABC
{
  namespace DEF
  {

#ifdef USE_QT
    const char* perPixelQml = R"QML(
)QML";
  }
}
#endif // USE_QT
```

**Running PMD through:** *CLI*

### PR DESCRIPTION
**Pull request by adangel**
Fixes #1559

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-core/src/main/java/net/sourceforge/pmd/cpd/JavaCCTokenizer.java [hunk 1]
```diff
@@ -0,0 +1,42 @@
+/**
+ * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
+ */
+
+package net.sourceforge.pmd.cpd;
```
[the remark this answers is not in the document]
Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/cpd/JavaCCTokenizer.java]: Hm... not sure. I would consider this still an API - you typically subclass this abstract class instead of implementing the whole Tokenizer interface directly, when you're implementing support for a new language.

We could mark it as \@Experimental, since it adds a couple of protected methods - which might or might not change in the future...

[the remark this answers is not in the document]
Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/cpd/JavaCCTokenizer.java]: I'll move this to the internal package.

[the remark this answers is not in the document]
Comment (jsotuyod) [reply pmd-core/src/main/java/net/sourceforge/pmd/cpd/JavaCCTokenizer.java]: I agree with you @adangel, this is intended as a utility for new languages to subclass, and therefore probably public API... Using `@Experimental` would be an option if we feel this may change in the future, and we possibly graduate it in a future release (8.0.0?).

Marking it internal is maybe too strong a message to third party developers.

File: docs/pages/release_notes.md [hunk 2]
```diff
@@ -60,6 +60,8 @@ This is a {{ site.pmd.release_type }} release.
     *   [#1542](https://github.com/pmd/pmd/pull/1542): \[apex] Include the documentation category
     *   [#1546](https://github.com/pmd/pmd/issues/1546): \[apex] PMD parsing exception for Apex classes using 'inherited sharing' keyword
     *   [#1568](https://github.com/pmd/pmd/pull/1568): \[apex] AST node attribute @Image not usable / always null in XPath rule / Designer
+*   cpp
+    *   [#1559](https://github.com/pmd/pmd/issues/1559): \[cpp] CPD: Lexical error in file (no file name provided)
```
Comment (jsotuyod) [inline docs/pages/release_notes.md]: I think we should move this to core / all. Even if the original bug was filed for cpp, this affects all languages.

File: pmd-cpp/src/main/java/net/sourceforge/pmd/cpd/CPPTokenizer.java [hunk 3]
```diff
@@ -92,4 +69,14 @@ private String maybeSkipBlocks(String test) throws IOException {
         }
         return filtered.toString();
     }
+
+    @Override
+    protected TokenManager getLexerForSource(SourceCode sourceCode) {
+        try {
+            StringBuilder buffer = sourceCode.getCodeBuffer();
+            return new CppTokenManager(IOUtil.skipBOM(new StringReader(maybeSkipBlocks(buffer.toString()))));
```
Comment (jsotuyod) [inline pmd-cpp/src/main/java/net/sourceforge/pmd/cpd/CPPTokenizer.java]: we should add a TODO to move `maybeSkipBlocks` logic into a tokenfilter extending `JavaCCTokenFilter`

File: pmd-core/src/main/java/net/sourceforge/pmd/cpd/internal/JavaCCTokenizer.java [hunk 4]
```diff
@@ -0,0 +1,46 @@
+/**
+ * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
+ */
+
+package net.sourceforge.pmd.cpd.internal;
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/cpd/internal/JavaCCTokenizer.java]: I didn't heard back from you guys, so I'm raising my concern again.

I don't think this should be internal. We actually want language developers to use this as a starting point. I'm ok with marking it `@Experimental` if we are unsure about the included methods.

Actually, the `AntlrTokenizer` is currently neither internal nor `@Experimental`

Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/cpd/internal/JavaCCTokenizer.java]: Some point we discussed on a comment in #1558 is whether implementing third party languages should really be a published API. It's very likely that we're the only ones to work with that API (if we're not then I would assume that the numbers of clients can be counted on one hand). I personally don't think publicly supporting that API is worth the trouble if it's next to unused outside of our codebase. Wdyt?

Comment (jsotuyod) [reply pmd-core/src/main/java/net/sourceforge/pmd/cpd/internal/JavaCCTokenizer.java]: I agree, they are far too few, but there are a couple such as https://github.com/jk1/pmd-kotlin

I fear what kind of message it sends to both them and their users when they can't rely on which versions of PMD it will work, as an internal package means it can be broken at any single point in time.

If I wear them, I would avoid this base class altogether / copy it locally; which kind of misses the point of having a base class in the first place.

Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/cpd/internal/JavaCCTokenizer.java]: What you say makes sense too. I've not made up my mind, I think we should discuss that further in the next meeting

Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/cpd/internal/JavaCCTokenizer.java]: Let's keep it internal for now. We can make it a public API later, if needed.

*TODO:* Make it consistent with AntlrTokenizer -> this should be marked as internal API then

Comment (jsotuyod) [reply pmd-core/src/main/java/net/sourceforge/pmd/cpd/internal/JavaCCTokenizer.java]: I already did this upon merge
