### PR TITLE
[plsql,tsql] Fix CPD being case sensitive in PLSQL and TSQL

### LINKED ISSUE #4396: [core] CPD is always case sensitive
**Affects PMD Version:** 6.x

**Description:**

Some languages like PL/SQL or the new T-SQL (#4390) are case-insensitive. When tokenizing, this is working correctly, e.g. the lexers are agnostic to casing. JavaCC has a grammar option and ANTLR since 4.10 as well.

However, when we convert the original tokens into CPD TokenEntries, we don't seem to use the token kind and use the original token text, which contains the original casing. It's therefore very easy to work around duplicated for these languages by just changing the casing:

```shell
echo 'select a, b, c, d, e, f from table where x = 1 and y = 2;' > file1.plsql
cp file1.plsql file2.plsql
echo 'sEleCt a, b, c, d, e, f frOm table where x = 1 and y = 2;' > file3.plsql

run.sh cpd --minimum-tokens 20 --language plsql --dir file1.plsql file2.plsql
```

results correctly in:
```
Found a 1 line (23 tokens) duplication in the following files: 
Starting at line 1 of /home/andreas/temp/plsql/file1.plsql
Starting at line 1 of /home/andreas/temp/plsql/file2.plsql

select a, b, c, d, e, f from table where x = 1 and y = 2;
```
since file1.plsql and file2.plsql are identical.

However, comparing file1.plsql and file3.plsql which differ only in casing, shows no duplications:

```
run.sh cpd --minimum-tokens 20 --language plsql --dir file1.plsql file3.plsql
```

I think, this problem affects both JavaCC and ANTLR based languages.

### PR DESCRIPTION
**Pull request by oowekyala**
## Describe the PR

Since these are two different lexer implementations (Javacc and Antlr), there are two different solutions which use the same idea, which is to project the image of most tokens into uppercase. I didn't use a language property to disable this behavior (like done in Apex) although that could be done.

## Related issues

- Fixes #4396

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/antlr4/AntlrToken.java [hunk 1]
```diff
@@ -30,10 +34,14 @@ public class AntlrToken implements GenericToken<AntlrToken> {
      * @param previousComment The previous comment
      * @param textDoc         The text document
      */
-    public AntlrToken(final Token token, final AntlrToken previousComment, TextDocument textDoc) {
-        this.token = token;
+    AntlrToken(final Token token, final AntlrToken previousComment, TextDocument textDoc, AntlrLexerBehavior behavior) {
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/antlr4/AntlrToken.java:37]: Note that this is a breaking change, but it's in an `impl` package.

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/antlr4/AntlrToken.java [hunk 2]
```diff
@@ -17,9 +17,13 @@
  */
 public class AntlrToken implements GenericToken<AntlrToken> {
 
-    private final Token token;
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/antlr4/AntlrToken.java:20]: I removed this so that we don't store two different image strings for each token, which would be memory inefficient.

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/8618350584">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParser.java [hunk 3]
```diff
@@ -4,16 +4,53 @@
...
+    // Stores images of constant string literals.
+    // This is to reuse the image strings for PLSQL keywords.
+    // JavaCC unfortunately does not store a constant image for those
+    // keywords because the grammar is case-insensitive.
+    // This optimization has the effect that the image of keyword tokens
+    // is always upper-case, regardless of the actual case used in the code.
+    // The original casing can be found by looking at the TextDocument for the file.
+
+    // NOTE: the size of this array should be greater than the number of tokens in the file.
+    private static final String[] STRING_LITERAL_IMAGES_EXTRA = new String[512];
```
Comment (adangel) [inline pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParser.java:29]: We seem to have a public static list of all the tokens available:

```suggestion
    private static final String[] STRING_LITERAL_IMAGES_EXTRA = new String[PLSQLTokenKinds.TOKEN_NAMES.size()];
```

File: pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParser.java [hunk 4]
```diff
@@ -4,16 +4,53 @@
...
+        int i = 0;
+        String image = PLSQLTokenKinds.describe(i);
+        while (image != null && i < STRING_LITERAL_IMAGES_EXTRA.length) {
+            if (image.startsWith("\"") && image.endsWith("\"")) {
+                // a string literal image, remove the quotes
+                image = image.substring(1, image.length() - 1);
+                STRING_LITERAL_IMAGES_EXTRA[i] = image;
+            }
+            i++;
+        }
```
Comment (adangel) [inline pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParser.java:41]: Warning - I didn't try this... But I think, using TOKEN_NAMES directly is better than checking for null to find the end of the loop...

```suggestion
        for (int i = 0; i < PLSQLTokenKinds.TOKEN_NAMES.size(); i++) {
            String image = PLSQLTokenKinds.TOKEN_NAMES.get(i);
            if (image.startsWith("\"") && image.endsWith("\"")) {
                // a string literal image, remove the quotes
                image = image.substring(1, image.length() - 1);
                STRING_LITERAL_IMAGES_EXTRA[i] = image;
            }
        }
```

File: pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/cpd/testdata/sample-plsql.txt [hunk 5]
```diff
@@ -5,45 +5,45 @@ L1
     [REPLACE]                               11        18
 L2
     [PACKAGE]                               1         8
-    ["test_schema"]                         9         22
+    ["TEST_SCHEMA"]                         9         22
```
Comment (adangel) [inline pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/cpd/testdata/sample-plsql.txt:8]: hm... isn't that an identifier? ~If so, then we probably shouldn't uppercase it...~

Ok, it is an identifier, a "quoted literal"... In that sense, it is not different from e.g. a variable name, and we should indeed uppercase it...

Just double checking, can you confirm?

File: pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/cpd/testdata/sample-plsql_ignore-literals.txt [hunk 6]
```diff
@@ -0,0 +1,1729 @@
...
+L23
+    [AUTHOR]                                1         7
+    [CONSTANT]                              9         17
+    [VARCHAR2]                              18        26
+    [(]                                     26        27
+    [<UNSIGNED_NUMERIC_LITERAL>]            27        30
+    [)]                                     30        31
+    [:]                                     32        33
+    [=]                                     33        34
+    ["\\'"]                                 35        58
```
Comment (adangel) [inline pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/cpd/testdata/sample-plsql_ignore-literals.txt:54]: Unfortunately string literals don't appear here as `<STRING_LITERAL>` which would be nicer...

**Review by adangel — COMMENTED** [review]
Thanks!

>  I didn't use a language property to disable this behavior (like done in Apex) although that could be done.

That's ok. We already removed the property in Apex, as it usually doesn't make sense to have this configurable. It's defined by the language and the language is either case-insensitive or not.

Maybe we could mention this (the fact that a language could be case-insensitive) in https://docs.pmd-code.org/latest/pmd_devdocs_major_adding_new_cpd_language.html and the like?

File: pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/cpd/testdata/sample-plsql.txt (hunk 5 above)
Comment (oowekyala) [reply pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/cpd/testdata/sample-plsql.txt:8]: From the plsql [doc](https://docs.oracle.com/en/database/oracle/oracle-database/21/lnpls/plsql-language-fundamentals.html#GUID-C4B3F788-770E-48F8-9A44-ACD7977B1545):
> A quoted user-defined identifier is case-sensitive, with one exception: If a quoted user-defined identifier, without its enclosing double quotation marks, is a valid ordinary user-defined identifier, then the double quotation marks are optional in references to the identifier, and if you omit them, then the identifier is case-insensitive. 

Maybe we should only uppercase quoted identifiers that fit this criteria. E.g. `"not id"` will not be uppercased, but `"an_id"` is uppercased, because it can be referenced as `An_Id` for instance (without quotes), which would itself be uppercased.

File: pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/cpd/testdata/sample-plsql_ignore-literals.txt (hunk 6 above)
Comment (oowekyala) [reply pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/cpd/testdata/sample-plsql_ignore-literals.txt:54]: Yeah that's a javacc problem... I'm not sure we can transform the code to get the nice name but I will look into it

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/antlr4/AntlrLexerBehavior.java [hunk 7]
```diff
@@ -0,0 +1,32 @@
...
+ */
+public class AntlrLexerBehavior {
+
+
+    /**
+     * Return the image that the token should have, possibly applying a transformation.
+     * The default just returns {@link Token#getText()}.
+     * Transformations here are usually normalizations, for instance, mapping
+     * the image of all keywords to uppercase/lowercase to implement case-insensitivity,
+     * or replacing the image of literals by a placeholder to implement {@link CpdLanguageProperties#CPD_ANONYMIZE_LITERALS}.
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/antlr4/AntlrLexerBehavior.java:23]: Up to now these things would have been done in the token filter, which is supported by both Javacc and antlr.

I'm a little wary of adding yet another mechanism that can overlap. The only reason to get something into the lexer itself is because the behavior should apply both to cpd and pmd, as it's inherent to the language.

Yes, the tokenfilter was a catch all that made for some complex implementations and would probably use some cleanup, but I'm unsure this is is.

I feel we need to have a better defined boundary / limit extension points. Once this is published we will have to support it.

Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/antlr4/AntlrLexerBehavior.java:23]: > I'd love to see this behavior pushed into the lexer rather the token / token manager as is the case for Javacc.

Do you mean having this behavior pushed into the Antlr lexer, so that the Antlr parser also sees the normalized image? In that case I agree, it would be nicer. I can look into it.

I think overall using the token filter to do that is an abuse when the language itself applies specific normalizations. That's why I believe our Javacc extension point is justified, and we need a mirror extension point for Antlr.

Comment (jsotuyod) [reply pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/antlr4/AntlrLexerBehavior.java:23]: Yes, you got my intent right.

Try and push this down to the antlr lexer, the same way the Javacc one works. It will seamlessly apply to pmd and cpd, make it non optional (it's language behavior), and exclude it as an extension point.

Other cpd specific behaviors such as anonymize literals should be done in cpd specific code. Right now that is the token filter, but as we both agree, at some point that api will need to evolve.

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/antlr4/AntlrToken.java [hunk 8]
```diff
@@ -30,10 +34,22 @@ public class AntlrToken implements GenericToken<AntlrToken> {
...
+        this.endOffset = token.getStopIndex() + 1; // exclusive
+        this.channel = token.getChannel();
+        this.kind = token.getType();
+    }
+
+    /**
+     * @deprecated Don't create antlr tokens directly, use an {@link AntlrTokenManager}
+     */
+    @Deprecated
+    public AntlrToken(final Token token, final AntlrToken previousComment, TextDocument textDoc) {
```
Comment (adangel) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/antlr4/AntlrToken.java:51]: TODO: Release notes

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/javacc/JavaccToken.java [hunk 9]
```diff
@@ -147,6 +147,11 @@ public String getImage() {
         return image.toString();
     }
 
+    /** Returns the original text of the token. The image may be normalized. */
```
Comment (adangel) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/javacc/JavaccToken.java:150]:
```suggestion
    /** Returns the original text of the token. The image may be normalized, e.g. for case-insensitive languages. */
```

File: pmd-plsql/etc/grammar/PLSQL.jjt [hunk 10]
```diff
@@ -5436,10 +5430,13 @@ void KEYWORD(String id) #void:
     }
 }
 
-ASTKEYWORD_UNRESERVED KEYWORD_UNRESERVED (): {}
+// This is only used to generate a node class
+// @Deprecated
+ASTKEYWORD_UNRESERVED KEYWORD_UNRESERVED (): {}{KEYWORD_NOT_RESERVED() {return jjtThis;}}
```
Comment (adangel) [inline pmd-plsql/etc/grammar/PLSQL.jjt:5435]: TODO: Release notes

File: pmd-tsql/src/main/java/net/sourceforge/pmd/lang/tsql/cpd/TSqlCpdLexer.java [hunk 11]
```diff
@@ -19,4 +23,19 @@ public class TSqlCpdLexer extends AntlrCpdLexer {
     protected Lexer getLexerForSource(CharStream charStream) {
         return new TSqlLexer(new CaseChangingCharStream(charStream, true));
     }
+
+    @Override
+    protected AntlrLexerBehavior getLexerBehavior() {
```
[the remark this answers is not in the document]
Comment (adangel) [reply pmd-tsql/src/main/java/net/sourceforge/pmd/lang/tsql/cpd/TSqlCpdLexer.java:28]: This seems to be working... This means, we have now more time to think about the API, if we actually ever need one.

For some reason, the JavaCC implementation is much more complicated (with TokenDocumentBehavior)... But I left this as is.

[the remark this answers is not in the document]
Comment (oowekyala) [reply pmd-tsql/src/main/java/net/sourceforge/pmd/lang/tsql/cpd/TSqlCpdLexer.java]: The Javacc implementation is more complicated because it helps with actual Javacc lexing. OTOH Antlr does it lexing alone, and does not use this "token behavior", which is only used by CPD. Hence the difference
