### PR TITLE
[apex] New Rule: AvoidInterfaceAsMapKeyRule

### LINKED ISSUE #6492: [apex] Prevent use of interface -> abstract class with equals/hashcode as key in map
**Proposed Rule Name:** AvoidInterfaceAsMapKey

**Proposed Category:** Error Prone

**Description:** In apex, when a `Map` uses an interface as key, where equals / hashCode are implemented by an abstract class implementation of the interface, methods on `Map` such as `containsKey` do not dispatch to the correct equals/hashCode implementation. 

Involves many classes which might make a more accurate rule implementation difficult, easiest would be to prevent usage of interfaces in key, but that would likely be too broad. An ideal implementation would probably be difficult - where an interface is used as key & there is an implementation of that interface that defines equals/abstract.

**Code Sample:** A minimal reproduction of the apex bug can be seen here: https://github.com/Traction-Rec/map-eq-dispatch-bug/blob/main/force-app/main/default/classes/MapEqualsDispatchBugTest.cls 

```java
public interface IKey {
    Boolean equals(Object obj);
    Integer hashCode();
    String toString();
}

public abstract class AbstractKey implements IKey {
    protected abstract String getKeyValue();

    public Boolean equals(Object obj) {
        System.debug('AbstractKey.equals() called - dispatch worked!');
        if (obj instanceof AbstractKey) {
            return ((AbstractKey) obj).getKeyValue() == this.getKeyValue();
        }
        return false;
    }

    public Integer hashCode() {
        System.debug('AbstractKey.hashCode() called - dispatch worked!');
        String v = getKeyValue();
        return v != null ? System.hashCode(v) : 0;
    }

    public override String toString() {
        return getKeyValue();
    }
}

public class StringKey extends AbstractKey {
    private String value;

    public StringKey(String value) {
        this.value = value;
    }

    protected override String getKeyValue() {
        return value;
    }
}

@IsTest
private class MapEqualsDispatchBugTest {
    @IsTest
    static void containsKeyWithAbstractMiddle() {
        Map<IKey, String> m = new Map<IKey, String>(); // Rule would throw, violation is use of this interface
        IKey k1 = new StringKey('hello');
        m.put(k1, 'value');
        IKey k2 = new StringKey('hello');
        System.assertEquals(k1.hashCode(), k2.hashCode());
        for (IKey existing : m.keySet()) {
            System.assert(k2.equals(existing), 'k2.equals(existing)');
            System.assert(existing.equals(k2), 'existing.equals(k2)');
        }
        System.assert(m.containsKey(k2), 'Hypothesis: containsKey with interface→abstract→concrete (StringKey)'); // This incorrectly returns false
    }
}
```

**Possible Properties:**

I don't think properties are necessary / useful

### PR DESCRIPTION
**Pull request by JonnyPower**
## Describe the PR

Apex has a dispatch bug in the implementation of `Map` that can result in difficult errors. This PMD rule looks for the structure that results in `Map`'s bad dispatch, when a Map is using an interface as a key, the rule uses `ApexLink` to find implementations of the interface, then checking if any implementation is abstract & overrides equals / hashCode - this will result in incorrect dispatching from Map's methods.

This was largely implemented with AI, confirmed resulting jar finds violations against https://github.com/Traction-Rec/map-eq-dispatch-bug but doesn't trigger violation just because an interface is being used. 

Ran this rule against relatively large internal project and it completed succesfully.

## Related issues

- Fix #6492

## Ready?

- [X] Added unit tests for fixed bug/feature
- [X] Passing all unit tests
- [X] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [X] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/multifile/ApexMultifileAnalysis.java [hunk 1]
```diff
@@ -114,6 +126,127 @@ public List<Issue> getFileIssues(String filename) {
...
+        }
+        return false;
+    }
+
+    /**
+     * Returns true if the org contains an abstract class that implements the given interface (by simple name)
+     * and also defines {@code equals(Object)} or {@code hashCode()}.
+     * Returns false when multifile analysis is unavailable.
+     */
+    public boolean hasAbstractImplementorWithEqualsOrHashCode(String interfaceSimpleName) {
```
Comment (JonnyPower) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/multifile/ApexMultifileAnalysis.java]: could move this method to the rule class instead if we think this is way too specific for the general multifile class

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/multifile/ApexMultifileAnalysis.java [hunk 2]
```diff
@@ -114,6 +126,127 @@ public List<Issue> getFileIssues(String filename) {
...
+        if (org == null) {
+            return false;
+        }
+        for (TypeSummary summary : getAllTypeSummaries()) {
```
Comment (JonnyPower) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/multifile/ApexMultifileAnalysis.java]: open to much better (more performant) lookup here, each Map with an interface key in the input class will call here, with many types in an org, could be quite slow

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/internal/Helper.java [hunk 3]
```diff
@@ -195,4 +195,52 @@ public static String getFQVariableName(ASTParameter p) {
...
     }
+
+    /**
+     * Extracts the key type from a Map type string, e.g. {@code "Map<IKey, String>"} returns {@code "IKey"}.
+     * Handles nested generics e.g. {@code "Map<List<A>, B>"} returns {@code "List<A>"}.
+     *
+     * @param typeName full type string (e.g. from {@link net.sourceforge.pmd.lang.apex.ast.ASTVariableDeclaration#getType()})
+     * @return the key type, or null if the type is not Map&lt;K,V&gt; or malformed
+     */
+    public static String getMapKeyType(String typeName) {
```
Comment (JonnyPower) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/internal/Helper.java:206]: the `@Type` attribute seemed the correct thing to target here, couldn't see a better / more specific attribute for Map's key type

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java
Comment (JonnyPower) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java:1]: - [ ] `mfa` vs single file having two different implementations feels off, will likely refactor - single file only useful for tests

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java [hunk 4]
```diff
@@ -0,0 +1,443 @@
...
+                        // Check if there's an abstract class in this type's hierarchy with equals/hashCode
+                        if (hasProblematicAbstractInHierarchy(type, abstractClasses, typesWithEqualsOrHashCode)) {
+                            return true;
+                        }
+                    }
+                }
+            }
+
+            // Check sub-interfaces (interface inheritance)
+            Set<TypeSummary> subInterfaces = interfaceToSubInterfaces.get(ifaceName);
```
Comment (JonnyPower) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java:250]: - [ ] there is no interface inheritance in apex, can drop this

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java [hunk 5]
```diff
@@ -0,0 +1,443 @@
...
+                }
+            }
+
+            return false;
+        }
+
+        /**
+         * Checks if an interface extends another interface (directly or transitively).
+         */
+        private boolean interfaceExtendsInterface(TypeSummary iface, String targetIfaceName, Set<String> visited) {
```
Comment (JonnyPower) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java:311]: - [ ] similar - can be dropped I believe

Comment (JonnyPower) [reply pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java:311]: incorrect, interfaces can extend interfaces in apex as well (TIL)

Image

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java (hunk 4 above)
Comment (JonnyPower) [reply pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java:250]: incorrect, interfaces can extend interfaces in apex as well (TIL)

Image

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java [hunk 6]
```diff
@@ -0,0 +1,443 @@
...
+/**
+ * Flags use of an interface as Map key when that interface has an implementing class
+ * that is abstract and defines equals or hashCode. In Apex, Map operations like
+ * containsKey do not dispatch to the correct equals/hashCode in that case.
+ *
+ * <p>Requires multifile analysis: set the {@code PMD_APEX_ROOT_DIRECTORY} environment variable
+ * to the root of your SFDX project (where {@code sfdx-project.json} lives). Without it the
+ * rule produces no violations.
+ *
+ * @see <a href="https://github.com/pmd/pmd/issues/6492">Issue 6492</a>
```
Comment (adangel) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java:44]:
```suggestion
 * @see <a href="https://github.com/pmd/pmd/issues/6492">[apex] New rule: Prevent use of interface -> abstract class with equals/hashCode as key in Map #6492</a>
 * @since 7.24.0
```

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/multifile/ApexMultifileAnalysis.java [hunk 7]
```diff
@@ -114,6 +121,49 @@ public List<Issue> getFileIssues(String filename) {
                            : Collections.unmodifiableList(Arrays.asList(org.issues().issuesForFile(filename)));
     }
 
+    /**
+     * Returns an unmodifiable list of all type summaries in the org.
+     * Returns an empty list when multifile analysis is unavailable.
+     * This enables rules to perform complex cross-type analysis.
+     */
```
Comment (adangel) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/multifile/ApexMultifileAnalysis.java:128]:
```suggestion
     * @since 7.24.0
     */
```

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTApexFile.java [hunk 8]
```diff
@@ -61,6 +61,10 @@ public List<Issue> getGlobalIssues() {
         return multifileAnalysis.getFileIssues(fileId.getAbsolutePath());
     }
 
+    public @NonNull ApexMultifileAnalysis getMultifileAnalysis() {
```
Comment (adangel) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTApexFile.java:64]: Instead of this method, I'd return the type summaries directly. For now at least, this fits more the style - like the above method `getGlobalIssues`.

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java [hunk 9]
```diff
@@ -0,0 +1,443 @@
...
+
+    @Override
+    protected @NonNull RuleTargetSelector buildTargetSelector() {
+        return RuleTargetSelector.forTypes(ASTApexFile.class);
+    }
+
+    @Override
+    public Object visit(ASTApexFile node, Object data) {
+        ApexMultifileAnalysis mfa = node.getMultifileAnalysis();
+        if (mfa.isFailed()) {
```
Comment (adangel) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java:62]: I think, this warning should be implemented in ApexMultifileAnalysis directly

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java [hunk 10]
```diff
@@ -0,0 +1,443 @@
...
+ * rule produces no violations.
+ *
+ * @see <a href="https://github.com/pmd/pmd/issues/6492">Issue 6492</a>
+ */
+public class AvoidInterfaceAsMapKeyRule extends AbstractApexRule {
+
+    private static final Logger LOG = LoggerFactory.getLogger(AvoidInterfaceAsMapKeyRule.class);
+    private static boolean warnedAboutMissingOrg = false;
+
+    // Cached index - computed once per PMD run, reused across all file visits
```
Comment (adangel) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java:51]: Note: This is likely once per thread - if PMD is run multithreaded, each rule is instantiated once per thread.
If we want to cache it once per PMD run, then we would need to move it into ApexMultifileAnalysis. But that is maybe something for later, when we know, what we need. I could imagine, the TypeHierarchyIndex is maybe not rule specific and ApexMultifileAnalysis could have method like `getSuperType(type)` -> Type, `Type.getMethods()`, ... something like this.

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java [hunk 11]
```diff
@@ -0,0 +1,443 @@
...
+
+            for (TypeSummary summary : allTypes) {
+                String nature = summary.nature();
+                String simpleName = summary.typeName().name().value().toLowerCase(Locale.ROOT);
+                String fullName = getFullTypeName(summary).toLowerCase(Locale.ROOT);
+
+                typesBySimpleName.computeIfAbsent(simpleName, k -> new HashSet<>()).add(summary);
+                typesByFullName.put(fullName, summary);
+
+                if ("interface".equalsIgnoreCase(nature)) {
```
Comment (adangel) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyRule.java:166]: It probably makes sense to extract these natures as constants

File: pmd-apex/src/main/resources/category/apex/errorprone.xml [hunk 12]
```diff
@@ -109,7 +109,35 @@ public without sharing class Foo {
...
+        since="7.24.0"
+        message="Avoid using an interface as Map key when an abstract implementing class defines equals or hashCode"
+        class="net.sourceforge.pmd.lang.apex.rule.errorprone.AvoidInterfaceAsMapKeyRule"
+        externalInfoUrl="${pmd.website.baseurl}/pmd_rules_apex_errorprone.html#avoidinterfaceasmapkey">
+    <description>
+      In Apex, when a Map uses an interface as key and an abstract class implements that interface
+      and defines equals/hashCode, methods like containsKey do not dispatch to the correct implementation.
+      This rule reports Map declarations (fields, variables, parameters) whose key type is an interface
+      that has at least one abstract implementing class defining equals or hashCode (requires multi-file
+      analysis provided by apex-link).
```
Comment (adangel) [inline pmd-apex/src/main/resources/category/apex/errorprone.xml:124]:
````suggestion
In Apex, when a Map uses an interface as key and an abstract class implements that interface
and defines equals/hashCode, methods like containsKey do not dispatch to the correct implementation. This results in potentially duplicated map entries or not being able to get entries by key.
      
For example (`IKey` is an interface and `StringKey` implements IKey and equals/hashCode):
```apex
Map<IKey, String> m = new Map<IKey, String>();
m.put(new StringKey('hello'), 'value');
Boolean exists = m.containsKey(new StringKey('hello')); // might return false
m.put(new StringKey('hello'), 'other value'); // might add a second entry instead of replacing the existing one
```

This rule reports Map declarations (fields, variables, parameters) whose key type is an interface that has at least one abstract implementing class defining equals or hashCode.

[Apex Language Server](https://github.com/apex-dev-tools/apex-ls) is used to make this possible and this needs
additional configuration. The environment variable `PMD_APEX_ROOT_DIRECTORY` needs to be set prior to executing
PMD. With this variable the root directory of the Salesforce metadata, where `sfdx-project.json` resides, is
specified. Apex Language Server can then load all the types in the project and figure out the type hierarchy.
````

File: pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyTest.java [hunk 13]
```diff
@@ -0,0 +1,191 @@
...
+                "Expected 1 violation when abstract class is deep in hierarchy");
+        assertViolation(report.getViolations().get(0), "MapUser.cls", 4);
+    }
+
+    private void assertViolation(RuleViolation violation, String fileName, int lineNumber) {
+        assertEquals(fileName, violation.getFileId().getFileName());
+        assertEquals(lineNumber, violation.getBeginLine());
+    }
+
+    private Report runRule(Path testProjectDir) throws IOException {
```
Comment (adangel) [inline pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyTest.java:166]: Looks like this is the same as in UnusedMethodTest - maybe it's time to provide test framework support?

File: pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyTest.java [hunk 14]
```diff
@@ -0,0 +1,191 @@
...
+     * Expected: 3 violations (field, parameter, local variable).
+     */
+    @Test
+    void abstractImplementorWithBothEqualsAndHashCodeViolations() throws Exception {
+        Report report = runRule(Paths.get(TEST_RESOURCES_BASE + "project1"));
+
+        assertEquals(3, report.getViolations().size(), "Expected 3 violations in MapUser.cls");
+        for (RuleViolation v : report.getViolations()) {
+            assertEquals("MapUser.cls", v.getFileId().getFileName());
+        }
```
Comment (adangel) [inline pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidInterfaceAsMapKeyTest.java:58]: This is not necessary, filename is asserted with assertViolation as well

**Review by adangel — APPROVED** [review]
Thanks!

I'll fix the issues myself.
