### PR TITLE
[java] UnnecessaryFullyQualifiedName: regression / false positive

### LINKED ISSUE #2098: [java] UnnecessaryFullyQualifiedName: regression / false positive
https://github.com/pmd/pmd/commit/493e0014b042bf1076244ad7b7c7e91a31f52d42#diff-bc84f21dff8725b7dc1441ccbc43bef1R243-R253

**Affects PMD Version:** *6.18.0 and 6.19.0*

**Rule:** [UnnecessaryFullyQualifiedName](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#unnecessaryfullyqualifiedname)

**Description:**

*I do have a package-info.java file containing an annotation that lays in a subpackage. Therefore specifying a fully qualified name is required. Though, the rule `UnnecessaryFullyQualifiedName` outputs a violation.*

*This problem does **not** occur with PMD 6.17.0. I took a look at the rules code and at a first view https://github.com/pmd/pmd/commit/493e0014b042bf1076244ad7b7c7e91a31f52d42#diff-bc84f21dff8725b7dc1441ccbc43bef1R243-R253 seems to cause the problem.*

**Code Sample demonstrating the issue:**

```
@com.example.subpackage.ExampleAnnotation
package com.example;
```

*`pmd.xml` example:*

```
<file name="...\com\example\package-info.java">
<violation beginline="1" endline="1" begincolumn="2" endcolumn="42" rule="UnnecessaryFullyQualifiedName" ruleset="Code Style" externalInfoUrl="https://pmd.github.io/pmd-6.18.0/pmd_rules_java_codestyle.html#unnecessaryfullyqualifiedname" priority="4">
Unnecessary use of fully qualified name 'com.example.subpackage.ExampleAnnotation' due to existing same package import 'com.example.*'
</violation>
</file>
```

**Running PMD through:** *Maven*

### PR DESCRIPTION
**Pull request by adangel**
Fixes #2098

Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 20 violations, 2 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/9106dbaef67649fb91802a05e126fd01/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java [hunk 1]
```diff
@@ -256,12 +256,20 @@ private boolean isSamePackage(TypeNode node, String name) {
...
             }
-            i = name.lastIndexOf('.');
+        }
+        // if it is a name used inside a primary prefix, then it is ambiguous, whether it references
+        // a type or a field or a type inside a subpackage
+        // we assume here, it won't be a subpackage the name references a field, e.g.
+        // package a;
+        // name: a.b.c.d(); -> we assume, b is a class, c is a field, d is a method.
+        // but it could very well be, that: a.b is a package and c is a class, d is a (static) method.
+        if (node.jjtGetParent() instanceof ASTPrimaryPrefix) {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java]: There seem to be a couple of false-negatives now - PrimaryPrefix is maybe too restrictive...

* https://github.com/spring-projects/spring-framework/blob/v5.0.6.RELEASE/spring-web/src/test/java/org/springframework/protobuf/Msg.java#L80
* https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassClassWithPrivateCtorWithNestedExtendingClass.java#L12
* https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalType.java#L9
