### PR TITLE
[java] Fix #4602 - unnecessaryimport FPs

### LINKED ISSUE #4602: [java] UnnecessaryImport: false positives with static imports
**Affects PMD Version:** 
7.0.0-rc3
**Rule:**
UnnecessaryImport
Please provide the rule name and a link to the rule documentation:
<https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#unnecessaryimport>

**Description:**
I'm trying to analyze a project with UI tests and check the imports used. But the result of the check is incorrect.

Suppressing these exceptions is too time-consuming for me, because these imports are in the entire project. There was no such problem in PMD 6.37, but when upgrading to 7.0.0 it showed up.

In CM 7.0.0-rc2, you wrote that this problem was detected and fixed (if I'm not confusing anything), but it didn't give a result (
**Code Sample demonstrating the issue:**

```java
import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Selenide.$;

public class CallRateLayer extends ExtendsPage {
    @Override
    public void checkPage() {
        $(ROOT_ELEMENT).shouldBe(visible.because("msg")); // its import use
    }
}
```

**Expected outcome:**
Expected no violations

PMD reports a violation, but that's wrong. That's a false positive.
Example:
/myPath/test.java:8:	UnnecessaryImport:	Unused static import 'com.codeborne.selenide.Condition.visible'
/myPath/test.java:9:	UnnecessaryImport:	Unused static import 'com.codeborne.selenide.Selenide.$'

**Running PMD through:** *Maven*

### LINKED ISSUE #4785: [java] False Positive: PMD Incorrectly report violation for UnnecessaryImport
**Affects PMD Version:7.0.0-rc4** 

**Rule:UnnecessaryImport**

<https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#unnecessaryimport>

**Description:**
According to the rule description, if a class is imported, and subsequently, used in the code, PMD should not report it as a violation. However, the provided sample code, adhering to the rule's specifications, is erroneously marked as a violation. This inconsistency suggests a false positive in the PMD analysis.
**Code Sample demonstrating the issue:**

```java
import org.junit.Test;
import java.util.Arrays;
import static org.junit.Assert.assertTrue;
public class Foo{
   @Test
   public void testfoo(Object a){
       assertTrue(a instanceof Arrays);
   }
}

```

**Expected outcome:**

PMD reports a violation at line 2 and line 3, but that's wrong. That's a false positive.

**Running PMD through:** *[CLI]*

### PR DESCRIPTION
**Pull request by oowekyala**
## Describe the PR

UnnecessaryImport was written with compilable code in mind. In invalid code, or code we do not know is valid because of missing aux classpath, it currently tends to FP which is not user-friendly. This implements a better strategy for when we can't resolve some names.

## Related issues

- Fixes #4602
- fix #4785

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 58 violations, 2 errors and 7 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/8545320357">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryImportRule.java [hunk 1]
```diff
@@ -230,12 +237,36 @@ public Object visit(ASTClassType node, Object data) {
...
+        LOG.debug("UnnecessaryImport: Failed type res for {} will cause all {}imports named {} to be marked as used", location, target, name);
+        boolean foundNamedImport = allSingleNameImports.removeIf(
+            decl -> (!onlyStatics || decl.isStatic())
+                && name.equals(decl.node.getImportedSimpleName()));
+        if (!foundNamedImport) {
+            LOG.debug("+ Since no such named import can be found, all {}on-demand-imports will be marked as used", target);
+
+            allImportsOnDemand.removeIf(it -> !onlyStatics || it.isStatic());
+        }
+    }
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryImportRule.java:261]: As we discussed in #3901, we need to work out a better way for users to detect and fix these incomplete auxclasspath issues that don't require them proactively running PMD in verbose mode and manually reading the massive non-structured logs to find them…
