### PR TITLE
[apex] Fix Apex XPath attributes

### LINKED ISSUE #1568: [apex] AST node attribute @Image not usable / always null in XPath rule / Designer
pmd_rule_designer__v_6_1_0_

**Affects PMD Version:** 
6.1

**Rule:**
Custom XPath Rule see screenshot

**Description:**
I am unable to see the contents of the Image AST Attribute and do regexp on it in XPath rules

**Code Sample demonstrating the issue:**

```
class MyApexClass {
    void bar(){
         if(!list.isEmpty() && list != null) {
            foo();
         }
    }
}
```

```
//*[matches(@Image, '&& [a-zA-Z0-9]* != null')]
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
Designer from CLI

### PR DESCRIPTION
**Pull request by oowekyala**
* Apex nodes now also present the attributes of their underlying node
* Enums are now a considered return type for XPath attributes. The XPath engines see enum constants as strings (their toString). This *may* cause incompatibility when changing the toString of exposed enums so we'll have to be careful.

Fixes #1568

### CODE REVIEW

File: pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/ApexXpathRuleTest.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+import net.sourceforge.pmd.lang.apex.ast.ApexNode;
+import net.sourceforge.pmd.lang.apex.ast.ApexParserTestHelpers;
+import net.sourceforge.pmd.lang.ast.xpath.Attribute;
+
+import apex.jorje.semantic.ast.compilation.Compilation;
+
+
+/**
+ * @author Clément Fournier
+ * @since 7.0.0
```
Comment (adangel) [inline pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/ApexXpathRuleTest.java]: This is actually 6.11.0...

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/AbstractApexNode.java [hunk 2]
```diff
@@ -57,4 +64,20 @@ public String getLocation() {
             return "no location";
         }
     }
+
+
+    @Override
+    public Iterator<Attribute> getXPathAttributesIterator() {
+        // Attributes of this node have precedence over same-name attributes of the underlying node
+        return Stream.concat(iteratorToStream(new AttributeAxisIterator(this)),
+                             iteratorToStream(new AttributeAxisIterator(this, node)))
```
Comment (adangel) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/AbstractApexNode.java]: Hm... ok, so this exposes all the attributes/props of the underlying jorje node.

Naivly, I would have solved this problem by adding another method in ASTBooleanExpression that delegates the Operator and exposes it to be used.

Any changes to the attributes in the jorje lib will change the API of the node in PMD. I think, this will happen in any case (like the parse tree changes with an upgrade jorje lib or nodes appear/disappear). However, we would see e.g. missing/renamed attributes only at runtime (no compilation errors).

If we manually expose the attributes, we have the advantage, that the rules are coupled to PMD's API rather than to Jorje's API. E.g. now, if you want to write a Java rule that checks the operator, you'll need to know to look at the jorje node for the operator - it would be easier, if ASTBooleanExpression had a method "getOp" (now you need to call boolExpr.getNode().getOp()).
Of course, we will then need to expose any useful attribute manually...

I'm not sure whether we should suggest such a usage...

Comment (jsotuyod) [reply pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/AbstractApexNode.java]: You make a very interesting point, and I agree with it. We should aim to wrap Jorje and make sure we produce compilation errors if jorje changes (it usually does!) that way we can make sure to rework our internals with each jorje update and keep compatible outwards.

Only changes to the AST itself should impact users.

**Comment by oowekyala** [comment]
I exposed some attributes manually. There still is a problem with BinaryExpression, which can be any binary expression in Apex but the operator is not publicly available. So we can't make the difference between e.g. addition or multiplication expression unless we fetch the private field with reflection.

Shall I remove the changes to AttributeAxisIterator too?

**Comment by adangel** [comment]
I'll remove the changes to AttributeAxisIterator (and Attribute) when I merge, so that we can only iterate on the attributes on the node again.

About the BinaryExpression: It now has the operator exposed (like the many other nodes). Maybe this came in with the recent jorje update? I'll add a similar getOperator method when I merge.
