### PR TITLE
[java] Fix #6096: Detect Lombok generated equals/hashCode in Comparable

### LINKED ISSUE #6096: [java] OverrideBothEqualsAndHashCodeOnComparable on class with lombok.EqualsAndHashCode annotation
**Affects PMD Version:** 
7.17.0

**Rule:**
https://docs.pmd-code.org/pmd-doc-7.17.0/pmd_rules_java_errorprone.html#overridebothequalsandhashcodeoncomparable

**Description:**

`OverrideBothEqualsAndHashCodeOnComparable` is reported when:

- Comparable is implemented
- lombok.EqualsAndHashCode annotation is used

**Code Sample demonstrating the issue:**

```java
import lombok.EqualsAndHashCode;
import lombok.RequiredArgsConstructor;

@EqualsAndHashCode
@RequiredArgsConstructor
public class RuleTest implements Comparable<RuleTest> {

    private final String x;

    @Override
    public int compareTo(RuleTest other) {
        return x.compareTo(other.x);
    }
}
```

**Expected outcome:**

PMD reports a violation at line 11, but that's wrong. That's a false positive.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
Gradle

### PR DESCRIPTION
**Pull request by mrclmh**
## Describe the PR
Rule: [OverrideBothEqualsAndHashCodeOnComparable](https://pmd.github.io/pmd/pmd_rules_java_errorprone.html#overridebothequalsandhashcodeoncomparable)

Detect generated equals and hashCode in Comparable when neither method has been implemented manually.
Currently Lombok `@EqualsAndHashCode,` `@Data` and `@Value` are detected.

## Related issues

- Fix #6096
- Related to #6072 and #6081 - same issue for records
- See also #3119

## Ready?

- [X] Added unit tests for fixed bug/feature
- [X] Passing all unit tests
- [X] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by mrclmh** [comment]
Not sure about the line break in the Set init line. What is the preferred max line length for the project?

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/OverrideBothEqualsAndHashCodeOnComparableRule.java [hunk 1]
```diff
@@ -24,6 +29,11 @@ public class OverrideBothEqualsAndHashCodeOnComparableRule extends OverrideBothE
     private static final String MISSING_HASH_CODE = MESSAGE_PREFIX + "hashCode() should be overridden";
     private static final String MISSING_EQUALS = MESSAGE_PREFIX + "equals() should be overridden";
     private static final String MISSING_EQUALS_AND_HASH_CODE = MESSAGE_PREFIX + "both equals() and hashCode() should be overridden";
+    private static final Set<String> GENERATED_EQUALS_HASHCODE = setOf(
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/OverrideBothEqualsAndHashCodeOnComparableRule.java]:
```suggestion
    private static final Set<String> LOMBOK_GENERATED_EQUALS_HASHCODE = setOf(
```

for records, equals and hashCode are also generated...

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/OverrideBothEqualsAndHashCodeOnComparableRule.java [hunk 2]
```diff
@@ -47,7 +57,9 @@ protected void maybeReport(RuleContext ctx, ASTTypeDeclaration node, ASTMethodDe
         }
 
         if (equalsMethod == null && hashCodeMethod == null) {
-            ctx.addViolationWithMessage(compareToMethod, MISSING_EQUALS_AND_HASH_CODE);
+            if (!JavaAstUtils.hasAnyAnnotation(node, GENERATED_EQUALS_HASHCODE)) {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/OverrideBothEqualsAndHashCodeOnComparableRule.java]: I would do this check before line 59 (outside of this if):

```java
if (equalsMethod == null && hashCodeMethod == null
    && JavaAstUtils.hasAnyAnnotation(node, LOMBOK_GENERATED_EQUALS_HASHCODE)) {
    return;
}

if (equalsMethod == null && hashCodeMethod == null) {
...
```

That way, we first deal with the "ok" cases and only the problematic cases are left.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/OverrideBothEqualsAndHashCodeOnComparable.xml [hunk 3]
```diff
@@ -363,4 +363,59 @@
...
+            }
+
+            @EqualsAndHashCode
+            public class FailManualEquals implements Comparable<FailManualEquals> {
+                @Override
+                public int compareTo(FailManualEquals other) {
+                    return 0;
+                }
+                @Override
+                public boolean equals(Object o) {
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/OverrideBothEqualsAndHashCodeOnComparable.xml]:
```suggestion
                public boolean equals(Object o) { // violation, line 35
```

assuming this is line 35.

I was wondering, whether this case (having equals and hash code generated but also overriding equals) is possible. But apparently it is.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/OverrideBothEqualsAndHashCodeOnComparable.xml [hunk 4]
```diff
@@ -363,4 +363,59 @@
...
+                }
+            }
+            @EqualsAndHashCode
+            public class FailManualHashCode implements Comparable<FailManualHashCode> {
+                @Override
+                public int compareTo(FailManualHashCode other) {
+                    return 0;
+                }
+                @Override
+                public int hashCode() {
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/OverrideBothEqualsAndHashCodeOnComparable.xml]:
```suggestion
                public int hashCode() { // violation, line 45
```

**Comment by adangel** [comment]
> Not sure about the line break in the Set init line. What is the preferred max line length for the project?

around 120 I think

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/OverrideBothEqualsAndHashCodeOnComparable.xml (hunk 3 above)
Comment (mrclmh) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/OverrideBothEqualsAndHashCodeOnComparable.xml]: Lombok does not generate equals/hashCode if one of them has been implemented manually. In the IDE a warning was displayed on the annotation about it. Therefore, the last two tests should hopefully not occur in reality and could also be removed based on this argument.

Comment (adangel) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/OverrideBothEqualsAndHashCodeOnComparable.xml]: > Therefore, the last two tests should hopefully not occur in reality

We should keep these tests. If they are possible, they will occur in reality.
