### PR TITLE
Fix #5369: [java] Consider that lombok.val and var are inferred

### LINKED ISSUE #5369: [java] UnusedPrivateMethod false positives with lombok.val
**Affects PMD Version:** 7.10.0

**Rule:** [UnusedPrivateMethod](https://docs.pmd-code.org/latest/pmd_rules_java_bestpractices.html#unusedprivatemethod)

**Description:**
When using [Lombok val](https://projectlombok.org/features/val), the type of the local variable is `lombok.val` instead of the inferred correct type.
When such a variable is used in a method call, we don't find the correct method declaration due to the different types and report the called method as unused.

Workaround: Don't use `val`, use `final var` instead. Note: lombok val is a _final_ local variable, while Java's var, is a non-final local variable.

**Code Sample demonstrating the issue:**

```java
package sample;

import lombok.val;

class Foo {
  public void method() {
     val test = "a";

     privateMethod(test);
  }

  private void privateMethod(String a) {
    System.out.println(a);
  }
}
```

Complete reproducer project: [issue-5369-unusedprivatemethod.zip](https://github.com/user-attachments/files/18904657/issue-5369-unusedprivatemethod.zip)

**Expected outcome:**

PMD reports a violation at line 12, but that's wrong. That's a false positive.

**Running PMD through:** Maven

### PR DESCRIPTION
**Pull request by oowekyala**
## Related issues

- Fix #5369 
- Ref #3119

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to main:<br />
This changeset changes 0 violations,<br />
introduces 1 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/13570264186?pr=5554">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaLanguageProperties.java [hunk 1]
```diff
@@ -35,11 +35,24 @@ public class JavaLanguageProperties extends JvmLanguagePropertyBundle {
                        .defaultValue(true)
                        .build();
 
+    /**
+     * @since 7.11.0
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaLanguageProperties.java:39]:
```suggestion
     * @since 7.12.0
```

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaLanguageProperties.java [hunk 2]
```diff
@@ -35,11 +35,24 @@ public class JavaLanguageProperties extends JvmLanguagePropertyBundle {
...
+     */
+    public static final PropertyDescriptor<Boolean> FIRST_CLASS_LOMBOK =
+        PropertyFactory.booleanProperty("lombok")
+                       .desc("Whether to consider lombok-specific things in core facilities like type inference. "
+                                 + "Disable this option if you want to analyze the AST as it would appear before the lombok pre-processing is applied. "
+                                 + "For instance, with this option enabled, variables declared with type lombok.val will have their type inferred based on the right-hand-side. "
+                                 + "With the option disabled, the variable will have type lombok.val instead. "
+                                 + "See https://github.com/pmd/pmd/issues/3119")
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaLanguageProperties.java:47]: I'll add this also to the documentation -> https://docs.pmd-code.org/latest/pmd_languages_configuration.html#java-language-properties

**Review by adangel — COMMENTED** [review]
Thanks!

I'll update docs, release notes, version reference and add a test case for #5369 explicitly and merge afterwards.

**Review by adangel — APPROVED** [review]

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaLanguageProperties.java (hunk 2 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaLanguageProperties.java:47]: Thanks. I didn't know we had that
