### PR TITLE
[java] Fix #4457: false negative about OverrideBothEqualsAndHashcode

### LINKED ISSUE #4457: [java] OverrideBothEqualsAndHashcode: false negative with anonymous classes
**Affects PMD Version:7.0.0-rc1** 

**Rule: OverrideBothEqualsAndHashcode**

Please provide the rule name and a link to the rule documentation:
<https://docs.pmd-code.org/latest/pmd_rules_java_errorprone.html#overridebothequalsandhashcode>

**Description:**
The anonymous class inside class B only has an ``equal`` method without ``hashCode`` method. It should be reported like the class A. I think this is a false negative. PMD mistakenly thinks ``hashCode`` method in B belong to the inner anonymous class.

**Code Sample demonstrating the issue:**

```java
public class Foo {
  public class A {
      Object o = new Object() {
          public boolean equals(Object other) {  // report a warning
              return false;
          }
      };
  }
  public class B {
      Object o = new Object() {
          public boolean equals(Object other) {   // report no warning
              return false;
          }
      };
      public int hashCode() {
          return 1;
      }
  }
}

```
The test example is found when using @EqualsAndHashCode from Lombok.

**Expected outcome:**

PMD reports no violations at line 11, but that's wrong. That's a false negative. 

**Running PMD through:** *CLI*

### LINKED ISSUE #4546: [java] OverrideBothEqualsAndHashCode ignores records
**Affects PMD Version:** 7.0.0-rc2 and 6.x

**Rule:** OverrideBothEqualsAndHashCode

Please provide the rule name and a link to the rule documentation:
<https://docs.pmd-code.org/latest/pmd_rules_java_errorprone.html#overridebothequalsandhashcode>

**Description:**

**Code Sample demonstrating the issue:**

```java
record Foo(int x) {
   @Override boolean equals(Object o) { return this == o; }
}
```

**Expected outcome:**

PMD should report a violation at line ..., but doesn't. This is a false-negative.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

### PR DESCRIPTION
**Pull request by LynnBroe**
## Describe the PR

This PR consider the `AnonymousClass`.

## Related issues

- Fixes #4457
- Fixes #4546 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 47 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 13 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/095363005f9e4a33ba0232a58381ccf4/diff1/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/OverrideBothEqualsAndHashcodeRule.java [hunk 1]
```diff
@@ -42,6 +43,25 @@ public Object visit(ASTClassOrInterfaceDeclaration node, Object data) {
         return data;
     }
 
+    @Override
+    public Object visit(ASTAnonymousClassDeclaration node, Object data) {
+        if (node.isInterface()) {
+            return data;
+        }
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/OverrideBothEqualsAndHashcodeRule.java:50]: this is always false for an `ASTAnonymousClassDeclaration`

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/OverrideBothEqualsAndHashcodeRule.java [hunk 2]
```diff
@@ -42,6 +43,25 @@ public Object visit(ASTClassOrInterfaceDeclaration node, Object data) {
...
+        if (!implementsComparable && containsEquals ^ containsHashCode) {
+            if (nodeFound == null) {
+                nodeFound = node;
+            }
+            addViolation(data, nodeFound);
+        }
+        implementsComparable = false;
+        containsEquals = false;
+        containsHashCode = false;
+        nodeFound = null;
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/OverrideBothEqualsAndHashcodeRule.java:61]: since the rule processes the code as it's written, and these are state vars shared for the whole processing, this will break on code such as:

```java
public class Foo {
  public boolean equals(Object o) { // containsEquals = true
    return false;
  }

 public void bar() {
    new Object{ // anonymous class declared
       public int hashCode() { return 42; } // containsHashCode = true
    } // anonymous class is ok (false negative), reset containsEquals and containsHashCode to false

  public int hashCode() { return 42; } // containsHashCode = true
 } // class has hashCode but no equals! (false positive)
```

The simplest way to fix this would be to remove the flags, remove the `Object visit(ASTMethodDeclaration node, Object data)` override, and directly navigate the AST here to match the equals / hashCode methods by doing:

```java
node.getOperations().filter(…)
```

**Review by jsotuyod — CHANGES_REQUESTED** [review]

**Review by jsotuyod — APPROVED** [review]
Thanks @LynnBroe for the PR. @oowekyala fixed all the issues. This should be ready to merge once we add it to the changelog.
