### PR TITLE
[java] Fix #5096 - StackOverflowError with recursively bounded tvar

### LINKED ISSUE #5096: [java] StackOverflowError with recursively bound type variable
**Affects PMD Version:** 7.0.0, 7.1.0, 7.2.0, 7.3.0

**Description:**

I'm trying to upgrade PMD from 6.55.0 to 7.x but the PMD runs just end up in `java.lang.StackoverflowErrror`s.

`ruleset.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset name="PMD ruleset"
         xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

  <description>PMD ruleset</description>

  <rule ref="category/java/bestpractices.xml/MissingOverride"/>
  <rule ref="category/java/bestpractices.xml/PrimitiveWrapperInstantiation"/>
  <rule ref="category/java/bestpractices.xml/ReplaceVectorWithList"/>
  <rule ref="category/java/bestpractices.xml/UseStandardCharsets"/>
  <rule ref="category/java/codestyle.xml/ExtendsObject"/>
  <rule ref="category/java/codestyle.xml/PackageCase"/>
  <rule ref="category/java/codestyle.xml/UnnecessaryCast"/>
  <rule ref="category/java/codestyle.xml/UnnecessarySemicolon"/>
</ruleset>
```
But also fails with just one of the rules in place. 

Gradle configuration:
```groovy
apply plugin: 'pmd'

pmd {
    toolVersion = '7.3.0'
    consoleOutput = true
    incrementalAnalysis = true
    ruleSets = [ "$rootProject.projectDir/gradle/pmd/ruleset.xml" ]
}
```

`gradle.properties`:
```ini
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx3g
```

Tested with both Temurin 17 and 21 (the project requires at least 17) on Ubuntu 22.04.

**Exception Stacktrace:**

The topmost part of the stack trace inline, [here is the full stack trace](https://github.com/user-attachments/files/16068013/stacktrace.txt).

```
Caused by: java.lang.StackOverflowError
        at net.sourceforge.pmd.lang.java.types.Substitution.apply(Substitution.java:45)
        at net.sourceforge.pmd.lang.java.types.Substitution.apply(Substitution.java:28)
        at net.sourceforge.pmd.lang.java.types.SubstVar.subst(SubstVar.java:25)
        at net.sourceforge.pmd.lang.java.types.WildcardTypeImpl.subst(WildcardTypeImpl.java:35)
        at net.sourceforge.pmd.lang.java.types.WildcardTypeImpl.subst(WildcardTypeImpl.java:17)
        at net.sourceforge.pmd.lang.java.types.TypeOps.lambda$subst$0(TypeOps.java:950)
        at net.sourceforge.pmd.lang.java.types.TypeOps.mapPreservingSelf(TypeOps.java:977)
        at net.sourceforge.pmd.lang.java.types.TypeOps.subst(TypeOps.java:950)
        at net.sourceforge.pmd.lang.java.types.JClassType.subst(JClassType.java:78)
        at net.sourceforge.pmd.lang.java.types.JClassType.subst(JClassType.java:54)
        at net.sourceforge.pmd.lang.java.types.TypeOps.subst(TypeOps.java:941)
        at net.sourceforge.pmd.lang.java.types.TypeConversion.capture(TypeConversion.java:213)
        at net.sourceforge.pmd.lang.java.types.TypeConversion.capture(TypeConversion.java:154)
        at net.sourceforge.pmd.lang.java.types.TypeConversion.capture(TypeConversion.java:152)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:662)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:598)
        at net.sourceforge.pmd.lang.java.types.TypeOps.isConvertiblePure(TypeOps.java:415)
        at net.sourceforge.pmd.lang.java.types.TypeOps.mostSpecific(TypeOps.java:1757)
        at net.sourceforge.pmd.lang.java.types.Lub.glb(Lub.java:316)
        at net.sourceforge.pmd.lang.java.types.TypeSystem.glb(TypeSystem.java:723)
        at net.sourceforge.pmd.lang.java.types.TypeConversion.capture(TypeConversion.java:227)
        at net.sourceforge.pmd.lang.java.types.TypeConversion.capture(TypeConversion.java:154)
        at net.sourceforge.pmd.lang.java.types.TypeConversion.capture(TypeConversion.java:152)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:662)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:598)
        at net.sourceforge.pmd.lang.java.types.TypeOps.isConvertiblePure(TypeOps.java:415)
        at net.sourceforge.pmd.lang.java.types.TypeOps.mostSpecific(TypeOps.java:1757)
        at net.sourceforge.pmd.lang.java.types.Lub.glb(Lub.java:316)
        at net.sourceforge.pmd.lang.java.types.TypeSystem.glb(TypeSystem.java:723)
        at net.sourceforge.pmd.lang.java.types.TypeConversion.capture(TypeConversion.java:227)
        at net.sourceforge.pmd.lang.java.types.TypeConversion.capture(TypeConversion.java:154)
        at net.sourceforge.pmd.lang.java.types.TypeConversion.capture(TypeConversion.java:152)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:662)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:598)
        at net.sourceforge.pmd.lang.java.types.TypeOps.isConvertiblePure(TypeOps.java:415)
        at net.sourceforge.pmd.lang.java.types.TypeOps.mostSpecific(TypeOps.java:1757)
        at net.sourceforge.pmd.lang.java.types.Lub.glb(Lub.java:316)
        at net.sourceforge.pmd.lang.java.types.TypeSystem.glb(TypeSystem.java:723)
```

**Code Sample demonstrating the issue:**

I cannot share the project as is, and I haven't yet been able to figure out what exactly triggers it. Any help in pinpointing the problematic class would be appreciated.

**Steps to reproduce:**

TBD.

**Running PMD through:** *Gradle 8.8*

### PR DESCRIPTION
**Pull request by oowekyala**
## Related issues

- Fixes #5096

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/JTypeVar.java [hunk 1]
```diff
@@ -112,17 +113,26 @@ default <T, P> T acceptVisitor(JTypeVisitor<T, P> visitor, P p) {
 
     /**
      * @throws UnsupportedOperationException If this is not a capture var
+     *
+     * <p>Note that this is only supposed to be used internally.
      */
+    @InternalApi
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/JTypeVar.java:119]: Note, I'm not sure what to do about these. Should we deprecate them? They shouldn't be used outside our codebase, as not all implementations of the interface support those methods, they just have one use each in our codebase. Maybe they should be deprecated and converted to static methods in TypeOps...

Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/JTypeVar.java:119]: So they are making the build failed because japicmp thinks they were removed. It seems the only way to satisfy japicmp with our current config is to deprecate these methods, but if we mark them `@InternalApi`, it thinks they were removed...

Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/JTypeVar.java:119]: I think we need either an annotation like I describe [here](https://github.com/pmd/pmd/pull/4931#issuecomment-2040011418), to document that we will internalize these deprecated methods. Or we just document that in the `@deprecated` Javadoc tag, but we will need to be more careful when cleaning up for PMD 8.

Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/JTypeVar.java:119]: While we discuss this in #4931 I will revert these changes so that this PR is only about the bugfix. We can then open another PR to deprecate these methods.

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to main:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/12183388791?pr=5387">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by adangel — APPROVED** [review]
Thanks!
