### PR TITLE
[java] Fix star import overwritten by explicit import not correctly handled

### LINKED ISSUE #1114: [java] Star import overwritten by explicit import is not correctly handled
**Affects PMD Version:** ??

**Rule:** [java-codestyle.xml/UnnecessaryFullyQualifiedName](https://pmd.github.io/pmd-6.3.0/pmd_rules_java_codestyle.html#unnecessaryfullyqualifiedname)??

**Description:**
Hi,
When we have two classes with the same name, but in separate packages and one is imported by 
`import package.*`
and the other by
`import otherPackage.fullName;`

Then in code if I use for example new fullName() java uses class defined by otherPackage.fullName.
So if I want to instantiate package.fullname I have to write new package.fullname(). But PMD says that it should not be fully qualified. But if it were not fully qualified then it would mean an another class.

**Code Sample demonstrating the issue:**

Please see attached sample:
./pmd.bat -d import_sample -format text -R default-java-ruleset.xml -version 1.6
[import_sample.zip](https://github.com/pmd/pmd/files/2016167/import_sample.zip)

**Running PMD through:** *[Maven]*

### PR DESCRIPTION
**Pull request by oowekyala**
Fixes #1114

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java [hunk 1]
```diff
@@ -53,38 +57,44 @@ public Object visit(ASTClassOrInterfaceType node, Object data) {
...
+     * is the enclosing package or type name of the imported type or static member.
+     */
+    private boolean declarationMatches(ASTImportDeclaration decl, String name) {
+        return name.startsWith(decl.getImportedName())
+                && name.lastIndexOf('.') == decl.getImportedName().length();
+    }
+
     private void checkImports(JavaNode node, Object data) {
         String name = node.getImage();
         matches.clear();
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java]: I've seen, that matches is actually only used in this method, so I would remove the field and add it as a local variable here.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java [hunk 2]
```diff
@@ -170,11 +178,31 @@ private boolean isAvoidingConflict(final JavaNode node, final String name,
...
         final String unqualifiedName = name.substring(name.lastIndexOf('.') + 1);
         final int unqualifiedNameLength = unqualifiedName.length();
+
+        // There could be a conflict between an import on demand and another import, e.g.
+        // import One.*;
+        // import Two.Problem;
+        // Where One.Problem is a legitimate qualification
+        if (firstMatch.isImportOnDemand() && !firstMatch.isStatic()) {
+            for (ASTImportDeclaration importDeclaration : imports) {
+                if (!Objects.equals(importDeclaration, firstMatch)
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java]: I think, using Object.equals here is misleading - we are actually comparing the references (ASTImportDeclaration doesn't have an own equals method implementation).
So, I'd use simply `importDeclaration != firstMatch`

Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java]: Yes, it would be clearer that way. We'll have to suppress CompareObjectsWithEquals though

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java (hunk 1 above)
Comment (oowekyala) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java]: Good catch
