### PR TITLE
[java] Fix #6079: IdenticalCatchBranches for overriden method calls

### LINKED ISSUE #6079: [java] IdenticalCatchBranches: False negative for overriden method calls
**Affects PMD Version:** 
7.17.0

**Rule:**

[IdenticalCatchBranches ](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#identicalcatchbranches)

**Description:**

Two exception handling blocks are not considered equivalent if both contain `e.getMessage()` and one of the exception types overrides `getMessage()`.

**Code Sample demonstrating the issue:**

```java
public class Foo {
    public void bar() {
        try {
            // nothing
        } catch (NullPointerException ex) {
            System.out.println(ex.getMessage());
        } catch (CustomException ex) {
            System.out.println(ex.getMessage());
        } catch (RuntimeException ex) {
            System.out.println(ex.getMessage());
        }
    }

    public static class CustomException extends RuntimeException {
        @Override public String getMessage() {
            return "";
        }
    }
}
```

**Expected outcome:**

PMD should report a violation at lines 7 and 9, but doesn't. This is a false-negative.
In Java < 17 only the second violation is missing because NPE does not override `getMessage`.

**Running PMD through:** IntelliJ

### PR DESCRIPTION
**Pull request by zbynek**
## Describe the PR

Fixes the false negative by only checking equality of formal parameters, not the declaring type.

## Related issues

- Fixes #6079 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/IdenticalCatchBranchesRule.java [hunk 1]
```diff
@@ -42,17 +45,34 @@ private boolean areEquivalent(ASTCatchClause st1, ASTCatchClause st2) {
...
+            if (!sym1.getFormalParameters().equals(sym2.getFormalParameters())) {
+                return OptionalBool.NO;
+            }
+            JTypeMirror declaringType1 = methodType1.getDeclaringType();
+            JTypeMirror declaringType2 = methodType2.getDeclaringType();
+            boolean isOverride = declaringType2.getSuperTypeSet().stream().anyMatch(st ->
+                TypeTestUtil.isA(st, declaringType1) && st.streamDeclaredMethods(
+                    method -> method.nameEquals(methodType1.getName())
+                        && method.getFormalParameters().equals(sym1.getFormalParameters())
+                ).findAny().isPresent()
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/IdenticalCatchBranchesRule.java]: I think we could benefit from factoring out this logic into TypeOps to join other override related methods like `overrides` or `isOverridableIn`.

Comment (zbynek) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/IdenticalCatchBranchesRule.java]: Done in my last commit. I was able to spimplify it a little bit by using `haveSameSignature`. Let me know if some further cleanup is needed.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/IdenticalCatchBranches.xml [hunk 2]
```diff
@@ -207,6 +207,63 @@ class Foo {
 
 
             }
-            ]]></code>
+        ]]></code>
+    </test-code>
+
+    <test-code>
+        <description>Overridden method call: common supertype</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/IdenticalCatchBranches.xml]:
```suggestion
        <description>Overridden method call: common supertype #6079</description>
```
