### PR TITLE
[java] Fix #885

### LINKED ISSUE #885: [java] CompareObjectsWithEqualsRule trigger by enum1 != enum2
**Affects PMD Version:** 
6.0.1

**Rule:**
CompareObjectsWithEquals

**Description:**
enum1 != enum2 triggers CompareObjectsWithEquals. 
I've seen there is code in CompareObjectsWithEqualsRule.java that says "skip, if it is an enum", but it doesn't.

**Code Sample demonstrating the issue:**

```
public static void assertEquals(final Enum<?> enum1,
                                    final Enum<?> enum2,
                                    final UUID errorKey,
                                    final Object... errorArgs)
        throws ResponseException
    {
        if (enum1 != enum2)
        {
            throw new ResponseException(errorKey, errorArgs);
        }
    }
```

**Running PMD through:** *[CLI | Gradle]*

### PR DESCRIPTION
**Pull request by MatiasComercio**
**PR Description:**
Fix #885: `CompareObjectsWithEqualsRule` Java rule should not be triggered by enums.
Enum class exlicit usage was not being considered an Enum type in the rule.

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CompareObjectsWithEqualsRule.java [hunk 1]
```diff
@@ -84,7 +84,9 @@ public Object visit(ASTEqualityExpression node, Object data) {
                 ASTReferenceType type1 = ((Node) nd1.getAccessNodeParent())
                         .getFirstDescendantOfType(ASTReferenceType.class);
                 // skip, if it is an enum
-                if (type0.getType() != null && type0.getType().equals(type1.getType()) && type0.getType().isEnum()) {
+                if (type0.getType() != null && type0.getType().equals(type1.getType())
+                    // It may be a custom enum class or an explicit Enum class usage
+                    && (type0.getType().isEnum() || type0.getType() == java.lang.Enum.class)) {
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CompareObjectsWithEqualsRule.java]: it seems to me, the issue lies on `isEnum()` itself, returning false for something that is an enum. I'd rather change it there than here.

**Comment by jsotuyod** [comment]
Also, please consider adding a proper unit test to make sure this fixes our issue

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CompareObjectsWithEqualsRule.java (hunk 1 above)
Comment (MatiasComercio) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CompareObjectsWithEqualsRule.java]: You are right about that the problem lies on `isEnum`. However, I've try to do so, but I realized that `isEnum` is a `Class` class method, and that's why I had to change it here.

**Comment by jsotuyod** [comment]
Merged, thanks!
