### PR TITLE
[java] Fix #6092: AssignmentInOperand false positive in 7.17.0 for case statements

### LINKED ISSUE #6092: [java] AssignmentInOperand false positive in 7.17.0 for case blocks in switch statements
**Affects PMD Version:**
7.17.0
**Rule:**
AssignmentInOperand
Please provide the rule name and a link to the rule documentation:
[AssignmentInOperand](https://docs.pmd-code.org/pmd-doc-7.17.0/pmd_rules_java_errorprone.html#assignmentinoperand)

**Description:**
The fix for issue https://github.com/pmd/pmd/issues/3434 causes version 7.17.0 to flag assignment in case assignments.

**Code Sample demonstrating the issue:**

```java
public final class FPTestAssignmentInOperand {
	
	private FPTestAssignmentInOperand() {}
	public static void main(String[] args)
	{
		String a = null;
		String b = null;
		String c = null;
		
	    switch (args[0])
	    {
	    	case "A" -> a = "a";
	    	case "B" -> b = "b";
	    	case "C" -> c = "c";
	    	default -> {/*Do Nothing*/}
	    }
	    System.out.println("A: " + a + ", B: " + b + ", C: " + c);
	}
}

```

**Expected outcome:**

PMD reports a violation at lines 12,13, and 14, but that's wrong. That's a false positive.

**Running PMD through:** Eclipse

### PR DESCRIPTION
**Pull request by mrclmh**
## Describe the PR
Add switch arrow branch as additional exception for AssignmentInOperand.
It allows assignments with switch arrow as parent.

## Related issues

- Fix #6092 

## Ready?

- [X] Added unit tests for fixed bug/feature
- [X] Passing all unit tests
- [X] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [X] Added (in-code) documentation (if needed)

### CODE REVIEW

**Review by adangel — CHANGES_REQUESTED** [review]
Thanks for the PR!

Can you check the following case? I think, we should report such a case, as it is a switch expression and within the expression an assignment is done. WDYT?

```java
class Scratch {
    public static void main(String[] args) {
        int a = 2;
        int b = switch(a) {
            case 2 -> a = 1;
            default -> 0;
        };

        System.out.println("a = " + a);
        System.out.println("b = " + b);
    }
}
```

Or would such an assignment be a legit case in terms of the rule [AssignmentInOperand](https://docs.pmd-code.org/latest/pmd_rules_java_errorprone.html#assignmentinoperand)?

**Comment by mrclmh** [comment]
Goot catch. Yes, I think when used in a switch expression it should be reported. 
Would you like a separate issue and PR for your case or should I change this PR?

**Comment by adangel** [comment]
Just update this PR, thanks!

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AssignmentInOperandRule.java [hunk 1]
```diff
@@ -88,14 +89,17 @@ private void checkAssignment(ASTExpression impureExpr, RuleContext ctx) {
...
-            return;
+        if (toplevel == impureExpr) {
+            if (parent instanceof ASTExpressionStatement
+                    || parent instanceof ASTStatementExpressionList
+                    || parent instanceof ASTLambdaExpression) {
+                // that's ok
+                return;
+            }
+            if (parent instanceof ASTSwitchArrowBranch
+                    && parent.getParent() instanceof ASTSwitchStatement) {  // switch expression excluded
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AssignmentInOperandRule.java]:
```suggestion
                    && parent.getParent() instanceof ASTSwitchStatement) {
    // switch statements are ok
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AssignmentInOperand.xml [hunk 2]
```diff
@@ -330,4 +330,37 @@ public class Foo {
...
+        <code><![CDATA[
+            // assignment allowed in switch statement case
+            public class Foo {
+                public static void main(String[] args) {
+                    String a = null;
+
+                    switch (args[0]) {
+                        case "A" -> a = "a";    // fixed false positive in 'a = "a"'
+                        default -> {}
+                    }
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AssignmentInOperand.xml:347]: there are two forms of switch statements: with the new arrow syntax or with the old colon syntax:

```java
switch (args[0]) {
  case "A": a = "a"; break;
  default:
}
```

This is also possible for switch expressions:
```java
int b = switch(a) {
                        case 2: yield a = 1;    // violation line 18
                        default: yield 0;
                    };
```

And there are variants, where you add a block:

```java
int b = switch(a) {
                        case 2 -> { yield a = 1; };    // violation line 18
                        default -> 0;
                    };
```

We should make sure to test all the possible cases...
