### PR TITLE
[core] Log wrong include/exclude patterns

### LINKED ISSUE #2036: [core] Wrong include/exclude patterns are silently ignored
Eg try `addExcludePattern("*")`. That should exclude everything, right? `ruleset.getExcludePatterns()` even contains the string afterwards. But no, we expect a regex, this one is invalid, and that's silently ignored later by the file filter:

https://github.com/pmd/pmd/blob/f5b02ef2b096acfb2920a124596f428324ff988c/pmd-core/src/main/java/net/sourceforge/pmd/util/filter/RegexStringFilter.java#L84-L86

Invalid patterns should be reported to the user, preferably when they build their ruleset. For compatibility on master we can log and ignore them, but for 7.0.0, it would be best to report a warning/error in RulesetBuilder, and make RulesetBuilder throw the PatternSyntaxException.

### PR DESCRIPTION
**Pull request by oowekyala**
Fix #2036

### CODE REVIEW

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java [hunk 1]
```diff
@@ -294,84 +296,99 @@ public RuleSetBuilder addRuleSetByReference(final RuleSet ruleSet, final boolean
...
-         * @param aPattern
-         *            the pattern
-         * @return The same builder, for a fluid programming interface
+         * @param aPattern A valid regular expression
          */
         public RuleSetBuilder addExcludePattern(final String aPattern) {
-            if (!excludePatterns.contains(aPattern)) {
-                excludePatterns.add(aPattern);
+            try {
+                Pattern.compile(aPattern);
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java]: this implies knowledge that:
1. These strings will be used only for `RegexStringFilter` instances
2. What the `RegexStringFilter` does within it's implementation (given in the name, true, but still implementation)

I'd either have `RegexStringFilter` complain itself inside the `optimize` method, or I'd cease to work with `Set<String>` here in favor of `Set<Pattern>`, and have `RegexStringFilter` receive a compiled `Pattern` instead of compiling itself (the "optimization" can still be done, as you can call `Pattern.pattern()`)

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java [hunk 2]
```diff
@@ -294,84 +296,99 @@ public RuleSetBuilder addRuleSetByReference(final RuleSet ruleSet, final boolean
...
-         * @param aPattern
-         *            the pattern
-         * @return The same builder, for a fluid programming interface
+         * @param aPattern A valid regular expression
          */
         public RuleSetBuilder addIncludePattern(final String aPattern) {
-            if (!includePatterns.contains(aPattern)) {
-                includePatterns.add(aPattern);
+            try {
+                Pattern.compile(aPattern);
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java]: ditto

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java (hunk 1 above)
Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java]: Hum you're right, making those methods accept `Pattern` would be the easiest solution.  That way, we can complain about invalid regexes directly in the ruleset parser (closer to the input), which is where the string to Pattern conversion should happen, and other code should handle it.

So basically, deprecate all those methods and introduce new overloads which take Pattern instead?

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 2 new errors and 0 new configuration errors,<br />
removes 0 violations, 2 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/8d5a7e7a4a1f45a48217921efd8bb112/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java (hunk 1 above)
Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java]: I used patterns directly instead. I don't want to touch RegexStringFilter, because for 7.0.0 I want to replace Filter with a standard Predicate, and RegexStringFilter can go away since its "optimisation" is completely insignificant, in view of profiling results.
