### PR TITLE
Fix #5770: [java] New Rule: VariableCanBeInlined

### LINKED ISSUE #5770: [java] New Rule: VariableCanBeInlined: Local variables should not be declared and then immediately returned or thrown
**VariableCanBeInlined**

**Proposed Category:** codestyle

**Description:**

Inline variables when they are immediately used to return or throw.

- https://sonarsource.github.io/rspec/#/rspec/S1488
- https://github.com/apache/maven/pull/2404/files#r2113612293
- https://docs.openrewrite.org/recipes/staticanalysis/inlinevariable
- https://github.com/checkstyle/checkstyle/pull/16488

**Code Sample:** This should include code, that should be flagged by the rule. If possible, the "correct" code
according to this new rule should also be demonstrated.

```java
public long ComputeDurationInMilliseconds()
{
  long duration = (((hours * 60) + minutes) * 60 + seconds ) * 1000 ;
  return duration;
}

public void DoSomething()
{
  ApplicationException myException = new ApplicationException();
  throw myException;
}
```

**Possible Properties:**

*   Should this rule be customizable via properties?

### PR DESCRIPTION
**Pull request by Pankraz76**
## Fix #5770: [java] `UnnecessaryLocalBeforeReturnOrThrowsRule`

evolute `UnnecessaryLocalBeforeReturnRule` to `UnnecessaryLocalBeforeReturnOrThrowsRule`.

## Related issues

- Fix #5770
- Old PR: #5835

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeRule.java [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+import net.sourceforge.pmd.lang.java.ast.ASTLocalVariableDeclaration;
+import net.sourceforge.pmd.lang.java.ast.ASTReturnStatement;
+import net.sourceforge.pmd.lang.java.ast.ASTThrowStatement;
+import net.sourceforge.pmd.lang.java.ast.ASTVariableAccess;
+import net.sourceforge.pmd.lang.java.ast.ASTVariableId;
+import net.sourceforge.pmd.lang.java.rule.AbstractJavaRulechainRule;
+import net.sourceforge.pmd.lang.java.symbols.JVariableSymbol;
+import net.sourceforge.pmd.properties.PropertyDescriptor;
+
+public class UnnecessaryLocalBeforeRule extends AbstractJavaRulechainRule {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeRule.java]: The rule is named now "UnnecessaryLocalBefore" ... before what? The name is now a mixture of @oowekyala suggestion (UnnecessaryLocalBeforeBranch) and my suggestion (UnnecessaryLocal).
Please consider first https://github.com/pmd/pmd/issues/5770#issuecomment-3016500638

File: pmd-java/src/main/resources/category/java/codestyle.xml [hunk 2]
```diff
@@ -1783,6 +1783,32 @@ public class Foo {
...
     </rule>
 
+    <rule name="UnnecessaryLocalBefore"
+          language="java"
+          since="7.15.0"
+          message="Consider simply using the value vs storing it in local variable ''{0}''."
+          class="net.sourceforge.pmd.lang.java.rule.codestyle.UnnecessaryLocalBeforeRule"
+          externalInfoUrl="${pmd.website.baseurl}/pmd_rules_java_codestyle.html#unnecessarylocalbefore">
+        <description>
+Avoid the creation of unnecessary local variables.
```
Comment (adangel) [inline pmd-java/src/main/resources/category/java/codestyle.xml:1816]: We should here mention the other rule (this rule replaces rule xyz etc.) We should also mention, the two cases it detects (before throw and before return).

When we deprecate the old rule, we have to mark it deprecated in the ruleset (deprecated=true) (and document in the description, which rule is the replacement).

File: pmd-java/src/main/resources/rulesets/java/quickstart.xml [hunk 3]
```diff
@@ -114,7 +114,7 @@
     <rule ref="category/java/codestyle.xml/UnnecessaryConstructor"/>
     <rule ref="category/java/codestyle.xml/UnnecessaryFullyQualifiedName"/>
     <rule ref="category/java/codestyle.xml/UnnecessaryImport" />
-    <rule ref="category/java/codestyle.xml/UnnecessaryLocalBeforeReturn"/>
+    <rule ref="category/java/codestyle.xml/UnnecessaryLocalBefore"/>
```
Comment (adangel) [inline pmd-java/src/main/resources/rulesets/java/quickstart.xml]: This will be worth mentioning the release notes (as for everbody who uses the quickstart ruleset this will create new violations). But it makes sense, to enable/use the new rule in quickstart directly.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeRule.java (hunk 1 above)
Comment (Pankraz76) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeRule.java]: Might consider sonar slang, assuming they impose SSOT.

As its complete new, we can redirect and name it accordingly to the essence of sonar.
 
- `ImmediatelyReturnedOrThrown`
- `ImmediatelyReturnOrThrows`

image


How you like this name?

Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeRule.java]: Can you closely read https://docs.pmd-code.org/latest/pmd_devdocs_major_rule_guidelines.html and make some suggestions that we can choose from?

File: pmd-java/src/main/resources/category/java/codestyle.xml (hunk 2 above)
Comment (Pankraz76) [reply pmd-java/src/main/resources/category/java/codestyle.xml:1816]: This is not objective, but my opinion. 

Might just copy sonar here as well? 

Declaring a variable only to immediately return or throw it is considered a bad practice because it adds unnecessary complexity to the code. This practice can make the code harder to read and understand, as it introduces an extra step that doesn’t add any value. Instead of declaring a variable and then immediately returning or throwing it, it is generally better to return or throw the value directly. This makes the code cleaner, simpler, and easier to understand.

Comment (adangel) [reply pmd-java/src/main/resources/category/java/codestyle.xml:1816]: How about explaining the rule in your own words? Not sure, if we are allowed to copy sonar. We can add a pointer, that his rule is similar to sonar rule S..., but I don't think we should copy verbatim... About pointers/references, I think, you opened in the past #5762 ...

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeRule.java (hunk 1 above)
Comment (Pankraz76) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeRule.java]: have: `UnnecessaryLocalBeforeReturn`
want: `UnnecessaryLocalBeforeReturnOrThrows`

`OrThrows` seems to be the smallest change, complain to current approach. As just extending so we should do for the name as well.

File: docs/pages/release_notes.md [hunk 4]
```diff
@@ -24,6 +24,9 @@ This is a {{ site.pmd.release_type }} release.
 
 ### 🚀 New and noteworthy
 
+* java-bestpractices
```
Comment (Pankraz76) [inline docs/pages/release_notes.md]:
```suggestion
* codestyle
```

**Comment by oowekyala** [comment]
I think the new name is too specific because this rule could as well apply to yield statements. I think the best applicable names would be `UnnecessaryLocalBeforeBranch` or `UnnecessaryLocalBeforeJump`

Or even BeforeControlFlowTransfer if you think those are too obscure. I would think people know what a jump is though.

**Comment by Pankraz76** [comment]
> I think the new name is too specific because this rule could as well apply to yield statements. I think the best applicable names would be `UnnecessaryLocalBeforeBranch` or `UnnecessaryLocalBeforeJump`
> 
> Or even BeforeControlFlowTransfer if you think those are too obscure. I would think people know what a jump is though.

thanks for the `yield` case.

Yes then might use `Branch`, as its known from test coverage tools too, also this was the initial suggestion.

Branch is generic and known in the dev context.

**Comment by adangel** [comment]
Let's first fix specification before continuing on the pull request, so that we know, what to do: #5770

**Comment by Pankraz76** [comment]
check issue:

again broken window effect still not closed.


[INFO] There are 2 errors reported by Checkstyle 10.26.1 with /net/sourceforge/pmd/pmd-checkstyle-config.xml ruleset.
[ERROR] src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/VariableCanBeInlinedRule.java:[1] (header) RegexpHeader: Line does not match expected header line of '^\/\*$'.
[ERROR] src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/VariableCanBeInlinedTest.java:[1] (header) RegexpHeader: Line does not match expected header line of '^\/\*$'.
[INFO] ------------------------------------------------------------------------

- https://github.com/pmd/pmd/issues/5850
- https://github.com/pmd/pmd/pull/5845

File: docs/pages/release_notes.md [hunk 5]
```diff
@@ -51,6 +51,7 @@ This is a {{ site.pmd.release_type }} release.
 * The new java rule {% rule java/bestpractices/RelianceOnDefaultCharset %} finds method calls that
   depend on the JVM's default charset. Using these method without specifying the charset explicitly
   can lead to unexpected behavior on different platforms.
+* [#5770](https://github.com/pmd/pmd/issues/5770): \[java] `VariableCanBeInlined`
```
Comment (adangel) [inline docs/pages/release_notes.md]: I'll update this myself. If you would have looked a few lines above, you would have seen, how we describe new rules in the release notes... just to throw some links and some words isn't good...

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeReturnRule.java [hunk 6]
```diff
@@ -14,7 +14,7 @@
 import net.sourceforge.pmd.lang.java.symbols.JVariableSymbol;
 import net.sourceforge.pmd.properties.PropertyDescriptor;
 
-
+@Deprecated
 public class UnnecessaryLocalBeforeReturnRule extends AbstractJavaRulechainRule {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeReturnRule.java:21]:
```suggestion
/**
 * @deprecated Since 7.17.0. This rule is replaced by VariableCanBeInlined.
 */
@Deprecated
public class UnnecessaryLocalBeforeReturnRule extends AbstractJavaRulechainRule {
```

File: pmd-java/src/main/resources/category/java/codestyle.xml [hunk 7]
```diff
@@ -1827,6 +1828,48 @@ public class Foo {
         </example>
     </rule>
 
+    <rule name="VariableCanBeInlined"
+          language="java"
+          since="7.15.0"
```
Comment (adangel) [inline pmd-java/src/main/resources/category/java/codestyle.xml]:
```suggestion
          since="7.17.0"
```

File: pmd-java/src/main/resources/category/java/codestyle.xml [hunk 8]
```diff
@@ -1827,6 +1828,48 @@ public class Foo {
...
+          message="Consider simply using the value vs storing it in local variable ''{0}''."
+          class="net.sourceforge.pmd.lang.java.rule.codestyle.VariableCanBeInlinedRule"
+          externalInfoUrl="${pmd.website.baseurl}/pmd_rules_java_codestyle.html#variablecanbeinlined">
+        <description>
+            [S1488](https://sonarsource.github.io/rspec/#/rspec/S1488) Unnecessary variable declaration that only serves to return or throw it immediately. This adds needless coupling and complexity.
```
Comment (adangel) [inline pmd-java/src/main/resources/category/java/codestyle.xml]:
```suggestion
Local variables should not be declared and then immediately returned or thrown. Such
variable declarations add unnecessary complexity and make the code harder to read.
It is often simpler and cleaner to return or throw the value directly.

This rule implements SonarSource rule [S1488](https://sonarsource.github.io/rspec/#/rspec/S1488).
```

File: pmd-java/src/main/resources/category/java/codestyle.xml [hunk 9]
```diff
@@ -1827,6 +1828,48 @@ public class Foo {
         </example>
     </rule>
 
+    <rule name="VariableCanBeInlined"
```
Comment (adangel) [inline pmd-java/src/main/resources/category/java/codestyle.xml]: Since we try to keep the rules here sorted alphabetically, please move this somewhere down...

File: pmd-java/src/main/resources/category/java/codestyle.xml [hunk 10]
```diff
@@ -1807,6 +1807,7 @@ public class Foo {
 
     <rule name="UnnecessaryLocalBeforeReturn"
           language="java"
+          deprecated="true"
```
Comment (adangel) [inline pmd-java/src/main/resources/category/java/codestyle.xml:1810]: Please also update the rule description of this now deprecated rule:

```
Avoid the creation of unnecessary local variables

This rule has been deprecated since 7.17.0. Use the new rule
{%rule VariableCanBeInlined %} instead, which additionally covers throw statements.
```

File: pmd-java/src/main/resources/rulesets/java/quickstart.xml [hunk 11]
```diff
@@ -115,7 +115,7 @@
     <rule ref="category/java/codestyle.xml/UnnecessaryConstructor"/>
     <rule ref="category/java/codestyle.xml/UnnecessaryFullyQualifiedName"/>
     <rule ref="category/java/codestyle.xml/UnnecessaryImport" />
-    <rule ref="category/java/codestyle.xml/UnnecessaryLocalBeforeReturn"/>
+    <rule ref="category/java/codestyle.xml/VariableCanBeInlined"/>
```
Comment (adangel) [inline pmd-java/src/main/resources/rulesets/java/quickstart.xml]: The list was sorted alphabetically before, did you notice?. Please move VariableCanBeInlined to the end (after line 123 after "UselessQualifiedThis").

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml [hunk 12]
```diff
@@ -0,0 +1,1010 @@
...
+        <code><![CDATA[
+public class Foo {
+    public int bar() { return 5; }
+}
+        ]]></code>
+    </test-code>
+
+    <test-code>
+        <description>simple failure case</description>
+        <expected-problems>1</expected-problems>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml:33]:
```suggestion
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <expected-messages>
            <message>Consider simply using the value vs storing it in local variable 'x'.</message>
        </expected-messages>
```

I want to make sure, that we report the correct line (now and in the future). We report the variable declaration, correct? Or do we report the return statement?

Yes, according to the implementation, we report on the node, where the local var has been declared.

File: pmd-java/src/main/resources/category/java/codestyle.xml [hunk 13]
```diff
@@ -1827,6 +1828,48 @@ public class Foo {
         </example>
     </rule>
 
+    <rule name="VariableCanBeInlined"
+          language="java"
+          since="7.15.0"
+          message="Consider simply using the value vs storing it in local variable ''{0}''."
```
Comment (adangel) [inline pmd-java/src/main/resources/category/java/codestyle.xml]:
```suggestion
          message="Consider simply using the value vs. storing it in local variable ''{0}''."
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml [hunk 14]
```diff
@@ -0,0 +1,1010 @@
...
+        <code><![CDATA[
+public class Test {
+    void test() {
+        RuntimeException e = new RuntimeException();
+        RuntimeException f = new RuntimeException();
+        throw f;
+    }
+}
+        ]]></code>
+    </test-code>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]: This looks duplicated - the same test case is in line 460 "Multiple variables but only one used in throw". Please remove this test case.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml [hunk 15]
```diff
@@ -0,0 +1,1010 @@
...
+    <test-code>
+        <description>Return with method chain - no violation</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]: The test description is wrong - there is no method chain but a violation?

Maybe: "Return a concatenated string"?

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml [hunk 16]
```diff
@@ -0,0 +1,1010 @@
...
+        String name = getFirst() + " " + getLast();
+        return name;
+    }
+    private String getFirst() { return ""; }
+    private String getLast() { return ""; }
+}
+    ]]></code>
+    </test-code>
+    <test-code>
+        <description>Throw with method chain - no violation</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]: The test description is wrong - there is no method chain but a violation?

Maybe: "Throw an exception with a message build from a concatenated string"?

Not sure, if this test case is really necessary and adds anything new?

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml [hunk 17]
```diff
@@ -0,0 +1,1010 @@
...
+        throw name;
+    }
+    private String getFirst() { return ""; }
+    private String getLast() { return ""; }
+}
+    ]]></code>
+    </test-code>
+
+    <test-code>
+        <description>Return with array access - no violation</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]:
```suggestion
        <description>Return with array access - violation</description>
```

That's really confusing if the description says, there is no violation, but the test says, there is one...

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml [hunk 18]
```diff
@@ -0,0 +1,1010 @@
...
+    public int getFirst(int[] arr) {
+        int first = arr[0];
+        return first;
+    }
+}
+    ]]></code>
+    </test-code>
+
+    <test-code>
+        <description>Return with field access - no violation</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]:
```suggestion
        <description>Return with field access - violation</description>
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml [hunk 19]
```diff
@@ -0,0 +1,1010 @@
...
+    public int getCount() {
+        int current = this.count;
+        return current;
+    }
+}
+    ]]></code>
+    </test-code>
+
+    <test-code>
+        <description>Throw with ternary initialization - no violation</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]:
```suggestion
        <description>Throw with ternary initialization - violation</description>
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml [hunk 20]
```diff
@@ -0,0 +1,1010 @@
...
+        } catch (RuntimeException ex) {
+            e = ex;
+        }
+        throw e;
+    }
+    void something() throws IOException {}
+}
+    ]]></code>
+    </test-code>
+    <test-code>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]:
```suggestion
    <test-code disabled="true">
```

You can disable the test case instead of using a comment. Then the test case won't appear as "green, successfully executed", but as "skipped". It's like JUnit's disable/ignore.
See https://docs.pmd-code.org/latest/pmd_userdocs_extending_testing.html#test-code-attributes

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml [hunk 21]
```diff
@@ -0,0 +1,1010 @@
...
+        <!--  fixme      <expected-problems>1</expected-problems>-->
+        <expected-problems>0</expected-problems>
+        <code><![CDATA[
+public class Test {
+    void test() {
+        try {
+            something();
+        } catch (IOException ex) {
+            Exception e; // unnecessary instead use: throw ex;
+            e = ex; // unnecessary instead use: throw ex;
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml:787]: Would we detect it, if the declaration and initialization wouldn't be separated?
E.g.

```java
Exception e = ex; // unnecessary instead use: throw ex;
throw e;
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml [hunk 22]
```diff
@@ -0,0 +1,1010 @@
...
+public class Test {
+    void test() {
+        RuntimeException e = new RuntimeException();
+        doSomething();
+        throw e;
+    }
+    void doSomething() {}
+}
+        ]]></code>
+    </test-code>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml:420]: Please add here another test case, "when order does not matter" (set the rule property to false and expect one violation)

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml [hunk 23]
```diff
@@ -0,0 +1,1010 @@
...
+            }
+            default -> 0;
+        };
+    }
+}
+    ]]></code>
+    </test-code>
+
+    <test-code>
+        <description>Yield with complex expression - no violation</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]:
```suggestion
        <description>Yield with complex expression - violation</description>
```

**Review by adangel — CHANGES_REQUESTED** [review]
Thanks for the updated PR!

Unfortunately, it is not ready yet, but almost! Can you please have a look?

And don't worry about the release notes, I'll update it once the PR is ready to be merged.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml (hunk 22 above)
Comment (Pankraz76) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml:420]: added but dont get this:

```
    <test-code>
        <description>Statements not consecutive - violation when order does not matter</description>
        <rule-property name="statementOrderMatters">false</rule-property>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Test {
    void test() {
        RuntimeException e = new RuntimeException();
        doSomething();
        throw e;
    }
    void doSomething() {}
}
        ]]></code>
    </test-code>
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml (hunk 21 above)
Comment (Pankraz76) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml:787]: yes

File: docs/pages/release_notes.md (hunk 5 above)
Comment (Pankraz76) [reply docs/pages/release_notes.md]: its considered WIP, sorry. Assuming you would handle this as i dont care about documentation that much.

File: pmd-java/src/main/resources/category/java/codestyle.xml (hunk 10 above)
Comment (adangel) [reply pmd-java/src/main/resources/category/java/codestyle.xml:1810]: I'll fix this myself.

File: pmd-java/src/main/resources/rulesets/java/quickstart.xml (hunk 11 above)
Comment (adangel) [reply pmd-java/src/main/resources/rulesets/java/quickstart.xml]: I'll fix this myself.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml (hunk 12 above)
Comment (adangel) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml:33]: I'll improve the test case myself.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml (hunk 14 above)
Comment (adangel) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]: I'll remove this test case. It is exactly the same the the case above, just the variable names are different (e1/e2 vs. e/f).

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml (hunk 15 above)
Comment (adangel) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]: I'll fix this myself.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml (hunk 16 above)
Comment (adangel) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]: I'll change the test description myself and keep it.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml (hunk 17 above)
Comment (adangel) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]: I'll fix it myself.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml (hunk 18 above)
Comment (adangel) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]: I'll fix it myself.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml (hunk 20 above)
Comment (adangel) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]: I'll use disabled=true and change it. You resolved this comment without changing anything or explaining, why you decided differently...

Comment (adangel) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/VariableCanBeInlined.xml]: Actually, the test description doesn't make sense: there is only one catch block block, and not multiple.

File: pmd-java/src/main/resources/category/java/codestyle.xml (hunk 13 above)
Comment (adangel) [reply pmd-java/src/main/resources/category/java/codestyle.xml]: I'll fix this myself.
