### PR TITLE
[java] CloseResource false positive with Objects.nonNull

### LINKED ISSUE #3148: [java] CloseResource false positive with Objects.nonNull
**Affects PMD Version:** 
6.30.0

**Rule:**

https://pmd.github.io/latest/pmd_rules_java_errorprone.html#closeresource

**Description:**

if using 
`if (Objects.nonNull(preparedStmt))`
instead of
`if (preparedStmt != null)`
rule still fires a violation

**Code Sample demonstrating the issue:**
```
      PreparedStatement lPreparedStmt = null;
      try {
         lPreparedStmt = conn.prepareStatement(sqL);
         lPreparedStmt.execute();
      } catch (SQLException ex) {
         LOG.debug("lPreparedStmt.execute();loooooooooooooose" + ex);
      } finally {
         if (Objects.nonNull(lPreparedStmt)) {
            try {
               lPreparedStmt.close();
            } catch (SQLException pEx) {
               LOG.error("unrecoverable", pEx);
            }
         }
      }

```

**Expected outcome:**

false-positive

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
eclipse acanda plugin

### PR DESCRIPTION
**Pull request by adangel**
- fixes #3148

The problem with "!= null" comparison couldn't be reproduced. Depending on further feedback for #3148 this PR needs to be enhanced.

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 2 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/e60648b40de04f228aee8e9e14e90c97/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java [hunk 1]
```diff
@@ -526,19 +531,89 @@ private boolean isCloseCallOnVariable(ASTName op, String variableToClose) {
...
+            return methodName.getType() == Objects.class;
+        }
+        if (methodName.hasImageEqualTo("nonNull")) {
+            return hasStaticImportObjectsNonNull;
+        }
+
+        return false;
+    }
+
+    private boolean isVariableAccess(JavaNode node, String varName) {
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java:597]: This method could be reused by your other PR to check the lhs of the assignment
