### PR TITLE
[java] Fix NoClassDefFoundErrors

### LINKED ISSUE #2663: [java] NoClassDefFoundError on upgrade from 6.25.0 to 6.26.0
**Affects PMD Version:** 

[6.26.0](https://github.com/pmd/pmd/releases/tag/pmd_releases%2F6.26.0)

**Description:**

Upgrading pmd-core & pmd-java in maven project causes build to fail with:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.13.0:pmd (pmd) on project cnfex: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.13.0:pmd failed: A required class was missing while executing org.apache.maven.plugins:maven-pmd-plugin:3.13.0:pmd: javax/el/ELResolver
```
PMD 6.25.0 didn't complain about this missing dependency (which isn't required to compile and package given project, with `jakarta.faces-api` in `provided` scope).

**Exception Stacktrace:**
First caused by
```
Caused by: java.lang.NoClassDefFoundError: javax/el/ELResolver
    at java.lang.Class.getDeclaredMethods0 (Native Method)
    at java.lang.Class.privateGetDeclaredMethods (Class.java:2701)
    at java.lang.Class.privateGetPublicMethods (Class.java:2902)
    at java.lang.Class.getMethods (Class.java:1615)
    at net.sourceforge.pmd.lang.java.ast.internal.ImportWrapper.<init> (ImportWrapper.java:44)
    at net.sourceforge.pmd.lang.java.ast.internal.ImportWrapper.<init> (ImportWrapper.java:33)
    at net.sourceforge.pmd.lang.java.rule.bestpractices.UnusedImportsRule.visit (UnusedImportsRule.java:131)
    at net.sourceforge.pmd.lang.java.ast.ASTImportDeclaration.jjtAccept (ASTImportDeclaration.java:143)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:219)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:391)
    at net.sourceforge.pmd.lang.java.rule.bestpractices.UnusedImportsRule.visit (UnusedImportsRule.java:57)
    at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept (ASTCompilationUnit.java:44)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll (AbstractJavaRule.java:162)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply (AbstractJavaRule.java:156)
    at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply (AbstractDelegateRule.java:336)
```

**Code Sample demonstrating the issue:**

[pmd-6.26.0-CNFEx](https://github.com/pzrep/pmd-6.26.0-CNFEx/tree/dependabot/maven/pmdVersion-6.26.0)

**Steps to reproduce:**
For the reproducer from above:
```
./mvnw test -DpmdVersion=6.25.0
```
vs
```
./mvnw test -DpmdVersion=6.26.0
```

**Running PMD through:** *Maven*

### PR DESCRIPTION
**Pull request by adangel**
## Describe the PR

When determining methods/fields by reflection, we could run into situations, that the classes, that are referenced in the methods (e.g. parameter types, return types) are not on the auxclasspath. Then a LinkageError is thrown, which was not handled before.

The reason, why the types are missing on the auxclasspath is actually a valid case: As long as the methods are not used in the code, the referenced classes neither need to be on the compile classpath. And we use the compile classpath as our auxclasspath.

This can happen, if a project uses a provided dependency and this dependency has other transitive dependencies. These transitive dependencies are not on the compile classpath.

This PR fixes the problem in ImportWrapper as well as in two other cases, where we use reflection.

## Related issues

- Fixes #2663 

## Ready?

- [ ] Added unit tests for fixed bug/feature - I only tested it with the integration test from #2663 
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/41956bd7cc7a4554a3630f83e3812c57/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/ImportWrapper.java [hunk 1]
```diff
@@ -8,57 +8,78 @@
...
             for (Method m : type.getDeclaredMethods()) {
                 if (Modifier.isStatic(m.getModifiers())) {
-                    allDemands.add(m.getName());
+                    names.add(m.getName());
                 }
             }
+            return names;
+        } catch (LinkageError e) {
+            if (ctx != null) {
+                ctx.getReport().addError(new ProcessingError(e, String.valueOf(ctx.getSourceCodeFile())));
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/ImportWrapper.java:78]: I'm not sure adding a processing error is appropriate here. I don't think we currently log missing classes to the report right? And for now, processing errors indicate errors in PMD code, the kind of errors people should report as bugs. Currently, a processing error may very well mean that the file was not processed by rules at all, and so, violations may be missing from the report. Whereas missing dependencies is more akin to a warning, ie, we can continue analysis (and we do), but results of some rules may be somewhat inaccurate. And users shouldn't think this is a bug on our side.

I would say a log call would be more appropriate, as it's possible to disable it, and it makes it clearer that this is just a warning. In PMD 7 this will be handled by the semantic checker, which is also akin to a logger, and won't touch the report.

Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/ImportWrapper.java:78]: Yes, you're right. This logging is something different than a processing error (and in other places, we silently ignore linkagerrors).

However, I still think, that such issues/warnings/problems should be part of the report, as it might indicate a incorrect/incomplete configuration when executing PMD. But that's for PMD 7 then.

I'll change that to a LOG.debug call. I'm not sure, how much duplicates we would log otherwise, and that could be annoying as well. See also #1371.
