### PR TITLE
[java] MethodReturnsInternalArray does not work in inner classes - Fixed #1738

### LINKED ISSUE #1738: [java] MethodReturnsInternalArray does not work in inner classes
**Affects PMD Version:** 6.12

**Rule:** MethodReturnsInternalArray

**Description:**
In the provided code sample only the getter of the outer class is found by the rule MethodReturnsInternalArray.
The rule ArrayIsStoredDirectly however finds both setters.

**Code Sample demonstrating the issue:**

```
public class Outer {
	private int[] arr;
	
	public int[] getArr() {
		return arr;
	}
	
	public void setArr(int... arr) {
		this.arr = arr;
	}
	
	public static class Inner {
		private int[] arr2;
		
		public int[] getArr2() {
			return arr2;
		}
		
		public void setArr2(int... arr2) {
			this.arr2 = arr2;
		}
	}
}
```

**Running PMD through:** *Eclipse*

### PR DESCRIPTION
**Pull request by Srini1993**
**PR Description:**

MethodReturnsInternalArray does not work in inner classes #1738 - Fixed

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 42 new violations, 0 new errors and 0 new configuration errors,<br />
removes 1 violations, 2 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/102749af051e4142bd64624aa1ec61bf/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Srini1993** [comment]
@adangel 
Thanks for the comments.
I have added the test case now.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MethodReturnsInternalArrayRule.java [hunk 1]
```diff
@@ -46,7 +46,7 @@ public Object visit(ASTMethodDeclaration method, Object data) {
             return data;
         }
         List<ASTReturnStatement> returns = method.findDescendantsOfType(ASTReturnStatement.class);
-        ASTTypeDeclaration td = method.getFirstParentOfType(ASTTypeDeclaration.class);
+        ASTClassOrInterfaceDeclaration td = method.getFirstParentOfType(ASTClassOrInterfaceDeclaration.class);
```
Comment (jsotuyod) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MethodReturnsInternalArrayRule.java]: possibly using `ASTAnyTypeDeclaration` here instead would keep things running and avoid the regression shown in #1845
