### PR TITLE
[plsql] ParseException with subqueries in WHERE clause

### LINKED ISSUE #1589: [plsql] ParseException with subqueries in WHERE clause
**Affects PMD Version:** 6.10.0

**Description:** Stacktrace
```
net.sourceforge.pmd.lang.plsql.ast.ParseException: Encountered " "=" "= "" at line 4, column 12.
Was expecting one of:
    ";" ...
    "FETCH" ...
    "GROUP" ...
    "OFFSET" ...
    "ORDER" ...
    
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.generateParseException(PLSQLParser.java:53977)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.jj_consume_token(PLSQLParser.java:53828)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.UnlabelledStatement(PLSQLParser.java:14915)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.Statement(PLSQLParser.java:15630)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.Block(PLSQLParser.java:848)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.Global(PLSQLParser.java:497)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.Input(PLSQLParser.java:194)
```

**Code Sample demonstrating the issue:**

```
BEGIN

SELECT id INTO v_id FROM table
  WHERE id = (SELECT id FROM other_table);

UPDATE table SET name = 'a'
  WHERE id = (SELECT id FROM other_table);

END;
/
```

**Running PMD through:** Designer

### PR DESCRIPTION
**Pull request by adangel**
Fixes #1589

### CODE REVIEW

File: pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/WhereClauseTest.java [hunk 1]
```diff
@@ -68,4 +68,11 @@ public void testConcatenationOperator() throws Exception {
                 StandardCharsets.UTF_8);
         ASTInput input = parsePLSQL(code);
     }
+
+    @Test
+    public void testSubqueries() throws Exception {
```
Comment (jsotuyod) [inline pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/WhereClauseTest.java]: this `throws` is failing the `pmd:check` task
