### PR TITLE
[doc] Fix missing additional rulesets

### LINKED ISSUE #4051: [doc] Additional rulesets are not listed in documentation
**Affects PMD Version:** since 6.46.0

**Description:**

In older versions, we e.g. show the quickstart ruleset and the old deprecated rulesets: https://pmd.github.io/pmd-6.45.0/pmd_rules_java.html#additional-rulesets

This is missing since 6.46.0, there is no section "Additional rulesets" anymore: https://pmd.github.io/latest/pmd_rules_java.html

### PR DESCRIPTION
**Pull request by adangel**
Fixes #4051

### CODE REVIEW

File: pmd-doc/src/main/java/net/sourceforge/pmd/docs/GenerateRuleDocsCmd.java [hunk 1]
```diff
@@ -47,16 +47,17 @@ public static void main(String[] args) throws IOException {
         System.out.println("Generated docs in " + (System.currentTimeMillis() - start) + " ms");
     }
 
+    static final Pattern ADDITIONAL_RULESET_PATTERN = Pattern.compile("^.+" + Pattern.quote(File.separator) + "pmd-\\w+"
+            + Pattern.quote(IOUtil.normalizePath(File.separator + Paths.get("src", "main", "resources", "rulesets").toString()) + File.separator)
```
Comment (adangel) [inline pmd-doc/src/main/java/net/sourceforge/pmd/docs/GenerateRuleDocsCmd.java:51]: The fix is, to have the trailing "File.seperator" outside IOUtil.normalizePath - as it would be normalized away.

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No regression tested rules have been changed.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
