### PR TITLE
[core] Fix handling of cached XPath rule violations

### LINKED ISSUE #1990: [core] Incremental analysis mixes XPath rule violations
**Affects PMD Version:** 6.17

**Rule:** TooManyStaticImports (but maybe the problem is not related to the rule)

**Description:**
I updated my Gradle version to 5.6 and started to use incremental analysis flag.
https://docs.gradle.org/5.6/release-notes.html#support-for-pmd-incremental-analysis
It seems that the rule reference is wrong but the description is right.
Also the priority field is from the wrong rule.
Here 2 example of xml. Unfortunately I can't give you my project to test this issue, sorry.

**Code Sample demonstrating the issue:**
**right example**
```
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd"
    version="6.17.0" timestamp="2019-08-26T11:46:19.393">
<file name="MyFile.java">
<violation beginline="1" endline="457" begincolumn="1" endcolumn="2" rule="TooManyStaticImports" ruleset="Code Style" package="my.package" class="MyFile" externalInfoUrl="https://pmd.github.io/pmd-6.17.0/pmd_rules_java_codestyle.html#toomanystaticimports" priority="5">
Too many static imports may lead to messy code
</violation>
</file>
</pmd>
```
**wrong example**
```
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd"
    version="6.17.0" timestamp="2019-08-26T10:35:33.313">
<file name="MyFile.java">
<violation beginline="1" endline="457" begincolumn="1" endcolumn="2" rule="ByteInstantiation" ruleset="Performance" package="my.package" class="MyFile" externalInfoUrl="https://pmd.github.io/pmd-6.17.0/pmd_rules_java_performance.html#byteinstantiation" priority="2">
Too many static imports may lead to messy code
</violation>
<violation beginline="1" endline="457" begincolumn="1" endcolumn="2" rule="ByteInstantiation" ruleset="Performance" package="my.package" class="MyFile" externalInfoUrl="https://pmd.github.io/pmd-6.17.0/pmd_rules_java_performance.html#byteinstantiation" priority="2">
Too many static imports may lead to messy code
</violation>
<violation beginline="1" endline="457" begincolumn="1" endcolumn="2" rule="ByteInstantiation" ruleset="Performance" package="my.package" class="MyFile" externalInfoUrl="https://pmd.github.io/pmd-6.17.0/pmd_rules_java_performance.html#byteinstantiation" priority="2">
Too many static imports may lead to messy code
</violation>
<violation beginline="1" endline="457" begincolumn="1" endcolumn="2" rule="ByteInstantiation" ruleset="Performance" package="my.package" class="MyFile" externalInfoUrl="https://pmd.github.io/pmd-6.17.0/pmd_rules_java_performance.html#byteinstantiation" priority="2">
Too many static imports may lead to messy code
</violation>
</file>
</pmd>
```
I also executed pmd different times:
**first launch**
```
<file name="MyFile.java">
<violation beginline="1" endline="442" begincolumn="1" endcolumn="2" rule="ByteInstantiation" ruleset="Performance" package="my.package" class="MyFile" externalInfoUrl="https://pmd.github.io/pmd-6.17.0/pmd_rules_java_performance.html#byteinstantiation" priority="2">
Too many static imports may lead to messy code
</violation>
```
**second launch**
```
<file name="MyFile.java">
<violation beginline="1" endline="457" begincolumn="1" endcolumn="2" rule="ProperCloneImplementation" ruleset="Error Prone" package="my.package" class="MyFile" externalInfoUrl="https://pmd.github.io/pmd-6.17.0/pmd_rules_java_errorprone.html#propercloneimplementation" priority="2">
Too many static imports may lead to messy code
</violation>
```
**third launch after clean**
```
<file name="MyFile.java">
<violation beginline="1" endline="457" begincolumn="1" endcolumn="2" rule="JUnitStaticSuite" ruleset="Error Prone" package="my.package" class="MyFile" externalInfoUrl="https://pmd.github.io/pmd-6.17.0/pmd_rules_java_errorprone.html#junitstaticsuite" priority="3">
Too many static imports may lead to messy code
</violation>
```
**fourth launch after clean**
rule reference changed again: **WhileLoopWithLiteralBoolean**

**Running PMD through:** Gradle 5.6

O.S. both linux and windows
JDK 1.8

### PR DESCRIPTION
**Pull request by jsotuyod**
- Fixes #1990

### CODE REVIEW

File: pmd-core/src/main/java/net/sourceforge/pmd/cache/CachedRuleMapper.java [hunk 1]
```diff
@@ -9,21 +9,26 @@
 
 import net.sourceforge.pmd.Rule;
 import net.sourceforge.pmd.RuleSets;
+import net.sourceforge.pmd.annotation.InternalApi;
 
 /**
  * A mapper from rule class names to rule instances for cached rules.
  */
+@Deprecated
+@InternalApi
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/cache/CachedRuleMapper.java]: +1, but I feel like all of this package should be internal API too. Violation caching is something that should ideally happen transparently (with user consent), and I can't see why some external client would like to manipulate the cache themselves, given how low-level the API is.

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/e1173929efd34beaa32214a883300756/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-core/src/main/java/net/sourceforge/pmd/cache/CachedRuleMapper.java (hunk 1 above)
Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/cache/CachedRuleMapper.java]: Ok I'll do that after merging
