### PR TITLE
Fix #5442: [java] Fix stackoverflow with recursive generic types

### LINKED ISSUE #5442: [java] StackOverflowError in 7.9.0
**Affects PMD Version:** 7.8.0 and 7.9.0 at least

**Description:**

I'm trying to upgrade PMD from 6.55 in our codebase. I started out with 7.3.0 but got a `StackOverflowError` that was reported in #5096 and fixed in 7.9.0. Now I'm seeing another `StackOverflowError`.

**Exception Stacktrace:**

The start and end of the stack trace inline ([and the full one](https://github.com/user-attachments/files/18297589/full-stack-trace.txt), [and the full `--debug` log](https://github.com/user-attachments/files/18297675/full-debug-log.txt)):

```
Exception in thread "main" java.lang.StackOverflowError
	at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitSentinel(TypeOps.java:586)
	at net.sourceforge.pmd.lang.java.types.SentinelType.acceptVisitor(SentinelType.java:66)
	at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:656)
	at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:598)
	at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.typeArgContains(TypeOps.java:785)
	at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitClass(TypeOps.java:854)
	at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitClass(TypeOps.java:586)
	at net.sourceforge.pmd.lang.java.types.JClassType.acceptVisitor(JClassType.java:312)

        ...

	at net.sourceforge.pmd.lang.java.types.JClassType.acceptVisitor(JClassType.java:312)
	at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:656)
	at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:598)
	at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitTypeVar(TypeOps.java:808)
	at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitTypeVar(TypeOps.java:586)
	at net.sourceforge.pmd.lang.java.types.JTypeVar.acceptVisitor(JTypeVar.java:103)
	at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitSentinel(TypeOps.java:826)
	at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitSentinel(TypeOps.java:586)
	at net.sourceforge.pmd.lang.java.types.SentinelType.acceptVisitor(SentinelType.java:66)
```

Also tested 7.8.0 on only the file that triggers it and [got a slightly different stack trace](https://github.com/user-attachments/files/18297703/pmd-7.8.0-stacktrace.txt).

**Code Sample demonstrating the issue:**

I have spent quite some time on trying to extract a reproducer outside our codebase, but no success yet. Using `PMD_JAVA_OPTS="-Dpmd.error_recovery"` I was able to figure out that the class triggering the `StackOverflowError` is an `AbstractResourceAssembler` that has the following shape at least:

```java
abstract class AbstractResourceAssembler<T, R extends Resource<? extends R>, UID, V> implements EntityResourceAssembler<T, R, UID, V> {
}

interface EntityResourceAssembler<T, R extends Resource<? extends R>, UID, V> extends ResourceAssembler<R, UID, V> {
}

interface ResourceAssembler<R extends Resource<? extends R>, UID, V> {
}

abstract class Resource<T extends Resource<? extends T>> extends org.springframework.hateoas.RepresentationModel<T> {
}
```

But I'm not able to get PMD to fail using just those 4 classes.

Ruleset:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset name="PMD ruleset"
         xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

  <description>PMD ruleset</description>

  <rule ref="category/java/bestpractices.xml/MissingOverride"/>
  <rule ref="category/java/bestpractices.xml/PrimitiveWrapperInstantiation"/>
  <rule ref="category/java/bestpractices.xml/ReplaceVectorWithList"/>
  <rule ref="category/java/bestpractices.xml/UseStandardCharsets"/>
  <rule ref="category/java/bestpractices.xml/UseTryWithResources"/>
  <rule ref="category/java/codestyle.xml/ExtendsObject"/>
  <rule ref="category/java/codestyle.xml/PackageCase"/>
  <rule ref="category/java/codestyle.xml/UnnecessaryCast"/>
  <rule ref="category/java/codestyle.xml/UnnecessarySemicolon"/>
  <rule ref="category/java/codestyle.xml/UseDiamondOperator"/>
  <rule ref="category/java/errorprone.xml/AvoidDecimalLiteralsInBigDecimalConstructor" />
  <rule ref="category/java/errorprone.xml/ClassCastExceptionWithToArray" />
  <rule ref="category/java/errorprone.xml/IdempotentOperations" />
  <rule ref="category/java/errorprone.xml/MissingSerialVersionUID" />
  <rule ref="category/java/errorprone.xml/NonStaticInitializer" />
  <rule ref="category/java/errorprone.xml/UseEqualsToCompareStrings" />
  <rule ref="category/java/errorprone.xml/UselessOperationOnImmutable" />
  <rule ref="category/java/multithreading.xml/DontCallThreadRun" />
</ruleset>
```
**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1.  TBD

**Running PMD through:** *CLI and Gradle 8.10*

Java 21 and 23 (Temurin).

### LINKED ISSUE #5505: [java] java.lang.StackOverflowError while executing a PmdRunnable
**Affects PMD Version:** 

PMD 7.10.0 (db70a20d4294fda0786145c126ca977b1a882a3c, 2025-01-31T09:22:09Z)

**Description:**

Unknown error occurred while executing a PmdRunnable: java.lang.StackOverflowError

**Exception Stacktrace:**

```
Exception in thread "main" java.lang.StackOverflowError
        at net.sourceforge.pmd.lang.java.types.SentinelType.acceptVisitor(SentinelType.java:66)
        at net.sourceforge.pmd.lang.java.types.TypeOps.isSameType(TypeOps.java:134)
        at net.sourceforge.pmd.lang.java.types.TypeOps.access$000(TypeOps.java:50)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.typeArgContains(TypeOps.java:769)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitClass(TypeOps.java:854)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitClass(TypeOps.java:586)
        at net.sourceforge.pmd.lang.java.types.JClassType.acceptVisitor(JClassType.java:312)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:656)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:598)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitTypeVar(TypeOps.java:808)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitTypeVar(TypeOps.java:586)
        at net.sourceforge.pmd.lang.java.types.JTypeVar.acceptVisitor(JTypeVar.java:103)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:656)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:598)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.typeArgContains(TypeOps.java:788)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitClass(TypeOps.java:854)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitClass(TypeOps.java:586)
        at net.sourceforge.pmd.lang.java.types.JClassType.acceptVisitor(JClassType.java:312)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:656)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:598)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitTypeVar(TypeOps.java:808)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitTypeVar(TypeOps.java:586)
        at net.sourceforge.pmd.lang.java.types.JTypeVar.acceptVisitor(JTypeVar.java:103)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:656)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.isConvertible(TypeOps.java:598)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.typeArgContains(TypeOps.java:788)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitClass(TypeOps.java:854)
        at net.sourceforge.pmd.lang.java.types.TypeOps$SubtypeVisitor.visitClass(TypeOps.java:586)
        at net.sourceforge.pmd.lang.java.types.JClassType.acceptVisitor(JClassType.java:312)
...
```

**Code Sample demonstrating the issue:**

```java
package org.example;

import java.util.Collection;
import java.util.Collections;
import java.util.Optional;

public class Main {

    public static <T extends Comparable<? super T>> Optional<T> getMaxElementCausesStackoverflow(Collection<? extends T> collection) {
        return collection == null || collection.isEmpty() ? Optional.empty() : Optional.of(Collections.max(collection));
    }

    public static <T extends Comparable<? super T>> Optional<T> getMaxElementIsFine(Collection<? extends T> collection) {
        return Optional.ofNullable(collection).filter(c -> !c.isEmpty()).map(Collections::max);
    }
}
```

**Steps to reproduce:**

pmd check -d ./Main.java -R rulesets/java/quickstart.xml

**Running PMD through:** *CLI*
Java version: 21.0.2, vendor: Amazon.com Inc
OS: macOS 14.5

### PR DESCRIPTION
**Pull request by oowekyala**
~I unfortunately wasn't able to create source that triggers the bug. I identified the infinite loop from the stack trace, and had to add a new entry point to the convertibility visitor to fall into it.~ #5505 provided a test case.

## Related issues

- Fix #5442
- Fix #5505

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to main:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/13330470165?pr=5528">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/SubtypingTest.kt [hunk 1]
```diff
@@ -329,5 +330,29 @@ class SubtypingTest : FunSpec({
         }
     }
 
+    test("Capture of recursive types #5442 stackoverflow") {
```
Comment (adangel) [inline pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/SubtypingTest.kt:333]:
```suggestion
    test("Capture of recursive types #5505 stackoverflow") {
```

**Review by adangel — APPROVED** [review]
Thanks!
