### PR TITLE
[java] Resolve StackOverflow in JavaTypeDefinitionSimple.toString()

### LINKED ISSUE #831: [java] StackOverflow in JavaTypeDefinitionSimple.toString
**Affects PMD Version:** 
6.0.0

**Rule:**
Don't know if this is related to any particular rule, can check further.

**Description:**
With 5.8.1 pmd everything works fine, with 6.0.0 I'm getting StackOverflowException from toString method when called from MethodTypeResolution(358):
`LOG.log(Level.FINE, "Method {0} couldn't be resolved", String.valueOf(methodType));
`
```
Cause: java.lang.StackOverflowError
	at net.sourceforge.pmd.lang.java.typeresolution.typedefinition.JavaTypeDefinitionSimple.toString(JavaTypeDefinitionSimple.java:246)
	at net.sourceforge.pmd.lang.java.typeresolution.typedefinition.JavaTypeDefinitionSimple.toString(JavaTypeDefinitionSimple.java:246)
...

```
**Code Sample demonstrating the issue:**
```
public abstract class MessageBuilder<T extends MessageBuilder, U extends PartBuilder<U>> implements IMessageBuilder {
	public T addComponent(U builder) {
		components.add(builder);
		return (T) this;
	}
}

```
**Running PMD through:** *Gradle*

### PR DESCRIPTION
**Pull request by jsotuyod**
- Resolves #831

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java [hunk 1]
```diff
@@ -243,7 +245,21 @@ public boolean isArrayType() {
     public String toString() {
         return new StringBuilder("JavaTypeDefinition [clazz=").append(clazz)
                 .append(", definitionType=").append(getDefinitionType())
-                .append(", genericArgs=").append(genericArgs)
+                .append(", genericArgs=").append(genericArgs.stream().map(new Function<JavaTypeDefinition, String>() {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java]: stream() is a java8 feature, isn't it? We are still on java7... I'm wondering, why the ci build doesn't fail...

Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java]: It seems, we run into the "wrong bootclasspath" problem - it compiles fine as java7 but doesn't run later with java7 (e.g. class not found: java.util.function.Function).

For releasing 6.0.0 I switched back from java9 to java8, so that pmd-scala is included. When switching to java9 we removed the maven toolchain support (which would avoid the wrong bootclasspath problem) and used the new java9 "-release" feature.

I'll look into a solution like [this](https://stackoverflow.com/questions/9164625/maven-use-jdk-7-to-compile-for-jvm-5) tomorrow.

Comment (jsotuyod) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java]: Interesting! good we find this! I'll rework the PR ASAP, but glad we can tackle it to close the door for future mistakes

Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java]: See #842

**Comment by jsotuyod** [comment]
@adangel fixed now! Rebased against your Travis fix also to be sure.
