### PR TITLE
[java] Add support for Lombok-generated getters in symbol resolution

### LINKED ISSUE #5787: [java] InvalidLogMessageFormat: False positive with lombok @Value generated methods
**Affects PMD Version:** 7.14.0

**Rule:** [InvalidLogMessageFormat](https://pmd.github.io/pmd/pmd_rules_java_errorprone.html#invalidlogmessageformat)

**Description:**
If there is no argument but only the log message and the exception then pmd reports `InvalidLogMessageFormat`

**Code Sample demonstrating the issue:**

```java
@Slf4j
public class Main {
    public static void main(String[] args) {
        var abcd = new AClass(new Exception("abcd"));
        log.error("Hello World", abcd.getT());
    }

    @Value
    private static class AClass {
        Throwable t;
    }
}
```

**Expected outcome:**

PMD reports a violation at line ..., but that's wrong. That's a false positive.

**Running PMD through:** *Maven*

### PR DESCRIPTION
**Pull request by altaiezior**
## Describe the PR

Adds support for lombok generated getters in symbol resolution
PMD doesn't recognize the getters generated by lombok and results in false positives

## Related issues

- Fix #5787

## Ready?

- [x] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by altaiezior** [comment]
@adangel I have created an MR to address the getter not being recognized by pmd, but I am facing some issues in reading the annotation from the field, a little help would help me complete the MR.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AstDisambiguationPass.java [hunk 1]
```diff
@@ -58,6 +58,14 @@ public static void disambigWithCtx(NodeStream<? extends JavaNode> nodes, Referen
         nodes.forEach(it -> it.acceptVisitor(DisambigVisitor.INSTANCE, ctx));
     }
 
+    public static void retryDisambigWithCtx(NodeStream<? extends ASTAmbiguousName> nodes, ReferenceCtx ctx, JSymbolTable symbolTable) {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AstDisambiguationPass.java]: public?

Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AstDisambiguationPass.java]: The class `AstDisambiguationPass` is package private itself, so it doesn't necessarily make a difference...
