### PR TITLE
[core] Use real file name in ruleContext during analysis

### LINKED ISSUE #1923: [core] Incremental analysis does not work with shortnames
**Affects PMD Version:** 
6.16.0

**Rule:**
N/A

**Description:**
I am trying to run the incremental analysis with the shortFilenames option on. On first run of the code base everything works and a cache file is created with violations that exist within the code base. Upon fixing one of those violations and running PMD again, PMD is using the existing violations within the cache file and not scanning the changed file with the resolved violation. PMD then reports on the old violations that existed within the cache file.

**Code Sample demonstrating the issue:**
Here is the Ant target I used to recreate the issue:
```
<target name="pmd">
        <taskdef name="pmd" classname="net.sourceforge.pmd.ant.PMDTask">
            <classpath>
                <fileset dir="<path_to_pmd_lib>">
                    <include name="*.jar"/>
                </fileset>
            </classpath>
        </taskdef>
        <pmd shortFilenames="true" cacheLocation="pmd.cache">
            <formatter type="xml" toFile="pmd_report.xml" toConsole="true"/>
            <ruleset>build/archruleset_java.xml</ruleset>
            <fileset dir="${src}">
                <include name="**/Application.java"/>
            </fileset>
        </pmd>
    </target>
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
This was run through Ant. I tried replicating this with the CLI as well but I ran into a separate error:;
```
<error filename="src/main/java/Application.java" msg="NullPointerException: null">
<![CDATA[java.lang.NullPointerException
        at net.sourceforge.pmd.cache.AbstractAnalysisCache.ruleViolationAdded(AbstractAnalysisCache.java:232)
        at net.sourceforge.pmd.Report.addRuleViolation(Report.java:335)
        at net.sourceforge.pmd.lang.rule.AbstractRuleViolationFactory.addViolation(AbstractRuleViolationFactory.java:37)
        at net.sourceforge.pmd.lang.rule.AbstractRule.addViolation(AbstractRule.java:349)
        at com.pmd.archrules.hystrix.HystrixConfigRule.visit(HystrixConfigRule.java:40)
        at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceDeclaration.jjtAccept(ASTClassOrInterfaceDeclaration.java:55)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
        at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
        at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:280)
        at net.sourceforge.pmd.lang.java.ast.ASTTypeDeclaration.jjtAccept(ASTTypeDeclaration.java:37)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
        at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
        at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:255)
        at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll(AbstractJavaRule.java:39)
        at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:27)
        at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:499)
        at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:143)
        at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:184)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
]]>
</error>
```

### PR DESCRIPTION
**Pull request by adangel**
**PR Description:**

* This is needed to fix #1923
* RuleContext, RuleViolations all use the real name
* The shortname is only applied by the renderers now
  at the end of the processing
* Error logging and reporting also uses the real, full name
  of the file being analysed

The implementation is not optimal yet. E.g. now every renderer needs to take care of applying shortnames. But now, until the result is rendered, PMD uses the real, full pathname of the file being analyzed.

The NPE can be reproduced maybe when reusing a PMD cache file creating with a PMD run with "shortnames" and then removing the shortnames option (not entirely sure though).

The analysis cache needs to read the file content in order to calculate the checksums. If the file don't existed (because with shortnames the ruleContext.getSourceCodeFile() didn't point to a existing file anymore), the checksum was 0. Executing PMD multiple times always returned checksum 0 for this file and thus, no changes were detected for this file and the analysis was not executed and only the  cache result was used. I changes this, to return a timestamp, which should be different everytime the file is analyzed. We _should_ not run into this problem anymore due to the other changes.

We seem to be missing an abstraction level - something to think about for PMD 7: What do we analyze? Currently we mostly analyze files... This means, we can use filenames as a pointer. However, "DataSource" (the already existing abstraction) could already be something else.. but for ruleviolations, processing errors, etc. - we always report them against files... which makes it difficult, if PMD every analyses code from other sources (like database, web request, ...).

Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/c84f14ebd5364bd78d796e01756c2291/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jsotuyod** [comment]
I was working on a much simpler, but far less elegant solution. I'll review this, as the general approach seems far better / more maintainable.

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleContext.java [hunk 1]
```diff
@@ -31,6 +30,7 @@
 
     private Report report = new Report();
     private File sourceCodeFile;
+    @Deprecated
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/RuleContext.java]: the field is private, we can simply remove it

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleContext.java [hunk 2]
```diff
@@ -97,21 +97,29 @@ public void setSourceCodeFile(File sourceCodeFile) {
...
      * @param filename
      *            The file name.
+     * @deprecated This method will be removed. The file should only be
+     * set with {@link #setSourceCodeFile(File)}. Setting the filename here
+     * has no effect.
      */
+    @Deprecated
     public void setSourceCodeFilename(String filename) {
-        this.sourceCodeFilename = filename;
+        // ignored, does nothing.
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/RuleContext.java]: we could nag (log an error) about the usage of a deprecated API

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java [hunk 3]
```diff
@@ -499,11 +499,11 @@ public void apply(List<? extends Node> acuList, RuleContext ctx) {
                         rule.apply(acuList, ctx);
                     } catch (RuntimeException e) {
                         if (ctx.isIgnoreExceptions()) {
-                            ctx.getReport().addError(new Report.ProcessingError(e, ctx.getSourceCodeFilename()));
+                            ctx.getReport().addError(new Report.ProcessingError(e, String.valueOf(ctx.getSourceCodeFile())));
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java]: isn't this equivalent to calling `ctx.getSourceCodeFile().toString()`, or more explicitly `ctx.getSourceCodeFile().getPath()`?

File: pmd-core/src/main/java/net/sourceforge/pmd/SourceCodeProcessor.java [hunk 4]
```diff
@@ -108,7 +108,7 @@ public void processSourceCode(Reader sourceCode, RuleSets ruleSets, RuleContext
 
     private Node parse(RuleContext ctx, Reader sourceCode, Parser parser) {
         try (TimedOperation to = TimeTracker.startOperation(TimedOperationCategory.PARSER)) {
-            Node rootNode = parser.parse(ctx.getSourceCodeFilename(), sourceCode);
+            Node rootNode = parser.parse(String.valueOf(ctx.getSourceCodeFile()), sourceCode);
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/SourceCodeProcessor.java]: ditto

File: pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java [hunk 5]
```diff
@@ -254,7 +254,7 @@ private void handleError(RuleContext ctx, Report errorReport, RuntimeException p
         if (failOnError) {
             throw new BuildException(pmde);
         }
-        errorReport.addError(new Report.ProcessingError(pmde, ctx.getSourceCodeFilename()));
+        errorReport.addError(new Report.ProcessingError(pmde, String.valueOf(ctx.getSourceCodeFile())));
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java]: ditto

File: pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisResult.java [hunk 6]
```diff
@@ -49,7 +49,10 @@ private static long computeFileChecksum(final File sourceFile) {
             // the analysis will fail and report the error on it's own since the checksum won't match
         }
 
-        return 0;
+        // we couldn't read the file, maybe the file doesn't exist
+        // in any case, we can't use the cache. Returning here the timestamp should make
+        // sure, we see that the file changed every time we analyze it.
+        return System.currentTimeMillis();
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisResult.java]: this seems unrelated to the rest of the PR, although related to the original report

File: pmd-core/src/main/java/net/sourceforge/pmd/renderers/AbstractRenderer.java [hunk 7]
```diff
@@ -6,22 +6,31 @@
...
 
+import net.sourceforge.pmd.PMDConfiguration;
+import net.sourceforge.pmd.cli.PMDParameters;
 import net.sourceforge.pmd.properties.AbstractPropertySource;
 
 /**
  * Abstract base class for {@link Renderer} implementations.
  */
 public abstract class AbstractRenderer extends AbstractPropertySource implements Renderer {
+    private static final String FILE_SEPARATOR = System.getProperty("file.separator");
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/renderers/AbstractRenderer.java]: any reason to not use `File.separator` directly?

File: pmd-core/src/main/java/net/sourceforge/pmd/renderers/AbstractRenderer.java [hunk 8]
```diff
@@ -62,6 +71,47 @@ public void setShowSuppressedViolations(boolean showSuppressedViolations) {
...
+    protected String determineFileName(String inputFileName) {
+        for (final String prefix : inputPathPrefixes) {
+            final Path prefPath = Paths.get(prefix).toAbsolutePath();
+            final String prefPathString = prefPath.toString();
+
+            if (inputFileName.startsWith(prefPathString)) {
+                if (prefPath.toFile().isDirectory()) {
+                    return trimAnyPathSep(inputFileName.substring(prefPathString.length()));
+                } else {
+                    if (inputFileName.indexOf(FILE_SEPARATOR.charAt(0)) == -1) {
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/renderers/AbstractRenderer.java]: or `File.separatorChar` directly
```suggestion
                    if (inputFileName.indexOf(File.separatorChar) == -1) {
```

File: pmd-core/src/main/java/net/sourceforge/pmd/renderers/AbstractRenderer.java [hunk 9]
```diff
@@ -62,6 +71,47 @@ public void setShowSuppressedViolations(boolean showSuppressedViolations) {
...
+                        return inputFileName;
+                    }
+                    return trimAnyPathSep(inputFileName.substring(prefPathString.lastIndexOf(FILE_SEPARATOR)));
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/renderers/AbstractRenderer.java]:
```suggestion
                    return trimAnyPathSep(inputFileName.substring(prefPathString.lastIndexOf(File.separatorChar)));
```

File: pmd-core/src/main/java/net/sourceforge/pmd/renderers/AbstractRenderer.java [hunk 10]
```diff
@@ -62,6 +71,47 @@ public void setShowSuppressedViolations(boolean showSuppressedViolations) {
...
+                }
+            }
+        }
+
+        return inputFileName;
+    }
+
+    private String trimAnyPathSep(String name) {
+        return name.startsWith(FILE_SEPARATOR) ? name.substring(1) : name;
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/renderers/AbstractRenderer.java]: our own rules would suggest changing this to use `name.charAt(0) == File.separatorChar` (adding a null check or assuming non-nullness)

File: pmd-core/src/main/java/net/sourceforge/pmd/renderers/CSVRenderer.java [hunk 11]
```diff
@@ -95,7 +95,14 @@ public CSVRenderer(ColumnDescriptor<RuleViolation>[] columns, String theSeparato
...
     public CSVRenderer() {
-        this(ALL_COLUMNS, DEFAULT_SEPARATOR, PMD.EOL);
+        super(NAME, "Comma-separated values tabular format.");
+
+        separator = DEFAULT_SEPARATOR;
+        cr = PMD.EOL;
+
+        for (ColumnDescriptor<RuleViolation> desc : allColumns) {
+            definePropertyDescriptor(booleanPropertyFor(desc.id, desc.title));
+        }
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/renderers/CSVRenderer.java]: this seems unrelated to the rest of the PR… what are we fixing here exactly?

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRuleChainVisitor.java [hunk 12]
```diff
@@ -100,11 +100,11 @@ public void visitAll(List<Node> nodes, RuleContext ctx) {
                         rcto.close(visits);
                     } catch (RuntimeException e) {
                         if (ctx.isIgnoreExceptions()) {
-                            ctx.getReport().addError(new Report.ProcessingError(e, ctx.getSourceCodeFilename()));
+                            ctx.getReport().addError(new Report.ProcessingError(e, String.valueOf(ctx.getSourceCodeFile())));
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRuleChainVisitor.java]: ditto

File: pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java [hunk 13]
```diff
@@ -103,9 +110,10 @@ public void processFiles(RuleSetFactory ruleSetFactory, List<DataSource> files,
         SourceCodeProcessor processor = new SourceCodeProcessor(configuration);
 
         for (DataSource dataSource : files) {
-            String niceFileName = filenameFrom(dataSource);
+            // this is the real, canonical and absolute filename (not shortened)
+            String realFileName = dataSource.getNiceFileName(false, null);
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java]: should we deprecate this method from the datasource too and remove all such logic from it?

Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java]: @jsotuyod I'm not sure what that would achieve... It looks like we could reimplement everything in terms of DataSource to avoid depending on File like that. In that case, a DataSource needs a way to provide a readable name (eg a URI or something) for reporting.

Comment (jsotuyod) [reply pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java]: the thing is, not all datasources map to a file. Actually, of all `DataSource` implementation, only one does: `FileDataSource`.

The others take the data from other sources:
* `ReaderDataSource`: from a `Reader`, which is currently used only with data loaded from a database through JDBC
* `StringDataSource`: from a `String`, used mainly by designers and tests, can be used with data from a db through JDBC too
* `ZipDataSource`: from a `ZipEntry` within a zip file

So, when we ask the `DataSource` for the file / filename, it's all lies. The source should have a name, but it's not necessarily a file name, and it should not know how to trim that path to make it short / relative to something else.

Comment (oowekyala) [reply pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java]: So possibly the method is badly named (because it's not a *file* name). Yet if a DataSource cannot trim its name, then I don't know what can. As you say a name is not necessarily a file path, and the only thing that knows what the name *means* is the DataSource implementation. So I don't know how relativizing the name *cannot* be left to the implementation.

> Actually, of all DataSource implementation, only one does: FileDataSource.

For a ZipDataSource we can view a zip entry as a file in the filesystem of the zip, but i get the point.

In any case if we want to support autofixes we need to have some "data sources" that are both readable and writable, and possibly also renamable, movable, etc. If we want to support multifile analysis we also need a strong concept of what is a "file".

For the record, IDEs all use an abstraction that allows seeing archive entries, http resources, etc, as files. For example, Intellij OpenAPI's [virtual file system](https://www.jetbrains.org/intellij/sdk/docs/basics/virtual_file_system.html), or eclipse's [IResource](https://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fcore%2Fresources%2FIResource.html) and [IPath](https://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fcore%2Fruntime%2FIPath.html).
Maybe we need something of that kind too.

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java (hunk 3 above)
Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java]: This way, we might avoid a NPE, in case ctx.getSourceCodeFile() is null.

File: pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisResult.java (hunk 6 above)
Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisResult.java]: Yes, this would be fixing the symptom, so that the cache would be essentially disabled when using shortnames... I can separate it out in a extra PR.

File: pmd-core/src/main/java/net/sourceforge/pmd/renderers/AbstractRenderer.java (hunk 7 above)
Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/renderers/AbstractRenderer.java]: Just reusing the original implementation from DataSource.... but yes, we should simply use File.separator directly :smile:

File: pmd-core/src/main/java/net/sourceforge/pmd/renderers/CSVRenderer.java (hunk 11 above)
Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/renderers/CSVRenderer.java]: I needed to change the property  descriptors for the default columns to non-static, so that I can access the instance method `determineFileName` of AbstractRenderer/CSVRenderer.

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleContext.java (hunk 1 above)
Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/RuleContext.java]: Indeed, I'll remove it.

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleContext.java (hunk 2 above)
Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/RuleContext.java]: Yes, makes sense. Internally we don't seem to use it anymore.

File: pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java (hunk 13 above)
Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java]: We currently still use it for sorting the files before processing. This means, after this PR, we'll have the logic to determine the short names duplicated. I think, I'll extract it in a helper class used by both....

The DataSource seems like a good name for an abstraction of what PMD is analyzing. However, the rule context e.g. needs a file/filename. As does the rule violation. While DataSource is abstract to work with more than files, anything else doesn't seem to be. That's something we should aim to fix for PMD 7, but not in PMD 6 (unless there is a bug to fix).

File: pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisResult.java (hunk 6 above)
Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisResult.java]: Here it is: #2000

File: pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java (hunk 13 above)
Comment (adangel) [reply pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java]: I've extracted it now into a `ShortFilenameUtil` used by both AbstractRenderer and FileDataSource.

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java (hunk 3 above)
Comment (jsotuyod) [reply pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java]: good call, shouldn't happen, but better be safe

File: pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java (hunk 13 above)
Comment (jsotuyod) [reply pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java]: I've created #2004 to track this, I'm merging the PR as is for 6.x
