### PR TITLE
[java] Fix false positives of LawOfDemeter: this and cast expressions

### LINKED ISSUE #2174: [java] LawOfDemeter: False positive with 'this' pointer
https://github.com/pmd/pmd/issues/2160#issuecomment-565639733

**Affects PMD Version:** 
6.20.0

**Rule:**
[LawOfDemeter](https://pmd.github.io/latest/pmd_rules_java_design.html#lawofdemeter)

**Description:**
LawOfDemeter does not recognise 'this' pointer and includes its dot accessor as a count towards method chaining. It must not. Similarly for 'super' while calling parent class functions. 

**Code Sample demonstrating the issue:**

```java
package pmdtests;

public class Foo {
  private final int i;

  public Foo(int i) {
    this.i = i;
  }


  public void meth() {
    System.out.println(this.i); // wrong violation: method chain calls
    System.out.println(super.i); // wrong violation: method chain calls
    System.out.println(i);      // no violation
  }

  public void method(Foo this) {
    System.out.println(this.i);  // wrong violation: method chain calls
  }

  public void method(Foo this, String... args) {
    System.out.println(this.i);  // wrong violation: method chain calls
    for (String arg: args)
      System.out.println(arg);
  }
}
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

### LINKED ISSUE #2189: [java] LawOfDemeter: False positive when casting to derived class
https://github.com/pmd/pmd/issues/2160#issuecomment-565639733

**Affects PMD Version:** 
6.20.0
**Rule:**
LawOfDemeter
**Description:**
Casting to derived class triggers method chaining error for this rule.
**Code Sample demonstrating the issue:**

```java
package pmdtests;


  class TaskManager {
   
    private final List<ForkJoinTask<Integer>> tasks;

  
    public void cancelTasks(ForkJoinTask<Integer> cancelTask) {
      for (ForkJoinTask<Integer> task : tasks) {
        if (!task.equals(cancelTask)) {
          task.cancel(true);
          ((SearchNumberTask) task).writeCancelMessage();
        }
      }
    }
}
 

```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

### PR DESCRIPTION
**Pull request by xioayuge**
## Describe the PR

Issue 2174 is about a false positive of 'this' pointer and issue 2189 is  about a false positive when casting to derived class. Both the issue are about LawOfDemeterRule.java. I think there is still some problem about the code I modified. Hope this can give you some inspiration. 

## Related issues

- Fixes #2174 
- Fixes #2189

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/LawOfDemeterRule.java [hunk 1]
```diff
@@ -175,7 +177,7 @@ private boolean isNotBuilder() {
         private static List<ASTPrimarySuffix> findSuffixesWithoutArguments(ASTPrimaryExpression expr) {
             List<ASTPrimarySuffix> result = new ArrayList<>();
             if (hasRealPrefix(expr)) {
-                List<ASTPrimarySuffix> suffixes = expr.findDescendantsOfType(ASTPrimarySuffix.class);
+                List<ASTPrimarySuffix> suffixes = expr.findChildrenOfType(ASTPrimarySuffix.class);
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/LawOfDemeterRule.java:180]: Interesting, that's the same fix suggested in #2561

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 9941 violations, 2 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/b482371664794b9c854f0eceef7ef37f/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
