### PR TITLE
[java] Created fix for UselessStringValueOf false positive

### LINKED ISSUE #3491: [java] UselessStringValueOf: False positive when `valueOf(char [], int, int)` is used
**Affects PMD Version:** 6.37.0

**Rule:** [UselessStringValueOf](https://pmd.github.io/latest/pmd_rules_java_performance.html#uselessstringvalueof)

**Description:** False positive for UselessStringValueOf when valueOf(char [], int, int) is used

**Code Sample demonstrating the issue:**
ab37b1ccb2d040eb782dead5f28679cbc9532499/https://github.com/pmd/pmd/pull/3490
```java
public class Test {
    public String test(char buf[], int offset, int len) {
        print("XML Parser characters: " + String.valueOf(buf, offset, len));
    }
}
```

**Expected outcome:**

PMD reports a violation at line 3, but that's wrong. That's a false positive.

**Running PMD through:** *Maven*

### PR DESCRIPTION
**Pull request by johnra2**
- Fixes #3491

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/UselessStringValueOfRule.java [hunk 1]
```diff
@@ -45,6 +47,13 @@ public Object visit(ASTPrimaryPrefix node, Object data) {
                                 && ((ASTReferenceType) argType.getChild(0)).isArray()) {
                             return super.visit(node, data);
                         }
+                        // declaration may be of format [TYPE] [IDENTIFIER] [LBRACKET] [RBRACKET]
+                        try {
+                            GenericToken t = ((ASTPrimitiveType)argType.getChild(0)).jjtGetFirstToken();
+                            if (t.getNext().getNext().getKind() == 79 && t.getNext().getNext().getNext().getKind() == 80) {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/UselessStringValueOfRule.java:53]: That's very hard to understand... (and it would fail, if the code would be `String.valueOf(otherString.toCharArray(), 0, 10)`)
I think, the problem is, that the rule doesn't check the number or arguments of the method call "String.valueOf".
In line 30/32 we figured, that this is a String.valueOf call. In line 37/39, we figured, that there are arguments - and exactly here we can check the number of arguments (`args.size()`) - the rule should IMHO only consider calls to String.valueOf with exactly one argument - which then automatically ignores "String.valueOf(char[], int, int)".

**Review by adangel — CHANGES_REQUESTED** [review]
Thanks for your PR!
Please have a look at my comment

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/UselessStringValueOfRule.java (hunk 1 above)
Comment (johnra2) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/UselessStringValueOfRule.java:53]: I think the issue more stems from how the PMD Java parser works. The problem is that the parser sees `char buf[]` as a primitive `char` type, not an array, since the identifier comes before the brackets. You can write a test case with just `char buf[]` as the parameter to the function and it would fail in that case. I tried playing around with the parser to get it to properly recognize the brackets but couldn't get it to work.

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 3 configuration errors.<br />
<a href="https://chunk.io/pmd/1169c4f70bc84545b8ce2b1077340c21/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
