### PR TITLE
[java] Support JDK 22

### LINKED ISSUE #4794: [java] Support JDK 22
[OpenJDK 22](https://openjdk.org/projects/jdk/22/)  GA is scheduled for 2024/03/19.

The following JEPs are important for us:
* 447: 	[Statements before super(...) (Preview)](https://openjdk.org/jeps/447)
* 456: 	[Unnamed Variables & Patterns](https://openjdk.org/jeps/456)
* 459: 	[String Templates (Second Preview)](https://openjdk.org/jeps/459)
* 463: 	[Implicitly Declared Classes and Instance Main Methods (Second Preview)](https://openjdk.org/jeps/463)

In summary: https://javaalmanac.io/jdk/22/

This issue is similar to the previous: #4583 

EA Release of JDK22 is available here: https://jdk.java.net/22/

**Tasks:**

- [x] Add new java language versions 22 and 22-preview: `net.sourceforge.pmd.lang.java.JavaLanguageModule`
    - 22 is the new default
    - update also java.md and ant.md
    - and add in KotlinTestingDsl.kt.
    - Update `net.sourceforge.pmd.lang.java.LanguageVersionTest`
    - Update `net.sourceforge.pmd.lang.java.JavaLanguageModuleTest#previewVersionShouldBeGreaterThanNonPreview`
- [x] Update asm dependency to 9.6:
    - https://search.maven.org/artifact/org.ow2.asm/asm
    - https://asm.ow2.io/versions.html
    - Update net.sourceforge.pmd.lang.java.symbols.internal.asm.AsmSymbolResolver#ASM_API_V if necessary
- [x] Remove java language version 20-preview: `net.sourceforge.pmd.lang.java.JavaLanguageModule`
    - update also java.md
    - update KotlinTestingDsl.kt
    - remove exclusions in pmd-core/src/main/resources/internal/all-java.xml
    - Update `net.sourceforge.pmd.lang.java.LanguageVersionTest`
    - Remove `net.sourceforge.pmd.lang.java.ast.Java20PreviewTreeDumpTest`  (including resources)
- [x] Update implementation for "String Templates" (430, 459)
    - https://cr.openjdk.org/~gbierman/jep459/jep459-20231114/specs/string-templates-jls.html
    - "Except for a technical change in the types of template expressions, there are no changes relative to the first preview."
- [x] Update implementation for "Implicitly Declared Classes and Instance Main Methods" (445, 463)
    - https://cr.openjdk.org/~gbierman/jep463/jep463-20231030/specs/implicitly-declared-classes-instance-main-methods-jls.html
- [x] Update implementation for "Unnamed Variables & Patterns" (443, 456)
    - https://cr.openjdk.org/~abimpoudis/unnamed/jep456-20231128/specs/unnamed-jls.html
    - Promote this feature to a standard language feature (was preview before). E.g. remove experimental
    - "We here propose to finalize this feature without change."
- [x] Implement preview feature "Statements before super(...)" (447)
    - https://cr.openjdk.org/~gbierman/jep447/jep447-20230927/specs/statements-before-super-jls.html
- [x] Write release notes
    - removed experimental:
      - ASTUnnamedPattern
    - removed classes: -
    - deprecated classes: -
    - new experimental: -
- [x] Add JDK22 to the build, so that we integration test with 22, ~as this is a LTS version~
    - integration test in pmd-dist
    - Not necessary, as JDK22 is not LTS
- [x] Make sure, we can build PMD with JDK22
- [x] Update https://github.com/pmd/java-regression-tests
    - new regular language features, so update needed
    - Note: This can only be done, after this issue has been implemented
    - See https://github.com/pmd/java-regression-tests/pull/2

### PR DESCRIPTION
**Pull request by adangel**
## Related issues

- Fixes #4794

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 17 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 1 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/7915349572">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-ant/src/main/java/net/sourceforge/pmd/ant/Formatter.java [hunk 1]
```diff
@@ -210,8 +211,21 @@ private static Writer getToFileWriter(String baseDir, File toFile, Charset chars
...
+            try {
+                Boolean isTerminal = (Boolean) MethodUtils.invokeMethod(console, "isTerminal");
+                if (!isTerminal) {
+                    // stop here, we don't have an interactive console.
+                    return null;
+                }
+            } catch (InvocationTargetException | NoSuchMethodException | IllegalAccessException ignored) {
+                // fall-through - we use a Java Runtime < 22.
+            }
+
```
Comment (jsotuyod) [inline pmd-ant/src/main/java/net/sourceforge/pmd/ant/Formatter.java:228]: I'd assume since our CLI progressbar uses JLine3 under the hood to detect terminal capabilities that it is safe and won't choke on this change… but did you have the chance to test it?

Comment (adangel) [reply pmd-ant/src/main/java/net/sourceforge/pmd/ant/Formatter.java:228]: This change is about how we determine the console encoding for ant, if the report should be output to the console (`toConsole=true`) - and when building PMD with Java 22, the (ant) unit tests failed, because then we couldn't override the encoding for testing purpose anymore and couldn't test various encoding combinations. The tests are actually in pmd-java:

https://github.com/pmd/pmd/blob/04c2c0106ddbd200fb8a978849606389757dd7c0/pmd-java/src/test/java/net/sourceforge/pmd/ant/PMDTaskTest.java#L89-L110

And we explicitly set the system property "file.encoding" in the unit test, so that we can "override" the encoding for the test. That didn't work anymore, because Java 22 now returns always a Console and the tests used then always the correct console encoding rather than the faked test encoding.

I actually didn't test PMD CLI with Java 22 - if I remember correctly, I only tested the build with Java 22 and eventually it works - that means the integration tests in pmd-dist were successful. However, I think we don't test the progress bar there.
