### PR TITLE
[apex] Fix ApexDoc handling with inner classes

### LINKED ISSUE #1783: [apex] comments on constructor not recognized when the Class has inner class
Affects PMD Version: 6.13.0

Rule: [ApexDoc](https://pmd.github.io/pmd-6.14.0/pmd_rules_apex_documentation.html#apexdoc)

Description: comments on constructor not being recognized when the apex class has inner classes

Code Sample demonstrating the issue:
```
/**
 * @description outer class
 */
public class OuterClass {

    private String testStr;

    /**
     * @description constructor
     *
     * @param       testStr     test string
     */
    public OuterClass(String testStr) { 
        this.testStr = testStr;
    }

    /**
     * @description inner class
     */
    public class InnerClass {

    }
}
```

when I run pmd with the rule, it reports that there is Missing ApexDoc Comment on the OuterClass constructor, after I removed the InnerClass definition, it passed the pmd check.

Running PMD through: CLI

Java Version: "1.8.0_25"
OS: Mac Mojave 10.14.4

### PR DESCRIPTION
**Pull request by jeffhube**
Before submitting a PR, please check that:
 - [X] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [X] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**

Fixes #1783 

This changes tweaks how we find the corresponding ApexDoc comment for classes/methods/etc. The current approach assumes that classes/methods/etc will be visited in the order that they appear in the code, which is not the case with the code in #1783.

With the new approach, when we capture the ApexDoc tokens, we store with it a range from the end of the comment to the end of the next non-whitespace token. When visiting classes/methods/etc, we find the start index, and see if that index is within the range stored on any ApexDoc tokens. This requires doing the work in `visitEnd()` instead of `visit()` because we need to check for a child ASTAnnotation node to determine the start index of the method. This also means that in order to insert the ASTFormalComment node as the first child, we need to shift the existing nodes first.

This is similar to what I had originally before 29c5d5b, but instead of storing a list of every token and iterating over it to find the ApexDoc token, we store only the ApexDoc tokens along with the potential range of the class/method/etc that it applies to.

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java [hunk 1]
```diff
@@ -279,55 +278,68 @@ public ApexTreeBuilder(String sourceCode) {
...
 
     private int getApexDocIndex(ApexNode<?> node) {
-        final int index = node.getNode().getLoc().getStartIndex();
+        ASTAnnotation annotation = node.getFirstDescendantOfType(ASTAnnotation.class);
+        ApexNode<?> firstNode = annotation == null ? node : annotation;
+        final int index = firstNode.getNode().getLoc().getStartIndex();
         return sourceCode.lastIndexOf('\n', index);
     }
 
-    private TokenLocation getApexDocTokenLocation(int index) {
```
Comment (adangel) [inline pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java]: There seems to be an easier solution, which avoids dealing with Annotation nodes specifically (maybe other nodes have also a different position in the AST?).

So, yes, we can't use ListIterator, since we might skip more than one token until we find a match and then we don't backup more than one... so in the end we loose a comment.

But we can iterate through the comments and find the nearest match. In order to "mark" the comments, that are already matched, we remove them from the list. Then for the next call, we start the search from the beginning again. With the list iterator, we started the next search after the last match, which is a problem, if the order of the AST doesn't match the source code.

```java
    private TokenLocation getApexDocTokenLocation(int index) {
        TokenLocation last = null;
        for (TokenLocation location : apexDocTokenLocations) {
            if (location.index >= index) {
                // gone too far - this token corresponds to a different node
                break;
            }
            last = location;
        }
        if (last != null) {
            apexDocTokenLocations.remove(last);
        }
        return last;
    }
```

If the list is big, I think, it still takes some time to copy the content when removing a item in the ArrayList. Since we mostly remove a item from the beginning, it should be found fast. We probably should use a `LinkedList` in `buildApexDocTokenLocations()`.

**Comment by jeffhube** [comment]
@adangel The downside there is that could assign comments to the wrong class / method. In the following case, since the Bar class is processed before the constructor, Bar will be given the Foo constructor's comment, and then we will get an error that Foo constructor is missing a comment, when actually it is Bar that is missing the comment.

```
/**
 * @description Foo
 */
public class Foo {
    /**
     * @description Foo
     */
    public Foo() {
    }

    public class Bar {
    }
}
```

It might be possible to avoid that problem if we build a list of all the class / method nodes, and then found all the corresponding comments at the very end, instead of as we visit each node.

One approach might be to build a unified list of the class / method and comment nodes, sorted by position. Then we just look for comment nodes that are directly followed by class / method nodes.

If the nodes appeared in this order: (C = Comment, M = Method)
`M C M C C M M C`
We would pair them like this:
`M (C M) C (C M) M C`
Only two methods are directly preceded by comments.

**Comment by adangel** [comment]
@jeffhube True, your example would be a false-negative.
I think yes, we can't assign the comments correctly in a single pass. So, I'd suggest to first collect for each comment the corresponding node and refine the corresponding node, if we visit later a better matching node (it is nearer to the comment).
And only in the end, after we have visited all potential nodes, we can add the comments into the AST.
I'll push my changes to this PR shortly...
