### PR TITLE
[core] Typesafe and immutable properties

### LINKED ISSUE #459: [core] EnumeratedProperty<T> does not return a T as its value
**Description:** To use a rule property that can take its value in an enumeration, I think the preferred approach is an EnumeratedProperty. I create an EnumeratedProperty like this:
```java
private static final String[] LABELS = { "foo", "bar" };
enum Foo { FOO, BAR }
private static final Foo[] CHOICES = { Foo.FOO, Foo.BAR };

public static final EnumeratedProperty<Foo> FOO_DESCRIPTOR = new EnumeratedProperty<>(
    "fooChoice", "Choose a instance of Foo", LABELS, CHOICES, 0, 3.0f);
```
where the parameter `0` indicates the default index. But the value returned by `getProperty` is really weird:
* If the property was not explicitly given a value in the ruleset.xml, then `getProperty` returns `"foo"` (a String)
* Otherwise, `getProperty` returns an instance of `Foo`, which corresponds to the label given in the XML.

I would think it's abnormal that `getProperty` may return something other than a `Foo`, especially since it's an `EnumeratedProperty<Foo>`. Is that a bug or am I doing this wrong ?

### PR DESCRIPTION
**Pull request by oowekyala**
Hi, this is a proposed API changed for rule properties (initiated in #459). The number of files touched is huge but it's mainly because some tweaks were made to many rules to accommodate the changes. The most interesting changes are in interfaces `net.sourceforge.pmd.*PropertyDescriptor`, and classes of `net.sourceforge.pmd.lang.rule.properties`. I think the best approach to get a view of the changes is to explore the class hierarchy of `AbstractProperty`.

### Main features
* Fully typesafe properties, even for enumerated properties (fixes #459)
* Property descriptors can now be considered immutable (might help #464). I followed the recommendations of Item 15 of Effective Java, the only caveat I know about is that I didn't bother to make defensive copies of the objects contained in the maps of enumerated properties. I don't think that's a problem though
* The code of this framework is *much* more legible now imho, and I tried to document it thoroughly

### Main API changes
* Several new interfaces accommodate different flavours of property descriptors. A primary distinction is made between `SingleValuePropertyDescriptor` and `MultiValuePropertyDescriptor`. The latter now implement `PropertyDescriptor<List<V>>`, which means `getProperty` no longer returns an array, but a `List` (hence the changes in rules).
* That split between single value and multi value properties is reflected in the new class hierarchy of `AbstractProperty`
* The `PropertyDescriptor` interface has been stripped of some methods that weren't relevant to all property descriptors (`choices()` and `multiValueDelimiter()`). These were moved to more specific interfaces (details in the javadoc comment of `PropertyDescriptor` and the doc comments of these interfaces).
* `PropertyDescriptorWrapper`s have also been split. They're now created via a static method, which dispatches to the PropertyDescriptor they're supposed to wrap, so that a wrapper implements the same interfaces as the descriptor it wraps. Thus, we no longer need to unwrap the property descriptors to use the interfaces the property implements (casting the wrapper is enough). This was used to reduce the amount of boilerplate that was in the eclipse plugin. 

The PR for the plugin will follow soon. Cheers!

Edit: the PR for the plugin is at pmd/pmd-eclipse-plugin#25

### CODE REVIEW

File: pmd-core/src/main/java/net/sourceforge/pmd/EnumeratedPropertyDescriptor.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+    Map<String, E> mappings();
+
+
+    /**
+     * Returns a set of choice tuples if available. This is kept for compatibility with the eclipse plugin, even
+     * though it returns the same information as {@link #mappings()} (only it returns them ordered).
+     *
+     * @return An array of the label value mappings. The first column is the labels, the second is the value.
+     */
+    Object[][] choices();
```
Comment (jsotuyod) [inline pmd-core/src/main/java/net/sourceforge/pmd/EnumeratedPropertyDescriptor.java]: we should probably add an issue to update the plugin to use `mappings` and remove this once this is merged.

Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/EnumeratedPropertyDescriptor.java]: We could do so, the thing is that the plugin uses `Object[][]` so heavily (passing integer indices in parameters everywhere, etc.) that I though it was too much work. A middle ground would be to remove `choices` from pmd's API and convert the map to an object array in the plugin.

File: pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptor.java [hunk 2]
```diff
@@ -67,22 +84,24 @@
      */
     boolean isRequired();
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptor.java]: This could be eliminated from the API too, it's not used anywhere

**Comment by ryan-gustafson** [comment]
@oowekyala This is great.  I remember trying to do something similar when descriptors were first being added, but never completed the effort.  I'll start reviewing too.

File: pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertySource.java [hunk 3]
```diff
@@ -127,25 +118,22 @@ public boolean hasDescriptor(PropertyDescriptor<?> descriptor) {
         return result;
     }
 
-    /**
-     * {@inheritDoc}
-     */
+
     @Override
     public <T> void setProperty(PropertyDescriptor<T> propertyDescriptor, T value) {
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertySource.java]: The use of `Arrays.asList` everywhere to set the values is very boilerplate-y.  I wonder if this additional signature would be useful:
```
public <T> void setProperty(PropertyDescriptor<List<T>> propertyDescriptor, T... values)
```
Or, maybe, assuming the more specific interface is used in practice:
```
public <T> void setProperty(MultiValuePropertyDescriptor<T> propertyDescriptor, T... values)
```

File: pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptor.java [hunk 4]
```diff
@@ -94,55 +104,40 @@
      */
     float uiOrder();
 
+
     /**
-     * If the property is multi-valued then return the separate values after
-     * parsing the propertyString provided. If it isn't a multi-valued property
-     * then the value will be returned within an array of size[1].
+     * Retunrs the value represented by this string.
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptor.java]: Typo: _Returns_

File: pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptorField.java [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+    LABELS("labels"),
+    /** Choices for enumerated properties. */
+    CHOICES("choices"),
+    /** Default index for enumerated properties. */
+    DEFAULT_INDEX("defaultIndex");
+
+    final String attributeName;
+
+
+    PropertyDescriptorField(String attributeName) {
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptorField.java]: Make `private`.

And the `attributeName` field?

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java [hunk 6]
```diff
@@ -848,15 +841,15 @@ private static String valueFrom(Node parentNode) {
     private static void parsePropertyNodeBR(Rule rule, Node propertyNode) {
 
         Element propertyElement = (Element) propertyNode;
-        String typeId = propertyElement.getAttribute(PropertyDescriptorFields.TYPE);
-        String strValue = propertyElement.getAttribute(PropertyDescriptorFields.VALUE);
+        String typeId = propertyElement.getAttribute(PropertyDescriptorField.TYPE.attributeName);
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java]: There is a bunch of commented out PropertyDescriptor related code 10+ lines above this comment.  Should it be cleaned up?

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSetWriter.java [hunk 7]
```diff
@@ -266,21 +265,11 @@ private Element createPropertiesElement(List<PropertyDescriptor<?>> propertyDesc
...
-                    // to
-                    // go
-                    // out
-                    // as
-                    // a
-                    // definition.
+            for (PropertyDescriptor<?> propertyDescriptor : propertyDescriptors) {
+                // For each provided PropertyDescriptor
+
+                if (propertyDescriptor instanceof PropertyDescriptorWrapper) {
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/RuleSetWriter.java]: This would seem to be the root of a _lot_ of complexity.  I can no long remember the full subtleties which led me to introduce the wrapper, and my comments here are insufficient to jog my memory.  I checked my email history too.  Let's assume the comment on `PropertyDescriptorWrapper` tells the whole story (not sure what's going on in the UIs, @hooperbloob  always knew far more about that than me), and this is truly just about knowing whether to serialize as a _value_ or a _descriptor_.

Looking at the code I have local, without these changes, I'd think if the _creation_ of a `PropertyDescriptor` by the `RuleSetFactory`, _or_ the subsequent `Rule.definePropertyDescriptor` could cause some _stateful_ information to be set onto the descriptor or the Rule, it could be used to obviate the need for wrappers.  The former seems more preferable.  So...

What if `PropertyDescriptor` had a _source_ specified upon creation?  Say, INTERNAL or EXTERNAL?  Java based Rules would use INTERNAL, and XML would use EXTERNAL.  And thus, INTERNAL means serialize as value, and EXTERNAL means serialize as descriptor.

Then everything wrapper related goes the way of the telegraph.

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/EnumeratedProperty.java [hunk 8]
```diff
@@ -4,97 +4,115 @@
...
-    /**
-     * @return Class
-     * @see net.sourceforge.pmd.PropertyDescriptor#type()
-     */
+
+    public EnumeratedProperty(String theName, String theDescription, Map<String, E> labelsToChoices,
+                              E defaultValue, Class<E> valueType, float theUIOrder) {
+        super(theName, theDescription, defaultValue, theUIOrder);
+
+        this.valueType = valueType;
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/EnumeratedProperty.java]: Can we derive `Class<E>` by looking at one of the label choices, if at least one is always provided?

Given these are immutable, a real-world case for an empty enumerations eludes me.

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java [hunk 9]
```diff
@@ -4,48 +4,103 @@
...
     }
 
-    /**
-     * @return boolean
-     * @see net.sourceforge.pmd.PropertyDescriptor#isMultiValue()
-     */
+
+    private void checkNumber(T number) {
+        if (valueErrorFor(number) != null) {
+            throw new IllegalArgumentException(valueErrorFor(number));
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java]: Double call to `valueErrorFor`.

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java [hunk 10]
```diff
@@ -4,48 +4,103 @@
...
+
     @Override
-    public boolean isMultiValue() {
-        return true;
+    protected String valueErrorFor(T value) {
+
+        double number = value.doubleValue();
+
+        if (number > upperLimit.doubleValue() || number < lowerLimit.doubleValue()) {
+            return value + " is out of range " + AbstractNumericProperty.rangeString(lowerLimit, upperLimit);
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java]: Inheritance provides no means to share `rangeString`?  Using "unrelated" `abstract` classes as holders for `static` utility methods isn't my first choice.

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java [hunk 11]
```diff
@@ -4,48 +4,103 @@
...
+    @Override
+    public Number upperLimit() {
+        return upperLimit;
+    }
+
+
+    @Override
+    protected void addAttributesTo(Map<PropertyDescriptorField, String> attributes) {
+        super.addAttributesTo(attributes);
+        attributes.put(MIN, lowerLimit.toString());
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java]: Wouldn't `asString(...)` be the way to convert to a String representation?

Also I thought I saw this identical method implementation in another class, was it `AbstractNumericProperty`?  Are we on Java 8 yet?  Could `interface` `default` methods help reduce duplication? Sorry I don't have a robust mental visual of the interface and class hierarchies yet, so not quite sure if this is even a practical/useful suggestion.

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/EnumeratedProperty.java (hunk 8 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/EnumeratedProperty.java]: Problem is that if E is an abstract type or interface, the concrete values could have different runtime types. I mean that `whateverValue.class` is not necessarily a `Class<E>`, most probably it's the literal of a subtype of E

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java (hunk 9 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java]: Right

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java (hunk 10 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java]: Yes that's not great :s Perhaps using something like a decorator would solve that

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiPackagedProperty.java [hunk 12]
```diff
@@ -4,48 +4,176 @@
...
  */
-public abstract class AbstractMultiPackagedProperty<T> extends AbstractPackagedProperty<T> {
+/* default */ abstract class AbstractMultiPackagedProperty<T> extends AbstractMultiValueProperty<T> {
 
+    /** Delimiter between values. */
     protected static final char DELIMITER = '|';
+    /** Required keys in the map. */
+    protected static final Map<PropertyDescriptorField, Boolean> PACKAGED_FIELD_TYPES_BY_KEY
+        = BasicPropertyDescriptorFactory.expectedFieldTypesWith(new PropertyDescriptorField[] {LEGAL_PACKAGES},
+                                                                new Boolean[] {false});
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiPackagedProperty.java]: I find the lockstep arrays as Map pattern unfortunate.  I'd much prefer a builder approach:
`expectedFieldTypes().with(LEGAL_PACKAGES, false).with(XXX, true).get()`

However, this is non-trivial to support.  Map literals would be even better. 

But now I'm not talking about Java. :)

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java (hunk 11 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java]: Right, asString would be preferred!

Default interface methods could certainly reduce duplication, unfortunately we're not on Java 8 yet. You're right that it's been implemented twice, but it's the same problem as above: the class hierarchy imposes some duplication of new functionality in order to share the behaviour of multi/single value. So either interface defaults, or something like a decorator, or an object to delegate to (sorry I don't know the name of that pattern)

File: pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertySource.java (hunk 3 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertySource.java]: That's a nice idea! I'll implement the first version, I think it's a bit clearer with the more generic interface

File: pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptorField.java (hunk 5 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptorField.java]: Right the field should be private, however enum constructors are always private ;)

Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptorField.java]: We'll have to replace  the field accesses with accessors though

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java (hunk 6 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java]: I think so. I think it was related to PropertyDescriptorFactory (the old, bloated version in package `properties`), but was replaced with a better implementation... Although we can't really tell without any comments

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSetWriter.java (hunk 7 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/RuleSetWriter.java]: Hmm I see, thanks for this info! I didn't really think about why wrappers were needed at all, but dropping them would really simplify the logic here. The thing is we need to make sure descriptors stay immutable. I think we'd have to make a package private constructor taking a source for each property, and initialise this source field to EXTERNAL when built with a factory, and defaulting to INTERNAL. A boolean might be enough btw

File: pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptorField.java (hunk 5 above)
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptorField.java]: I've always declared my enum constructors private, like I do with classes, until I need them visible, but never tried calling one on an enum for obvious reasons.  I just tested, interesting to see the errors around modifiers and attempts to use the constructor.

I doesn't have to be changed to an accessor.  It's more a suggestion on conventions. `public` non-`static` `final` field access isn't very common.  Although with an `enum`, `public` `final` would be fairly equivalent.

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/EnumeratedProperty.java (hunk 8 above)
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/EnumeratedProperty.java]: Yes in general, I wasn't considering there was a need for that kind of usage.  In the heterogeneous value type case, the class of one value may not even be assignable with another value.  One would have to choose amount the set of classes in the intersection set of all the value hierarchies, decidedly non-trivial.

I don't think the `E[]` constructor would have this same issue, the component type would be compatible.

Let's say you did one of these scenarios, what is the practical use of such a `type()` at this point, especially for an enumeration, as once is basically limited to the pre-defined choices?

That said, providing `Class<E>` explicitly would get the compiler involved to unsure a compatible value was provided for both constructors.

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiPackagedProperty.java (hunk 12 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiPackagedProperty.java]: Right that would be neat!

**Comment by oowekyala** [comment]
@ryan-gustafson Thanks for your help on that :)

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java (hunk 11 above)
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java]: Maybe a comment for future consideration post Java 8?

Or, when are this changes going in?  It's looks potentially API breaking.  Would a Java runtime upgrade be apropos too?

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSetWriter.java (hunk 7 above)
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/RuleSetWriter.java]: I had consider `boolean`, but I felt it lacked clarity to help me get my point across.  Welcome to implement as such of course.

I wasn't considering a change on immutability.

It's not clear to me the factories can be use to delineate these scenarios, currently they appear to be publicly available, so Rules could be using them.

Perhaps having all the current means default to INTERNAL, provide another new means on the factory for creating with EXTERNAL, and use that where ever wrappers were created?  This should prevent accidental misuse, and not limit flexibility.

**Comment by ryan-gustafson** [comment]
@oowekyala No problem.  I'm not done reviewing, I only got through `AbstractMultiPackagedProperty.java` in the commit file list.  I'll pick it up again next time I have some hours free the evening.  I need to get some sleep!

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/EnumeratedProperty.java (hunk 8 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/EnumeratedProperty.java]: Well `type()` is used by RuleSetWriter, and the factory methods, which are currently not implemented for enumerated properties (or badly bugged), so at the moment it's no good. I can't see a way to implement enumerated property factory construction though, as the key point is that they can take arbitrary objects of arbitrary types... impossible to parse from a string. Is it really worth the trouble? We could give up on that and clean up, so that we wouldn't need to provide the literal in the constructor.

Or we could make it so that only enumerated properties of certain types (like the primitive types) can be built externally. We would still need special syntax in the xml to define the choices and the default values. Is it worth the trouble?

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSetWriter.java (hunk 7 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/RuleSetWriter.java]: Right I hadn't considered that. Your solution seems right, I'll try it :)

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java (hunk 11 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java]: Those are planned for 6.0.0, because we sure break down some of the API. I'll be totally in favor of a runtime upgrade, but I think some users might still be on 1.7? Frankly I'm not knowledgeable enough to see whether it's possible or not. @adangel @jsotuyod ?

File: pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptorField.java (hunk 5 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptorField.java]: Well I learned that because Checkstyle colors `private` in bright red in this situation :) 

Right, since enum constants are actually `public static final` fields I guess it's nearly equivalent. I'll still put an accessor should we refactor someday.

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/EnumeratedProperty.java (hunk 8 above)
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/EnumeratedProperty.java]: I don't see the need to support such complex external definitions of enumerates.  We should be able to limit external representations to Strings only for now.  It could always be expanded in the future.

Then we need only focus on internal Java based usages.  These serialize only the value, which I'd expect to use the _label_ String?  So your case for heterogenous _value_ types is good, and should be support.  It's not clear to me though if any usages of `type()` remain for these cases.  If needed, keep current API, otherwise, see if it can be paired down.  Regardless, for posterity, javadoc the design indicating supported/unsupported usages.

If something thorny comes up, it can be discussed further.

File: pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertySource.java (hunk 3 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertySource.java]: Hum we actually can't implement the first version since `setProperty(PropertyDescriptor<T>, T)` has the same erasure as `setProperty(PropertyDescriptor<List<T>>, T)`. We'll go for the second version

File: pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java [hunk 13]
```diff
@@ -28,30 +30,42 @@
...
 public abstract class AbstractPropertyDescriptorFactory<T> implements PropertyDescriptorFactory<T> {
 
-    protected static final Map<PropertyDescriptorField, Boolean> CORE_FIELD_TYPES_BY_KEY
-        = CollectionUtil.mapFrom(new PropertyDescriptorField[] {NAME, DESCRIPTION, DEFAULT_VALUE, DELIMITER},
-                                 new Boolean[] {true, true, true, false});
+
+
+
+    static {
+        System.err.println(CORE_FIELD_TYPES_BY_KEY);
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java]: ?

File: pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java [hunk 14]
```diff
@@ -62,38 +76,70 @@ public AbstractPropertyDescriptorFactory(Class<?> theValueType, Map<PropertyDesc
...
+        if (StringUtil.isEmpty(deft)) {
+            throw new RuntimeException("Default value was null, empty, or missing");
+        }
+        return deft;
     }
 
 
     @Override
     public final PropertyDescriptor<T> createWith(Map<PropertyDescriptorField, String> valuesById) {
+      //  checkRequiredFields(valuesById);
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java]: ?

File: pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java [hunk 15]
```diff
@@ -107,6 +153,20 @@ protected String defaultValueIn(Map<PropertyDescriptorField, String> valuesById)
...
     /**
+     * Checks if the value is considered as missing or not. Some properties support whitespace values, hence the
+     * check. By default this does not support it. The factory can override this method to change the predicate.
+     *
+     * @param value The value to check
+     *
+     * @return True if the value must be considered missing, false otherwise
+     */
+    protected boolean isValueMissing(String value) {
+     //   return StringUtil.isEmpty(value);
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java]: ?

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/PropertyDescriptorUtil.java [hunk 16]
```diff
@@ -88,4 +89,53 @@ public static String typeIdFor(Class<?> valueType, boolean multiValue) {
...
+     */
+    public static ExpectedFieldsBuilder expectedFields() {
+        return new ExpectedFieldsBuilder();
+    }
+
+
+    /** Builder for an expected fields map. */
+    public static final class ExpectedFieldsBuilder {
+
+        Map<PropertyDescriptorField, Boolean> requiredFields = new HashMap<>();
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/PropertyDescriptorUtil.java]: `private final`

I use this as the default for all fields when I'm writing a new class.  I widen scope, and allow mutability when needed.

File: pmd-core/src/main/java/net/sourceforge/pmd/util/StringUtil.java [hunk 17]
```diff
@@ -79,21 +86,50 @@ public static String withoutPrefixes(String text, String... prefixes) {
...
         if (value == null || "".equals(value)) {
             return true;
         }
 
+        return false;
+    }
+
+
+    /** Argument must not be null. */
+    private static boolean nullSafeIsBlank(String value) {
```
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/util/StringUtil.java]: In my experience, people use "null safe" to indicate the method operates on nulls without issue.  You use it in the reverse here.  `nullUnsafeIsBlank` would be more apropos.

File: pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java (hunk 13 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java]: Yeah I ran into an absurd bug and pushed to see if travis reproduced. The bug is that, in the static initializer of PropertyDescriptorUtil, for some reason the FACTORY of IntegerProperty is null. It's uncomprehensible, since it only happens for this specific factory, but the others are declared nearly identically. Moreover, the factory is static final and assigned in its declaration with `new` (which can't return null as per the JLS). You can see the log of the error on the travis log, but you'll need a debugger to see what I mean. I don't know what to do...

Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java]: Could it be a static initialization cycle?  I guess I've not hit issues with this before.  Try this to see what I mean:

```
public class Test1 {
    public static final Test2 TEST2 = new Test2();

    static {
        System.out.println("test1 -> test2: " + Test2.TEST1);
    }
    public static void main(final String[] args) {
        System.out.println("main called");
    }
}
```

```
public class Test2 {
    public static final Test1 TEST1 = new Test1();
    static {
        System.out.println("test2 -> test1: " + Test1.TEST2);
    }
}
```
When I run, I get this output:
```
test2 -> test1: null
test1 -> test2: com.firepond.cmod.Test1@7852e922
main called
```

You'll need to track down the class initialization cycle and find a way to break it.

When I'm designing a non-trivial subsystem, I sometimes like to get a tool to visualize the real dependencies between the different classes.  A picture can make it immediately obvious where I've introduced a connection that breaks the "layering" or intended encapsulation.  I tend to shoot for trees if I can, DAGs if I must, and spend a lot of time trying to eliminate cycles. 
 It's also useful to check the implementation meets my design goals.  Perhaps helpful here to understand where the cycle exists.

Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java]: I thought it was a cycle too, but I after some verification, IntegerProperty has no dependency on PropertyDescriptorUtil. The class is entirely similar to eg `FloatProperty`, but it's initialized after PropertyDescriptorUtil accesses its factory.
To illustrate, I added the following snippet right after the `FACTORY` declaration of FloatProperty and IntegerProperty:
```java
static {
  System.out.println("FACTORY INITIALISED: " + FACTORY);
}
``` 
and I added logging statements to the PropertyDescriptor initialiser:
```java
static {
  ...
  temp.put("Integer", IntegerProperty.FACTORY);
  System.out.println("DONE WITH INTEGER FACTORY:" + IntegerProperty.FACTORY);
  ...
  temp.put("Float", FloatProperty.FACTORY);
  System.out.println("DONE WITH FLOAT FACTORY:" + FloatProperty.FACTORY);
}
```
Console output starts with this:
```
DONE WITH INTEGER FACTORY:null
FACTORY INITIALISED: net.sourceforge.pmd.lang.rule.properties.IntegerProperty$1@123a439b
FACTORY INITIALISED: net.sourceforge.pmd.lang.rule.properties.FloatProperty$1@379619aa
DONE WITH FLOAT FACTORY: net.sourceforge.pmd.lang.rule.properties.FloatProperty$1@379619aa
```
The integer factory is initialized after having been accessed, which makes no sense (see [this SO answer](https://stackoverflow.com/a/2007701/6245827)). I have no idea where the bug comes from, but a workaround would be to use a static method returning the factory, with the downside that this factory would not be a singleton (though this method could be made package private). It looks sloppy though :/

File: pmd-core/src/main/java/net/sourceforge/pmd/RuleSetWriter.java (hunk 7 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/RuleSetWriter.java]: Maybe we could make the factories package private? Wouldn't that release the need to consider that factories can be used by rules/ downstream?

File: pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java (hunk 13 above)
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java]: The cycle need not be a 2-cycle, it could be rather long and circuitous.  Try putting a `main` method on `IntegerProperty`, and run it using the `-verbose:class` JVM argument.  You should see the order of classloading with `IntegerProperty` coming first, and hopefully `PropertyDescriptorUtil` eventually.  I think the static initialization likely correlates well with this loading.  If so, it seems reasonable that a _portion_ of _a_ cycle between will be included in the classes listed between them, including perhaps some unrelated classes not part of the cycle path.  You could also try this starting on the `PropertyDescriptorUtil` and see another part of the cycle, but I think that's the part you want to keep.

It makes sense for the `IntegerProperty` to appear initialized afterward, it's just not _fully_ initialized in the middle of the cycle.  Once the JVM finishes initializing `PropertyDescriptorUtil` it will continue with the initialization of `IntegerProperty`.

This [SO answer](https://stackoverflow.com/questions/30142611/recursive-initialization-static-initializer-not-getting-called-when-i-access-c) is more directly related.

See [JLS 12.4](https://docs.oracle.com/javase/specs/jls/se8/html/jls-12.html#jls-12.4) for the initialization process.  This wording from 12.4.1 speaks to the fact that `null` (the default value) is returned in the case you're hitting.

> The fact that initialization code is unrestricted allows examples to be constructed where the value of a class variable can be observed when it still has its initial default value, before its initializing expression is evaluated, but such examples are rare in practice. (Such examples can be also constructed for instance variable initialization (§12.5).) The full power of the Java programming language is available in these initializers; programmers must exercise some care. This power places an extra burden on code generators, but this burden would arise in any case because the Java programming language is concurrent (§12.4.2).

File: pmd-core/src/main/java/net/sourceforge/pmd/EnumeratedPropertyDescriptor.java [hunk 18]
```diff
@@ -0,0 +1,27 @@
...
+
+package net.sourceforge.pmd;
+
+import java.util.Map;
+
+/**
+ * Interface defining an enumerated property descriptor.
+ *
+ * @param <E> The type of the values
+ * @param <T> The type of default values the descriptor can take (can be a List)
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/EnumeratedPropertyDescriptor.java]: Correct! For a multi value property, T == List<E> before erasure

File: pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptor.java [hunk 19]
```diff
@@ -32,12 +61,15 @@
...
     /**
-     * Denotes the value datatype.
+     * Denotes the value datatype. For multi value properties, this is not the
+     * List class but the list's component class.
      *
-     * @return Class
+     * @return Class literal of the value type
      */
-    Class<T> type();
+    Class<?> type();
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptor.java]: No, for multi valued properties, `T` is the `List<V>`, and the `type()` method returns a `Class<V>`. That's also why I named `V` the type argument in `AbstractMultiValuePropertyDescriptor`, so as not to mistake the two. See [this comment above](https://github.com/pmd/pmd/pull/479#commitcomment-22769778)

File: pmd-core/src/main/java/net/sourceforge/pmd/MultiValuePropertyDescriptor.java [hunk 20]
```diff
@@ -0,0 +1,38 @@
...
+
+package net.sourceforge.pmd;
+
+import java.util.List;
+
+/**
+ * Specializes property descriptors for single valued descriptors. For this type of property, the return value of the
+ * {@link #type()} method must be the class literal of the type parameter of the interface {@link PropertyDescriptor}.
+ *
+ * @param <V> The type of value this descriptor works with. This is the type of the list's component.
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/MultiValuePropertyDescriptor.java]: I wanted to be consistent with AbstractMultiValuePropertyDescriptor, because V is not the T of the PropertyDescriptor. But if you think it's best I'll change it

File: pmd-core/src/main/java/net/sourceforge/pmd/util/StringUtil.java [hunk 21]
```diff
@@ -283,6 +261,69 @@ public static void appendXmlEscaped(StringBuilder buf, String src, boolean suppo
...
 
+
+    /**
+     * Replace some whitespace characters so they are visually apparent.
+     *
+     * @param o
+     *
+     * @return String
+     */
+    public static String escapeWhitespace(Object o) {
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/util/StringUtil.java]: Right I sometimes hit the "format" shortcut mechanically, which is fine when I refactor an entire class but not so much for small changes x) I've now disabled code rearrangement

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/ValueParser.java [hunk 22]
```diff
@@ -0,0 +1,263 @@
...
+import net.sourceforge.pmd.util.ClassUtil;
+import net.sourceforge.pmd.util.StringUtil;
+
+/**
+ * Parses a value from a string.
+ *
+ * @param <U> The type of the value to parse
+ */
+// FUTURE @FunctionalInterface
+public interface ValueParser<U> {
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/ValueParser.java]: You're right, I'll move them. 
Thinking about it, maybe a better solution would be not to use a functional interface but a utility class with static parsing methods. That way, we use eg `ValueParsers.parseMethod(valueString)` which is shorter and more expressive than `METHOD_PARSER.valueOf(valueString)`, and `ValueParsers.parseMultiPropertyValues(valueString, DELIMITER, ValueParsers::parseMethod)`. We should end up with a bit less boilerplate, and a cleaner syntax. Plus I think it might be better style to define a bunch of static utility methods than a bunch of lambda constants :) We'd need find another name than `ValueParsers` though, maybe `ParseUtil`? I guess it should be package private too, not like our current interface

File: pmd-core/src/main/java/net/sourceforge/pmd/util/StringUtil.java [hunk 23]
```diff
@@ -79,21 +86,50 @@ public static String withoutPrefixes(String text, String... prefixes) {
...
      * (string).trim().length() == 0
      *
      * @param value
-     * @return <code>true</code> if the value is empty, <code>false</code>
-     *         otherwise.
+     *
+     * @return <code>true</code> if the value is empty, <code>false</code> otherwise.
      */
     public static boolean isEmpty(String value) {
+        return isMissing(value) || nullSafeIsBlank(value);
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/util/StringUtil.java]: Oo that's a great idea!

**Comment by oowekyala** [comment]
@adangel I agree this is spiralling out of control. I guess we can merge once we find a solution to the initialisation bug, and make other, smaller PRs for the rest of the refactoring. The package reorganisation for example would warrant a PR on its own since so many rules would have to be updated...

About using maps to build descriptors, maybe we could use some kind of builder pattern? That could be shared with rules so that we don't have to define two separate mechanisms for xml and java. In rules, they could produce clearer and more flexible code:
```java 
IntegerProperty prop = IntegerProperty.builder().name("myProperty").desc("My property is a property").defalt(3).min(2).max(10).uiOrder(0f);
```
That would reduce boilerplate in property classes too, as for instance numeric properties share an identical builder, differing only by the `ValueParser` they use.

File: pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java (hunk 13 above)
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java]: @oowekyala Pushing PropertyDescriptorUtil.ExpectedFieldsBuilder into a stand alone type would seem to break the cycle.  I'll see if I can make a tool to print out an actual static dependency path.

Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java]: Nice, that works! Thanks for your help, you're the man

File: pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java [hunk 24]
```diff
@@ -0,0 +1,321 @@
...
+        if (StringUtil.isEmpty(deft)) {
+            throw new RuntimeException("Default value was null, empty, or missing");
+        }
+        return deft;
+    }
+
+
+    @Override
+    public final PropertyDescriptor<T> createWith(Map<PropertyDescriptorField, String> valuesById) {
+      //  checkRequiredFields(valuesById);
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java]: Right I commented it out to debug something. I'll push a commit to remove all traces of debugging

File: pmd-core/src/main/java/net/sourceforge/pmd/PropertySource.java [hunk 25]
```diff
@@ -44,29 +44,61 @@
...
 
+
+    /**
+     * Sets the value of a multi value property descriptor with only one argument.
+     *
+     * @param propertyDescriptor The property descriptor for which to add a value
+     * @param value              Value
+     * @param <V>                The type of the values
+     */
+    <V> void setProperty(MultiValuePropertyDescriptor<V> propertyDescriptor, V value);
```
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/PropertySource.java]: You're right, that's probably early optimisation.

File: pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptor.java (hunk 19 above)
Comment (oowekyala) [inline pmd-core/src/main/java/net/sourceforge/pmd/PropertyDescriptor.java]: I see where you might have gotten confused. The javadoc for MultiValuePropertyDescriptor was a copy paste of that of SingleValuePropertyDescriptor, which I forgot to rewrite. It's fixed now, sorry about that

File: pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java (hunk 11 above)
Comment (adangel) [inline pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/AbstractMultiNumericProperty.java]: I've no decision made yet, when we should upgrading to java8.
Looking at maven and gradle, as the two most common build tools, they both are still on java7 as a minimum requirement. Once they upgrade, it doesn't make sense for us, to stay behind. But until then: Upgrading PMD to java8 would force the end users to use java8, too (effectively changing the minimum required java version of maven/gradle to java8 then). No big deal personally, and thanks to the toolchains support in maven, it's easy to run maven with java8, but let the code be compiled with a real java7 compiler (no -target flags). Not sure, how easy such a mix is with gradle.
The users, who are still on 1.7 (or even 1.6), I assume, are bigger companies, that move a bit slower. I know, that [tiobe](https://github.com/tiobe/pmd) is maintaining PMD 5.3.x for customers, that are still on java 1.6...

Looking at the current maven plugins, no common/official plugin is yet moved to java8 (see the [profiles java-6 and java-7](https://github.com/apache/maven-plugins/blob/trunk/pom.xml#L111)).
Upgrading to java8 has at least the follow-up to upgrade maven-pmd-plugin to java8, too.

So, for now, I would say, we post-pone this decision. Implementing it would be anyway a completely independent task with no functional change.

For completeness, that's [the oracle support roadmap](http://www.oracle.com/technetwork/java/eol-135779.html):
* Java 7: Available since: July 2011, end of public updates: April 2015 (more than 2 years ago...)
* Java 8: Available since: March 2014, end of public updates: probably September 2018 (in about 1 year...)

File: pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java (hunk 13 above)
Comment (ryan-gustafson) [inline pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertyDescriptorFactory.java]: I have a tool written, needs some polish yet.  But here's what it told me when I said find a path from `IntegerProperty` to `PropertyDescriptorUtil`, obviously for the version of the code with the problem:
```
INITIAL_CLASS_LOAD: net/sourceforge/pmd/lang/rule/properties/IntegerProperty.<clinit>()V
SUPERCLASS: net/sourceforge/pmd/lang/rule/properties/AbstractNumericProperty.<clinit>()V
SUPERCLASS: net/sourceforge/pmd/lang/rule/properties/AbstractSingleValueProperty.<clinit>()V
SUPERCLASS: net/sourceforge/pmd/lang/rule/properties/AbstractProperty.<clinit>()V
INTERFACE: net/sourceforge/pmd/PropertyDescriptor.<clinit>()V
INVOKE_METHOD: net/sourceforge/pmd/lang/rule/properties/PropertyDescriptorUtil$ExpectedFieldsBuilder.get()Ljava/util/Map;
```

This explains why pushing `ExpectedFieldsBuilder` out of `PropertyDescriptorUtil` can break the cycle.

**Comment by adangel** [comment]
Using the builder pattern to define the property will definitely help in reading the code - I currently always need to hover to the javadoc/parameter names, to figure out which of the arguments is the default value of the property, etc... So: +1

**Comment by adangel** [comment]
I've merged this now. For further changes please create new issues/PRs.
@oowekyala Thanks for your work!

**Comment by oowekyala** [comment]
@adangel Nice! Hopefully I'll be able to do the builder refactoring in the next few weeks
