### PR TITLE
[java] Regression in MethodReturnsInternalArray not handling enums

### LINKED ISSUE #1845: [java] Regression in MethodReturnsInternalArray not handling enums
**Affects PMD Version:** 
6.15
**Rule:**
[MethodReturnsInternalArray](https://pmd.github.io/pmd-6.15.0/pmd_rules_java_bestpractices.html#methodreturnsinternalarray)
**Description:**
It seems like https://github.com/pmd/pmd/pull/1799 breaks the rule for enums
**Code Sample demonstrating the issue:**

Consider I have the following enum:

```
package com.ourapp.constants.forms;

import java.util.Arrays;
public enum OptionConditionsMenu {
    REDIRECT(Constants.REDIRECT),

    CONTINUE_TO_NEXT_PAGE(Constants.REDIRECT, "Continue to next page"),
    GO_TO_PAGE(Constants.REDIRECT, "Go to page %d"),

    private String[] titles;

    OptionConditionsMenu(String... titles) {
        this.titles = Arrays.copyOf(titles, titles.length);
    }

    public String[] getTitles() {
        return titles.clone();
    }

    @Override
    public String toString() {
        return titles[0];
    }

    private static class Constants {
        static final String REDIRECT = "Redirect";
    }

}
```

I've reduced it a bit just not to be that big. When PMD checks this file, it shows the following warning:
```
May 26, 2019 8:30:59 PM net.sourceforge.pmd.RuleSet apply
WARNING: Exception applying rule MethodReturnsInternalArray on file /directory/com/ourapp/constants/forms/OptionConditionsMenu.java, continuing with next rule
java.lang.NullPointerException
	at net.sourceforge.pmd.lang.java.rule.bestpractices.AbstractSunSecureRule.isField(AbstractSunSecureRule.java:42)
	at net.sourceforge.pmd.lang.java.rule.bestpractices.MethodReturnsInternalArrayRule.visit(MethodReturnsInternalArrayRule.java:52)
	at net.sourceforge.pmd.lang.java.ast.ASTMethodDeclaration.jjtAccept(ASTMethodDeclaration.java:33)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:130)
	at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceBodyDeclaration.jjtAccept(ASTClassOrInterfaceBodyDeclaration.java:43)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:135)
	at net.sourceforge.pmd.lang.java.ast.ASTEnumBody.jjtAccept(ASTEnumBody.java:22)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:260)
	at net.sourceforge.pmd.lang.java.ast.ASTEnumDeclaration.jjtAccept(ASTEnumDeclaration.java:23)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:280)
	at net.sourceforge.pmd.lang.java.ast.ASTTypeDeclaration.jjtAccept(ASTTypeDeclaration.java:37)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:255)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll(AbstractJavaRule.java:39)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:27)
	at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:336)
	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:499)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:143)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:184)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I believe the source of the problem is that in `MethodReturnsInternalArrayRule:49` there is this line of code:

```ASTClassOrInterfaceDeclaration td = method.getFirstParentOfType(ASTClassOrInterfaceDeclaration.class);```

This one becomes null as it's a enum and this check fails:
```            if (!isField(vn, td)) {```

**Running PMD through:** *[Other]*

### PR DESCRIPTION
**Pull request by KroArtem**
Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**
This pr fixes #1845 .
I've blindly followed the instructions from the comment in the issue:

Steps to fix this issue:

- [x] Reproduce this in a test case (see MethodReturnsInternalArray.xml and MethodReturnsInternalArrayTest.java)

- [x] Fix this Nullpointer (in AbstractSunSecureRule.java). Take the comment on #1799 into account.

- [x] Verify if there are other users than MethodReturnsInternalArray that make use of the method AbstractSunSecureRule.isField() and check whether we have a similar problem there

- [x] Verify if we have a similar problem with interfaces or annotations (like with enums) or with inner classes (annoations, interfaces, enums).

I'm not sure about last point, though. `MethodReturnsInternalArray.xml` has test for interface and now for enum, inner classes are also covered.

### CODE REVIEW

**Comment by KroArtem** [comment]
I don't get checkstyle rule, it is based on an xml file that is generated during `clean verify` phase

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MethodReturnsInternalArrayRule.java [hunk 1]
```diff
@@ -6,9 +6,9 @@
 
 import java.util.List;
 
+import net.sourceforge.pmd.lang.java.ast.ASTAnyTypeDeclaration;
```
Comment (oowekyala) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MethodReturnsInternalArrayRule.java]: @KroArtem This is the Checkstyle violation. This import should be grouped with other `net.sourceforge.pmd` imports below, in alphabetical order

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 2 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/515f86939ab84133acd84a7930403e1a/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MethodReturnsInternalArrayRule.java (hunk 1 above)
Comment (KroArtem) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MethodReturnsInternalArrayRule.java]: Thanks! Those violation was referring to an xml that was (I suppose) generated during clean verify phase and then deleted, that's why I was wondering what exactly is wrong.

Comment (adangel) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MethodReturnsInternalArrayRule.java]: FYI for the future - you should see a similar output as on travis when running the build locally: 
https://travis-ci.org/pmd/pmd/jobs/539209393#L3475

```
[INFO] --- maven-checkstyle-plugin:3.0.0:check (checkstyle-check) @ pmd-java ---
[INFO] There is 1 error reported by Checkstyle 8.18 with /net/sourceforge/pmd/pmd-checkstyle-config.xml ruleset.
[ERROR] src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MethodReturnsInternalArrayRule.java:[10] (imports) ImportOrder: Wrong order for 'org.jaxen.JaxenException' import.
```
It appears a couple of lines above the summary message...

**Comment by adangel** [comment]
@KroArtem thanks for the PR!

>> Verify if we have a similar problem with interfaces or annotations (like with enums) or with inner
>> classes (annoations, interfaces, enums).
>
> I'm not sure about last point, though. MethodReturnsInternalArray.xml has test for interface and now > for enum, inner classes are also covered.

We have test cases for top-level classes and interfaces, for inner classes and one test case for a top-level enum now. What we are missing are the following tests:

* A inner interface. Only one test, which doesn't expect any violations, since there is not implementation in an interface. (Actually, we could have a default implementation, that returns a array... but we don't have access there to any field, thus we wouldn't return a internal array, but return an array, that we got from somewhere else - I would ignore this case for now).
* Top-level annotation and a inner annotation. I think, there is also one test for each case sufficient, which doesn't expect any violations.
* Top-level enum, which indeed does return a array. In this case, we should flag the enum (expect 1 violation). You could change your test case, to add a additional method which returns the array directly (instead of cloning it).
* A inner enum: We need two test cases - one without any violations, and one with 1 expected violation.

 Could you add these additional test cases? That way, we can easily verify, we don't have similar problems with these cases...

**Comment by KroArtem** [comment]
@adangel , yep, thanks for precise description. I'll try to work on it during this week.

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MethodReturnsInternalArrayRule.java (hunk 1 above)
Comment (KroArtem) [reply pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MethodReturnsInternalArrayRule.java]: Thanks! The thing is that those ruleset does not exist in repository that's why firstly I was a bit frustrated.
`[INFO] There is 1 error reported by Checkstyle 8.18 with /net/sourceforge/pmd/pmd-checkstyle-config.xml ruleset.`

**Comment by KroArtem** [comment]
@adangel , @oowekyala , I believe this PR is ready to be reviewed now.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml [hunk 2]
```diff
@@ -266,4 +266,116 @@ public enum MethodReturnsInternalArrayCaseEnum {
         ]]></code>
     </test-code>
 
+    <test-code>
+        <description>Inner interface</description>
+        <expected-problems>0</expected-problems>
+        <code><![CDATA[
+public interface OuterInterface {
+       interface InnerInterface {
+            String method();
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml]: The method should actually return a array, otherwise we are testing not our rule here :smile:

```java
public interface OuterInterface {
       interface InnerInterface {
            String[] method();
       }
}
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml [hunk 3]
```diff
@@ -266,4 +266,116 @@ public enum MethodReturnsInternalArrayCaseEnum {
...
+        <expected-problems>0</expected-problems>
+        <code><![CDATA[
+import java.lang.annotation.RetentionPolicy;
+import java.lang.annotation.Retention;
+
+public final class I {
+    private I(){
+    }
+    @Retention(RetentionPolicy.RUNTIME)
+    public static @interface Inner {}
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml]: Same here, we'll need something with an array:

```java
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;
public final class I {
    private I(){
    }
    @Retention(RetentionPolicy.RUNTIME)
    public static @interface Inner {
        String[] value();
    }
}
```

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml [hunk 4]
```diff
@@ -266,4 +266,116 @@ public enum MethodReturnsInternalArrayCaseEnum {
...
+        <code><![CDATA[
+import java.lang.annotation.ElementType;
+import java.lang.annotation.Retention;
+import java.lang.annotation.RetentionPolicy;
+import java.lang.annotation.Target;
+
+@Target(ElementType.METHOD)
+@Retention(RetentionPolicy.RUNTIME)
+public @interface TopLevelAnnotation {
+
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml]: we should here also add a attribute with an array type, such as `String[] value();`.

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml [hunk 5]
```diff
@@ -266,4 +266,116 @@ public enum MethodReturnsInternalArrayCaseEnum {
...
+}
+        ]]></code>
+    </test-code>
+
+    <test-code>
+        <description>Enum that returns array instead of copy</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml]: :+1:

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml [hunk 6]
```diff
@@ -266,4 +266,116 @@ public enum MethodReturnsInternalArrayCaseEnum {
...
+        public String[] getTitles() {
+            return titles;
+        }
+    }
+}
+        ]]></code>
+    </test-code>
+
+    <test-code>
+        <description>Inner enum that returns array instead of copy</description>
```
Comment (adangel) [inline pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml]: This test description is misleading, it should be "Inner enum that returns copy of array".

Comment (KroArtem) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml]: whoops, copy-pasting

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml (hunk 4 above)
Comment (KroArtem) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml]: done

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml (hunk 3 above)
Comment (KroArtem) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml]: done

File: pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml (hunk 2 above)
Comment (KroArtem) [reply pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml]: I should not commit anything after midnight :/
fixed

**Comment by KroArtem** [comment]
@adangel , next iteration, please :)
