### PR TITLE
[java] Fix #6276: NullAssignment should not report assigning null to a final field in a constructor

### LINKED ISSUE #6276: [java] NullAssignment: False positive when assigning `null` to a `final` field in a constructor
**Affects PMD Version:**  7.18.0

**Rule:** [NullAssignment](https://docs.pmd-code.org/latest/pmd_rules_java_errorprone.html#nullassignment)

**Description:**

If you have a `final` field that might be `null` or not, depending on the called constructor or depending on the arguments given to the constructor, you **must** set it to `null` explicitly in the constructor.
If you set it at declaration time, you cannot set it to a different value.
So assigning `null` to a `final` field in a constructor should not trigger a finding.

This does sometimes work as expected for example when directly assigning `null`, but if it is done as part of a ternary expression for example, the rule complains.

**Code Sample demonstrating the issue:**

https://github.com/Vampire/command-framework/blob/4e8f3137014399bc3e0673077239dbd641b63b20/src/main/java/net/kautler/command/api/Version.java#L95

```java
import java.time.Instant;

public class Version {
    private final Instant buildTimestamp;

    public Version(String buildTimestamp) {
        this.buildTimestamp = "$buildTimestamp".equals(buildTimestamp) ? null : Instant.parse(buildTimestamp);
    }
}
```

**Expected outcome:**

PMD reports a violation at line 95, but that's wrong. That's a false positive.

**Running PMD through:** *Gradle*

### PR DESCRIPTION
**Pull request by lukasgraef**
## Related issues

- Fixes #6276 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

File: pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/NullAssignmentRule.java [hunk 1]
```diff
@@ -68,10 +65,39 @@ private boolean isBadTernary(ASTConditionalExpression ternary, ASTNullLiteral nu
...
+        if (!isInsideConstructor(expression)) {
+            return false;
+        }
+
+        @Nullable
+        JVariableSymbol symbol = tryGetLeftOperandSymbol(expression);
+        return symbol != null && symbol.isField() && symbol.isFinal();
+    }
+
+    private boolean isInsideConstructor(JavaNode node) {
```
Comment (adangel) [inline pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/NullAssignmentRule.java:100]: We don't need to check, whether this field assignment happens inside a constructor, because final fields must either be initialized with a value or assigned in a constructor - they can't be assigned somewhere else.

Searching via ancestors for the constructor declaration might resolve to a different constructor, if this happens to be a local/inner class inside a constructor...

I'll remove this check when I merge this.

**Review by adangel — APPROVED** [review]
Thanks!
